### ISSUE TITLE
Styles are overridden when used with UI libraries

### ISSUE THREAD

**Issue by nomadus** [tinymce/tinymce#4726] opened 2018-12-23 08:22 UTC
This is more a usage question. I am using Grommet UI library and I would like to integrate TinyMCE into my page. When the editor is rendered I have all the button styles overridden by grommet style, which makes them large. How to avoid such a behavior?

![image](https://user-images.githubusercontent.com/3382143/50381961-13f6b900-06be-11e9-8eef-a7a772013627.png)

**Comment by Afraithe** [comment] 2019-01-10 09:32
What version of TinyMCE are you using?

**Comment by lnewson** [comment] 2019-03-04 05:39
Closing due to lack of information. If you can reply with what TinyMCE version you're using and a way to reproduce the issue, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-03-04 05:39 UTC
Labels: needs: more info
