### ISSUE TITLE
Pasting a picture from the clipboard 

### ISSUE THREAD

**Issue by srirampearson** [tinymce/tinymce#4221] opened 2018-02-13 11:14 UTC
Hi All,

I am trying to paste a picture from the clipboard (copied the image from folder) within the Tinymce editor. Its not allowing me to do this.

When I copied the image from Ms Paint and paste it in the Tinymce Editor, its working correctly.

Can you please fix this issue. Its reproducible in the current Tinymce demo site.

Regards.
Sriram

**Comment by jayarjo** [comment] 2018-02-21 12:33
If you are looking to move files from your desktop to TinyMCE, drag&drop them. By copying them directly from a folder you are not making them accessible in a browsers clipboard, therefore we cannot extract it from there.

**Comment by jayarjo** [comment] 2018-02-21 12:34
Will close this, since it is not a bug.

**Closed by jayarjo** 2018-02-21 12:34 UTC

**Comment by srirampearson** [comment] 2018-02-21 12:37
Thanks for the quick reply
