### ISSUE TITLE
Problem with text formatting selected text on mobile

### ISSUE THREAD

**Issue by lezso6** [tinymce/tinymce#5173] opened 2019-09-22 16:10 UTC
I use the following codes:

JS initialization:
```
tinymce.init({
        selector: '#test',
        toolbar: false,
        inline: true,
        menubar: false,
        custom_ui_selector: 'a',
    })
```

HTML:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.0.15/tinymce.min.js"></script>

<div contenteditable="true" id="test"></div>

<a href="#" onclick="tinyMCE.execCommand('Bold');return false;">[Bold]</a>
<a href="#" onclick="tinyMCE.execCommand('Italic');return false;">[Italic]</a>
<a href="#" onclick="tinyMCE.execCommand('mceInsertContent',false,'<b>Hello world!!</b>');return false;">[Insert some HTML]</a>
<a href="#" onclick="tinyMCE.execCommand('mceReplaceContent',false,'<b>{$selection}</b>');return false;">[Replace selection]</a>
```

When I select some text on Android Chrome and click Bold it bolds only first word.

When I use the toolbar it works, but not with a custom button.

**Comment by lnewson** [comment] 2019-09-24 21:25
Thanks for the report, however there's already an issue about this, so I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5156

**Closed by lnewson** 2019-09-24 21:25 UTC
