### ISSUE TITLE
input "data:" will broken the dom with images_dataimg_filter: () => false 

### ISSUE THREAD

**Issue by laggage** [tinymce/tinymce#7777] opened 2022-04-22 06:20 UTC
**What is the current behavior? Describe the bug**
If set `images_dataimg_filter` to `() => false`, and insert a data image to the editor, then move cursor before the data image and input `data:`,  then open `source code` dialog we can see that the dom broken

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Please goto [codepen](https://codepen.io/laggagela/pen/MWrRYPy) to see the problem

**What is the expected behavior?**

The excepted html should be 

```html
<p>hello, data:</p><p><img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJAQMAAADaX5RTAAAAA3NCSVQICAjb4U/gAAAABlBMVEX///+ZmZmOUEqyAAAAAnRSTlMA/1uRIrUAAAAJcEhZcwAACusAAArrAYKLDVoAAAAWdEVYdENyZWF0aW9uIFRpbWUAMDkvMjAvMTIGkKG+AAAAHHRFWHRTb2Z0d2FyZQBBZG9iZSBGaXJld29ya3MgQ1M26LyyjAAAAB1JREFUCJljONjA8LiBoZyBwY6BQQZMAtlAkYMNAF1fBs/zPvcnAAAAAElFTkSuQmCC" alt="" width="9" height="9" /></p>
```

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**5.x.x**

**Comment by lnewson** [comment] 2022-04-22 07:03
Thanks for the report and I can confirm this is a known issue that we're already tracking in https://github.com/tinymce/tinymce/issues/7737. As such I'm going to close this as a duplicate of that issue.

**Closed by lnewson** 2022-04-22 07:03 UTC
