### ISSUE TITLE
Formatting fails to be removed when there is an empty span tag in the end of text

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3749] opened 2017-06-16 01:26 UTC
Please open http://fiddle.tinymce.com/MSfaab

1. Double click the last word (test2)
2. click bold, bold is applied
3. leave word selected and click bold again (to remove it), bold can't be removed

You can see that I also passed valid_elements, with a valid string, but somehow the empty span tag is making this weird behavior to happen.
I know that we can do ```-span``` in the valid_elements, so that span get removed when setContent is called, but I can't see why that empty span in the end can screw up the formatting like that.

**Comment by thiagolacerda** [comment] 2017-06-16 18:10
The empty span was causing a Range element to be returned with startContainer as the strong tag and endContainer as the parent span.
Then the code would enter the if clause in here: https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/Formatter.js#L1003
the unwrap occurs, but no formatting is removed. Shouldn't this piece of code from https://github.com/tinymce/tinymce/blob/master/src/core/src/main/js/Formatter.js#L1036 be executed as well? So TinyMCE assures that the formatting is removed?

```
process(node);
// Remove parent span if it only contains text-decoration: underline, yet a parent node is also underlined.
if (node.nodeType === 1 && ed.dom.getStyle(node, 'text-decoration') === 'underline' &&
  node.parentNode && getTextDecoration(node.parentNode) === 'underline') {
  removeFormat({
    'deep': false,
    'exact': true,
    'inline': 'span',
    'styles': {
      'textDecoration': 'underline'
    }
  }, null, node);
}
```

Created a PR for that, please let me know if that would work -> #3750
Extensively tested manually. I will write some unit tests if you guys think it is ok to merge it

**Comment by thiagolacerda** [comment] 2017-07-06 18:50
Hi @spocke and @fyrkant did you guys had a chance to look at this and the PR that I submitted?

Thanks

**Comment by lnewson** [comment] 2020-05-02 09:34
Hi,

Firstly, thanks for the report and potential fixes! Secondly, I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. I was able to reproduce it in TinyMCE 4.6.7 though, so it's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 09:34 UTC
