### ISSUE TITLE
Version 5.0.1 - Unable to see Throbber on spellchecker callback 

### ISSUE THREAD

**Issue by avinashy1** [tinymce/tinymce#4881] opened 2019-03-06 13:04 UTC
Hi Team,
 I am unable to see throbber(loader) during spellchecker callback  for the code `editor.setProgressSate(true)` for tinymce version 5.0.1. 

I have seen a css class in `/skin/{skin_name}/skin.min.css` - `mce-throbber` which is used in displaying throbber(loader)  while making an ajax call in version 4.x version. However i didn't see anything like loader while i am doing the same for version 5.0.1.

![image](https://user-images.githubusercontent.com/28036676/53900537-c229c200-4062-11e9-8982-5d15721bfe21.png)

Can you help out in this.

Thanks
Avinash.

**Comment by avinashy1** [comment] 2019-03-08 09:42
Any update on this?

**Comment by alecpl** [comment] 2019-03-08 11:28
The same here. It was working in TinyMCE 4 with custom spellchecker engine.

**Comment by avinashy1** [comment] 2019-03-08 13:01
@alecpl , can you confirm the throbber(loader) functionality in version 5.0.1.

**Comment by alecpl** [comment] 2019-03-08 13:09
I tested with 5.0.2, it is not working.

**Comment by avinashy1** [comment] 2019-03-08 13:28
@alecpl , any plan for resolution?

**Comment by alecpl** [comment] 2019-03-08 13:50
I'm not TinyMCE developer.

**Comment by lnewson** [comment] 2019-03-11 01:08
Verified that this worked in 4.9.3, but doesn't work in 5.x. I've talked to the team and it looks as though this was missed in the new UI implementation sorry. We'll try and get this added back in as soon as we can.

For reference, here's an example fiddle to reproduce the issue: http://fiddle.tinymce.com/DDgaab

**Comment by avinashy1** [comment] 2019-03-11 05:26
Even spellchecker didn't provide any suggestions in 5.x unlike 4.x.

![image](https://user-images.githubusercontent.com/28036676/54101902-0ebb2780-43ec-11e9-80e1-fceed60466e9.png)

@lnewson , Can i raise a separate issue or this gets addressed in this issue itself?

**Comment by lnewson** [comment] 2019-03-11 06:15
@avinashy1 the suggestions were working fine for me:
<img width="705" alt="Screen Shot 2019-03-11 at 4 12 41 pm" src="https://user-images.githubusercontent.com/1575550/54103569-a20a5200-4418-11e9-8b00-e21bc042549e.png">

Remember that since you can't see the throbber, it does take a bit of time for the spellchecker to show the invalid words and provide the suggestions. However if you can reproduce it, then can you please log a separate issue (it gets very messy having multiple issues logged in one GitHub issue).

**Comment by lnewson** [comment] 2019-03-11 06:19
Oh, I should add that in v5 we did drop support for the legacy spellchecker callback format. As such the callback needs to be an object with a words key (see the fiddle above for an example).

Looking at the docs, I see they haven't yet been updated unfortunately. We have a tasked logged internally to get that fixed, but I'll have to follow up on it again.

**Comment by avinashy1** [comment] 2019-03-11 12:13
It seems like spellchecker suggestions added to the context menu(`5.x`). In 4.x spellchecker suggestions didn't get populated in context menu instead they were added as a separate container css class. In 4.x these spellchecker suggestions appear when a word has been clicked unlike right-clicking on context menu.

@lnewson , Can you confirm.

**Comment by lnewson** [comment] 2019-03-11 22:55
@avinashy1 yes that's expected, as v4 was done that way because it would have conflicted with the contextmenu plugin. Now that the context menu is in core, we can make it work together which makes it more consistent with the expected user behaviour/what other applications use.

**Comment by lnewson** [comment] 2019-04-23 05:14
This has been fixed in 5.0.4, which has just been released. Please let us know if you find any further problems!

**Closed by lnewson** 2019-04-23 05:14 UTC
Labels: 5.x, component: ui, resolution: fixed in coming release, status: escalated, status: regression, type: bug
