### ISSUE TITLE
Bug: Inline formatting does not respect <br> boundary and formats first word of another line

### ISSUE THREAD

**Issue by alphestdev** [tinymce/tinymce#4094] opened 2017-11-24 23:10 UTC
This bug occurs when **selection is collapsed** within the last word before `<br>`

**Current behavior** (where caret is inside "content")

    ... content.<br><br>Other content.

becomes:

    ... <code>content.</code><br><br><code>Other</code> content.

**Expected behavior**

    ... content.<br><br>Other content.

Should become:

    ... <code>content.</code><br><br>Other content.

The issue can be reproduced here:
https://codepen.io/anon/pen/YEvgQx

**Additional anomaly**
On our configuration it even inserts another `<code>` element as child of the first code element:

    ... content.<br><br>Other content.

becomes:

    ... <code>content.<code></code></code><br><br><code>Other</code> content.` 

which makes it even weirder. I could not reproduce this second-child bug in a fiddle, but please look into it too. Debugger shows that there are `\ufeff` characters inserted inside and after child code element. (red dots on the screenshot)

![tinymce inline code bug](https://user-images.githubusercontent.com/32202/33225303-2056ddb2-d175-11e7-9c76-23ae0d716eb1.png)

_Found in v4.7.2, also appears in your demo, which I think is running hotlink to 4.x (=latest v4.7.3)
Seen at least in Chrome62 and FF57_

**Comment by alphestdev** [comment] 2017-11-24 23:14
Same goes for other inline formats too, like Bold.

**Comment by lnewson** [comment] 2020-05-03 23:48
Hi,

I'm unable to reproduce either issue in TinyMCE 4.9.10 and 5.2.2 using the details provided. I was able to reproduce the first issue at least in TinyMCE 4.7.2 though, so it's likely the issue has been fixed since this was originally reported. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-03 23:48 UTC
