### ISSUE TITLE
tinymce requires non minified version of files but community edition gives only minified version of files. 

### ISSUE THREAD

**Issue by mohitpawar10** [tinymce/tinymce#4478] opened 2018-07-01 13:59 UTC
**Do you want to request a *feature* or report a *bug*?** 
 Report a bug.

**What is the current behaviour?**
 TinyMCE community edition gives a minified version of files but when I integrated it with HTML it requires the non minified version of files. 
![screenshot 9](https://user-images.githubusercontent.com/14096291/42135048-685446d2-7d63-11e8-9385-cf6c5f5210aa.png)
![screenshot 10](https://user-images.githubusercontent.com/14096291/42135049-68812bac-7d63-11e8-8b4c-2be31ebd9a43.png)

**What is the expected behavior?**
 It should have taken a minified version of files by default. I need to manually change minified files names so tinymce can accept it. It would have been better if we could have had the option in initialization to take the minified version of file or normal files. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue?**
I am using 4.7.13 version of community edition. OS Windows 10, browser Gooogle Chrome.

**Comment by fyrkant** [comment] 2018-07-02 14:57
Are you using the minified version of tinymce? I think it checks so if you're using the `tinymce.min.js` it will check for the `.min.js` plugin file.

**Comment by mohitpawar10** [comment] 2018-07-02 16:31
@fyrkant Yes, I am using minified version only.

**Comment by fyrkant** [comment] 2018-07-03 09:01
I'm not able to reproduce this using the community download from the [tinymce.com downloads page](https://stagecoach.tinymce.com/download/), is that the one you are using?

**Comment by mohitpawar10** [comment] 2018-07-03 15:57
@fyrkant Yes. That one only. 4.7.13.

**Comment by lnewson** [comment] 2020-04-27 23:52
I tried to reproduce this using the latest version of TinyMCE (5.2.2) locally and I was unable to reproduce the issue. As such given the age of this I'm going to close it, however if you're still able to reproduce the issue please let us know and we'll reopen this issue.

**Closed by lnewson** 2020-04-27 23:52 UTC
Labels: needs: more info
