### ISSUE TITLE
Buttons are not reseted when switching between multiple instances

### ISSUE THREAD

**Issue by oliver-wagner-ds24** [tinymce/tinymce#6297] opened 2020-12-01 16:27 UTC
When having multiple inline editors in one page, the sometimes seems to share the instance. In the following preview I have 3 paragraphs which have a separate editor:

https://codepen.io/oliver-wagner-ds24/pen/qBadvYo

- Click on the first paragraph, select a word and format it bold by clicking the bold button. The bold button gets enabled.
- Click into the second paragraph

Observed behavior:

The bold button is still enabled in the second editor. When I now switch to the third paragraph, the bold button is not enabled any more.

![tinymce-instances](https://user-images.githubusercontent.com/53758733/100767797-77d1a280-33fa-11eb-9810-c54bab75fa34.gif)

Expected behavior:

When I switch the editor, the buttons are correct updated. In this case, the bold button is not enabled.

---

Found in current Chrome (Version 86.0.4240.198 - x86_64) on Mac Catalina (10.15.7)

**Comment by JamesToohey** [comment] 2020-12-08 00:53
Hi @oliver-wagner-ds24, thanks for reporting this bug. This is a duplicate of #5947 so I will be closing this issue.

This has been logged internally for a fix, so we will make sure to reference #5947 when we have a fix in place.

**Closed by JamesToohey** 2020-12-08 00:53 UTC
