### ISSUE TITLE
nonEditable plugin Delete/backspace bug on Chrome and Safari

### ISSUE THREAD

**Issue by ryandang** [tinymce/tinymce#2526] opened 2015-12-02 18:34 UTC
http://plnkr.co/edit/8czUbXktcWpvxt3R8GUl?p=preview

STR:

Click on the beginning of "Editable Content 2" and hit back space, it will join 2 editable section together.

**Comment by lnewson** [comment] 2020-05-08 09:37
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:37 UTC
Labels: plugin: noneditable, status: verified, type: bug
