### ISSUE TITLE
Clicking on an image selects the IMG's parent tag instead of the IMG when the image has a float style, in Google Chrome.

### ISSUE THREAD

**Issue by volumeone** [tinymce/tinymce#3544] opened 2017-03-16 20:18 UTC
**Do you want to request a *feature* or report a *bug*?**

BUG

**Current behavior?**

When clicking on an image, it selects the IMG's parent tag instead of the IMG tag. So when you click on the image button in the toolbar, the image's info will not be filled in (because editor.selection.getNode() doesn't return the img tag).

**Steps to reproduce:**

[http://fiddle.tinymce.com/SLfaab/1](http://fiddle.tinymce.com/SLfaab/1)

**What is the expected behavior?**

When you click on an image, editor.selection.getNode() should return the IMG tag.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

The bug was introduced in 4.5.4. 

Mac 10.11
 - Chrome 49 (BUG)
 - Chrome 56 (BUG)
 - Firefox 52 (works fine)
 - Safari 10 (works fine)

Windows 7
 - Chrome 54 (works fine)
 - Internet Explorer 9 (works fine)

Windows 10
 - MSEdge (works fine)

**Comment by donShakespeare** [comment] 2017-03-17 09:19
The fiddle works for me in Chrome 56

**Comment by spocke** [comment] 2017-05-23 13:19
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2017-05-23 13:19 UTC
Labels: plugin: image, status: regression, status: verified
