### ISSUE TITLE
When more editors and there are inline:true, There is a bug in the align function  

### ISSUE THREAD

**Issue by gosear** [tinymce/tinymce#6448] opened 2021-01-20 09:34 UTC
**What is the current behavior? Describe the bug**
when more editors(inline Mode). when there are first active ,The toolbar  "align" display error.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://www.tiny.cloud/docs/demo/inline/#

1. First : click this paragraph.
![image](https://user-images.githubusercontent.com/59965827/105154227-4b0d5200-5b44-11eb-81a0-1217c38d2ecd.png)
2. Then: select one "align" icon click on toolbar . For example: now I click set the "align center"
![image](https://user-images.githubusercontent.com/59965827/105154546-9c1d4600-5b44-11eb-96e5-51fb18be84a6.png)
3. Finally： I click one another editor. Now "align center" display error!  it should not be focus!
![image](https://user-images.githubusercontent.com/59965827/105155003-1352da00-5b45-11eb-80b3-cd40d24a20f4.png)

**What is the expected behavior?**
when First active editor . the "align" icons in  toolbar should not be focus！
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
vesion:5.x all exist , browser.

**Comment by gosear** [comment] 2021-01-20 09:41
How to go this page?  
you should click the this Demo link:
![image](https://user-images.githubusercontent.com/59965827/105156283-958fce00-5b46-11eb-9530-9f6f42c7cd82.png)

**Comment by JamesToohey** [comment] 2021-02-03 03:12
Hi @gosear, thanks for reporting this bug. This is a duplicate of #5947 so I will be closing this issue.

This has been logged internally for a fix, so we will make sure to reference #5947 when we have a fix in place.

**Closed by JamesToohey** 2021-02-03 03:12 UTC
