### ISSUE TITLE
WRONG li object in automatic TOC

### ISSUE THREAD

**Issue by wahlj** [tinymce/tinymce#6662] opened 2021-03-25 11:59 UTC
**What is the current behavior? Describe the bug**
TOC always shows an phantom Heading initial after 3rd level entrys.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Wrong Element in TOC after initila insert TOC.
![Bildschirmfoto 2021-03-25 um 12 54 03](https://user-images.githubusercontent.com/37443921/112469118-5f024980-8d69-11eb-808d-ec7681b79292.png)

html code
![Bildschirmfoto 2021-03-25 um 12 58 09](https://user-images.githubusercontent.com/37443921/112469517-de901880-8d69-11eb-94df-16defdab067d.png)

**What is the expected behavior?**
Korrekt TOC
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Version 4 and 5 same

**Comment by JamesToohey** [comment] 2021-03-30 22:30
Hi @wahlj, thank you for reporting this. I can confirm this is a bug, and we have an issue to track this already so I'm closing this as a duplicate of #5369.

**Closed by JamesToohey** 2021-03-30 22:30 UTC
