### ISSUE TITLE
< sign does not get encoded correctly all of the time

### ISSUE THREAD

**Issue by edmozley** [tinymce/tinymce#6650] opened 2021-03-19 21:34 UTC
I am trying to write &lt;CODE&gt; and at first when I view source I can see it is correctly encoded.

However when I save the contents of my TinyMCE it gets turned into <code></code> because it thinks I am trying to write some HTML and it needs a closing tag or something.  I've attached some screenshots which makes it a bit clearer.

![tinymce_3](https://user-images.githubusercontent.com/23417281/111844416-ec254880-88fa-11eb-9b93-09a2490235af.png)
![tinymce_2](https://user-images.githubusercontent.com/23417281/111844419-ecbddf00-88fa-11eb-9ea9-937002d46c8d.png)
![tinymce_1](https://user-images.githubusercontent.com/23417281/111844421-ed567580-88fa-11eb-8d5a-7ff9e2fccd37.png)

**Comment by spocke** [comment] 2021-03-20 07:05
I think this is due to the textarea not being encoded properly. So basically the html on the page should be <textarea>(encoded html)</textarea>.

Here is a fiddle showing how it's supposed to work notice that all tags are properly entity encoded:
http://fiddle.tinymce.com/Ychaab

There is nothing we can do about this on our end. It's how the DOM and the browser works html should be encoded in the textarea if you want the browser to not interpret the contents as tags.

I'm closing this since it's it's working as intended. I can re-open it if you provide more details like a fiddle describing the problem and showing it's not the same as the encoding problem described above.

**Closed by spocke** 2021-03-20 07:05 UTC

**Comment by edmozley** [comment] 2021-03-20 13:27
Hello!

Thank you very much indeed - it's all working perfectly now.  It's on an old ASP page so I used this in the text area

Server.HTMLEncode(htmlSource)

Thanks again!

Ed
