### ISSUE TITLE
Table border is written to border attribute instead of style

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2268] opened 2015-06-22 11:50 UTC
Description of problem:

TinyMCE writes table border width as `border` attribute, even for `HTML5` `schema`.  

Steps to reproduce:
1. Set the `schema` configuration option to 'html5' (or just don't use it, since it is 'html5' by default)
2. Insert a table
3. Set Table - Table properties - Border width: 1

Expected result:
&ltg;table style="border: 1px solid black">
or similar.

Actual result:
&ltg;table border="1">

Comment:
the `border` attribute is deprecated in HTML5.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7556](http://archive.tinymce.com/develop/bugtracker_view.php?id=7556) posted by [r.osmanov](http://archive.tinymce.com/profile.php?name=r.osmanov)_
> 
> _**Tags:** [table border style attribute]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/8Peaab_

**Comment by fyrkant** [comment] 2017-05-26 11:43
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Closed by fyrkant** 2017-05-26 11:43 UTC
Labels: origin: tinymce.com, plugin: table, type: bug

**Comment by KaKi87** [comment] 2017-10-15 13:58
Hi,

I'm using TinyMCE 4.5.3 and the problem is still here.

Thanks !

**Comment by KaKi87** [comment] 2017-10-15 14:24
My temporary solution (client-side).

![screen shot 10-15-17 at 04 24 pm](https://user-images.githubusercontent.com/21284089/31585632-5bcdbb06-b1c5-11e7-874e-e54c4bda3195.PNG)

**Comment by plainnany** [comment] 2019-09-29 03:24
you can set `table_default_attributes: {}`, [docs](https://www.tiny.cloud/docs/plugins/table/#table_default_attributes)

**Comment by ktroendle** [comment] 2020-04-20 20:56
Table border color still does not work
https://www.tiny.cloud/docs/demo/full-featured/

1. - Right-click on table - table properties
2. - Set border width to 1 
3. - Click "Save"
4. - Right-click on table - table properties - Click "Advanced"
5. - Set border style to solid, set border color.
6. - Click "Save".
7. - No border color is applied?
8. - Looking at the source, it appears the border-collapse is causing the border to not show.
`_border-collapse: collapse;_ width: 100%; height: 141px; border-color: #e03e2d; border-style: solid;`

**Comment by Zazimou** [comment] 2021-04-08 14:14
> Table border color still does not work
> https://www.tiny.cloud/docs/demo/full-featured/

Same problem after one year without answer. I need it in style attribute for mpdf generator which ignores border attribute.
Any ideas please?
