### ISSUE TITLE
Under the inlite theme, the cursor exceeds the editing range, and the toolbar does not appear.

### ISSUE THREAD

**Issue by tonyChenHey** [tinymce/tinymce#4517] opened 2018-08-06 06:59 UTC
The toolbar cannot appear when the text selected in the editing area is beyond the editing area.

**Comment by fyrkant** [comment] 2018-08-08 11:37
Can you create a reproduction of the issue in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:37
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:37 UTC
Labels: needs: more info
