### ISSUE TITLE
Serious bug in new version 4.7.7.

### ISSUE THREAD

**Issue by batata004** [tinymce/tinymce#4246] opened 2018-02-23 02:52 UTC
Hi,

Untill this last update this bug that I am reporting didnt happen. Test case: https://jsfiddle.net/agLjo58f/

Open the test case link and click in the BACKGROUND COLOR button. You will see the colors (colorpicker) appears offscreen and the user can only see them if he scroll. ALSO if the page is not tall enough, the user wont be able to scroll so he wont see the colors.

Also when you click the PARAGRAPH button it shows weird, it should show up without having the user to scroll down the page.

Finally the hints of the buttons in the last row (when you hover then for a few seconds) dont show (actually they show at the bottom, offscreen). 

The problems above could be corrected with 2 paths: 1) improve the algorithm that decides wheter the dropdown will be shown up/down or 2) give the user the ability to set the dropdown/hint to be shown above or below, many other libraries like SEMANTIC UI offer this basic UI setting since the very first release!

I am receiving tons of users complaning of this problem, I use tinymce in at least 800 websites and custeomers are complaning colors are not showing, the dropdown menus cant be accessed when the page has no enought height to allow scroll... 

I know I was stupid, instead of using "http://cdn.tinymce.com/4/tinymce.min.js" in all the 800 websites my company has been developing in the last years, I should have used somethings like "http://cdn.tinymce.com/4.5/tinymce.min.js" to avoid problems... how I am complete fuc***ed and this is not TINYMCE team fault, it's mine.

However it would be nice to have this fixed.

**Comment by spocke** [comment] 2018-02-23 06:24
I moved the fiddle to: http://fiddle.tinymce.com/Okgaab so that it's easier to flip between tinymce versions.

From what I can see there the colorpickers has always appeared offscreen in that scenario. Tested 4.7.6 the version before the latest 4.7.7 where we did some alterations to how the floating panels gets calculated.

The tooltips are also offscreen in older versions so I see no regression there either.

The only issue I could find is that the the menus appear offscreen when there isn't enough room height wise.

![4 7 6](https://user-images.githubusercontent.com/115879/36580720-b833396a-1869-11e8-9990-f998ca182dde.png)
![4 7 7](https://user-images.githubusercontent.com/115879/36580721-b84f7972-1869-11e8-9d50-678c0627ed71.png)

One of the things we changed is that it now constrains the panels to the document body/document element height not the innerHeight of the window. It seem more common to do that or even not have any constraints at all.

Would be helpful to have a fiddle at fiddle.tinymce.com that reproduces the problem so we can look into it. As I see it there is no regressions between 4.7.7 and 4.7.6 in terms of color panels or tooltips they work the same for me at least.

**Comment by spocke** [comment] 2018-02-23 08:58
Rolled back the document constraint in favor of the old window viewport constraint. Updated the nightly so a.f.i.i.k. everything is now working as 4.7.6 before we did that change. We will probably release this early next week to the old cdn and community download.

**Comment by batata004** [comment] 2018-02-23 12:17
@spocke thanks! You are right, everything you said is right.

The colorpicker never worked but because of a hack in my CMS we made it work! The same happens with the tooltips. However in the newest version the "+" button (and others similar to that) does not work anymore, it worked perfectly till today but in the 4.7.7 it does not work anymore.

So my suggestion:

1) fix the tooltip cause it's great having the tooltip working. It's not veeery important but it helps a lot!

2) fix the colorpicker since it's been a long time with this bug living in the code. I managed to fix it using a custom stylesheet however I think this is a good opportunity to fix it

3) the "+" button bug also happens when using custom drop down buttons and also in the paragraph button.

I thank you for reverting the change regarding this issue in the nightly version, you saved my life!

**Comment by batata004** [comment] 2018-02-23 12:30
@spocke  I used your suggestion and created another test case of this bug with custom buttons. You can see the bug also here -> http://fiddle.tinymce.com/Skgaab

Click the ACOES button at the bottom, you will see the options inside cant be seen. This is something my customers complain a lot cause this didnt happen in older version.

Here is an example of the same cobe above using tinymce 4.7.6 (previous version) and you can see it works perfectly. -> http://fiddle.tinymce.com/Tkgaab

So: the link http://fiddle.tinymce.com/Tkgaab has the old version and the link http://fiddle.tinymce.com/Skgaab has the new version, that's the only change in both cases. However the  old test case works and the new does not work as expected.

**Comment by spocke** [comment] 2018-02-23 13:43
Yes, the nightly seems to solve that as well.

But this is a bit weird use case since tinymce is not really designed to work with the toolbar at the bottom. The default UI we have the toolbar is always at the top and the content is below the toolbar. So we don't really support any other mode out of the box.

**Comment by batata004** [comment] 2018-02-23 14:50
@spocke  yeap I understood :) I know you dont support toolbar at the bottom, however it was working well till last update. Maybe you could redesign the code that was changed in order to prevent this problem.

See, in all my websites I insert the toolbar at the bottom and center aligned so the user can edit the content and use the tools at the bottom cause when you are writing a post/blog it's much more confortable having the toolbar at the bottom so you can focus at the content at the top, where your eyes are already pointed.

The nightly worked perfectly (except the hints/tooltips and the colorpicker which already didnt work), can I expect this nightly fix to be kept later in the next release or should I expect this problem in the next release?

**Comment by spocke** [comment] 2018-02-26 15:41
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2018-02-26 15:41 UTC
Labels: component: ui, status: verified, type: bug

**Comment by batata004** [comment] 2018-02-26 22:46
@spocke the bug with the colorpicker still happens. Wouldnt it be possible to fix it?
