### ISSUE TITLE
ResizeWindow is fired on scrolling

### ISSUE THREAD

**Issue by Lughino** [tinymce/tinymce#3628] opened 2017-05-09 10:13 UTC
I have the same problem reported in this issue #3195 
With Firefox (last 4 versions) and with tinymce versions 4.6.0, 4.5.6, 4.5.3, 4.5.2, 4.4.1, 4.3.1 .
This is serious problem for me, with 10+ editors in a page the browser freeze!

**Comment by spocke** [comment] 2017-05-09 11:24
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Was unable to reproduce this. Thanks

**Comment by fyrkant** [comment] 2018-03-22 15:08
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.

**Comment by lnewson** [comment] 2019-01-29 10:21
Was able to reproduce this given the above example, so reopening.

**Comment by blackcathikari** [comment] 2019-02-05 04:45
This should be fixed in TinyMCE 5.0 - please let us know if you find otherwise. I won't close this yet though, since it was originally a TinyMCE 4.x bug report.

**Closed** 2019-02-05 05:09 UTC
Labels: status: escalated, type: bug
