### ISSUE TITLE
TinyMCE 5: Remove link just removes the link on a word (not the whole link)

### ISSUE THREAD

**Issue by androb** [tinymce/tinymce#4668] opened 2018-11-13 17:16 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Remove Link command will only remove the link on the word that the cursor is in.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/tinymce/pen/79ec454375d41f576b3a9f687994570b

**What is the expected behavior?**
The hyperlink is removed entirely.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
This is a regression from TinyMCE 4.0.

**Comment by lnewson** [comment] 2019-02-25 02:15
This issue should now be fixed in 5.0.1. This issue was interesting, as it turns out it was Mac specific, as Mac's when right clicking would actually select the word you right click on. As such this would have actually been reproducible in 4.x as well, however 4.x didn't include a "Remove link" menu item in the context menu.

**Closed by lnewson** 2019-02-25 02:15 UTC
Labels: 5.x, plugin: link, resolution: fixed in coming release, status: escalated
