### ISSUE TITLE
Dropdown menus doen't move with popups

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2221] opened 2015-05-11 15:22 UTC
Description of problem:

Steps to reproduce:
1. open any popup in tinymce or moxiemanager that has dropdown (such as add link)
2. press the drop down
3. move the popup window
4. the dropdown stays
5.

Expected result:
the dropdown follows the window, or hides

Actual result:
it stays where you left it.

This is yet another example of why you should use a third party UI lib such as bootstrap, or foundation.  People know it, and can extend/skin it.  It's better and more bug free then yours.  It's built for responsiveness.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7508](http://archive.tinymce.com/develop/bugtracker_view.php?id=7508) posted by [bubach](http://archive.tinymce.com/profile.php?name=bubach)_
> 
> _**Tags:** [chrome chrome positioning]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by blackcathikari** [comment] 2016-07-25 01:57
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by davidjsilva** [comment] 2017-05-15 15:58
I was able to reproduce this issue very easily using a TinyMCE Demo https://www.tinymce.com/docs/demo/basic-example/.

I created a demo video to show the issue -> https://drive.google.com/file/d/0B5l2TmXaVpemZmNEXzROd2gteG8/view

I think this issue should be re-opened

**Comment by blackcathikari** [comment] 2017-05-16 22:48
Thanks @davidjsilva, the video helped a lot. I'll reopen this. 
Replicated on Win7 Firefox and Chrome, didn't test on other browsers.

**Comment by lnewson** [comment] 2020-08-15 08:17
This appears to have been fixed since this was originally reported, as when dragging a dialog in TinyMCE 4.9.11 and 5.4.1 the dropdown will now close. As such I'm going to close this, however if you're still able to reproduce this using the latest version of TinyMCE, let us know and we'll reopen this.

**Closed by lnewson** 2020-08-15 08:17 UTC
Labels: browser: chrome, origin: tinymce.com, type: bug
