### ISSUE TITLE
bug: Wrong color of underline

### ISSUE THREAD

**Issue by Dominis13** [tinymce/tinymce#4048] opened 2017-11-08 14:00 UTC
**bug**
Steps to reproduce:
1. open editor
2. set color red
3. set underline
4. type text
as a result underline will be black, not red; Issue related to the HTML structure of the content
`<span style="text-decoration: underline;" data-mce-style="text-decoration: underline;"><span style="color: rgb(255, 0, 0);" data-mce-style="color: #ff0000;">﻿test</span></span>`
As you can see, span with the color is the children of the underline span, so underline can't has proper color.

**Comment by fyrkant** [comment] 2017-11-08 15:34
Duplicate of #3751

**Closed by fyrkant** 2017-11-08 15:34 UTC
