### ISSUE TITLE
Formatting is applied to next element on delete

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2411] opened 2015-10-01 13:29 UTC
Description of problem:

Steps to reproduce:
1. Insert heading
2. Insert paragraph after
3. Delete heading
4. Paragraph is converted into h1 tag

Expected result: Paragraph is the same after deletion of heading

Actual result: Paragraph is replaced by heading tag

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7706](http://archive.tinymce.com/develop/bugtracker_view.php?id=7706) posted by [ars](http://archive.tinymce.com/profile.php?name=ars)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by amaranthrose** [comment] 2015-12-14 16:02
Hello, I was wondering if there is any workaround to that issue? 
Or is there any estimation on when will it be resolved?

**Comment by fyrkant** [comment] 2018-03-27 13:39
Can't reproduce this in the latest version of TinyMCE so I'm closing this issue. If you are able to reproduce it with the latest version please open up a new issue.

**Closed by fyrkant** 2018-03-27 13:39 UTC
Labels: browser: chrome, component: keyboard, origin: tinymce.com, status: verified, type: bug
