### ISSUE TITLE
Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector

### ISSUE THREAD

**Issue by brainfoolong** [tinymce/tinymce#9462] opened 2024-03-04 06:30 UTC
## 📝 Provide detailed reproduction steps (if any)
We had recently upgraded from 6.6.0 to 6.8.3 and now our JS error logger get flodded by some new error messages from TinyMCE.

Unfortunetely i cannot provide a repdroducable example, as this errors are thrown by clients that we don't know many of.

I have an error message, a stack trace and the used browser, i hope this helps. The error is new and never appeared in 6.6.0, so maybe this could be a hint also.

### Error
     Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector

### Stack (Used tinymce.min.js file in attachment here)
    at xs (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:26046)
    at ks (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:26869)
    at Object.parse (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:214872)
    at /files/vendor/tinymce-6.8.3/tinymce.min.js:4:240061
    at Object.serialize (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:240202)
    at lp (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:137040)
    at /files/vendor/tinymce-6.8.3/tinymce.min.js:4:226988
    at I.fold (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:2160)
    at /files/vendor/tinymce-6.8.3/tinymce.min.js:4:226937
    at Object.getContent (/files/vendor/tinymce-6.8.3/tinymce.min.js:4:227000)

### Browser
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

### Sourcefile
[tinymce.min.js.txt](https://github.com/tinymce/tinymce/files/14477418/tinymce.min.js.txt)

**Comment by TheSpyder** [comment] 2024-03-04 22:02
Duplicate of #9201

As [noted in our documentation](https://www.tiny.cloud/docs/tinymce/6/support/#supported-web-browsers-table) the oldest version of Chrome we support is extended stable. That is currently [`122`](https://chromereleases.googleblog.com/search/label/Extended%20Stable%20updates).

Sorry.

**Closed by TheSpyder** 2024-03-04 22:02 UTC
