### ISSUE TITLE
Images in table with links not working

### ISSUE THREAD

**Issue by mrRiff** [tinymce/tinymce#6033] opened 2020-09-14 11:52 UTC
Images with links in table cells - the links don't seem to work
I've only noticed this recently and it seems to be an issue on the site I'm working on and on the demo on tiny.cloud
All I did was add a basic table, add an image into one of the cells and add a link to the image. 
When I previewed this the link didn't work.

**Comment by lnewson** [comment] 2020-09-16 08:35
Hi @mrRiff,

Could you please clarify what you mean by both "links don't seem to work" and "When I previewed this"?

For the first one, do you mean when clicking on the link? If so that is expected behaviour, as TinyMCE will not allow links to be clicked as it would take users away from the content and potentially cause content to be lost. You can get links to work by pressing Ctrl (Windows/Linux) or Command (Mac) and then clicking the link.

For the latter part, do you mean within the editor, or when using say the preview plugin? The behaviour should be the same though, in that you need to Ctrl + Click to follow a link.

**Comment by mrRiff** [comment] 2020-09-16 08:59
Hi Lee,
"links don't seem to work" means that when the image with the link is clicked nothing happens.
"When I previewed this" means that I clicked on the preview option and viewed the preview.

So this is exactly the issue I'm seeing.
I create a 2 cell table
I add an image to each cell
When I try to add a link to either image the link won't save.

I'm running an old version though so that may be the issue - I'll upgrade and see if that fixes it.

**Comment by lnewson** [comment] 2020-09-16 09:03
Thanks for the reply 👍 

> "links don't seem to work" means that when the image with the link is clicked nothing happens.

As noted above, this is the expected behaviour. You'll need to Ctrl+Click to open the link, as TinyMCE will block any clicks since they'll open in the same window.

I should also add I tested this before posting and it seemed to work fine, provided you Ctrl+Click on the image using our full featured demo in the docs. So if you're still having issues with the latest version, could you provide more details, such as what browser you're using?

**Comment by lnewson** [comment] 2020-10-22 00:14
Closing this as there have been no additional details provided in the last month. If you can provide the details requested above, then we'd be happy to re-open this issue.

**Closed by lnewson** 2020-10-22 00:14 UTC
Labels: needs: more info
