### ISSUE TITLE
Clicking on table cell yields no result when a content non-editable section is placed on the same row

### ISSUE THREAD

**Issue by krishna-babu** [tinymce/tinymce#6455] opened 2021-01-22 01:37 UTC
This is observed in case of content non-editable sections (div with contenteditable=false). If such an object is placed inside a row, other cells next to it become unclickable.

caveats: 
1. This happens if there is an element (paragraph, br etc) after non-editable section. The fake cursor calculation goes wrong and the cursor is always placed next to non-editable section but not on the cell where click has happened

![click issue](https://user-images.githubusercontent.com/12712808/105433824-3a75de00-5c0f-11eb-92ee-cecec7e1c4b8.gif)

**Comment by JamesToohey** [comment] 2021-02-03 05:59
Hi @krishna-babu, thank you for reporting this bug. This is a duplicate of #6350 so I'll close this issue. We will update #6350 when we have a fix in place.

**Closed by JamesToohey** 2021-02-03 05:59 UTC
