### ISSUE TITLE
Delete issue with NonEditable container with cursor moving to next line

### ISSUE THREAD

**Issue by sravanreddy-li** [tinymce/tinymce#4772] opened 2019-01-21 07:29 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

Please find the sample TEST button(which inserts nonEditableContent) created in the fiddle example and follow the steps mentioned below
http://fiddle.tinymce.com/x9gaab/8

**Steps to reproduce**
1. Clear contents of the editor. 
1. Press the "Test" button three times. 
1. Press the Enter key to move the cursor to a new line. 
1. Press the "Test" button once. 
1. Press the delete (or backspace) key three times. 
**Expected Results**
2. On the first press of delete, the first noneditable container is deleted. 
2. On the second press of delete, the cursor moves to the first line, and the last noneditable on the first line is deleted. 
2. Further keypresses of delete will delete the noneditables on the first row. 
**Actual Results**
3. On the first press of delete, the first noneditable container is deleted. 
3. On the second press of delete, the cursor moves to the first line, and the last noneditable on the first line is NOT deleted. 
3. Further keypresses of delete do nothing. 

**Related Issues**
https://github.com/tinymce/tinymce/issues/3728﻿

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment] 2019-02-21 12:18
@sravanreddy-li I believe this issue has been fixed in version 5.0.1, but could you confirm? If it helps, here's an updated version of your fiddle: http://fiddle.tinymce.com/x9gaab/12

**Comment by wonderbugtiny** [comment] 2019-04-08 03:47
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:47 UTC
Labels: component: cE=false, needs: more info
