### ISSUE TITLE
remove tinymce instance cause typeerror

### ISSUE THREAD

**Issue by liuhetongzi** [tinymce/tinymce#4703] opened 2018-12-12 08:27 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When I click the textarea，it change to tinymce。when the tinymce lost focus ，it change to textarea。My code is below，but the console tells me typeerror 。What is wrong with me。Please help me，Thank you。

my jquery is：

       $("#mytextarea").focus(function(){
             tinymce.init({
				selector: '#mytextarea',
				language: 'zh_CN', //中文
				browser_spellcheck: true,//拼写检查
				
				menubar: false,//菜单栏隐藏
				auto_focus : true, //默认获取焦点
				plugins: [
					"advlist autolink lists link image charmap print preview anchor",
					"searchreplace visualblocks code fullscreen",
					"insertdatetime media table contextmenu paste imagetools wordcount",
					"code"
				],
				toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | code | table",
			setup: function(editor) {
                             editor.on('focus', function(e) {
                             console.log("focus");
                           });
                             editor.on('blur', function(e) {
                             console.log("blur");                   
                            tinyMCE.activeEditor.setContent(''); //清除输入内容
                            tinymce.remove("#mytextarea");
                        });
                    }
		  	});
    });

my html is：

    <textarea id="mytextarea" style="width:100%" placeholder="签字意见"></textarea>

the console tells me：

     Uncaught TypeError: Cannot read property 'childNodes' of null

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I use version 4.9.1

**Comment by feraing** [comment] 2018-12-12 08:32
能不能格式化一下！

**Comment by lnewson** [comment] 2020-05-04 06:52
Closing as a duplicate of https://github.com/tinymce/tinymce/issues/5330.

**Closed by lnewson** 2020-05-04 06:52 UTC
