### ISSUE TITLE
[Bug] Typo in schema. Incorrect `xml="lang"` attribute added to all elements

### ISSUE THREAD

**Issue by rzymek01** [tinymce/tinymce#2977] opened 2016-06-06 15:17 UTC
There's a bug in Schema, ie. typo:
`if (type != "html5-strict") { globalAttributes.push("xml:lang"); ...`

it should be:
`if (type != "html5-strict") { globalAttributes.push("xml::lang"); ...`

notice two colons instead of one

The typo forces xml attribute to have lang value (according to doc & checked in runtime). This is obviously bad thing.

Note: similar case may be the case for `xml:space` however I have not checked that.

**Comment by rzymek01** [comment] 2016-06-10 09:21
I've also added fix for the xml:space.

**Comment by spocke** [comment] 2016-09-19 15:18
How can I reproduce this issue. Could you setup a fiddle at fiddle.tinymce.com?

**Comment by rzymek01** [comment] 2016-09-19 16:48
I cannot reproduce it right now.

However, take a look at the code:
`globalAttributes.push("xml:lang");`
If you rewrite schema, for example, to exclude a common attribute from every element, then you'd have something like:
`valid_elements : 'div[xml:lang]'`
which adds `xml="lang"` to every `div`

Maybe the problem here lies somewhere else. How to exclude a common attribute (such as style, contenteditable) from every element in schema?

**Comment by jayarjo** [comment] 2017-10-14 08:36
A way to reproduce: http://fiddle.tinymce.com/vcgaab
1. open code editor
2. paste in `<div>some text</div>`
3. after it is added open code editor again
4. notice forced `xml="lang"` attribute on div

**Comment by rzymek01** [comment] 2017-10-16 12:17
Which version your fix will land in?

**Comment by spocke** [comment] 2017-10-16 12:36
4.7.2

**Comment by lnewson** [comment] 2020-04-26 12:03
I'm going to close this, because as noted above the fix/feature to escape a colon was released in TinyMCE 4.7.2.

**Closed by lnewson** 2020-04-26 12:03 UTC
Labels: component: input/output, status: escalated, status: verified, type: bug
