### ISSUE TITLE
When doing a second edit http://www.tinymce.com/tryit/full.php, ALL my tabs crash!  

### ISSUE THREAD

**Issue by metasean** [tinymce/tinymce#2454] opened 2015-11-04 18:26 UTC
BROWSER-specific: FirefoxDeveloperEdition 44.0a2 (2015-11-04)  
  
Steps to reproduce:
On http://www.tinymce.com/tryit/full.php
Highlight some text in the text box, 
Apply an initial style [bold, italics], 
Apply a second style [bold, italics] - All browser tabs crash.

This is specific to the latest Firefox, but is not happening with any other text editor listed at http://www.webdesignerdepot.com/2008/12/20-excellent-free-rich-text-editors/

**Comment by spocke** [comment] 2015-11-26 05:23
Seems to be fixed in the latest version. I reported it and it's marked solved on bugzilla and also I can't reproduce it anymore. So I'm closing this one.

**Closed by spocke** 2015-11-26 05:23 UTC
Labels: browser: firefox, type: bug
