### ISSUE TITLE
no translation of notifications

### ISSUE THREAD

**Issue by autrado** [tinymce/tinymce#2602] opened 2016-01-05 15:15 UTC
the notifications in plugins will not translated at all by lang-files. It appears always the key-Value in english - not in the selected language. example:

/plugins/paste/plugin.min.js ("Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.")

**Comment by czirkoszoltan** [comment] 2016-01-05 19:35
At Editor.js:1178, the function is:

    translate: function(text) {
        var lang = this.settings.language || 'en', i18n = this.editorManager.i18n;

        if (!text) {
            return '';
        }

        return i18n.data[lang + '.' + text] || text.replace(/\{\#([^\}]+)\}/g, function(a, b) {
            return i18n.data[lang + '.' + b] || '{#' + b + '}';
        });

You must change this to

    translate: function(text) {
        var lang = this.settings.language || 'en', i18n = this.editorManager.i18n;

        if (!text) {
            return '';
        }

        return i18n.data[lang][text] || text.replace(/\{\#([^\}]+)\}/g, function(a, b) {
            return i18n.data[lang][b] || '{#' + b + '}';
        });

And then it will work.

**Comment by lnewson** [comment] 2020-05-04 00:08
Hi,

I'm unable to reproduce either issue in TinyMCE 4.9.10 and 5.2.2. So it's likely this is something that was fixed since this was originally reported, as based on the snippets provided this was an issue in TinyMCE 3 (which is no longer supported). As such I'm going to close this, however if you're still experiencing issues with the latest versions of TiinyMCE then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-04 00:08 UTC
Labels: component: ui, type: bug
