### ISSUE TITLE
Can't get mobile theme working in TypeScript

### ISSUE THREAD

**Issue by grzegorztomasiak** [tinymce/tinymce#4826] opened 2019-02-12 22:07 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The following code works flawlessly on desktop but does not show tinymce on mobile at all. It's just an empty textarea visible and cursor is blinking (still weird, since it should have that book icon at least):

```JS
    import tinymce from 'tinymce/tinymce';
    import 'tinymce/themes/silver/theme';
    import 'tinymce/themes/mobile/theme';
    import 'tinymce/plugins/link/plugin';
    ....
    target: document.getElementById('textarea')
    menubar: false,
    skin: false,
    plugins: 'link',
    toolbar: 'bold italic | link',
```
Does it look fine for mobile? Or should I implement something more to get this work?
Console does not throw any error. The only thing is content.css file throwing 404 since skin is set to false I believe.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
n/a

**What is the expected behavior?**
There should be book icon visible that I could click and trigger editor on full mobile screen

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0.0

**Comment by blackcathikari** [comment] 2019-02-12 23:42
@grzegorztomasiak Thanks for the report. I'm looking into this, but I'm curious why you set skin to false? What behaviour did you expect from that?

**Comment by grzegorztomasiak** [comment] 2019-02-12 23:45
hey @blackcathikari just few minutes ago I got it working.
I had to put @import "../../../../../node_modules/tinymce/skins/ui/oxide/skin.mobile.min.css"; for my scss compiler and now mobile skin works.

I am still confused between skin and theme and somewhere I've read that it's better to disable skin if you import it in TypeScript like I did. Does it make any sense? Or should I get it done differently?

**Comment by blackcathikari** [comment] 2019-02-13 00:12
Theme is all the UI code. It's both the framework that defines all the components, and the code that uses those components to make the editor UI. 

Skin is purely CSS, but each skin is also specific to a theme. E.g. the Oxide skin only works for TinyMCE 5's Silver theme, while TinyMCE 4's Modern theme has its own skin. 

Does it work if you don't import a skin and don't specify `skin` in your config? You shouldn't need to, provided the files are in the default locations. 

We have similar code in our test framework for importing TinyMCE - I'll check what we do.

**Comment by blackcathikari** [comment] 2019-02-13 03:20
A team member has pointed out that setting `skin: false would make sense in a headless environment - i.e. when you're not using the UI. Would that apply to your use case?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:48
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:48 UTC
Labels: needs: more info
