### ISSUE TITLE
Heading formatting options are not translated

### ISSUE THREAD

**Issue by pbleser** [tinymce/tinymce#2692] opened 2016-02-12 16:23 UTC
The "Heading" as well as "Heading 1", "Heading 2", etc.. formatting options are not translated.
In the I18N files, they are translated against the key "Header", "Header 1", ...

**Comment by lnewson** [comment] 2020-05-09 08:38
Hi,

Thanks for reporting this and looking at both the TinyMCE 4 and 5 translations, the missing strings are now included. Additionally, when testing out the translations with TinyMCE 4.9.10 and 5.2.2 I was unable to reproduce the issue, so it's likely we've fixed this since this was reported. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!

**Closed by lnewson** 2020-05-09 08:38 UTC
Labels: component: i18n, component: ui, type: bug
