### ISSUE TITLE
 HTML code sample

### ISSUE THREAD

**Issue by xue-shuai** [tinymce/tinymce#5451] opened 2020-03-02 18:22 UTC
Why do I need to escape the HTML code sample first, if not, it will parse the HTML for me

 code sample:  ```<h1>ohhhh</h1>```
but :   <h1>ohhhh</h1>

**Comment by lnewson** [comment] 2020-03-02 22:01
I'm not sure what you mean sorry. Can you please include a [fiddle](http://fiddle.tinymce.com/) or more information to help us understand what your issue is?

**Comment by xue-shuai** [comment] 2020-03-03 04:22
For example, I need an HTML code example, so I type `<h1>ohhh</h1>,` but when I submit it, again in tinymce, it's parsing <h1>ohhh</h1>

**Comment by lnewson** [comment] 2020-03-03 04:24
That isn't any clearer and doesn't provide any more information than your original message I'm afraid. Please include a way for us to reproduce this, or a video to show what you are doing, otherwise we won't be able to help.

**Comment by xue-shuai** [comment] 2020-03-03 04:55
https://i.loli.net/2020/03/03/gfWJKadurCs6BGi.gif

**Comment by lostkeys** [comment] 2020-03-03 05:53
Ok. seems like something happens in between data is stored and retrieved. Can you check in the database exactly what is stored and post it here?

**Comment by xue-shuai** [comment] 2020-03-03 06:09
https://i.loli.net/2020/03/03/VRqjar1PKvBEAGY.png

The database seems to be fine

**Comment by lnewson** [comment] 2020-03-03 06:09
I was able to replicate this using http://fiddle.tinymce.com/Wchaab. It looks to be due to how the code sample is being parsed, as it's being converted to nodes before the schema validation is done. That then means that since h1 elements aren't a valid child, it breaks the content up.

**Comment by xue-shuai** [comment] 2020-03-03 06:15
https://i.loli.net/2020/03/03/dRsureS2wYCg9Ii.png

I use Vue.js, bind data through v-model, and submit

**Comment by spocke** [comment] 2020-03-03 09:44
This is a classic one the tinymce is doing the correct thing here. You just need to encode the html properly in the textarea. So basically <textarea>(encoded html)</textarea>.

Here is a fiddle showing how it's supposed to work notice that all tags are properly entity encoded:
http://fiddle.tinymce.com/Ychaab

There is nothing we can do about this it's how the DOM and the browser works html should be encoded in the textarea if you want the browser to not interpret the contents.

I'm closing this since it's not really a bug.

**Closed by spocke** 2020-03-03 09:44 UTC
Labels: plugin: codesample, status: verified, type: bug

**Comment by lnewson** [comment] 2020-03-03 09:52
Oops, sorry I missed that and thanks for catching that @spocke 👍 For reference, here's an alternative fiddle to show it works as expected when using the TinyMCE setContent API: http://fiddle.tinymce.com/Wchaab/1

@xue-shuai given the above, please make sure you're appropriately encoding the content that's in the element TinyMCE is being initialised on. If that doesn't work, you might be able to try using the `setContent` API like in the above fiddle.

**Comment by xue-shuai** [comment] 2020-03-03 10:11
oh, thank you very much, it may be my mistake, I try to correct it
