### ISSUE TITLE
Deleted Tracking Issue in Mozilla firefox 65.0 version in Ice plugin

### ISSUE THREAD

**Issue by jeeva1989** [tinymce/tinymce#4816] opened 2019-02-07 05:11 UTC
Deleted Tracking Issue in Mozilla firefox 65.0 version in Ice plugin

**Comment by blackcathikari** [comment] 2019-02-07 07:18
@jeeva1989 Could you please clarify what you mean?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:47
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:47 UTC
Labels: needs: more info
