### ISSUE TITLE
Problem writing korean characters inside table cell

### ISSUE THREAD

**Issue by stmkjp** [tinymce/tinymce#2661] opened 2016-01-28 04:30 UTC
Hi, thanks for the great app!

No problem writing in korean when there's no table or writing outside of table, but korean characters took apart ( each korean character consist of consonants and a vowel ). it's very frustrating.
for example :       안 (it's ok ㅇ+ㅏ+ㄴ make a character)          
                     vs.  ㅇㅏㄴ ( this is what happens inside table cell)

Could you kindly fix this problem? or at least let me know where to look into if you guys are all busy.

oh, fyi, characters not broken if I paste them from outside table.

Best,
JP

**Comment by spocke** [comment] 2016-01-29 09:53
What browser are you using also make sure you have the latest version since we recently fixed a bug with IME in tables.

**Comment by stmkjp** [comment] 2016-01-29 11:40
Hi spocke, thanks for the reply.

I'm using IE11 and tested also using emulation (IE10,IE9,IE8). all same.
I downloaded the js using custom builder on tinymce homepage.(it's 4.3.2 and you're saying 4.3.3, right?)
I'll test  github version and let you guys know the result.

and, thanks for the great product, you guys rock!

**Comment by stmkjp** [comment] 2016-01-30 04:58
Tested with 4.3.3 and result were still the same.

**Comment by ssoju** [comment] 2016-03-18 08:33
@spocke is there any updates regarding this issue?
We are experiencing the exact same issue using the most recent version.  There are no problems with any other browser other than IE. 
We love everything else about TinyMCE but can't apply it to our service if we can't resolve this issue. 

We hope you could help us resolve this soon because we would LOVE start using this editor.

**Comment by spocke** [comment] 2016-03-18 09:49
Is this still happening i 4.3.8? I couldn't reproduce it after the fixes I've made can you record a video displaying the issue and detailed instructions. Might be doing different tjings with the IME.

**Comment by stmkjp** [comment] 2016-03-18 10:56
@spocke , 

I almost forgot about this issue, but thanks to @ssoju 's comment, I came back..=)   (hooray github notification mail!)
and yeah...the problem still exists until 4.3.8.
I've attached captured video reproducing the issue.

fyi, it's a webm file captured from virtulBox and I zipped it for github doesn't like this file format.
[captured.webm.zip](https://github.com/tinymce/tinymce/files/179486/captured.webm.zip)
Thanks again for caring this issue!

**Comment by ssoju** [comment] 2016-04-28 02:45
@spocke 
Sorry to keep bringing this up but this is the only one thing that is holding us back from applying tinymce to our service.  We REALLY REALLY want to use tinymce so if you could take a look into it that would be amazing.  Thank you so much.

**Comment by spocke** [comment] 2016-04-29 03:14
I made a patch for this that you can try out:
https://github.com/tinymce/tinymce/commit/ef380446f5896432b978d80378c3bdf025d3917b

You could also wait for the nightly build.

**Comment by spocke** [comment] 2016-05-11 13:24
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2016-05-11 13:24 UTC
Labels: component: keyboard, type: bug
