### ISSUE TITLE
Font family reselecting switches to default

### ISSUE THREAD

**Issue by Narrenschyff** [tinymce/tinymce#4074] opened 2017-11-16 18:29 UTC
You can replicate by:
1. Select a text and click on the font family dropdown and choose font
2. Notice the text changes its font family to your chosen font
3. Click on the same font family in the dropdown again
4. Notice the text changes to a default font family

Is this expected? If I try this scenario in Word, reselecting the font family, will keep the text formatted as the one selected and it won't change to default. Reselecting a font family behaves like toggling.
Same thing happens for paragraph formatting dropdown in the demo here (https://www.tinymce.com/docs/demo/basic-example/) and font size. 

I am using community edition tinymce 4.7.1.

**Comment by LaurieY** [comment] 2017-11-30 17:31
I have also had complaints from my users on a Wordpress site about this behaviour, they keep failing to apply the required formatting because of it.

**Comment by lnewson** [comment] 2020-05-03 23:39
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided. I was able to reproduce it in TinyMCE 4.7.1 though, so it's likely the issue has been fixed since this was originally reported. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-03 23:39 UTC
