### ISSUE TITLE
Preview plugin: preview simulated 'mobile view'

### ISSUE THREAD

**Issue by vibonacci** [tinymce/tinymce#6375] opened 2020-12-30 15:57 UTC
Hello,

Migrating from v4 to v5, the preview plugin lost the ability to set fixed width and height. The preview popup was made nicely responsive and that is an improvement.

However, lets say we're editing content on desktop. Now we want to see how our content would look on an (simulated) mobile screen (max-width 500px for example). The user would now have to resize his browser viewport to match a mobile width. This works fine, but wouldn't it be nice to have a button or programmatic control to make the preview window fixed width 500px? Or a toggle button to switch between the current responsive implementation and a fixed width?

Or maybe there is a current way to achieve this?

Thx in advance.

**Comment by lnewson** [comment] 2021-01-03 23:06
Closing as a duplicate of #6076. There's also a potential workaround mentioned in the last comment that may work for you.

**Closed by lnewson** 2021-01-03 23:06 UTC
