### ISSUE TITLE
Adding content after a DIV and Table

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2398] opened 2015-09-15 10:56 UTC
Description of problem:

Basically when you add or edit a textarea with a DIV/Table in you can't click to the end of the DIV/Table to press return or enter/insert anything else!

Steps to reproduce:
1. Add a DIV/Table (or Table in a DIV) to the textarea
2. Try and create something after it!
3. Try clicking below the DIV/Table

Expected result:
Clicking at the end/below a DIV, would put the mouse pointer there, where by I can click return or insert something else.

Actual result:
The mouse always enters the DIV/Table. Once a DIV/Table is inserted, unless you view the source and put in a letter after them, you can't add to the content afterwards.

When Viewing the source, and then putting the mouse pointer after the closing DIV tag, when you close that panel and go back to the editor the pointer is at the start of the content. The only way is to add a letter after the DIV/Table. This isn't very user friendly for my clients using the CMS I built for them.

Is there a config setting to stop this happening? I've created some templates that insert Foundation column DIVS to the page. This works great, but if the client adds the DIVS to the page, they can't add anything after them without viewing the source and adding a letter.

Cheers
G
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7689](http://archive.tinymce.com/develop/bugtracker_view.php?id=7689) posted by [gwow](http://archive.tinymce.com/profile.php?name=gwow)_

> _**Tags:** [firefox msie safari chrome div table mouse click]_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by Digitaledgestudios** [comment] 2016-03-14 22:17
Duplicate of #1627

The not so perfect solution: `end_container_on_empty_block: true`

**Comment by blackcathikari** [comment] 2016-08-01 01:43
Since this is a duplicate of a closed issue, and there is a solution available, I'm going to close this report. Let me know if this is still a problem though, and I can reopen it. Thanks,
Millie @ TinyMCE

**Closed by blackcathikari** 2016-08-01 01:43 UTC
Labels: browser: chrome, browser: firefox, browser: ie, browser: safari, origin: tinymce.com, status: verified, type: bug

**Comment by sowmi3114** [comment] 2021-07-22 03:22
Yes the problem still exists in latest version of tinyMCE
