### ISSUE TITLE
[4.9.6] BUG: TinyMCE FORM Element deleted when INLINE

### ISSUE THREAD

**Issue by futureweb** [tinymce/tinymce#5148] opened 2019-09-04 14:37 UTC
**What is the current behavior? Describe the bug**
When it's used in INLINE Mode it's deleting FORM Elements - even when they are allowed in valid_elements or extended_valid_elements ...
Working as soon one disabled INLINE Mode.
Also happening in official Examples.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Insert simple HTML Form into Source View of TinyMCE, FORM Element get's deleted

**What is the expected behavior?**
FORM Element shoudn't be deleted

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested with TinyMCE 4.9.6 + latest Firefox

**Comment by lnewson** [comment] 2019-09-05 22:03
@futureweb can you please provide a fiddle or video to reproduce the problem, as I attempted to reproduce the issue using http://fiddle.tinymce.com/jQgaab but the form element isn't removed in 4.9.6 or the latest 5.x version.

I should note that it will be removed if you use the inline editor inside another form element, as allowing that would produce invalid HTML.

**Comment by lnewson** [comment] 2019-10-15 21:30
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-10-15 21:30 UTC
Labels: needs: more info
