### ISSUE TITLE
table_toolbar option issue

### ISSUE THREAD

**Issue by lenamtl** [tinymce/tinymce#2694] opened 2016-02-12 18:46 UTC
Hi,

I'm using the latest version
I'd like to use option to display only a few table option using **table_toolbar** I took the info from
https://www.tinymce.com/docs/plugins/table/#table_toolbar

`table_toolbar: "tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow",`
but it does not work, all drowndown list options are displayed.

Any clue?

**Comment by spocke** [comment] 2016-02-15 10:33
That's for the inline toolbar that pops up when you focus a table not menus these are configured else where.

**Comment by lnewson** [comment] 2020-05-08 10:15
Hi,

I attempted to reproduce this issue using TinyMCE 4.9.10 and 5.2.2 via http://fiddle.tinymce.com/Zhhaab, however it appears to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 10:15 UTC
Labels: plugin: table, type: bug
