### ISSUE TITLE
Source code for Horizontal text align

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#2486] opened 2015-11-24 11:32 UTC
Hi,
    I need to give an option inside the tinymce editor to align the text and other contents vertically top, middle and bottom. Can anyone please provide a way to achieve this or provide me the source code for the Horizontal align left, center and right which is already in the tinymce editor. so that i can make a copy of it and proceed.

Regards,
Kavi

**Comment by spocke** [comment] 2015-11-24 23:22
Use the formats option and vertical-align:
https://www.tinymce.com/docs/configure/content-formatting/#formats

Closing this since it's not a bug or feature request.

**Closed by spocke** 2015-11-24 23:22 UTC
