### ISSUE TITLE
Paste link into word under contenteditable false elements

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5580] opened 2020-04-17 09:52 UTC
**What is the current behavior? Describe the bug**
Current behavior is described here https://github.com/tinymce/tinymce/issues/5152

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Look this fiddle: http://fiddle.tinymce.com/efhaab

**What is the expected behavior?**
Link is pasted to word correctly
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome 80, TinyMCE 5.2.*

**Comment by lnewson** [comment] 2020-04-20 08:54
I'm able to reproduce this, however the original instructions weren't clear and I just happened to stumble upon it which is why the previous issue was closed as unable to reproduce.

Here are the steps to reproduce:
1. Open http://fiddle.tinymce.com/efhaab
2. Highlight the google URL at the bottom of the fiddle and copy the text (eg CTRL+C)
3. Highlight the word "paste" and then attempt to paste the URL (eg CTRL+V)
4. Notice the link wasn't pasted and the selection has moved inside the content editable false element.

This looks to be an issue with the community paste plugins `smart paste` feature. I'm unable to reproduce the issue when that is disabled, or when using the premium PowerPaste plugin. As such my suggestion would be to add the `smart_paste: false` configuration to your init if this is causing an issue until the issue can be fixed.

**Comment by versusvirus** [comment] 2020-04-28 05:24
> I'm able to reproduce this, however the original instructions weren't clear and I just happened to stumble upon it which is why the previous issue was closed as unable to reproduce.
> 
> Here are the steps to reproduce:
> 
> 1. Open http://fiddle.tinymce.com/efhaab
> 2. Highlight the google URL at the bottom of the fiddle and copy the text (eg CTRL+C)
> 3. Highlight the word "paste" and then attempt to paste the URL (eg CTRL+V)
> 4. Notice the link wasn't pasted and the selection has moved inside the content editable false element.
> 
> This looks to be an issue with the community paste plugins smart paste feature. I'm unable to reproduce the issue when that is disabled, or when using the premium PowerPaste plugin. As such my suggestion would be to add the `smart_paste: false` configuration to your init if this is causing an issue until the issue can be fixed.

I debugged it. Bug is going because, when tiny tries to return to bookmark, it expects that there is no block data-mce-caret, so cause of that selection restores incorrectly.

**Closed** 2024-06-15 00:39 UTC
Labels: type: bug, plugin: paste
