### ISSUE TITLE
Version 4.7.9 - Table bug with cursor - Wrong location when fullscreen

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4255] opened 2018-02-27 20:50 UTC
Tested in Firefox. The big cursor that appears before the table is at the right location when the editor is loaded. Now go to View/Fullscreen and you will see that the big cursor is located several pixels to the left.

http://fiddle.tinymce.com/Algaab

**Comment by lnewson** [comment] 2020-05-08 08:42
Hi,

This is another one I'm unable to reproduce in TinyMCE 4.9.10 and 5.2.2 sorry. Looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.10, so sorry for not updating this when it was released. I'm going to close this given it appears to have been fixed, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 08:42 UTC
Labels: plugin: table, status: escalated, status: verified, type: bug
