### ISSUE TITLE
Media plugin bug with <video /> and <img />

### ISSUE THREAD

**Issue by jimshute** [tinymce/tinymce#4667] opened 2018-11-12 09:24 UTC
I got a problem while using media plugin. I have something html writing like this: 
```
<p>
  <video src="//xxx" />
</p>
<p>
  <img src="//xxx" />
</p>
```
When I load it into the editor, the images after the video are disappeared.
If I remove the media plugin, they show up.
And if write the `<video />` as `<video></video>`, the images show as well.
The demo is here. I forked from the official demo and append a ```<video />``` on the top.
https://codepen.io/jimshute/pen/xQRbeX
I wonder whether it is a bug or something else?

**Comment by cloydlau** [comment] 2020-11-19 06:23
Running into this in the newest version

**Comment by lnewson** [comment] 2020-11-19 07:08
This is largely expected behaviour. The content shown is XHTML, but is not valid HTML 5 content. So without the closing `</video>` element TinyMCE will consider all the HTML after that to be part of the video.

The following are the only elements that can be shortened (ie are void elements) via the [HTML 5 spec](https://html.spec.whatwg.org/multipage/syntax.html#elements-2):
> area, base, br, col, embed, hr, img, input, link, meta, param, source, track, wbr

**Closed by lnewson** 2020-11-19 07:08 UTC
Labels: plugin: media, type: bug

**Comment by cloydlau** [comment] 2020-11-20 08:00
Oh, it seems my issue is a little bit different: the video element turns into a img like this↓ which is called placeholder in the document when I enable media plugin. The problem is this base64 img is actually entirely blank. And Videos previews normally when I don't use media plugin.

```html
<img class="mce-object mce-object-video" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" width="300" height="150"  data-mce-object="video">
```
