### ISSUE TITLE
Inline toolbar does not scroll with content when inside inner scroll element

### ISSUE THREAD

**Issue by arsnyder16** [tinymce/tinymce#5953] opened 2020-08-07 19:37 UTC
**What is the current behavior? 
I have a web application with multiple independent scrolling panels. When adding inline tinymce toolbar if i scroll the inner panel the editor is hosted the toolbar stayed in a fixed location and does not scroll with the content.

https://jsfiddle.net/5e8uhwxz/5/

**What is the expected behavior?**
I would expect it to scroll with the content, and in my case would prefer for it to also respect `toolbar_sticky: true`

I noticed that the toolbar is only placed on the body element and that seems to be the underlying problem in this scenario. One option would be to allow it to be configured in my example i would like to set it to something like  `.tinyhost` but if TinyMCE responded to the scroll changed it could remain on the body. I would rather not use fixed_toolbar_container because then i need to handle all the positioning myself relative to the associated paragraph, i also don't want the toolbar constrained to the size of paragraph, my real world case has paragraphs of varying widths 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?
Stable 5, didn't work in 4 either didn't go back anyfurther 
**

**Comment by arsnyder16** [comment] 2020-08-07 19:54
As a stop gap, are there any ways to force the toolbar to re layout? I could put in a check for my scroll element to change and then force a re layout

**Comment by arsnyder16** [comment] 2020-08-07 20:37
quick update, i did a little hack that seems to work, i am open to suggestions

react
```js
 <div className="scroll-host" onScroll={() => {
        window.dispatchEvent(new Event('resize'));      
      }}
```

Raising scroll didn't seem to do it.

**Comment by lnewson** [comment] 2020-08-08 08:18
Hi @arsnyder16 this is a known issue, as TinyMCE doesn't currently support rendering within a scrollable container. As such I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5097, which is where we are currently tracking this feature request.

**Closed by lnewson** 2020-08-08 08:18 UTC

**Comment by arsnyder16** [comment] 2020-08-10 14:53
@lnewson So there are no workarounds like i mentioned that you could offer as a stop gap?
