### ISSUE TITLE
font color & background color not triggering a "ExecCommand" event

### ISSUE THREAD

**Issue by jkrth617** [tinymce/tinymce#3932] opened 2017-09-19 19:58 UTC
I saw a similar bug [here](https://github.com/tinymce/tinymce/issues/2436)
I left a comment but I will repeat it here as well

[fiddle](http://fiddle.tinymce.com/ygfaab/4)
here is the fiddle that was posted a with the original issue. Before the event being listened on was the "change" event, and that does trigger when the font/background colors are changed.
In the fiddle I posted it is changed to the "ExecCommand" event and for all the menu items except the font/background color that event is fired.

Are the background/font color buttons supposed to not fire this event? The "change" event wasn't specific enough for my use case and I wanted to listen to just the menu item buttons getting pressed.

**Comment by lnewson** [comment] 2020-05-02 10:59
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the fiddle provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.5. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 10:59 UTC
Labels: component: formatting, status: escalated, status: verified, type: bug
