### ISSUE TITLE
Different behaviour of delete images

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5029] opened 2019-05-31 11:17 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
In chrome and other browsers press backspace will remove image, in FF image will be selected and second press will remove image
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1.Insert image(floated left or right)
2.Set cursor to image
3.Press backspace
**What is the expected behavior?**
Image will be removed after first backspace press
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0 Firefox 67.0

**Comment by alecpl** [comment] 2019-06-11 10:36
This works for me on https://www.tiny.cloud/ with Firefox 67.0.1.

**Comment by wonderbugtiny** [comment] 2019-07-03 05:23
@versusvirus I was not able to reproduce the issue on Firefox 67.0.4. Please provide a video of the behaviour you are describing to help us try and replicate it. Thank you.

**Comment by lnewson** [comment] 2019-08-18 03:55
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-08-18 03:55 UTC
Labels: needs: more info
