### ISSUE TITLE
[UI Component] Context toolbar does not work in full screen

### ISSUE THREAD

**Issue by MimyyK** [tinymce/tinymce#5124] opened 2019-08-21 10:26 UTC
**What is the current behavior? Describe the bug**
I have a context toolbar on an image and that work in normal view but not in full screen.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
https://codepen.io/MimyyK/pen/JjPbNGO

**What is the expected behavior?**
See context toolbar in full screen

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I tried on Safari and Chrome (Mac OS) 
It work on version 5.0.11 but seems to be broke on 5.0.12

**Comment by lnewson** [comment] 2019-08-23 00:33
Thanks for the report! I can reproduce the issue and know the cause, so I'll try and get a fix into the next community release.

**Comment by lnewson** [comment] 2019-09-24 04:35
Sorry for the late update on this, but this issue was fixed in TinyMCE 5.0.15. Please let us know if you have any further issues.

**Closed by lnewson** 2019-09-24 04:35 UTC
Labels: 5.x, status: escalated, type: bug
