### ISSUE TITLE
TinyMCE editor is not working in Internet Explorer 11.

### ISSUE THREAD

**Issue by mohitanand123** [tinymce/tinymce#2897] opened 2016-05-04 13:02 UTC
I have implemented the tinymca editor in my application. But the problem is that when I click on the text editor area, tinymce options and menu appears but suddenly it disappears. Even the text area is not allowing to enter any text inside it.
It is working fine in Chrome and Safari. The issue persists only in IE11.

**Comment by spocke** [comment] 2016-05-04 13:08
Does it work on tinymce.com or fiddle.tinymce.com if so it's likely that it's an implementation issue.

**Comment by mohitanand123** [comment] 2016-05-04 17:14
In my application I am facing the problem I mentioned above. 
As suggested, I tried the inline mode example from [Inline Mode](https://www.tinymce.com/docs/demo/inline/) in IE 11 and IE10. With this example, as I click in the text editor area, the menus and options did not get displayed at its respective location and the menu layout is distorted. Though I am able to edit the text and set bold and Italic options.
Find below screenshot for inline mode example as displayed in IE 11. The menu options are highlighted in yellow.
![inlinemode](https://cloud.githubusercontent.com/assets/19188061/15022451/5c24d340-1249-11e6-8010-6a32612d73ad.JPG)

Menu should appear as:
![image](https://cloud.githubusercontent.com/assets/19188061/15022496/a30060b8-1249-11e6-95a5-afe65d31ac5e.png)

Kindly suggest.

**Comment by cyau73** [comment] 2016-05-05 01:12
We have implemented TinyMCE on IE 11.0.9600.18230CO successfully on our system with no issue. Maybe you can share your config file, TinyMCE version and IE version.

**Comment by mohitanand123** [comment] 2016-05-05 03:00
You specifically mentioned 11.0.9600.18230CO, will it not support IE 11 version lesser than 18230CO as I have 17728. What I believe, if it support IE 11 than it must be supporting IE 9 and 10 versions also.

We are using IE version 11.0.9600.17728, TinyMCE version: 4.3.11 and it is the default Inline mode example as available on site with no modifications. you can download the code from [here](http://codepen.io/tinymce/share/zip/YydQoj/).

Kindly confirm.

**Comment by mohitanand123** [comment] 2016-05-05 06:31
We simulate the scenario as we have in our application in this [link](http://fiddle.tinymce.com/Fwfaab).
Here we are trying to attach menu with a `<td>` element. This works in chrome but fail for IE.
If we replace the `<td>` with `<textarea>` it work but that also with issues as discussed above.

**Comment by starquake** [comment] 2016-05-25 11:42
This seems to be working:
http://fiddle.tinymce.com/oyfaab/1

Is this of any use to you?

**Comment by spocke** [comment] 2016-05-25 11:45
Will see if we can black list elements we don't support inline mode on this includes table cells, textareas etc.

**Comment by mentemind** [comment] 2017-02-02 21:57
Maybe you could check what version you are using since v3.x.x which is not supported for IE 11 see http://archive.tinymce.com/wiki.php/TinyMCE3x:Browser_compatiblity and https://moodle.org/mod/forum/discuss.php?d=253109

**Comment by chiplueck** [comment] 2017-11-20 18:22
I encountered this problem and found that my html had <!doctype html> instead of <!DOCTYPE html>, and IE is very picky about that. Fixing the html fixed the problem.

**Comment by lnewson** [comment] 2020-05-09 06:05
Hi,

I'm going to close this because of its age and because in the latest TinyMCE versions it now does prevent initializing on unsupported elements such as table cells and logs the following error in the console:
```
Could not initialize inline editor on invalid inline target element <td style=​"width:​200px;​height:​200px;​" id=​"tinyMceTesting">​
```
If you're still able to reproduce the issue using a supported inline target in the latest version of TinyMCE, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 06:05 UTC
Labels: browser: ie11, type: bug
