### ISSUE TITLE
DevTools failed to parse SourceMap

### ISSUE THREAD

**Issue by bjkippax** [tinymce/tinymce#5589] opened 2020-04-21 10:25 UTC
**What is the current behavior? Describe the bug**

When loading a component with the tinymce component imported on it there are console errors relating to missing source maps files. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

This is a pretty basic issue, so I won't be included a reproduction.

**What is the expected behavior?**

I cannot see these in the node_modules directory so these files will need adding, or the reference to the sourcemap in the CSS files will need removing.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Using the TinyMCE-vue@3.2.0 and TinyMCE@5.2.0 packages.
All Browsers/OS'
It did not work in the previous version(s) we've had installed.

![image](https://user-images.githubusercontent.com/36036691/79855307-b57d4000-83c2-11ea-855b-b39dade5b3de.png)

**Comment by lnewson** [comment] 2020-04-21 10:27
This was fixed in TinyMCE 5.2.1, so marking this as a duplicate of https://github.com/tinymce/tinymce/issues/5489

**Closed by lnewson** 2020-04-21 10:27 UTC

**Comment by bjkippax** [comment] 2020-04-21 10:42
> This was fixed in TinyMCE 5.2.1, so marking this as a duplicate of #5489

Really pleased with the prompt response @lnewson - Thank you.
