### ISSUE TITLE
After increasing the font size text deprecation line is not aligned properly

### ISSUE THREAD

**Issue by Rafiul-Islam** [tinymce/tinymce#8369] opened 2023-01-04 06:32 UTC
**What is the current behavior? Describe the bug**
Text deprecation line is aligned top of the text after increasing the font size.
[Error Image](https://i.postimg.cc/W32SVgnM/Capture.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**
[Expected behavior Image](https://i.postimg.cc/BnpBgXsb/Capture.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE Version `2.1`

**Comment by yacodes** [comment] 2023-02-13 11:25
Hi @Rafiul-Islam, unfortunately TinyMCE 2.x is no longer supported. TinyMCE 5 is our supported community version, I'd suggest [upgrading](https://www.tiny.cloud/docs/migration-from-4x/) and seeing if that fixes your issue. I'm going to close this since it's not a version we are supporting, but if you can reproduce on a supported version then please let us know and we'll reopen this issue.

**Closed by yacodes** 2023-02-13 11:25 UTC
