### ISSUE TITLE
Force not to load plugins dynamically?

### ISSUE THREAD

**Issue by AlecTaylor** [tinymce/tinymce#3500] opened 2017-02-21 12:19 UTC
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
TinyMCE gives a bunch of 404s for http://localhost:4200/skins/lightgray/skin.min.css &etc.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

**What is the expected behavior?**
I've minified all the .css and .js files. TinyMCE loads just fine. Now I want to get rid of the 404s; as visible in the console/network tabs.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Looks like this has been wanted since at least 2014: http://stackoverflow.com/a/26658959

**Comment by fyrkant** [comment] 2017-02-22 14:17
Have you set the `skin_url` option correctly?

**Comment by AlecTaylor** [comment] 2017-02-25 02:01
@fyrkant well my [`skin_url`](https://www.tinymce.com/docs/configure/editor-appearance/#skin_url) is currently set, however it is looking for specific .css files within there.

Whereas I have already loaded those .css files in my bundle. So I just want it to not try to dynamically load anything (as both JS and CSS have already been loaded outside TinyMCE).

**Comment by donShakespeare** [comment] 2017-02-25 07:35
If you have already loaded the CSS try:
`skin_url: 'path/to/own/empty/skin`
____________
Wishful thinking
------------
It would be good if we had
`plugin_url: '/basepath/to/own/stuff/'`  

Or force default plugins to load via
`external_plugins`

**Comment by fyrkant** [comment] 2017-02-27 08:25
@AlecTaylor Have you tried setting `skin: false`? I think should be possible to disable the loading of the normal skin files.

**Comment by vupham2909** [comment] 2017-06-21 03:51
@fyrkant I having the same issue as @AlecTaylor said that TinyMCE keep appending stylesheet `skin.min.css` and `content.inline.min.css` link to `<head>`  every time a editor init. If we have many editors on a same page then these pair of stylesheet links keep appending manytime.
I also tried setting `skin: false` but appear to me that this setting make return a default skin location url : `/skins/lightgray/` instead of disable the loading of normal skin files.
Any suggestion to disable to not load these files dynamically in case these styles are bundled and already loaded ?

**Comment by gauthierm** [comment] 2018-01-04 00:59
`skin: false` seems to work in the latest release.

**Comment by lnewson** [comment] 2020-05-08 09:16
As noted above this appear to have been fixed, as I'm unable to reproduce the issue in the latest versions of TinyMCE. Looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.2, so I'm going to close this. However, if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:16 UTC
Labels: status: escalated, type: bug
