### ISSUE TITLE
tinymce problem with tbody tags

### ISSUE THREAD

**Issue by edelmoral** [tinymce/tinymce#3010] opened 2016-06-20 04:53 UTC
the editor doesn't like multiple tbody tags inside a table, and this is part of the standards:
- [HTML 4.01 Specification](https://www.w3.org/TR/html401/struct/tables.html#h-11.3.1)
- [HTML5](https://www.w3.org/TR/html5/tabular-data.html#the-tbody-element)

steps to reproduce it:
1. open [http://codepen.io/edelmoral/pen/rLMdeO](http://codepen.io/edelmoral/pen/rLMdeO).
2.  with the console open (F12 in most browsers) select with the mouse the rows 2 and 3.. or 3 and 4, in fact any couple of rows below the 2nd.
3. an exception is thrown:
   `tinymce.min.js:49 Uncaught TypeError: Cannot read property 'x' of undefined`
4. with the dev version of tinymce you'll see:

```
plugin.js:1065 Uncaught TypeError: Cannot read property 'x' of undefined
(anonymous function)    @   plugin.js:1065
cellSelectionHandler    @   plugin.js:1566
fire    @   EventDispatcher.js:114
fire    @   Observable.js:54
delegate    @   EditorObservable.js:121
executeHandlers @   EventUtils.js:268
defaultNativeHandler    @   EventUtils.js:295
```

This is inside the table plugin. The exception thrown is bothering the selection object and its actions. This happens in all selections made inside a table with multiple tbody tags from the 2nd tbody rows.

Aditional references:
[http://stackoverflow.com/questions/3076708/can-we-have-multiple-tbody-in-same-table](http://stackoverflow.com/questions/3076708/can-we-have-multiple-tbody-in-same-table)
[http://it.toolbox.com/blogs/paytonbyrd/tbody-to-the-rescue-4097](http://it.toolbox.com/blogs/paytonbyrd/tbody-to-the-rescue-4097)
[Learn to use the TBODY Element to Make Your Tables More Accessible](http://webdesign.about.com/od/tables/a/aa092606_4.htm)

from [http://www.w3.org/TR/html-markup/table.html#table](http://www.w3.org/TR/html-markup/table.html#table):

> An optional caption element, followed by zero or more colgroup elements, followed by an optional thead element, followed by ... **zero or more tbody elements** or one or more tr elements ...

 #thanks in advance!

**Comment by lnewson** [comment] 2020-05-09 07:23
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 07:23 UTC
Labels: plugin: table, type: bug
