### ISSUE TITLE
Lists change order of lines

### ISSUE THREAD

**Issue by arvidne** [tinymce/tinymce#3063] opened 2016-07-14 06:47 UTC
If you mark three lines of text, and then click the bullet list or ordered list buttons the order of lines gets switched.

First
Second
Third

Gives you:
- Second
- First
- Third

or
1. Second
2. First
3. Third

**Comment by acshef** [comment] 2016-07-14 14:46
Happens in 4.4.0

**Comment by spocke** [comment] 2016-07-18 07:04
We fixed this bug now and it only happens if the advlist plugin is enabled. This will be part of the next release you can try out the nightly build in the meantime to help us verify that the issue is solved on your end as well. Thanks.

**Closed** 2020-04-20 12:52 UTC
Labels: plugin: lists, status: verified, type: bug
