### ISSUE TITLE
Uncaught module definition dependecy not found: tinymce/ui/Rect

### ISSUE THREAD

**Issue by wengfujia** [tinymce/tinymce#2562] opened 2015-12-16 12:40 UTC
i use the imagetool plugin,find the error.Uncaught module definition dependecy not found: tinymce/ui/Rect.

**Comment by spocke** [comment] 2015-12-16 12:50
Seems to work fine on the tinymce.com site. Couldn't reproduce it with the downloaded 4.3.2 version either. So need more details here. Thanks.

**Comment by wengfujia** [comment] 2015-12-16 13:07
yes,i use the v4.3.2 down from the tinymce.com site.

i use it like this:
var editorGetHtml = function () {
    return tinymce.activeEditor.getContent();
}

var htmlContent;

var editorSetHtml = function (html) {
    if (tinymce.activeEditor) {
        tinymce.activeEditor.setContent(html);
    }
    else {
        // If not initialized yet, we need to delay it
        htmlContent = html;
    }
}

tinymce.init({
    selector: '#txtContent',
    content_style: 'img {  max-width: 100%; }',
    plugins:["image","imagetools"],
    toolbar: false,
    menubar: false,
    statusbar: false,
    autosave_ask_before_unload: false,
    max_height: 600,
    min_height: 160,
    height: 280,
    setup: function (editor) {
        editor.on('init', function (e) {
            if (htmlContent) {
                editor.setContent(htmlContent);
            }
        });
    }
});

i use the plugins:["image","imagetools"],if i remove the imagetools plugin,the error is none,i add it,the error is :  Uncaught module definition dependecy not found: tinymce/ui/Rectc @ plugin.min.js:1d @ plugin.min.js:1(anonymous function) @ plugin.min.js:1(anonymous function) @ plugin.min.js:1

thanks.

**Comment by spocke** [comment] 2015-12-16 13:37
Hmm, make sure you clear your cache and use the latest version of tinymce with the imagetools plugin. Verify the tinymce version by checking tinymce.minorVersion should be "3.2" I couldn't reproduce this anywhere.

Created a fiddle here:
http://fiddle.tinymce.com/imfaab

Load fine.

**Comment by wengfujia** [comment] 2015-12-16 14:09
yeah,i rebuild this site`s tinymce with node.js.i found it work...thank you very much!

**Comment by spocke** [comment] 2015-12-16 15:25
Nice. Closing.

**Closed by spocke** 2015-12-16 15:25 UTC
Labels: needs: more info, type: bug

**Comment by rajkishor-89** [comment] 2016-09-07 07:35
@wengfujia #2932
