### ISSUE TITLE
Rtl applies randomly to  (ul or li ) or (ol or li)

### ISSUE THREAD

**Issue by AliMejbar** [tinymce/tinymce#6619] opened 2021-03-14 12:23 UTC
**What is the current behavior? Describe the bug**

when applying rtl (ul or ol) the dir = "rtl" applies randomly sometimes to the ul or ol itself or it applies to the li inside. When setting rtl before inserting the list it does not apply dir = "rtl" to the ul or ol but rather the first il added by the button.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**
Add the dir = "rtl" to both or only the "ul" or "ol"

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMce : TinyMCE 5.5.0
Chrome : Version 89.0.4389.90 (Build officiel) (64 bits)
Os : Windows 10 version 20H2

**Comment by SimonFc** [comment] 2021-03-16 12:33
Closing as duplicate of #5355

The randomness you experience is most likely due to the varying editor selection you have as the directionality will simply be applied to the selected element(s). This is a known compatibility issue with the directionality plugin and lists as shown in the linked issue.

**Closed by SimonFc** 2021-03-16 12:33 UTC
