### ISSUE TITLE
[5.3.0 BUG] Click toolbar buttons caused scroll to top

### ISSUE THREAD

**Issue by netlabc** [tinymce/tinymce#5691] opened 2020-05-22 07:16 UTC
https://s1.ax1x.com/2020/05/22/YO6P29.png

Hello, I've found a bug happens in TinyMCE 5.3.0, which was normal in 5.2.2.

When the height of content greater then editor height, there will be scroll bar.

I pull the scroll bar to the bottom, select the last line of content, click 'Blod' / 'Underline' / 'Italic' in toolbar.

**Then the scroll bar will always jump to the top of the editor.**

System: Windows 10
Browser: Firefox 76.0.1 (x64)

This issue doesn't happen in TinyMCE 5.2.2, please check.
Thank you very much!

Best regards

**Comment by cfconsultancy** [comment] 2020-05-23 19:00
Tested in all browsers windows 10 tinymce 3.5.0 and cannot reproduce that, so it must something else in you're code

**Comment by netlabc** [comment] 2020-05-24 05:57
> 
> 
> Tested in all browsers windows 10 tinymce 3.5.0 and cannot reproduce that, so it must something else in you're code

Thanks for reply!
I've disabled all extra codes but the issue still exists in Firefox.
It doesn't happens in Chrome.

![](https://s1.ax1x.com/2020/05/24/YzcK8f.gif)

**Comment by lnewson** [comment] 2020-05-24 23:11
I can replicate this bug when using our default content css. If I use a custom one, then it doesn't occur. We recommend using the content css from your site anyways, however our default shouldn't be causing this so we'll get it fixed up.

**Comment by netlabc** [comment] 2020-05-25 06:04
> I can replicate this bug when using our default content css. If I use a custom one, then it doesn't occur. We recommend using the content css from your site anyways, however our default shouldn't be causing this so we'll get it fixed up.

Thank you very much!

**Comment by lnewson** [comment] 2020-05-27 04:55
We've just released TinyMCE 5.3.1 to the community, which includes a fix for this issue. Please let us know if you continue to experience any issues.

**Closed by lnewson** 2020-05-27 04:55 UTC
Labels: 5.x, browser: firefox, resolution: fixed in coming release, status: escalated, type: bug
