### ISSUE TITLE
[BUG] Multiple toolbars are in the same row instead of separate rows

### ISSUE THREAD

**Issue by ronfogel** [tinymce/tinymce#4819] opened 2019-02-09 10:23 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
multiple toolbars (toolbar1, toolbar2, toolbar3) are in the same line (both implementations - toolbar1,2,3 or toolbar as an array)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/OBgaab

**What is the expected behavior?**
Each toolbar should be in a separate line

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5+
I believe it's not browser/os related issue, but I am using macOS Mojave v10.14

It worked in TinyMCE 4.9.2 and below.

**Comment by TheSpyder** [comment] 2019-02-09 11:09
Oh this is embarrassing. The new toolbar design called for toolbars to wrap rather than allow multiple lines as in the previous design. What you're seeing is intentional; rather than drop toolbar(n) support completely we merge the configs into a single toolbar.

However it seems the task to update the documentation was incorrectly assigned and completely left out of the release, it's not in the migration guide and we also left the [toolbar(n) documentation](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbarn) in place.

I'll make sure the documentation is updated next week, my sincere apologies. This was one of the changes we were wondering if we'd get community feedback on, we would like to hear about cases where multiple toolbars are used. It's not difficult to bring them back if we need to.

We are also working on a "more drawer" design which will enforce a single row toolbar with groups overflowing into a second toolbar that is hidden by default.

**Comment by ronfogel** [comment] 2019-02-09 11:47
Well, my use case is as follows:
I wanted to have a separation between styling and rest (all the buttons that changes the style in one row, and all the other in a different row)
<img width="1314" alt="screen shot 2019-02-09 at 13 45 34" src="https://user-images.githubusercontent.com/16741829/52520333-1498de00-2c71-11e9-839a-7c1970c5f753.png">

It's not that important for me, I dont mind having them in the same row, though I would prefer to have in a separate rows.

**Comment by WarwickGoatee** [comment] 2019-02-22 13:43
Losing the option of multiple toolbars would be a problem for us - I'd very much support keeping it in as an option. Many people upgrading from 4 to 5 will end up with broken layouts as a result...

**Comment by guiligan** [comment] 2019-02-24 14:39
We use 2/3 rows in our editor leaving our custom plugins' buttons in different rows, allowing our users to find their expected functionality faster and easier than if merged in a single line with all formating options.

**Comment by JerimSD** [comment] 2019-03-05 16:10
Hi, I thought it was a bug too.
We use different rows to separate functionalities exactly like @ronfogel
And just like @WarwickGoatee said upgrading from v4 to v5 has resulted in a broken layout for us.

**Comment by halfninja** [comment] 2019-03-07 12:18
I think it would be fine to have this new behaviour by default, as long as you can provide an init option to allow us to go back to the old behaviour with multiple toolbars. There are many reasons why they are useful.

@TheSpyder is the documentation still due to be updated?

**Comment by TheSpyder** [comment] 2019-03-07 12:29
No, I logged it as a documentation ticket and it fell through the cracks in the lead-up to release.

This is one of the regression issues we are discussing internally. There has been enough requests for it that we are probably going to reimplement multiple toolbars. We haven't scheduled the work yet but we are thinking through the design considerations of this.

Sorry for not updating this ticket, I'll make an effort to do better.

**Comment by ronfogel** [comment] 2019-04-03 17:55
@TheSpyder Is there any progress? any plans for bringing it back?

**Comment by TheSpyder** [comment] 2019-04-03 23:39
@ronfogel it looks like we will bring it back, yes. However other issues (see the pinned list) have taken priority at the moment.

**Comment by zortext** [comment] 2019-04-09 10:33
Looks like tinymce team won't  bring the multiple toolbars back. 
BUT... I found 2 HACKS to bring the functionality back.

**METHOD 1**
Using a single pipe  "|" character to seperate rows.
**Explanation:** If the tool bar width is larger than editor width, toolbar will be broken at the pipe.
**Demo:** https://codepen.io/zortext/pen/VNKovN
**Config:**
`{
 toolbar:  'undo redo formatselect fontsizeselect  bold italic strikethrough forecolor backcolor permanentpen  link image media pageembed |  alignleft aligncenter alignright  alignjustify numlist bullist outdent indent removeformat  addcomment'
}`

**METHOD 2**
Add any builtin menu item to menu where you want to break and add some custom css
**Explanation:** Adding an invisible group item and expanding it with a zero height and full-width will break toolbar
**Demo:** https://codepen.io/zortext/pen/wZgBpG
**CSS:**
```
/* Breaks at 5th group item */
.tox-tinymce .tox-toolbar > .tox-toolbar__group:nth-child(5) {
    height: 0;
    overflow: hidden;
    width:100vw;
}

```

**Comment by halfninja** [comment] 2019-04-09 10:37
@zortext who has told you that it's not coming back?

**Comment by zortext** [comment] 2019-04-09 10:39
> @zortext who has told you that it's not coming back?
https://github.com/tinymce/tinymce/issues/4819#issuecomment-462035233

**Comment by halfninja** [comment] 2019-04-09 10:42
@zortext I would have thought that would be overridden by the more recent comment above yours saying:
> it looks like we will bring it back, yes

**Comment by zortext** [comment] 2019-04-09 10:45
Yes you are right. It has been 2 months issue opened. Have no idea how long will it take.  Until it comes back the 2 hacks may help.

**Comment by zortext** [comment] 2019-04-09 10:52
@halfninja have updated original comment and deleted my useless comments to keep things clean

**Comment by TheSpyder** [comment] 2019-04-09 11:53
Look, I saw all of the deleted messages, and I'm sorry that this isn't higher on our priority list. We have a lot of things to get through.

Method 2 is actually not far off the technique we've discussed internally for implementing this. We need to make sure it works with things like keyboard navigation so it's not _quite_ as easy as it looks.

**Comment by martyf** [comment] 2019-04-26 04:20
Stumbled across this issue right now actually. Just adding my +1 for this too - been working on the base framework for a new job and any multiple toolbars aren't working like the docs suggest.

I can see it's already on your to-do list, but just wanted to add that I feel the biggest reason why this is a good feature is to help breaking down the length of toolbar rows and increasing usability and button access - it's like the whole reading line length in usability studies - too long and the eye can get confused when it does eventually start to wrap - especially with larger-scale editors that rely on the toolbar (and don't use a menu).

At the end of the day, the buttons in the toolbar do still work now (so it's not mission critical), and I don't doubt you'll tick it off the list when you can.

**Comment by jhaungs** [comment] 2019-04-28 00:34
My web platform stores tinymce configurations in a database, so my clients can configure their editors however they want. Most of them organize the icons in some logical fashion on multiple toolbars, so to me it's a very important feature, and its removal is a drastic change. I won't be able to upgrade to 5.x until it's fixed.

**Comment by okainov** [comment] 2019-05-11 15:18
+1 I'd like to still have option to keep toolbar on several rows *regardless* of total width of the screen

**Comment by TheSpyder** [comment] 2019-05-31 00:26
Update: This is well underway. I'm not sure if it will be complete in time for the 5.0.7 release, but if not it should definitely be in 5.0.8.

**Comment by TheSpyder** [comment] 2019-06-06 03:55
We had some last minute issues that prevented it from going into 5.0.7 but it has just been merged to master. 5.0.8 should be released before the end of the month.

**Closed by TheSpyder** 2019-06-06 03:55 UTC
Labels: 5.x, status: escalated, status: regression

**Comment by lnewson** [comment] 2019-06-18 03:09
TinyMCE 5.0.8 has just been released to the community, which includes the ability to use multiple toolbars again!

**Comment by teells** [comment] 2019-10-15 21:01
I can confirm with @blairzotron that using arrays like in 4.x is not working to render toolbars on multiple lines in 5.0.16.

`"toolbar":"["formatselect fontselect | bullist numlist | outdent indent | cut copy paste pastetext pasteword removeformat | undo redo", "bold italic underline strikethrough forecolor | alignleft aligncenter alignright alignjustify | link unlink table hr | image media |"]`

Everything still renders on one line. Some items are missing now too, but I assume I need to update the control's name.

**Comment by lnewson** [comment] 2019-10-15 21:16
@teells @blairzotron can you please include a fiddle to show your issue? As I tested using the example provided above and it works fine: http://fiddle.tinymce.com/BSgaab

@teells it's also worth noting that you seem to have a misplaced quotation mark before the start of the array, so that might be part of your issue.

**Comment by vanilla-thunder** [comment] 2020-06-09 00:35
just in case seomeone is still experiencing same problem:
make sure your toolbar config value is an array and not a string
correct: `'toolbar': ['button button button | ....'];`
wrong: `'toolbar': 'button button button | ....';`
