### ISSUE TITLE
tinymce does not read <pre> tags properly, messes up code sample

### ISSUE THREAD

**Issue by scorpanog** [tinymce/tinymce#6009] opened 2020-09-04 01:42 UTC
**What is the current behavior? Describe the bug**
When using TinyMce to add html sample code, insertion works great and content is correctly formatted with `<pre>` tags. when content is read on edit page html code is changed: eidtor closes and opens `<pre>` tags in multiple places and that messes up all formatting.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
steps to reproduce(it requires saving information somwwhere db in my case. I can provide all the screenshots or a video
1. create a text snippet and add code sample containing several html tags, choosing html in code sample popup
2. hit ok and it will become a coloured html snippet in editor. 
3. now saving content of that editor into db.
4. loading edit page.
5. when editor is loaded the content looks like a sandwich with html code betwen two pinkish layers.
6. checking source reveils two `<pre>` tags before html snipped and after, 
7. when loading up the same content just into a textarea without editor, html code looks proper.

**What is the expected behavior?**
when content is loaded back into editor it looks proper with html code sample being in a pink block.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce v5, firefox 79.0 on macos 10.15.6. I have not tried it on any other versions of the editor. Trying to make it work for my tech blog 
I am using full configuration with non-premium plagins copied exactly from config page.

**Comment by lnewson** [comment] 2020-09-04 05:43
I'm going to close this as a duplicate of #5559 and #5522, as this isn't actually an issue with TinyMCE and is an encoding issue, as you need to ensure to encode the HTML content stored inside a `textarea`. He's a working example to demo: https://fiddle.tiny.cloud/Nrhaab.

In this demo, I've also included a raw textarea to show why it needs to be encoded, as you can see the browser will decode it when rendering the text. Without properly escaping the content, it treats it as being something like this:
```
<pre class="language-markup"><code>
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
</head>
<body>
  <h1>Heading</h1>
</body>
</html>
<code></pre>
```
As you can see, that's invalid HTML and why it ends up being split when you're loading it back into the editor. As such, the solution is to ensure you accurately HTML encode the string from your backend when rendering it. The alternative is to use the `editor.setContent(html)` API which would work around this (as noted in the previously linked issues).

**Closed by lnewson** 2020-09-04 05:43 UTC

**Comment by scorpanog** [comment] 2020-09-04 12:38
Thanks, that did resolve all of my issues. Now editing and display works much better.

I agree it should be in the docs.

thanks again!
