### ISSUE TITLE
toolbar_sticky should also work for editor's parent element

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5227] opened 2019-11-02 08:35 UTC
I'm giving a try to TinyMCE 5.1.1 and I see that sticky toolbar only works when scrolling the whole page, but not when I put the editor inside of a scrollable element.

http://fiddle.tinymce.com/hUgaab/3

It would be nice the feature works also in a scrollable element. Please, note that Find and Replace dialog does stick to the top of the scrollable parent (almost) properly.

ps. `toolbar_sticky` is not documented.

**Comment by lnewson** [comment] 2019-11-04 11:02
TinyMCE in general doesn't currently have support for being inside a scrollable element and as such a number of other issues fallover as well. As such I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5097 which is what we're currently using to track making TinyMCE work properly inside a scrollable element.

As for the documentation issue you pointed out, the documentation site (with the exception of the changelogs) reflect the enterprise version of TinyMCE and 5.1 hasn't been released to enterprise yet. They'll be updated once 5.1 is released to enterprise, so it should be up later this month. For now, here's the docs in the documentation repo: https://github.com/tinymce/tinymce-docs/blob/feature/DOC-405/_includes/configuration/toolbar_sticky.md

**Closed by lnewson** 2019-11-04 11:02 UTC

**Comment by alecpl** [comment] 2019-11-04 11:06
Fair enough. Just note it is not about the inline mode.
