### ISSUE TITLE
Initial font update of text with multiple fonts fails

### ISSUE THREAD

**Issue by jeffhoffman1** [tinymce/tinymce#4205] opened 2018-02-05 20:51 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug report
**What is the current behavior?**
If you type two lines of text and give them different fonts, and then highlight both of them and attempt to give them the font of the currently selected the first block is changed to the default font and the second block is not updated
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/Fjgaab
**What is the expected behavior?**
All selected text should change to the selected option
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.6 On Chrome/Windows 10. Did not work in earlier versions either.

**Comment by lnewson** [comment] 2020-05-08 08:56
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 or 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.8. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 08:56 UTC
Labels: status: escalated, status: verified, type: bug
