### ISSUE TITLE
bullist and numblist options are not shown in toolbar

### ISSUE THREAD

**Issue by prcongithub** [tinymce/tinymce#3342] opened 2016-11-24 05:49 UTC
We have suddenly started facing issue where numlist, bullist icons do not appear in the toolbar.
This was a working code for a long time and since yesterday it stopped showing the list icons.

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
```
tinymce.init({
          selector: ".editable-mce",
          menubar: false,
          toolbar: 'bold italic underline | bullist numlist outdent indent',
          inline: true,
          forced_root_block: "p",
          forced_root_block_attrs: {
            'class': 'tiny-mce-root',
            'placeholder': $(selector).attr('placeholder')
          },
          setup: function(ed) {
            ed.on('init', function(args) {
              if(view.$el.find('p.tiny-mce-root').text().trim() == '') {
                view.$el.find('p.tiny-mce-root').addClass('placeholder'); 
              } 
            });
          }
        });
```

**Comment by spocke** [comment] 2016-11-24 06:13
Just enable the lists plugin. We removed the list buttons from core since it was using the browsers built in broken behavior and we have a lot of bug reports that would be resolved by using our custom lists implementation. Thanks for reporting this though.

**Comment by prcongithub** [comment] 2016-11-24 06:16
I tried enabling the lists plugin, but that still didn't work. Enabling advlist worked though.
```
tinymce.init({
          selector: selector,
          menubar: false,
          plugins: "advlist",
          toolbar: 'bold italic underline | bullist numlist outdent indent',
          inline: true,
          forced_root_block: "p",
          forced_root_block_attrs: {
            'class': 'tiny-mce-root',
            'placeholder': $(selector).attr('placeholder')
          },
          setup: function(ed) {
            ed.on('init', function(args) {
              if(view.$el.find('p.tiny-mce-root').text().trim() == '') {
                view.$el.find('p.tiny-mce-root').addClass('placeholder'); 
              } 
            });
          }
        });
```

**Comment by spocke** [comment] 2016-11-24 07:38
I've investigated this now and it's a bug in the cdn version only since the plugin detection logic was wrong. We will fix this and release it in 4.5.1 thanks for reporting.

**Comment by prcongithub** [comment] 2016-11-24 08:59
I am using version 4.
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
I am wondering how this upgrade has affected an older version?

**Comment by fyrkant** [comment] 2016-11-24 09:09
If you don't define what minor version you want from the CDN you automatically get the latest one (4.5), so when using `<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>` you are in fact getting 4.5 (you can verify this by [opening the link in your web browser](http://cdn.tinymce.com/4/tinymce.min.js) and see the full version written at the top of the file). 

Use `<script src="//cdn.tinymce.com/4.4/tinymce.min.js"></script>` like spocke said to get the previous 4.4 release.

**Comment by prcongithub** [comment] 2016-11-24 12:14
Yes, got it working with 4.4.
Thanks

**Comment by aCMoFoCord** [comment] 2016-11-25 15:59
Just came across this issue today, enabling the 'lists advlist' plugins seems to have fixed things.
Thanks

**Comment by boena** [comment] 2016-12-02 13:39
Also got it working with 4.4 in the meantime.

**Comment by HunterMeyer** [comment] 2016-12-08 04:11
Anyone else experiencing issues with applying bullet lists? I've recently began having the following issue: when highlighting a number of lines and then pressing the list button, the bullet list is applied to the entire document, not to my cursor selection.

Here's a visual: 
![example-480](https://cloud.githubusercontent.com/assets/4690516/20997324/6da84b9a-bcd2-11e6-837b-ab0510451640.gif)

**Comment by spocke** [comment] 2016-12-08 06:14
Use paragraphs not brs and it should work fine. We haven't got around adding br support just yet.

**Comment by ruant** [comment] 2016-12-13 14:50
Just a quick addon for this.
Please update the docs.

https://www.tinymce.com/docs/advanced/editor-control-identifiers/#toolbarcontrols
still lists (no pun intended) bullist and numlist under the core plugin.

**Comment by PiNotEqual3** [comment] 2016-12-14 13:10
This bug broke my live system. Does the cdn uses unstable versions or was it just a mistake?

Maybe you could document that the cdn version does change and how you can get a fixed/stable version: https://www.tinymce.com/download/

Am I save with //cdn.tinymce.com/4.4/tinymce.min.js or will this be changed too?

**Comment by fyrkant** [comment] 2016-12-15 07:50
@PiNotEqual3 I'm sorry that your system broke because of this, the CDN is not using unstable versions per se, but like I wrote earlier in this thread: 

> If you don't define what minor version you want from the CDN you automatically get the latest one (4.5), so when using <script src="//cdn.tinymce.com/4/tinymce.min.js"></script> you are in fact getting 4.5 (you can verify this by opening the link in your web browser and see the full version written at the top of the file).

> Use <script src="//cdn.tinymce.com/4.4/tinymce.min.js"></script> like spocke said to get the previous 4.4 release.
 
I understand that this isn't clearly stated in the documentation, we will fix this as soon as possible.

**Comment by PiNotEqual3** [comment] 2016-12-15 08:17
@fyrkant Thanks a lot. I really appreciate that.

**Comment by foxontherock** [comment] 2017-03-02 16:16
Why do I need to search in the issues, inste4ad of the documentation, to find why my "bulllist / numlist" are no longer working after moving from 4.x to 4.5!!! Suggestion: Auto-add the "lists" plugin when the toolbar constains bullist or numlist. OR edit the documentation to add informations about that mandatory required plugin.
[https://www.tinymce.com/docs/advanced/editor-control-identifiers/](https://www.tinymce.com/docs/advanced/editor-control-identifiers/)

**Comment by donShakespeare** [comment] 2017-03-02 20:01
Because it is still a bug (?)

**Comment by sitecarp** [comment] 2017-04-23 06:12
This bug now seems to affect both the CDN _and_ non-CDN versions as of 4.5.6 (possibly earlier versions). The "lists" plugin alone (without "advlist") doesn't work.

**Comment by spocke** [comment] 2017-04-23 06:19
Make sure you have the latest version. Can't reproduce it here: https://jsfiddle.net/mxh635df/

**Comment by sitecarp** [comment] 2017-04-23 06:31
Oops, you're right, it affects ONLY the non-CDN version 4.5.6.
"//cdn.tinymce.com/4/tinymce.min.js" works.

**Comment by sitecarp** [comment] 2017-04-26 03:47
Can anyone confirm the "lists" plugin alone (without "advlist") still doesn't work for non-CDN version 4.5.7?

**Comment by AlaeddineMessadi** [comment] 2017-07-20 15:04
The 'lists' plugin alone is enough

**Comment by rusllonrails** [comment] 2017-09-12 11:26
@AlaeddineMessadi you right :tada: 

Just adding of `lists` plugin to plugins list enabled fixed issue for me in Tinymce `4.6.3`

**Closed** 2020-04-26 12:45 UTC
Labels: plugin: advlist, plugin: lists, status: verified, type: bug

**Comment by codingyourlife** [comment] 2021-05-12 12:41
adding `plugins: 'lists advlist'` solved my problem. But it also works without advlist. What is it? Is it needed? advilist alone does not work.

**Comment by eybel** [comment] 2022-04-18 18:30
Just installed a brand new copy on my React app, followed the Docs that already include the **advlist**, **lists** plugins with **bullist** and **numlist** under "toolbar" not showing at all.

I used the example code from here: https://www.tiny.cloud/docs/integrations/react/

**Comment by alexgsummer** [comment] 2022-06-30 01:12
@eybel I was facing the same issue using tinymce v6 with React. The example React integration example you linked above is for v5, but the example configures plugins like this:
```
plugins: [
  'advlist autolink lists link image charmap print preview anchor',
  'searchreplace visualblocks code fullscreen',
  'insertdatetime media table paste code help wordcount'
],
```
That seems strange to me to pass an array of strings where the strings are space separated values. I tried passing a single string like this:
```
plugins: 'autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
```
and now bullet and number lists appears in the toolbar and works as expected.

**Comment by TheSpyder** [comment] 2022-06-30 01:27
@alexgsummer yes the weird “array of space separated strings” style worked for a long time but was unintentional. We removed it in version 6.

**Comment by eybel** [comment] 2022-07-01 12:26
> @alexgsummer yes the weird “array of space separated strings” style worked for a long time but was unintentional. We removed it in version 6.



> @eybel I was facing the same issue using tinymce v6 with React. The example React integration example you linked above is for v5, but the example configures plugins like this:
> 
> ```
> plugins: [
>   'advlist autolink lists link image charmap print preview anchor',
>   'searchreplace visualblocks code fullscreen',
>   'insertdatetime media table paste code help wordcount'
> ],
> ```
> 
> That seems strange to me to pass an array of strings where the strings are space separated values. I tried passing a single string like this:
> 
> ```
> plugins: 'autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
> ```
> 
> and now bullet and number lists appears in the toolbar and works as expected.

Thank you both, cant remember how I solved it I think it was something with the array, glad the new version fixed it. Will start using latest one.

**Comment by judygab** [comment] 2024-02-22 17:40
> @eybel I was facing the same issue using tinymce v6 with React. The example React integration example you linked above is for v5, but the example configures plugins like this:
> 
> ```
> plugins: [
>   'advlist autolink lists link image charmap print preview anchor',
>   'searchreplace visualblocks code fullscreen',
>   'insertdatetime media table paste code help wordcount'
> ],
> ```
> 
> That seems strange to me to pass an array of strings where the strings are space separated values. I tried passing a single string like this:
> 
> ```
> plugins: 'autolink lists link image charmap print preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
> ```
> 
> and now bullet and number lists appears in the toolbar and works as expected.

This is the only thing that worked for me, thanks!

**Comment by faulknor82** [comment] 2024-06-29 17:34
To possibly save some future frustration. I tried resolving this issue for 3 hours and nothing worked, until...
I changed:
toolbar_mode: 'floating',

to:
toolbar_mode: 'embedded',

and it's working. There might be some conflict with how a floating toolbar versus an embedded toolbar is displaying.
