### ISSUE TITLE
Removing last character of a line makes the whole line append to the privious line.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2233] opened 2015-05-20 20:34 UTC
Caused by this changeset:
https://github.com/tinymce/tinymce/commit/7519f9c4bef9ced1564fec03a6994e5f36b09ca4

Description of problem:

Steps to reproduce:
1. Type something in "bold" font in the first line.
2. Hit "return" to switch to second line, press ctl+B to cancel "bold" 
3. Type something, then hit backspace to delete last character.

Expected result:
Only the last character in second line is removed.

Actual result:
Two lines are combined into one.(the second line append to the first line) and the cursor jump to the end of the original first line. 
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7521](http://archive.tinymce.com/develop/bugtracker_view.php?id=7521) posted by [bubdou](http://archive.tinymce.com/profile.php?name=bubdou)_

> _**Tags:** [chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by bubdou** [comment] 2015-11-18 06:59
Look like this issue was fixed in the v4.2.7 release.

**Comment by blackcathikari** [comment] 2016-07-25 01:58
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 01:58 UTC
Labels: browser: chrome, origin: tinymce.com, type: bug

**Comment by noprobz09** [comment] 2023-11-14 01:33
same issue in version ^5.1.1, im currently using "@tinymce/tinymce-vue": "^5.1.1",
![tinymce](https://github.com/tinymce/tinymce/assets/3793621/ac8fd23e-e134-4f4e-9aad-3e7d0a85bf22)
