### ISSUE TITLE
TtinyMCE 4 doesn't display base64 inline image when html loaded into the editor

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2105] opened 2015-02-15 05:01 UTC
If I try to load into the tinyMCE 4 editor an html containing a base64 encoded inline image, the image is not shown.  I am able to insert an encoded image once the editor is displayed using a plug-in.

Steps to reproduce:
1.Create a Web Form with a TextBox.
2.Assign the html string containing an encoded image to the TextBox.Text on Page_Load
3.Run.
4.See attached files
5.

Expected result: The image should be displayed in the tinyMCE.Editor

Actual result: The image is not shown.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7389](http://archive.tinymce.com/develop/bugtracker_view.php?id=7389) posted by [ChicoAlvar](http://archive.tinymce.com/profile.php?name=ChicoAlvar)_
> 
> _**Tags:** [msie chrome msie11 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by bilalhaider** [comment] 2016-11-13 18:27
Is there any help available around this issue?
the img's src attribute is removed by tinymce

**Comment by fyrkant** [comment] 2017-05-24 14:47
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Closed by fyrkant** 2017-05-24 14:47 UTC
Labels: browser: chrome, browser: ie, browser: ie11, origin: tinymce.com, type: bug

**Comment by lrossict** [comment] 2023-03-25 19:45
The issue is still there, years later, same scenario of the initial post
