### ISSUE TITLE
Inline editor toolbar does not position itself correctly in scroll container 

### ISSUE THREAD

**Issue by jcursoli** [tinymce/tinymce#5633] opened 2020-05-05 00:12 UTC
**What is the current behavior? Describe the bug**
When you create a scrollable container that is not the `window`, the editor does not detect a scroll and otherwise does not re-position the toolbar when you scroll.

Yes i know there is a `fixed_toolbar_container` option, but we don't want the toolbar to be fixed, and if we attach it to something like an element positioned with popper, there is an issue with overflows of the dialog pop-up(s). It would be ideal if you can pass in an element that points to the scroll container if it's needed.

https://codesandbox.io/s/immutable-lake-x9whx

**What is the expected behavior?**
the toolbar should scroll with the focused inline editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
1) tinymce-react@latest
2) tinymce@latest

**Comment by lnewson** [comment] 2020-05-05 00:14
Closing as a duplicate of https://github.com/tinymce/tinymce/issues/5097. Currently, TinyMCE doesn't support being rendered within a scrollable container sorry. So there is the linked feature request open to support that.

**Closed by lnewson** 2020-05-05 00:14 UTC
