### ISSUE TITLE
Toolbar options didn't change when empty line selected

### ISSUE THREAD

**Issue by talaat197** [tinymce/tinymce#9242] opened 2023-12-12 13:02 UTC
## 📝 Context
In version 6.8.0 tinyMCE when we select content with empty line at first and change options from toolbar for example the font-size or the text type.
1. The content changed correctly 
2. The toolbar options don't change and stay the same
3. The empty line format doesn't change

### ✔️ Expected result
- The toolbar options should be changed as well.
- The first empty line should have the same format as the content.

### ❌ Actual result
- the Toolbar options don't change and stay the same.
- the first empty line format doesn't apply and stays the same.

![image](https://github.com/tinymce/tinymce/assets/32524463/1e9619a8-65db-499d-a27a-15a468058c9f)

## 📃 Other details
- Browser: Chrome
- OS: Mac, Windows
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment] 2024-01-24 03:55
I can't reproduce this in 6.8.2. If it still happens, please create a replication case for us using a tool like TinyMCE fiddle or codepen.

**Comment by lostkeys** [comment] 2024-02-19 14:34
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.

**Closed by lostkeys** 2024-02-19 14:34 UTC
Labels: needs: more info
