### ISSUE TITLE
Insert the char "ę" is impossible

### ISSUE THREAD

**Issue by jsosnowski** [tinymce/tinymce#2870] opened 2016-04-21 09:10 UTC
TinyMce 4.3.10 blocks char "ę" - this is letter from Polish alphabet. The problem is only with this letter. 
Tested on Windows 7, Chrome and Firefox.

**Comment by acshef** [comment] 2016-04-22 15:24
Is this character being typed by your regional keyboard? I've tried copying and pasting "ę" into https://www.tinymce.com/docs/demo/basic-example/ and it works just fine.

**Comment by alecpl** [comment] 2016-04-23 11:35
With Polish keyboard setting we enter this letter using Right Alt and "e".

**Comment by alecpl** [comment] 2016-04-23 11:37
Works for me in Firefox on Linux, tested on tinymce.com.

**Comment by kloss7** [comment] 2016-04-24 09:58
Problem exists only on windows.

**Comment by spocke** [comment] 2016-04-26 03:05
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2016-04-26 03:05 UTC
Labels: component: keyboard, type: bug
