### ISSUE TITLE
Table cells have a leading space when entering data (IE Only)

### ISSUE THREAD

**Issue by AdamJorgenson** [tinymce/tinymce#2583] opened 2015-12-22 16:04 UTC
Table cells have a leading space when entering data (IE Only)

1 - Insert a table and begin entering data in a cell

Expected Result: Data is entered as typed

Actual Result: IE has a leading space in the table cell. The workaround is to backspace before entering any data.

**Comment by Afraithe** [comment] 2015-12-23 09:23
This seems to be a duplicate of #2518

**Comment by jhaines** [comment] 2015-12-30 04:53
Fixed as per #2518 Thanks for the report.

**Closed by jhaines** 2015-12-30 04:53 UTC
Labels: plugin: table, type: bug
