### ISSUE TITLE
Image not upload automatically after rotate using imagetools

### ISSUE THREAD

**Issue by ybqboy** [tinymce/tinymce#5705] opened 2020-05-28 03:04 UTC
**What is the current behavior? Describe the bug**
I configured the automatic_uploads to true and the images_upload_url, when the image lose focus in editor, if behaves good. But if I clicked a button outside of the editor, the image did not upload automatically.

**What is the expected behavior?**
After clicked a button outside of the editor, the image should also lose focus and upload the image to server automatically. My scenario is common, user edit the article using TinyMce, and under the editor there is a submit button like the image below,  if the last action the user is editing the image, when I click the submit button the image will be a blob image not a server side url. So is this a problem or can I manually upload the unsaved image before submit?
![image](https://user-images.githubusercontent.com/11812236/83093848-d37d4500-a0d2-11ea-8e2d-e60a3a7b29bc.png)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMce 5.3.0

**Comment by spocke** [comment] 2020-05-28 04:55
You should wrap your submit call with editor.uploadImages that way it will always upload any pending image blobs before saving the document. Why it doesn't automatically upload on rotate is to reduce uploads if say the image is rotated back and multiple times by the user a lot of images would get uploaded. All image uploads are async so the only way to guarantee that they get upload is to use the function mentioned above. You can read more herehttps://www.tiny.cloud/docs/general-configuration-guide/upload-images/
I'm closing this ticket since it's by design behavior.

**Closed by spocke** 2020-05-28 04:55 UTC
