### ISSUE TITLE
Gboard newline behavior

### ISSUE THREAD

**Issue by coreyoss** [tinymce/tinymce#6811] opened 2021-05-10 18:29 UTC
If I use Google's GBoard on an Android phone, I get some odd behavior around newline characters. I'm using the TinyMCE jQuery plugin on version 5.7.0, the GBoard version is v10.4.04, and the phone is a Samsung Galaxy S8 running  Android 9 (though it's been reproduced on several devices and versions of GBoard).

I've found 2 issues -
Issue 1:
- In a blank editor, type "Foo"
- The cursor should be immediately after the 2nd "o" (no spaces after)
- Press the return character
A new &lt;p&gt; tag is added below the first line, but the cursor remains in the same place. This works as expected if there's a space or "." character after the 2nd "o".

Issue 2:
- In a blank editor, type "Foo."
- Press the return character
- Type "Bar"
- Move the cursor to the beginning of the second line, immediately before "Bar"
- Press backspace
- The new text is all on one line and correct ("Foo.Bar"), but the cursor is between "Foo.B" and the "ar" rather than between "Foo." and "Bar"

**Comment by lnewson** [comment] 2021-05-11 22:37
For issue 1, that is a duplicate of https://github.com/tinymce/tinymce/issues/6352. Basically, it's a GBoard bug and is reproducibly natively (eg in a contenteditable div) and in other editors. As such, TinyMCE is limited with what it can do and may not be able to workaround the GBoard bug. It's possible issue 2 is also related to that, however I can't say for sure at this stage.

**Comment by mikkorantalainen** [comment] 2022-11-18 10:05
Both are actually TinyMCE bugs because loading `data:text/html,<div contenteditable=true>` doesn't show similar issues with GBoard.

The workaround https://github.com/tinymce/tinymce/issues/6352#issuecomment-1079508660 can avoid the issue 1 but I don't know workaround for the issue 2.

I would guess the problem is that TinyMCE modifies browser native selection range before flushing the whole event queue which results in later events in the queue to be applied to incorrect selection range. All changes to selection should also pass through the event queue (basically apply only via `setTimeout(..., 0)`) to fully _syncronize_ to IME emitted events.

**Closed** 2024-06-14 00:50 UTC
