### ISSUE TITLE
Toolbar is not positioned properly in Distraction free mode 

### ISSUE THREAD

**Issue by krishnaeverestengineering** [tinymce/tinymce#6124] opened 2020-10-20 09:38 UTC
<img width="1263" alt="Screenshot 2020-10-20 at 3 07 05 PM" src="https://user-images.githubusercontent.com/55732888/96568792-f3154400-12e5-11eb-84b8-4281a8ef55f1.png">

At the same position in the line on every sentence toolbar was mispositioned. Any fixes to this? btw we are using 4.9.11 version.

**Comment by JamesToohey** [comment] 2020-10-22 06:32
Hi @krishnaeverestengineering, unfortunately TinyMCE 4.9 is no longer supported except for major issues. TinyMCE 5 is our supported community version, I'd suggest upgrading and seeing if that fixes your issue. I'm going to close this since it's not a version we are supporting, but if you can reproduce on a supported version then please let us know and we'll reopen this issue.

**Closed by JamesToohey** 2020-10-22 06:32 UTC
