### ISSUE TITLE
TinyMCE Toolbar Disappears

### ISSUE THREAD

**Issue by TomDaria** [tinymce/tinymce#3004] opened 2016-06-16 13:26 UTC
We are using TinyMCE within Umbraco v7.4.2 Content Management System.
Within our Umbraco content page, we have a TinyMCE Rich Text Editor along with other controls (i.e. image control, meta description, etc).

Our issue is as follows:
When we add several lines of text to our RTE (TinyMCE) control, at some variable point, the outer page window scroll bars appear and the TinyMCE toolbar disappears!  

See attached for more information.
[RTE losing its ToolBar.docx](https://github.com/tinymce/tinymce/files/318480/RTE.losing.its.ToolBar.docx)

Thanks 
BTD

[RTE losing its ToolBar.docx](https://github.com/tinymce/tinymce/files/318482/RTE.losing.its.ToolBar.docx)

**Comment by spocke** [comment] 2016-06-17 07:56
Can this be reproduced out side umbraco at fiddle.tinymce.com if so we can look into it otherwise it's an integration issue rather than a bug in tiny.

**Comment by TomDaria** [comment] 2016-06-17 11:12
It can't be reproduced at fiddle.tinymce.com.
It must be an integration issue with Umbraco.
How should I proceed?
Thanks

**Comment by spocke** [comment] 2016-06-17 12:23
I suggest reporting it to umbraco and their support/ticket system. You can reference this ticket why it was passed over to them. Thanks.

**Comment by TomDaria** [comment] 2016-06-17 12:49
They did that for me back in early May https://github.com/tinymce/tinymce/pull/2653 with a status of OPEN.
Can you give me an update on when you will accept Umbraco's request and get this fixed?

Thanks

Tom

**Comment by spocke** [comment] 2016-06-17 13:25
Ahh so it's that issue. I will look into merging that one.

**Comment by TomDaria** [comment] 2016-06-17 13:32
thank you very much,

**Comment by spocke** [comment] 2016-06-17 14:03
Is there a ticket on the umbraco side for this. Since even if we merge #2653 it needs to be fixed in Umbraco. Also not 100% sure that this fixes the toolbar issue since a.f.a.i.k the toolbar is just positioned statically. Enter scrolls all parent scroll containers into view this is just how the browser works when doing input in anything like a textarea or a contentEditable div.

**Comment by TomDaria** [comment] 2016-06-27 18:27
spocke
I just go this email update from Umbraco.

This PR  [#2653]((https://github.com/tinymce/tinymce/pull/2653)) hasn't been pulled in to TinyMCE yet, so it has been acknowledged but hasn't been fixed. Until TinyMCE accept this PR, there is no TinyMCE version to upgrade too.
You could try to persuade TinyMCE to accept this fix and then we can upgrade to the next TinyMCE version in another 7.x release.

Can you provide me with an update.

Thanks
Tom

**Comment by TomDaria** [comment] 2016-07-05 16:07
spocke
Are you there? 
Can you provide me with an update to my last thread?
Thanks

**Comment by jayarjo** [comment] 2016-11-07 08:33
https://github.com/tinymce/tinymce/pull/2653 seems to be merged now. Feel free to re-open if you still encounter that issue.

**Closed by jayarjo** 2016-11-07 08:33 UTC
Labels: status: verified, type: bug
