### ISSUE TITLE
SyntaxError: Can't create duplicate variable: 'typeMap'

### ISSUE THREAD

**Issue by Taygair** [tinymce/tinymce#4081] opened 2017-11-18 17:00 UTC
Bug: Error message showing in Javascript console after using tinymce.init twice: 
SyntaxError: Can't create duplicate variable: 'typeMap'

Use the following code/commands to reproduce it:
tinymce.init({...}
  tinymce.EditorManager.execCommand('mceRemoveEditor', true, 'texteditor');
  tinymce.remove('#texteditor');
  tinymce.remove();
tinymce.init({...}

Expected behaviour:
tinymce is properly cleaning up its stuff by using one of these functions, so the posted error message will not appear on calling tinymce.init again:
  tinymce.EditorManager.execCommand('mceRemoveEditor', true, 'texteditor');
  tinymce.remove('#texteditor');
  tinymce.remove();
I have checked tinymce.min.js and couldn't find a variable called 'typeMap' nor do I use this variable name in my code.

Affected version: 4.7.2 (had this problem also in 4.5.x) 
Affected browser: Thats funny, Safari (on Mac) only (tested version: 11.0.1 (12604.3.5.1.1))
It might be that this error doesn't show up in older Safari browsers.

**Comment by fyrkant** [comment] 2017-11-20 09:36
I'm not sure I understand, are you removing the same editor more than once or using one of those remove commands? Can you create a [fiddle](http://fiddle.tinymce.com) showing the problem?

**Comment by stickbyatlas** [comment] 2017-11-20 19:40
Hi there. I found this issue when doing a search for the same error message, which appeared in my dev console only recently. Strangely enough, I'm using CKEditor, not TinyMCE, and getting the exact same error as the one in the issue title. I'm embedding CKEditor inside an Ember component, which worked fine until just recently.

The version of Safari that's affected in my case is: 10.1.2 (12603.3.8)

I suspect that this is a problem with the browser, and not your library, but perhaps you may need to develop a workaround. Cheers.

**Comment by Taygair** [comment] 2017-11-20 20:05
@fyrkant You understood me correct:
1. Init tinymce
2. Remove tinymce
3. Re-init tinymce

It's kinda ugly, I know. I wish I wouldn't have to do that in my editor but my tinymce view (menu, custom toolbar buttons) differs depending on what the user enters. I don't know how to change tinymce's functionality at runtime (no documentation/samples found, couldn't make it work while tinymce was initialized).
I don't know how to permanently store my sample at Fiddle. Based on the initial Fiddle sample I have created one that causes the error. Working sample (copy/paste it to Fiddle)
```
<script type="text/javascript">
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});

// Completely remove tinymce
tinymce.EditorManager.execCommand('mceRemoveEditor', true, 'textarea');
tinymce.remove('#textarea');
tinymce.remove();

// Re-init tinymce ==> This produces the error in Safari (Mac, maybe Windows too)
tinymce.init({
    selector: "textarea",
    plugins: [
        "advlist autolink lists link image charmap print preview anchor",
        "searchreplace visualblocks code fullscreen",
        "insertdatetime media table contextmenu paste"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
});

</script>

<form method="post" action="dump.php">
    <textarea name="content"></textarea>
</form>
```

I have no idea in what way it may affect tinymce. Eveything seems still working fine. When I searched for the error I found this one. It's a different one but kinda same problem (only Safari affected): https://stackoverflow.com/questions/40091136/cant-create-duplicate-variable-that-shadows-a-global-property
-> Check out the one green answer there, maybe it helps.

I never had this error before, same code. This might be quite new as stickbyatlas commented (funny, chkeditor is affected as well).

**Comment by stickbyatlas** [comment] 2017-11-20 20:14
Just a follow-up: tested on Safari version 10.1.1 (12603.2.4) (previous patch version) and no error appears. As I suspected, this seems to be a Safari problem that affects both libraries. Unsure what kind of workaround is required (or whether it's even necessary).

**Comment by Taygair** [comment] 2017-11-20 20:48
Well, everything seems to work fine. It's just ugly to see it in the console. Hopefully it may disappear with next Safari version(s).

**Comment by fyrkant** [comment] 2017-11-22 15:53
`tinymce.init` is asynchronous so the code you pasted above won't work. 

Closing this issue as it does not seem like a problem with TinyMCE, if someone can create a fiddle showing that it is I can open it again.

**Comment by Taygair** [comment] 2017-11-22 15:59
What do you mean with "asynchronous"? You asked for a sample that I created and it does show the error, even in fiddle (see attachment).
<img width="897" alt="typemap" src="https://user-images.githubusercontent.com/21134000/33136818-7495da98-cfa6-11e7-9a4c-eb1fb5f2a3ec.png">

**Comment by caraffa** [comment] 2017-11-27 15:32
For is open too. I'm not using TinyMCE directly but wrapped within wordpress' WP_Editor, so that the underlying init process is out of my control.

**Comment by Oxonium** [comment] 2018-01-18 15:17
Same problem here, only on Safari. Do you plan on reopening this issue ?

**Comment by fyrkant** [comment] 2018-02-05 09:40
@caraffa @Oxonium 
Can you create a fiddle or something like that reproducing it?

**Comment by fyrkant** [comment] 2018-02-07 14:50
@caraffa @Oxonium @Taygair Are any of you using the safari extension AdBlock? I seem to only get the typemap error when I have the AdBlock extension activated.

**Comment by Taygair** [comment] 2018-02-07 19:51
Now you mention it... Yes, I do... I just stopped the AdBlocker but the error message from tinymce still appears (see attachments). The problem appeared with latest Safari release. Would have been weird it
<img width="668" alt="myproject" src="https://user-images.githubusercontent.com/21134000/35938179-a33cf668-0c48-11e8-989a-75d6d27211f0.png">
<img width="1327" alt="tinymce_page" src="https://user-images.githubusercontent.com/21134000/35938195-adbd900c-0c48-11e8-8bce-3505a01f3faa.png">

 now would be caused by AdBlock.

**Comment by fyrkant** [comment] 2018-02-07 19:54
I think you need to disable the extension fully by going to Safari preferences => extensions and deselect the adblock ckeckbox.

**Comment by Taygair** [comment] 2018-02-07 20:15
You're bloody right, then the error message won't appear again! Thanks for making this clear! Still weird this behaviour appeared since the latest Safari version.

**Comment by Bensume** [comment] 2018-02-23 18:47
The behavior seems to be caused by Ghostery. Even with the website whitelisted, the issue is present. Disabling the extension cases the error to go away.

**Comment by caraffa** [comment] 2018-04-16 16:52
@fyrkant Same for me, as for @Taygair

**Comment by fyrkant** [comment] 2018-04-17 05:45
@caraffa Then I would recommend the same solution - disable adblocker.

**Closed** 2018-10-05 15:07 UTC
Labels: needs: more info

**Comment by AndMe2** [comment] 2020-01-21 09:05
Same error with F-Secure Browsing protection. Turning it off gets rid of the error.
