### ISSUE TITLE
Bug with the br data-mce-bogus="1" tag in Firefox / IE11.

### ISSUE THREAD

**Issue by AnkitKamdar** [tinymce/tinymce#3833] opened 2017-07-25 18:50 UTC
Bug with the br data-mce-bogus="1" tag in Firefox / IE11.

**Follow below steps to reproduce issue in Firefox / IE11**
Write a word (e.g hello) => Select Bold =>write something with bold selection (e.g. **World**)
=> Select Italic => Write (e.g. _ABC_) => Select Underline => again write something (e.g. XYZ) => (e.g. hello **World _ABC XYZ_**)
=> Now Press enter => Write something (e.g. What are you doing) <-- this is in bold-italic-underline. Current position of caret is at the end of (**doing**) Now if you unselect underline, the caret will move to the next line. Now again in the next line write something and then unselect Italic, the caret will move to the next line.

**What is the expected behavior?**
The caret should remain at the same position without moving to the next line.

**Which versions of TinyMCE, and which browser / OS are affected by this issue?**
I am using Tinymce v4.5.7. But it happens with the latest version as well.

Please take a look into this issue ASAP.

**Comment by fyrkant** [comment] 2017-07-26 09:08
Duplicate of #3773

**Closed by fyrkant** 2017-07-26 09:08 UTC
