### ISSUE TITLE
After pressing enter, content in span tag following cursor does not move to the next line

### ISSUE THREAD

**Issue by zyslsufin** [tinymce/tinymce#8960] opened 2023-08-03 06:04 UTC
**What is the current behavior? Describe the bug**
Click enter right before the content which is inside a span tag, notice content in span tag does not move to next line together with cursor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
https://codesandbox.io/s/tinymce-vue-forked-rnjpx3?file=/src/App.vue

**What is the expected behavior?**
All content proceeding the cursor should be moved to next line along with cursor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested using windows 10 chrome browser: Version 113.0.5672.93 (Official Build) (64-bit)
@tinymce/tinymce-vue: 3.2.8,
vue: 2.6.14

**Comment by lostkeys** [comment] 2023-08-08 06:57
Hi @zyslsufin. Try upgrading to the latest version of TinyMCE 6 which seems to have fixed your issue. Here is a test: https://github.com/tinymce/tinymce/issues/8960

**Comment by zyslsufin** [comment] 2023-08-15 06:44
@lostkeys We have tested on sandbox using TinyMCE version 6.6.2 and issue remains unresolved:
https://codesandbox.io/s/tinymce-vue-forked-5yvgzn?file=/package.json

**Comment by spocke** [comment] 2023-08-15 07:25
That is still loading tinymce 5.10 from the cloud. You need to upgrade the vue integration to the latest version to get the latest 6 version. The channel version was bumped to 6 in the 5.0.0 tinymce-vue release see: https://github.com/tinymce/tinymce-vue/blob/main/CHANGELOG.md#changed-1 your code pen is using 3.2.8.

I was unable to reproduce this on a regular tinymce fiddle at fiddle.tiny.cloud on V6 however I was able to reproduce it on the latest V5 of tinymce. Made a fiddle here: https://fiddle.tiny.cloud/XEiaab

So the issue is fixed from our end so closing this ticket.

**Closed by spocke** 2023-08-15 07:25 UTC
