### ISSUE TITLE
Paste link into word under contenteditable false elements

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5152] opened 2019-09-06 14:20 UTC
**What is the current behavior? Describe the bug**
When i paste link into line under contenteditable false element, link doesn't appear and cursor moves into contenteditable false element
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Paste contenteditable false element
Type some text
Select word
Paste link by ctrl+v
**What is the expected behavior?**
Link appears, cursor doesn't move from current selection
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0+ Chrome 76

**Comment by wonderbugtiny** [comment] 2019-09-10 04:27
Hi @versusvirus, I was not able to reproduce the issue in TinyMCE version 5.0.15 using Chrome. Please provide a fiddle(http://fiddle.tinymce.com/baaaab) and/or a video to help us understand the behaviour you are experiencing. Thank you!

**Comment by versusvirus** [comment] 2019-09-11 08:28
![quote_link](https://user-images.githubusercontent.com/33262949/64680832-38323a00-d487-11e9-97b2-8c136de93f7d.gif)

**Comment by ltrouton** [comment] 2019-11-13 23:34
Thanks for the video. We are still having troubles reproducing this issue. If you could provide a forked [Fiddle](http://fiddle.tinymce.com/baaaab) that allows the issue to be reproduced that would be very helpful.

**Comment by lnewson** [comment] 2020-02-23 18:57
Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.

**Closed by lnewson** 2020-02-23 18:57 UTC
Labels: needs: more info

**Comment by versusvirus** [comment] 2020-04-04 19:38
> Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.

Bug is still reproducing
Look this fiddle: http://fiddle.tinymce.com/efhaab
