### ISSUE TITLE
Initial (default) "rem" font-size is converted to "px"

### ISSUE THREAD

**Issue by PeraMika** [tinymce/tinymce#6104] opened 2020-10-13 20:55 UTC
I have the following font-size formats:

```
fontsize_formats: "0.5rem 0.625rem 0.75rem 1rem 1.25rem 1.5rem 1.75rem",
```

and default font-size is set to `1rem`:

```
content_style: "body { font-size: 1rem; }",
```
However, when TinyMCE is loaded - it shows 16px as initial font size:

![TinyMCE font size issue](https://user-images.githubusercontent.com/41101578/95915075-eef99b80-0da6-11eb-9169-0957f149148e.png)

**FIDDLE:** http://fiddle.tinymce.com/tvhaab

I'm using:

- TinyMCE 5.4.2
- Browsers: Firefox 81.0 (64-bit); Chrome 85.0.4183.121 (64-bit);
- OS: Windows 7 (64-bit)

**Comment by lnewson** [comment] 2020-10-14 21:27
Hi @PeraMika, the browser only returns a pixel based computed value for the font-size (and many other CSS properties), so TinyMCE needs to manually remap that back to the various units that can be used. Currently TinyMCE don't support relative font sizes like this, so I'm going to close this as a duplicate of #4337 which is the current feature request to support that.

As a workaround, you can do something like this: http://fiddle.tinymce.com/tvhaab/1 This works as TinyMCE can get the explicit font-size instead of the computed font-size.

**Closed by lnewson** 2020-10-14 21:27 UTC

**Comment by lostkeys** [comment] 2021-03-10 13:19
@lnewson Just curiously asking, what's stopping us from making an `initial_fontsize: "12pt"` config option that does what you do in your workaround?

**Comment by lnewson** [comment] 2021-03-10 21:07
@lostkeys that wouldn't be possible as the default font-size needs to be configured via the content CSS in some form. Sure we could do something like that while editing, however it'd break as soon as someone tried to use the content outside of TinyMCE as the workaround above really only applies as an alternative to using `content_style`. As such, it's really just a hack to try and get something working for relative font sizes (the real solution would be to add relative font-size support).
