### ISSUE TITLE
Style tag with no content gets applied on IE

### ISSUE THREAD

**Issue by sosharma1403** [tinymce/tinymce#4894] opened 2019-03-13 09:30 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. enable code and fullpage plugin
2. click on code
3. add styles in head section
4. click on okay

Styles get applied on chrome and firefox, but for IE empty style tag is created.

Demo: http://fiddle.tinymce.com/3Wfaab/1

**What is the expected behavior?**
Styles should get applied on all the browsers

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Browsers affected: all
tinymce version: 4.9.3

**Comment by lnewson** [comment] 2019-03-14 04:43
Thanks for the report! I can verify this on IE 11 and I believe I know what the issue is, so it should be pretty easy to fix.

**Comment by wonderbugtiny** [comment] 2019-03-19 10:37
This should now be fixed in 5.0.3. Please let us know if you find any further problems!

**Closed by wonderbugtiny** 2019-03-19 10:37 UTC
Labels: browser: ie, plugin: fullpage, resolution: fixed in coming release, status: escalated, type: bug
