### ISSUE TITLE
li with p-tags inside breaks list button functionality

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2176] opened 2015-04-08 12:49 UTC
Description of problem:

Steps to reproduce:
1. Open Inline Editing Example http://www.tinymce.com/tryit/inline.php
2. Insert unordered list
3. select two paragraphs
4. drag them to the list entry
5. click list button again

Expected result:
- list is removed

Actual result:
- nothing happens

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7465](http://archive.tinymce.com/develop/bugtracker_view.php?id=7465) posted by [jaschil](http://archive.tinymce.com/profile.php?name=jaschil)_
> 
> _**Tags:** [firefox chrome firefox chrome]_
> _**Status:** Verified_
> _**Resolution:** Accepted_
> _**Attached URL:** none_

**Comment by janschilbach** [comment] 2015-11-09 14:59
Are there any news regarding this issue?

**Comment by blackcathikari** [comment] 2016-07-25 01:51
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by ziacik** [comment] 2017-06-03 15:00
This is still an issue in the latest tinymce.
Steps to reproduce:
1. Open http://www.tinymce.com/tryit/inline.php
2. Delete all content from the editor
3. Use Tools / View Source to add the following content
```
<ul>
<li>
<p>This is a paragraph</p>
</li>
</ul>

```
4. Put the cursor inside the paragraph and click the List icon. Nothing happens.

Using Chrome 54.0.2840.71 (64-bit)

**Comment by blackcathikari** [comment] 2017-06-06 23:57
Thanks for those steps @ziacik, that's much easier to replicate. I'll reopen this. Replicated in Chrome and Firefox.

Interestingly, I can switch the ul to an ol using the toolbar buttons, but even then clicking the list buttons doesn't remove the list formatting.

**Comment by fyrkant** [comment] 2017-08-31 10:24
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2017-08-31 10:24 UTC
Labels: plugin: lists, status: escalated, status: verified, type: bug
