### ISSUE TITLE
tinymce5RC1,upload bug,I am sure the upload interface must be correct.

### ISSUE THREAD

**Issue by luoxulx** [tinymce/tinymce#4771] opened 2019-01-21 03:20 UTC
**Do you want to request a *feature* or report a *bug*?**
yes

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/35016570/51450825-389d8980-1d6d-11e9-9c80-28c8ffd4a545.png)
example: 
![image](https://user-images.githubusercontent.com/35016570/51451030-456ead00-1d6e-11e9-8b6a-091ebfd98466.png)
![image](https://user-images.githubusercontent.com/35016570/51451064-764ee200-1d6e-11e9-90ab-8899d159f71f.png)
**When I click Save, I can't load it.**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
![image](https://user-images.githubusercontent.com/35016570/51450788-0db33580-1d6d-11e9-96f7-413f72822a03.png)
code: 
``` js
export default {
  name: 'Tinymce',
  props: {
    prefix: {
      type: String,
      required: true
    },
    id: {
      type: String,
      default: function() {
        return 'vue-tinymce-' + +new Date() + ((Math.random() * 1000).toFixed(0) + '')
      }
    },
    value: {
      type: String,
      default: ''
    },
    toolbar: {
      type: Array,
      required: false,
      default() {
        return []
      }
    },
    menubar: {
      type: String,
      default: 'file edit insert view format table'
    },
    height: {
      type: Number,
      required: false,
      default: 360
    }
  },
  data() {
    return {
      hasChange: false,
      hasInit: false,
      tinymceId: this.id,
      fullscreen: false,
      languageTypeList: {
        'en': 'en_GB',
        'zh': 'zh_CN'
      }
    }
  },
  computed: {
    language() {
      return this.languageTypeList[this.$store.getters.language]
    }
  },
  watch: {
    value(val) {
      if (!this.hasChange && this.hasInit) {
        this.$nextTick(() =>
          window.tinymce.get(this.tinymceId).setContent(val || ''))
      }
    },
    language() {
      this.destroyTinymce()
      this.$nextTick(() => this.initTinymce())
    }
  },
  mounted() {
    this.initTinymce()
  },
  activated() {
    this.initTinymce()
  },
  deactivated() {
    this.destroyTinymce()
  },
  destroyed() {
    this.destroyTinymce()
  },
  methods: {
    initTinymce() {
      const _this = this
      window.tinymce.init({
        language: this.language,
        selector: `#${this.tinymceId}`,
        height: this.height,
        body_class: 'panel-body ',
        object_resizing: false,
        toolbar: this.toolbar.length > 0 ? this.toolbar : toolbar,
        menubar: this.menubar,
        plugins: plugins,
        end_container_on_empty_block: true,
        powerpaste_word_import: 'clean',
        code_dialog_height: 450,
        code_dialog_width: 1000,
        advlist_bullet_styles: 'square',
        advlist_number_styles: 'default',
        imagetools_cors_hosts: ['www.tinymce.com', 'codepen.io'],
        default_link_target: '_blank',
        link_title: false,
        nonbreaking_force_tab: true, // inserting nonbreaking space &nbsp; need Nonbreaking Space Plugin
        // lx-new
        upload_image_url: 'https://www.lnmpa.top/api/file/upload',
        content_style: `*                         { padding:5; margin:5; }
                        html, body                { height:100%; }
                        img                       { max-width:100%; display:block;height:auto; }
                        a                         { text-decoration: none; }
                        iframe                    { width: 100%; }
                        p                         { line-height:1.6; margin: 0px; }
                        table                     { word-wrap:break-word; word-break:break-all; max-width:100%; border:none; border-color:#999; }
                        .mce-object-iframe        { width:100%; box-sizing:border-box; margin:0; padding:0; }
                        ul,ol                     { list-style-position:inside; }`,
        insert_button_items: 'image link | inserttable',
        paste_retain_style_properties: 'all',
        paste_word_valid_elements: '*[*]', // word需要它
        paste_data_images: true, // 粘贴的同时能把内容里的图片自动上传，非常强力的功能
        paste_convert_word_fake_lists: false, // 插入word文档需要该属性
        paste_webkit_styles: 'all',
        paste_merge_formats: true,
        paste_auto_cleanup_on_paste: false,
        toolbar_items_size: 'mini',
        init_instance_callback: editor => {
          if (_this.value) {
            editor.setContent(_this.value)
          }
          _this.hasInit = true
          editor.on('NodeChange Change KeyUp SetContent', () => {
            this.hasChange = true
            this.$emit('input', editor.getContent())
          })
        },
        setup(editor) {
          editor.on('FullscreenStateChanged', (e) => {
            _this.fullscreen = e.state
          })
        },
        images_upload_handler(blobInfo, success, failure, progress) {
          progress(0)
          const formData = new FormData()
          formData.append('file', blobInfo.blob())
          formData.append('path', 'post')
          fileUpload(formData).then((response) => {
            success('blob:' + response.data.data.url)
            progress(100)
          }).catch(err => {
            failure('If an unknown problem arises, refresh the page, or contact the programmer!')
            console.error(err)
          })
        }
      })
    },
    destroyTinymce() {
      if (window.tinymce.get(this.tinymceId)) {
        window.tinymce.get(this.tinymceId).destroy()
      }
    },
    setContent(value) {
      window.tinymce.get(this.tinymceId).setContent(value)
    },
    getContent() {
      window.tinymce.get(this.tinymceId).getContent()
    },
    imageSuccessCBK(arr) {
      const _this = this
      arr.forEach(v => {
        window.tinymce.get(_this.tinymceId).insertContent(`<img class="wscnph" src="${v.url}" >`)
      })
    },
    test() {
      fileUpload(1)
    }
  }
}
```
**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5RC1, chrome, vue2.5, php7. TinyMCE4.7.5 is working correct!

**Comment by lnewson** [comment] 2019-03-01 03:20
@luoxulx thanks for all the details! This is going to be a bit tricky to reproduce, however before I get to that, based on the images/logs provided it looks as though you're returning an invalid url in your success callback in `images_upload_handler`. The cause appears to be because you're adding the `blob:` prefix which then causes the browser to treat it as a blob uri, which isn't valid and therefore fails to load.

As such, I believe you could resolve this by simply removing adding the blob prefix, eg: `
success(response.data.data.url)`. I'm not sure how this worked on 4.7.5 though, as it really should have been failing there as well.

**Comment by wonderbugtiny** [comment] 2019-04-08 03:46
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:46 UTC
Labels: 5.x, needs: more info
