### ISSUE TITLE
MouseEvent.mozPressure is deprecated

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#5083] opened 2019-07-18 12:11 UTC
This is strange, because I cannot find that in the code, but Firefox complains about tinymce.min.js that "MouseEvent.mozPressure is deprecated. Use PointerEvent.pressure instead." in console.

**Comment by TheSpyder** [comment] 2019-07-18 22:47
Looking through `node_modules` as well, there are a couple of dependencies where it's referenced

* terser
* uglify-js

The first seems to be a webpack thing, and uglify only uses it in a "do not mangle this name" list, so I'm not sure where this is coming from.

I can't reproduce this on http://fiddle.tinymce.com/ (version `tinymce5-cloud-dev` loads it minified), can you please build a replication case for us?

**Comment by jdufresne** [comment] 2019-07-19 14:38
I can reproduce with the linked fiddle. When I hit http://fiddle.tinymce.com/ on Desktop Firefox, I see the warning when moving my mouse around the TinyMCE editor.

User agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by blissdev** [comment] 2019-07-19 16:36
I also can reproduce using Desktop Firefox on both macOS and Windows.

**Comment by lnewson** [comment] 2019-07-21 23:39
I was able to reproduce this as well using Firefox 68. The cause is that TinyMCE copies all the properties from the original event for it's own internal events here: https://github.com/tinymce/tinymce/blob/d16a86d9ec2e4fb1f6a5b352bbf6d659da785cc4/modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts#L102 It doesn't appear that mozPressure is actually being used however, but just accessing it to copy the property causes the warning to be thrown.

We'll log an internal issue to add the `mozPressure` property to the list of deprecated props.

**Comment by lnewson** [comment] 2019-08-06 07:42
This issue has been fixed in TinyMCE 5.0.13, which has just been released to the community. Please let us know if you have any further issues.

**Closed by lnewson** 2019-08-06 07:42 UTC
Labels: resolution: fixed in coming release, status: escalated, status: verified

**Comment by Matthias-Hermsdorf** [comment] 2019-08-28 07:53
@lnewson how did you have fixed it? In leaflet.js occures the same problem.

**Comment by TheSpyder** [comment] 2019-08-28 08:54
@Matthias-Hermsdorf we copy the event details, and we added `mozPressure` to the list of properties that we don't copy because they trigger deprecated warnings
https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts#L102
https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/core/main/ts/api/dom/EventUtils.ts#L33-L36

**Comment by Matthias-Hermsdorf** [comment] 2019-08-28 09:55
Thanks

**Comment by andreir91** [comment] 2020-08-13 13:39
The same issue is for "@tinymce/tinymce-react": "^3.6.0".
Can you check this package for react please?

**Comment by jzabate** [comment] 2024-03-01 10:22
This issue still appears on tinymce 6.7.0
`MouseEvent.mozInputSource is deprecated. Use PointerEvent.pointerType instead.`
