### ISSUE TITLE
Cut from toolbar or context menu not working

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2216] opened 2015-05-07 22:06 UTC
Description of problem:

Cut-to-clipboard from either the toolbar or the context menu does nothing and logs the following message in Chrome (and in nw.js):

"We don't execute document.execCommand() this time, because it is called recursively." 

In the dev package of TinyMCE this occurs in tinymce.js:26545 (4.1.6)

editor.getDoc().execCommand(isForward ? 'ForwardDelete' : 'Delete', false, null);

From here: https://code.google.com/p/chromium/issues/detail?id=363288#c3
it appears that it's due to a "security-related change in Chromium" that prevents the execCommand above from being called within the cut event handler.  I tried a quick test and wrapped the code in customDelete from the execCommand to the end in setTimeout() and it allowed the cut to work.  However, customDelete is called from many places in the code and any code following a call to customDelete would probably have to be passed in as a callback function (and wanted confirmation that this was the way to go).

I tried this both in 4.1.6 (the version we're currently using) and on the TinyMCE Basic example (http://www.tinymce.com/tryit/basic.php).

I did not test other browsers.
Note: Using Ctrl-X keyboard shortcut works.

Steps to reproduce:
1. use TinyMCE in Chrome
2. select some text
3. use "cut" from either the toolbar or the context menu

Expected result: text is cut from the editor (like it is with Ctrl-C)

Actual result: text remains, message in console: "We don't execute document.execCommand() this time, because it is called recursively." 

Thanks.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7503](http://archive.tinymce.com/develop/bugtracker_view.php?id=7503) posted by [TrevorPT](http://archive.tinymce.com/profile.php?name=TrevorPT)_
> 
> _**Tags:** [chrome chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by jaredthirsk** [comment] 2016-07-04 21:38
It has been a year since this issue was opened and I just ran into this.  Is this going to get fixed?

**Comment by blackcathikari** [comment] 2016-07-25 01:56
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by jayarjo** [comment] 2017-07-08 15:22
This issue seems to be back again.

**Comment by artemijan** [comment] 2017-08-18 09:32
yep, i ran into this issue too

**Comment by artemijan** [comment] 2017-08-18 09:47
fixed in v4.6.5

**Closed** 2018-02-19 15:42 UTC
Labels: browser: chrome, origin: tinymce.com, plugin: paste, resolution: fixed in coming release, status: verified, type: bug

**Comment by carlos-mg89** [comment] 2020-11-05 15:11
This happens to me in Firefox 82 (latest) although in Chrome works nicely.
If I press CONTROL + X it works on Firefox too.

**Comment by lnewson** [comment] 2020-11-05 20:42
@carlos-mg89 this is a known issue and is due to a recent change within Firefox itself. We have https://github.com/tinymce/tinymce/pull/6182 open to add a workaround/fix for that issue in TinyMCE 5.6.
