### ISSUE TITLE
Ampersands replaced in links

### ISSUE THREAD

**Issue by fricikoma** [tinymce/tinymce#3865] opened 2017-08-14 07:48 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Ampersands are replaced with &amp; in the links.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Add this example in the source code:
<p><a href="http://www.imdb.com/title/tt1361336/?Tom=1&Jerry=1">Tom &amp; Jerry</a></p>

**What is the expected behavior?**
The link should stay intact, otherwise it won't work.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
It's wrong in all I've tried.

**Comment by fyrkant** [comment] 2017-08-14 08:03
I don't understand when the problem occurs, when is the ampersand replaced in a way that it breaks the link?

**Comment by fricikoma** [comment] 2017-08-14 08:19
Go to the tinymce.com home page demo

Tools dropdown / Source code

Paste an anchor tag with a link containing an ampersand, for example 
&lt;a href="http://www.imdb.com/title/tt1361336/?Tom=1&Jerry=1">Tom and Jerry&lt;/a&gt;

Click OK

Open the source editor again to see the ampersand broken.

![amp-bug](https://user-images.githubusercontent.com/30999196/29263631-5970c448-80e2-11e7-8ef3-5a041606341a.png)

**Comment by fyrkant** [comment] 2017-08-14 08:28
No that is just the encoded named entity of a `&` and the link should still work. See this link for more info: http://mrcoles.com/blog/how-use-amersands-html-encode/

**Comment by fricikoma** [comment] 2017-08-14 08:52
No, it will become a completely different link. 
Take this link for example which has URL parameters and it can't read them when they're replaced like this.

Correct link:
[https://rubiks3x3.com/algorithm/?n=demo2tperm&moves=FoRUrupf&fields=boyyyybbyygyggggggoygooooooorrbbbbbbgyrrrrrrrwwwwwwwww&speed=3&bg=CCCCCC](url)

I replaced the ampersands and the link stopped working, the site can no longer interpret the URL parameters:
https://rubiks3x3.com/algorithm/?n=demo2tperm&amp;moves=FoRUrupf&amp;fields=boyyyybbyygyggggggoygooooooorrbbbbbbgyrrrrrrrwwwwwwwww&amp;speed=3&amp;bg=CCCCCC

**Comment by spocke** [comment] 2017-08-14 09:14
Make sure you encode everything correctly in the textarea like this:
```<textarea name="content">&lt;p&gt;&lt;a href=&quot;http://www.imdb.com/title/tt1361336/?Tom=1&amp;amp;Jerry=1&quot;&gt;http://www.imdb.com/title/tt1361336/?Tom=1&amp;amp;Jerry=1&lt;/a&gt;&lt;/p&gt;</textarea>```

With that html code I couldn't reproduce any issues with the links. So closing this one since it works as expected.

**Closed by spocke** 2017-08-14 09:14 UTC
Labels: needs: more info
