### ISSUE TITLE
Table of content issue

### ISSUE THREAD

**Issue by bobmitro** [tinymce/tinymce#4696] opened 2018-12-10 13:41 UTC
Hello,

After installing the TOC plugin the anchor ID's are added to any headings. 
How to change this behavior for "on demand", I mean when the TOC button is clicked? 

I've checked your demo on https://www.tiny.cloud/ and here it works as should, the ID's are added only when the TOC option is selected from the menu.

**Comment by lnewson** [comment] 2019-03-04 05:41
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-03-04 05:41 UTC
Labels: needs: more info
