### ISSUE TITLE
Version 4.7.9 - Editor bug - The editor believes that moving within a text link is a change in the document

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4279] opened 2018-03-15 13:01 UTC
Tested in Firefox. Position yourself at the beginning of the document. Now press the right key a few times to move within the link text and you will see that the 'Undo' icon is now active. Press F5 and you will get a lose changes alert message.

http://fiddle.tinymce.com/4ngaab

**Comment by metricjs** [comment] 2020-05-05 02:44
Hi,
I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.10. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.
Thanks!

**Closed by metricjs** 2020-05-05 02:44 UTC
Labels: status: escalated, status: verified, type: bug
