### ISSUE TITLE
When changing modes dynamically, focus going to tinymce

### ISSUE THREAD

**Issue by ramchaitanyap** [tinymce/tinymce#6701] opened 2021-04-05 12:53 UTC
**What is the current behavior? Describe the bug**
When changing modes dynamically, focus going to tinymce

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
Go to https://fiddle.tiny.cloud/i9haab
Press buttons: Change to readonly, Change to design
Focus is going to iframe in tinymce.(Add document.activeElement to live expression in dev tools for observing focussed element)

**What is the expected behavior?**
Focus should be on button itself

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.7.1, 4.4.3(ours)

**Comment by ramchaitanyap** [comment] 2021-04-05 12:58
@TheSpyder @aautio @camiloHimura  @dependabot

<img width="1330" alt="Screenshot 2021-04-05 at 6 28 08 PM" src="https://user-images.githubusercontent.com/17079910/113576177-b42d3d80-963c-11eb-8c3a-4817ba5f6b01.png">

**Comment by ashfordneil** [comment] 2021-04-06 07:44
Hi @ramchaitanyap,

Thanks for this detailed report and fiddle.

I've had a look at this bug using TinyMCE version 4.4.3, and version 4.9.11 (the last TinyMCE 4 release). For these versions, I am able to reproduce the bug.

However, using TinyMCE version 5.7.1 (the latest release) I am unable to reproduce the bug. What you're seeing in your reproduction is a result of TinyMCE Fiddle wrapping all fiddle content inside an iframe (and then within that iframe will be another iframe containing the editor). In your console, `document.activeElement` claims to be an iframe (specifically, the preview iframe), but that doesn't mean the editor has focus, it just means that the focus is within the fiddle content (as opposed to in the code editor, or the version select, or something like that). To get more details as to where the focus is, you'll need to change the scope of your console.

<img width="1330" alt="Annotated Chrome DevTools" src="https://user-images.githubusercontent.com/17724765/113669485-337f4780-96f7-11eb-970a-c120890a5755.png">

Have a look at where the red circle is on that image. You'll need to click that drop-down, and change it to `previewframe`. Once you've done that, you can inspect `document.activeElement` again and you'll be able to see the difference between focus being on the buttons, on the body, or within the editor (which will show as yet another iframe).

While your bug does exist in TinyMCE 4, it has been fixed in the latest version of TinyMCE 5. As support for TinyMCE 4 ended at the end of 2020, I suggest you upgrade to TinyMCE 5 to get a fix for this bug. Don't hesitate to reach out with a new issue if you face any issues upgrading. We have [a migration guide](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/) that might be useful here.

**Closed by ashfordneil** 2021-04-06 07:44 UTC

**Comment by ramchaitanyap** [comment] 2021-04-06 08:05
Hi @ashfordneil 
I can still reproduce this in 5.7.1
1. Click \"Change to readonly\" button in https://fiddle.tiny.cloud/i9haab
2. Tab to  \"Change to design\" button and click enter

Actual: Focus going inside tinymce
Expected: Focus should remain on button

**Comment by ashfordneil** [comment] 2021-04-06 08:20
Can you please tell me the browser and OS version you're using, and send a screen recording of it happening? I'm not able to reproduce the focus moving back to the editor with either the mouse or keyboard navigation (using Safari, on macOS).
