### ISSUE TITLE
TinyMCE Copy and Paste buttons

### ISSUE THREAD

**Issue by renatolopeslatitudde** [tinymce/tinymce#9709] opened 2024-06-17 16:06 UTC
Hello everyone, sorry for creating a new topic but i was trying to use the paste button of the editor and i get the error that the browser doesn't allow access to the clipboard (Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.).
I know that is the browser security measures but any way of bypass that? 
Is there any workaround that makes this work? Or create a popup to allow the permissions like roosterJS does (https://microsoft.github.io/roosterjs/index.html)?
And when i give it manual permissions in the browser it still gives the error that doesn't have permissions, why?
The copy button seems to be working fine, but i would like to put the paste working too.
Thanks!

---

If you'd like to see this implemented sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment] 2024-06-18 01:46
Duplicate of #7254

**Closed by TheSpyder** 2024-06-18 01:46 UTC

**Comment by TheSpyder** [comment] 2024-07-03 22:51
The other issue is the place to focus discussion, not here where I closed it as a duplicate.
