### ISSUE TITLE
nested tags not working with mceInsertContent

### ISSUE THREAD

**Issue by zilahir** [tinymce/tinymce#5200] opened 2019-10-09 06:18 UTC
**What is the current behavior? Describe the bug**

Get the following code: 

```javascript
var selected_text = ed.selection.getContent();
                var return_text = "<h1 class='highlight-block-alt-2'><p>" + `${selected_text}` + "</p></h1>";
                console.debug('returned', return_text)
                ed.execCommand("mceInsertContent", 1, `${return_text}`);
```

the `console.debug` returns the correct value, for example: 

```
returned <h1 class='highlight-block-alt-2'><p>demo</p></h1>
```

However, what is actually returned is 

```
<p>demo</p>
```

So the wrapper `h1` is simply gone. If i change them around so, having the `div` as a wrapper, and having a `p` inside, the inner tag ( the `p` in this example) is gone. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

Having 

```
<h2>
 <span>
   text
 </text>
<h2/>
```

returned, not just the wrapper. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

This problems seems to be valid in all major versions of `TinyMCE`.  
Not working on any OS, and on any browser. I believe this is a general bug. 

value of `tinymce` global var's value under `wp`: 

```
majorVersion: "4", minorVersion: "9.4", releaseDate: "2019-03-20"
```

**Comment by lnewson** [comment] 2019-10-09 06:49
@zilahir the content you're trying to insert in **not** valid HTML, as h1-h6 elements cannot have a `<p>` element as a child (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements). As such TinyMCE will attempt to correct this like so:
`<h1></h1><p>demo</p>` and since the h1 element is now empty it's ignored/cleaned up.

Since this is due to attempting to insert invalid HTML, which TinyMCE won't allow, I'm going to close this as not a bug as it works if you use a span, which is valid HTML. If you can reproduce the issue with valid HTML then let me know and I'll re-open the issue.

**Closed by lnewson** 2019-10-09 06:49 UTC

**Comment by zilahir** [comment] 2019-10-09 06:59
@lnewson 

thanks, and then please do, since: 

```
var return_text = `<h1 class='highlight-block-alt-2'> <span> ${selected_text} </span> </h1>`;
```

returns: 

```
<h1 class="highlight-block-alt-2"> demo</h1>
```

You were right with the invalid html nesting, i just forgot to mention that of course i've tried both. 

The issue persist.

**Comment by zilahir** [comment] 2019-10-09 07:03
@lnewson,

here's an update, managed to fix it. 

Out of curiosity, tried to give a class to the `span` element also: 

```
var return_text = `<h1 class='highlight-block-alt-2'><span class='lofasz'>${selected_text}</span></h1>`;
```

in this case the returned dom is: 

```
<h1 class="highlight-block-alt-2"><span class="lofasz">demo</span></h1>
```

anyway, the issue can stayed close, i am leaving this here as future reference, if someone comes across with this.  

Thanks again!
