### ISSUE TITLE
Invalid IIFE Structure in Angular CLI / Webpack build

### ISSUE THREAD

**Issue by JasonTheProgrammer** [tinymce/tinymce#4483] opened 2018-07-04 02:01 UTC
**Bug**

**Build Error**
ERROR in ./node_modules/tinymce/tinymce.js
Module build failed: Error: Invalid IIFE Structure

**Affected Version**
TinyMCE: 4.7.13
Angular CLI: 6.0.7
Node: 10.3.0
OS: Windows 10

**Repro Steps**

1. Create a new default Angular project using `ng new test-app`.
2. Add the following to package.json: `"tinymce": "4.7.13"`.
3. Run `npm install`.
4. Add the following to app.module.ts: `import 'tinymce';`
5. Build with `ng build --prod`.

**Further Info**
The same does *not* occur in version 4.7.4.
The same does *not* occur without the prod build flag, i.e. this does not produce the error: `ng build`.

**Full Error Message**
ERROR in ./node_modules/tinymce/tinymce.js
Module build failed: Error: Invalid IIFE Structure
    at updateEnumIife (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:307:15)
    at visitBlockStatements (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:82:61)
    at visitor (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:33:26)
    at visitNode (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:56836:23)
    at visitFunctionBody (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:56942:23)
    at Object.visitEachChild (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:57062:407)
    at visitor (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:53:23)
    at visitNode (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:56836:23)
    at Object.visitEachChild (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:57052:44)
    at visitor (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:53:23)
    at visitNode (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:56836:23)
    at Object.visitEachChild (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:57060:45)
    at visitor (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:53:23)
    at visitNode (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:56836:23)
    at Object.visitEachChild (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\node_modules\typescript\lib\typescript.js:57106:49)
    at visitor (C:\Users\Jason\Desktop\test-app\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:53:23)

**Comment by JasonTheProgrammer** [comment] 2018-07-04 02:01
#4164 Possibly related?

**Comment by fyrkant** [comment] 2018-07-09 08:03
Does it happen if you import the minified file instead?

**Comment by JasonTheProgrammer** [comment] 2018-07-09 23:08
It does *not* happen if I import the minified file instead, i.e. `import 'tinymce/tinymce.min.js';` works for version 4.7.13. Thanks for the suggestion.

You can close the issue if you like, or leave it open if you think the ability to import the non-minified version should be supported.

**Comment by fyrkant** [comment] 2018-07-10 05:42
I'll leave it open as we should probably try to get the non-minified version to spit out a correctly formatted file too.

**Comment by isawk** [comment] 2018-08-16 08:54
Issues still there with angular build tinymce 4.8.2

`ERROR in ./node_modules/tinymce/tinymce.js
Module build failed: Error: Invalid IIFE Structure
    at updateEnumIife (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:307:15)
    at visitBlockStatements (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:82:61)
    at visitor (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:33:26)
    at visitNode (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at visitFunctionBody (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56942:23)
    at Object.visitEachChild (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57062:407)
    at visitor (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57052:44)
    at visitor (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57060:45)
    at visitor (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)
    at visitNode (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:56836:23)
    at Object.visitEachChild (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/node_modules/typescript/lib/typescript.js:57106:49)
    at visitor (/Users/KOGA/Development/angular/ibudo-app/node_modules/@angular-devkit/build-optimizer/src/transforms/wrap-enums.js:53:23)`

**Comment by isawk** [comment] 2018-08-16 09:08
angular.json
scripts include "node_modules/tinymce/tinymce.min.js"

in component, declare tinymce
declare var tinymce:any;

**Comment by lnewson** [comment] 2019-05-19 04:10
Closing this as a duplicate of https://github.com/tinymce/tinymce/issues/4165. As noted in that issue, the JS produced is valid, so the issue instead appears to be a bug with how Angular is trying to detect and process/rewrite enums since the JS produced is fairly similar.

**Closed by lnewson** 2019-05-19 04:10 UTC
Labels: status: verified
