### ISSUE TITLE
Spacing before/after an inline element creates a non-breaking space

### ISSUE THREAD

**Issue by claviska** [tinymce/tinymce#3057] opened 2016-07-11 19:29 UTC
When spacing before/after an inline element, a `&nbsp;` is erroneously produced instead of a normal space.

Minimal test case: http://fiddle.tinymce.com/F2faab/2

Only seems to affect Webkit-based browsers. Tested on the latest Chrome and Safari with the same results. Firefox is unaffected.

**Comment by claviska** [comment] 2016-08-15 22:36
Tested on the latest Chrome update (52.0.2743.116) and the bug still exists. Has it been verified? I've noticed this behavior in apps other than my own too.

If this is a TinyMCE issue, any pointers as to where one would look? I'm thinking it might actually be a Chrome bug.

**Comment by Shoplifter** [comment] 2016-11-03 22:07
👍 I have the same issue on Chrome (54.0.2840.71), Firefox (49.0.2), Opera (41.0) and IE Edge (25.10586.0.0). So rather ubiquitous.
Non-breaking spaces `&nbsp;` are a serious issue in our application - we´re using those for finetuning line breaks in for pdf output with wkhtml2pdf (which doesnt supprt `&shy;`).

I am on Windows 10 and use tinymce in inline mode

**Comment by claviska** [comment] 2017-03-03 22:22
@Shoplifter are you sure you're not seeing the `&nbsp;` characters that were left over after saving in Chrome? I can't seem to replicate this in Firefox, but the issue still occurs in Chrome.

And, of course, it also affects WordPress. 🤷‍♂️

**Comment by lnewson** [comment] 2020-05-08 08:48
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided. Testing older versions, it appears this issue was fixed in TinyMCE 4.9.0. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 08:48 UTC
Labels: component: keyboard, status: escalated, status: verified, type: bug

**Comment by claviska** [comment] 2020-05-08 11:18
I can confirm that this appears to be resolved. Thanks!
