### ISSUE TITLE
when use autoresize plugin , click button in toolbar , the editor jump to top

### ISSUE THREAD

**Issue by flycj** [tinymce/tinymce#6250] opened 2020-11-19 02:57 UTC
**What is the current behavior? Describe the bug**
Thank you very much for providing a very useful editor, but I have a headache when using it. When tinymce starts the autoresize plugin, the following picture will appear, and it will always return to the top of the editor. This experience Really bad
![屏幕录制2020-11-19 上午10 50 09](https://user-images.githubusercontent.com/5103045/99614966-8f517880-2a55-11eb-87db-09aea7938658.gif)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud]https://fiddle.tiny.cloud/Zyhaab/6

**What is the expected behavior?**
I hope that when I click the button in the toolbar, the editor is still in the original position

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

tinymce: v5

**Comment by flycj** [comment] 2020-11-19 03:19
I checked the source code of autoresize plugin, this problem is caused by the following code
```
    // Ensure the selected node is in view, as it's potentially out of view after resizing the editor
    if (editor.hasFocus()) {
       editor.selection.scrollIntoView(editor.selection.getNode());
    }
```
I don’t know if I can provide you with ideas, I hope it helps

**Comment by lostkeys** [comment] 2020-11-19 08:09
Oh no, that's really bad experience. Sorry you feel you're struggling with TinyMCE. I can confirm this being an issue when selecting multiple list items and toggling the list off, the page jumps to the start which is really disruptive. I can only trigger the bug on lists, and I suspect it's because the HTML tags is transformed rather than just becoming wrappped in for example a blockquote. Thanks for finding this bug for us.

**Comment by metricjs** [comment] 2021-09-23 07:09
Hi @flycj, this appears to be the same issue as #6714 and we are already tracking that issue internally, so I'm going to close this ticket as a duplicate. Keep an eye on #6714 to be alerted when this is fixed.

**Closed by metricjs** 2021-09-23 07:09 UTC
Labels: type: bug, plugin: autoresize, plugin: lists, status: escalated
