### ISSUE TITLE
Image upload icon missing in tinyMCE 4.4.1

### ISSUE THREAD

**Issue by prasanna32** [tinymce/tinymce#7449] opened 2021-12-07 11:05 UTC
**I have implemented tinyMCE editor. All buttons are showing up except image upload in menu and toolbar. Below is my code:**

`        tinymce.init({
            selector: 'textarea',
            height: 400,
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table contextmenu paste imagetools wordcount"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            media_live_embeds: true,
            automatic_uploads: true,
            images_reuse_filename: false,
            images_upload_url: 'test.php',

            images_upload_handler: function (blobInfo, success, failure) { .....
            }
`
With above code, I can see below behaviour:

![image](https://user-images.githubusercontent.com/32702319/145017336-085a36ec-75b6-4a83-8d94-1cf6185d1a4e.png)

I need below behaviour:

![image](https://user-images.githubusercontent.com/32702319/145017900-90977fec-e19f-4fd5-b550-553f5b2e4d7b.png)

I am working on 4.4.1 TinyMCE, and chrome browser / Windows 10.

**Comment by landtastic** [comment] 2021-12-21 01:35
Hi, unfortunately TinyMCE 4.x is no longer supported (see https://www.tiny.cloud/blog/tinymce-4-support-window/). TinyMCE 5 is our supported community version, I'd suggest upgrading and seeing if that fixes your issue. I'm going to close this since it's not a version we are supporting, but if you can reproduce on a supported version then please let us know and we'll reopen this issue.

**Closed by landtastic** 2021-12-21 01:35 UTC
