### ISSUE TITLE
Problem in inline mode in  a modal the toolbar don't move with scrollbar

### ISSUE THREAD

**Issue by cyrilus** [tinymce/tinymce#5097] opened 2019-07-26 19:52 UTC
When tinymce in inline mode is use in a modal when the text is long if we try to scroll the toolbar don't move like in a none mode mode
here is a example in a modal
http://fiddle.tinymce.com/ANgaab/29
open the modal , select the text then tinymce appear but if you scroll the tooball don't move

Without modal
http://fiddle.tinymce.com/JNgaab/1
select the text then tinymce appear then when you scroll the tooball don't move

try  on chrome and firefox same problem
Thanks for all

**Comment by wonderbugtiny** [comment] 2019-07-29 03:20
Hi @cyrilus, since this doesn't seem like an issue with a TinyMCE modal, we could only suggest some workarounds. Within the modal, you could try using the editor in iframe mode instead of inline mode. If that is not an option for you then, you would have to handle the inline toolbar positioning through CSS manipulation. Thank you!

**Comment by smoore-ts** [comment] 2019-10-08 12:06
@wonderbugtiny Any update on this?  We have come across the same issue.

**Comment by wonderbugtiny** [comment] 2019-10-14 23:04
@smoore-ts Please note that we currently do not have a timeframe for when this feature request will be considered and added to our sprints. We will let you know when an update is available. Thank you!

**Comment by krolc** [comment] 2019-12-17 16:37
@wonderbugtiny would a fix for this also fix #5227 we are experiencing the same issue. Would be nice to have a fix for this.

**Comment by swirlsky** [comment] 2020-07-03 17:27
> @wonderbugtiny would a fix for this also fix #5227 we are experiencing the same issue. Would be nice to have a fix for this.

The same problem I encountered.

**Comment by xr0master** [comment] 2020-07-22 08:09
> @smoore-ts Please note that we currently do not have a timeframe for when this feature request will be considered and added to our sprints. We will let you know when an update is available. Thank you!

It's pretty funny, over one year with this issue. It's not that hard to fix it...

**Comment by benelliott** [comment] 2020-07-22 08:35
@xr0master submit a PR?

**Comment by xr0master** [comment] 2020-07-22 09:22
Yes. There is no choice. It looks buggy for production.
Today, after work, I will reverse engineer the code and see how to do it.
As in my suggestion, I am planning to add another filed to the init object, like `containerTarget` (to save the 'target' logic), and transfer the reference to the parent container there. By default, will used `document.body`

**Comment by xr0master** [comment] 2020-07-23 08:24
@benelliott Done, if you are interesting, you can test it for the inline mode. My purpose was to fix it for dropdowns:  https://github.com/tinymce/tinymce/issues/5905

**Comment by lnewson** [comment] 2020-07-24 02:19
I'm afraid this isn't just as easy as moving where the UI is attached to. While it will fix it for some cases, it won't fix it for others which is why we haven't made this change. There's a number of additional positioning and styling issues that need to be taken into account when it's not a child of the body, so we'll need to find ways to resolve them first (eg if it's in a fixed position element, or if there are transform styles that'll impact how left/top placement works). Additionally, we'd need to wire up scroll listeners on the scroll container for things like sticky toolbars and context toolbars to work properly.

All of that will take quite a bit of work to implement and test. Unfortunately, we don't currently have it scheduled in the near term either sorry, as we're tied up with other features/projects. I've passed this feature request to our PM to make sure they are aware of it. We'll try and keep this updated once it's been scheduled once and once we have a solution available.

As a side note, if this solution does work for your specific case, then you could do something like this as a workaround instead. However, we can't guarantee other things won't break.
```
setup: function(editor) {
  editor.on('PostRender', function() {
    var container = editor.getContainer();
    var uiContainer = document.querySelector('.tox.tox-tinymce-aux');
    container.parentNode.appendChild(uiContainer);
  });
}
```
**Note:** There are additional complexities if you have more than one editor on the page, as if there are multiple UI containers they will all have the same class.

**Comment by xr0master** [comment] 2020-07-24 06:00
@lnewson Of course, my PR does not cover all the small nuances of your huge project. A few hours of reverse engineering is not enough for this. Nevertheless, the solution is really simple and relevant. I am absolutely sure you will still come to such an idea, even after another year of fixing this bug :) Anyway, it was curious to see how your framework works.

Special thanks for this workaround! By slightly changing the `container`, it covers all our needs. I'm happy.

About your note, it is enough to use a wrapper instead of a document to solve the scope. For other visitors to this topic, I will give an example, just in case.

Let's assume we have a section where only **one** editor can be located. There can be many such sections:

``` html
<section id="my-eidtor-1"></section>
<section id="my-eidtor-2"></section>
```

``` js
setup: function(editor) {
  editor.on('PostRender', function() {
    var container = editor.getContainer();
    var wrapper = document.getElementById('my-eidtor-1');
    var uiContainer = wrapper.querySelector('.tox.tox-tinymce-aux');
    container.parentNode.appendChild(uiContainer);
  });
}
```
**Note**: Not optimized, written for simplicity of example. Indeed, the ID can be added directly to the querySelector.

**Comment by liesahead** [comment] 2020-11-17 07:41
+1. We have a task to inject a perfect scrollbar into inline tinymce editor and it's not possible as we can't mount it on parent HTML element. If we mount it there, then the toolbar positioning is starting to act weird after scrolling editor's content.

**Comment by TheSpyder** [comment] 2022-06-23 05:31
I'm happy to report we've finally scheduled time to look at this in Q3 (July-September). The reason we delayed so long is that moving the UI container element impacts both menus and dialogs. We can't make dialogs unusable just to solve the issue with menu scrolling.

Our efforts will be directed towards having two UI containers, which is a big change, but will allow the menu container to optionally be moved next to the editor.

**Comment by TheSpyder** [comment] 2022-12-13 00:47
Work is progressing, I don't think we'll solve every use case but it will at least fix simple cases of TinyMCE in a scrollable parent. See branch https://github.com/tinymce/tinymce/tree/feature/TINY-9242 and [associated PRs](https://github.com/tinymce/tinymce/pulls?q=Phase+author%3Aephox-mogran).

**Comment by warethis-dev** [comment] 2023-01-27 13:36
My issue is that in all your examples, dropdown menus work fine. Anywhere I use it, following your instructions, the dropdown menu never works properly - it will open below or above my screen every single time.

**Comment by TheSpyder** [comment] 2023-02-01 23:45
Yes, because our examples avoid the scenario that triggers this bug. With the way the UI was designed, if there is _any_ scrollable container in the parent tree of TinyMCE the popups will render incorrectly.

**Comment by TheSpyder** [comment] 2023-02-17 06:09
The branch seems to be complete, and is in the process of final approval before merging for TinyMCE 6.4
#8428

**Comment by angusmglfraser** [comment] 2023-02-27 10:30
Hi 👋🏻 
Do we have an ETA on when this change might be released?

**Comment by TheSpyder** [comment] 2023-03-06 01:25
The branch has now been merged, so it will be in TinyMCE 6.4 - the open source release is scheduled to happen in about two weeks. You could build from `develop` to give it a go, or it's live on the cloud dev channel:
https://fiddle.tiny.cloud/90iaab

I'll leave this ticket open until we know it's working for everyone.

**Comment by angusmglfraser** [comment] 2023-03-07 11:48
I was linked to this issue from [this](https://github.com/tinymce/tinymce/issues/8421) and it seems like the stacking context issues I brought up are still there with this fix https://fiddle.tiny.cloud/90iaab/1

**Comment by warethis-dev** [comment] 2023-03-07 12:26
according to this fiddle [https://fiddle.tiny.cloud/90iaab/1](https://fiddle.tiny.cloud/90iaab/1) the menu is still broken as well but it works in the one above

**Comment by TheSpyder** [comment] 2023-03-08 05:09
Apologies for not making the branch details clearer. The new feature is not enabled by default as it could break existing UIs (the entire reason we put the UI at the end of the body in the first place).

To enable this new feature, add `ui_mode: 'split'` to your config - that fixes the above fiddle.

**Comment by TheSpyder** [comment] 2023-03-17 03:10
TinyMCE 6.4 has been released to open source customers. The cloud stable release is due in a couple of weeks. Please let us know if this does not resolve the issue, particularly if I've linked a ticket to this one and it is not solved.

**Closed by TheSpyder** 2023-03-17 03:10 UTC
Labels: type: feature, status: escalated

**Comment by Yookey** [comment] 2023-11-09 03:39
> TinyMCE 6.4 已向开源客户发布。云稳定版本将在几周后发布。如果这不能解决问题，请告诉我们，特别是如果我已将工单链接到此工单但未解决。
hi, does it seem that this bug still exists, or is there an error in my code?
#9142
