### ISSUE TITLE
return I18n.translate(['{0} words', WordCount.getCount(editor)]); not translated

### ISSUE THREAD

**Issue by cfconsultancy** [tinymce/tinymce#3976] opened 2017-10-04 13:42 UTC
Version 4.7.0

return I18n.translate(['{0} words', WordCount.getCount(editor)]);

example NL "Words: {0}": "Woorden: {0}",

Keeps the name WORDS

**Comment by Afraithe** [comment] 2017-10-04 13:49
Yes, there are a few other language pack updates coming soon as well with 4.7

**Comment by lnewson** [comment] 2020-05-02 11:14
Hi,

Thanks for reporting this and looking at both the TinyMCE 4 and 5 translations, the missing string is now included. Additionally when testing out the translations with TinyMCE 4.9.10 and 5.2.2 I was unable to reproduce the issue, so it's likely we've fixed this since this was reported. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!

**Closed by lnewson** 2020-05-02 11:14 UTC
Labels: component: i18n, status: accepted, status: regression, status: verified
