### ISSUE TITLE
selection.setContent doesn't add node attributes, e.g., noteditable

### ISSUE THREAD

**Issue by scribe777** [tinymce/tinymce#3271] opened 2016-10-16 01:35 UTC
If you call selection.setContent, your new content will not fire all node attribute handlers, e.g., if you `tinymce.activeEditor.selection.setContent('<span class="mceNotEditable">xyz</span>')` then your new content will still be editable.

**Comment by spocke** [comment] 2016-10-17 07:33
No use editor.insertContent instead. Closing this since this is by design selection.setContent doesn't do any filtering.

**Closed by spocke** 2016-10-17 07:33 UTC

**Comment by scribe777** [comment] 2016-10-17 10:48
Thank you Johan. I am sorry for reporting a bug on this. Only a comment then, maybe others might also be led to think that since ed.setContent does filtering, ed.selection.setContent will also do filtering. Thanks for the great tool. It is so important for our work at http://ntvmr.uni-muenster.de

On October 17, 2016 12:33:02 AM MST, "Johan Sörlin" <notifications@github.com> wrote:
>No use editor.insertContent instead. Closing this since this is by
>design selection.setContent doesn't do any filtering.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tinymce/tinymce/issues/3271#issuecomment-254133113

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
