### ISSUE TITLE
iOS 10 Bluetooth Keyboard Arrow Key Abnromal Behavior (Help needed)

### ISSUE THREAD

**Issue by Josheua** [tinymce/tinymce#3288] opened 2016-10-20 23:08 UTC
In iOS 10 (not in iOS 9), TinyMCE responds abnormally. Specifically, when using TinyMCE where the content doesn't fit on the entire screen, using arrow keys causes the content to autoscroll down to the bottom of the page. Manually scrolling up to the content again shows the cursor in its proper spot. Below is a video link showing the isuse.

1) This behavior was not present in iOS 9. 
2) This behavior is limited to bluetooth keyboards (haven't tested smart keyboard yet) on both iPhone and iPad.
3) Testing shows this behavior occurs on both my site and the TinyMCE official site. 

https://m.youtube.com/watch?feature=youtu.be&v=mp9tpAy6Asg

**Comment by fyrkant** [comment] 2016-10-21 09:14
Duplicate of #3242

**Closed by fyrkant** 2016-10-21 09:14 UTC
Labels: resolution: duplicate
