### ISSUE TITLE
TinyMCE remove function kills other events in Firefox

### ISSUE THREAD

**Issue by fanfavorite** [tinymce/tinymce#3129] opened 2016-08-15 13:46 UTC
In TinyMCE v4.4.1, I get TypeError: this.getDoc(...) is null in Firefox (v48.0) on Windows 10 when removing an editor. I am initializing using the jQuery script and removing on blur, like:

```
$(document).ready(function(){
  $('#content').tinymce({
    setup: function(ed) {
      ed.on('blur', function(e) {
        ed.remove();
      });
    },
    script_url: 'https://cdn.tinymce.com/4/tinymce.min.js'
  });
});
```

You can see an example with https://jsfiddle.net/a2nzq6kj/2/

I have seen people have this error, but haven't found any solutions that work for me. When you focus on the editor, then click on the link, you will see that the blur event fires and removes the editor, but it throws the error and doesn't trigger the onclick of the link.

**Comment by lnewson** [comment] 2020-05-09 09:39
Sorry for the delayed response here, but I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5330. You need to wrap the `ed.remove()` call in a `setTimeout` or similar as other event callbacks will still try to run on remove (as they may need to clean things up as well).

We've logged an internal task to see if we can improve the remove behaviour so other callbacks won't be called, however this could cause unexpected behaviour as well. In general, removing the editor while it's processing an event is probably a bad idea, so when removing the editor it's a good idea to have it remove itself outside of the event loop.

**Closed by lnewson** 2020-05-09 09:39 UTC
Labels: status: verified, type: bug
