### ISSUE TITLE
Media plugin in 6.1.0 crashes on editor startup if EMBED tag is not permitted in valid elements

### ISSUE THREAD

**Issue by ShoresOfNowhere** [tinymce/tinymce#7965] opened 2022-07-09 09:16 UTC
**What is the current behavior? Describe the bug**

When starting TinyMCE 6.10 with the integrated media plugin enabled, if the valid elements rules DO NOT permit the EMBED tag, the editor startup crashes.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

Simply do not insert EMBED tag in valid elements and try starting tinymce with media plugin enable, an error appears in the console and the editor fails to start properly.

**What is the expected behavior?**

Media plugin should start and work properly even with EMBED tag disabled, but at least the editor should start properly without the media plugin features.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE 6.1.0 on latest chrome, but the error also appears in FF, Safari, Opera, Vivaldi...

**Comment by lnewson** [comment] 2022-07-09 10:26
Closing as a dupe of https://github.com/tinymce/tinymce/issues/7870. As noted there the media plugin currently requires `iframe`, `video`, `audio`, `embed` and `object` to work. To change this then TinyMCE would need a way to prevent certain URLs which it currently doesn't have, so if you'd like to see that please log a feature request instead.

**Closed by lnewson** 2022-07-09 10:26 UTC
