### ISSUE TITLE
tinymce.min.js - InvalidCharacterError - Internet Explorer 11

### ISSUE THREAD

**Issue by stevewin** [tinymce/tinymce#2550] opened 2015-12-11 16:42 UTC
Dear all,

we are using WordPress 4.3 and facing a problem with TinyMCE using Internet Explorer 11.

It is not possible to:
- Enter Text in the editor field (white screen)
- The Button bar is not available anymore

In the console of the internet explorer the following java script error:

SCRIPT5022: InvalidCharacterError
Datei: tinymce.min.js, Zeile: 3, Spalte: 24308

Mozilla Firefox is working fine.

Can anyone help to solve this issue?

Thanks in advance and all the best,

Steve

**Comment by spocke** [comment] 2015-12-14 10:28
Can't reproduce this on the tinymce.com website so I guess this is WP specific.

**Comment by fyrkant** [comment] 2017-05-26 14:50
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Closed by fyrkant** 2017-05-26 14:50 UTC
Labels: type: bug
