### ISSUE TITLE
Video tag AUTOPLAY defaults to "on"

### ISSUE THREAD

**Issue by chjan** [tinymce/tinymce#4600] opened 2018-10-08 05:46 UTC
For WordPress plugin of this editor. It must have been a couple of years ago that the Video tag AUTOPLAY was changed to default = ON, causing the several hundred videos on my site to autoplay.

This is a nightmare, in particular on pages with several videos. 

Is this related to Tiny MCE or to WordPress? If related to TinyMCE, is there a way to define default to OFF so that we can change this for all videos, instead of going into each video and correcting it?

I tried on one page to enter the TEXT mode of the editor and manually inserting this:

[Video autoplay="off"...], but this is not discovered by the editor. Therefore, back in VISUAL mode of the editor, all videos are still ticked to autoplay (i.e. on). Why is the text "instruction" not obeyed by the visual video configuration?

Thanks for any response and for routing me elsewhere if this is not a Tiny MCE bug.

**Comment by spocke** [comment] 2018-10-08 07:59
I think the shortcodes are part of the wp video embedding. If it can't be reproduced on fiddle.tinymce.com then it's likely an issue with wordpress and better that you report the issue there. If they think it's a tinymce issue we are likely to get the report back to us. I'm closing this since it's out of scope of this project we can re-open this if needed.

**Closed by spocke** 2018-10-08 07:59 UTC
