### ISSUE TITLE
table toolbar overlaps selected text fragment

### ISSUE THREAD

**Issue by grigorydan** [tinymce/tinymce#6552] opened 2021-02-22 13:47 UTC
please visit https://fiddle.tiny.cloud/J5haab
put caret at "Dear $formula....." at beginning.

the problem: table toolbar popup overlaps text that I am editing.

could you either add [x] close button or choose a better positioning algorithm

**Comment by lostkeys** [comment] 2021-02-22 14:18
Yes, we agree and we are working on a solution. As there already exist an issue for this I'm going to close this one as a duplicate of #6258

**Closed by lostkeys** 2021-02-22 14:18 UTC
