### ISSUE TITLE
chrome - center figure tag

### ISSUE THREAD

**Issue by agiorgini** [tinymce/tinymce#6697] opened 2021-04-02 08:12 UTC
**What is the current behavior? Describe the bug**
working correctly with firefox, not with chrome: when inserting (with a custom button) a `<figure>` tag (with an img inside), it doesn't get the style="text-align: center;" attribute

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
create a custom button that inserts a figure tag with an img inside, then click the button to align center

**What is the expected behavior?**
the image to be centered in the page (works in firefox but not in chrome)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

tiny 5.6.2 on windows with chrome (firefox works correctly)

**Comment by ashfordneil** [comment] 2021-04-06 04:47
Hi @agiorgini,

I've had a look, and I'm not able to reproduce the bug at this point in time. I've created [a fiddle that contains this figure tag with an image inside](https://fiddle.tiny.cloud/o9haab), and using that fiddle I have not been able to reproduce the bug you describe where clicking the align centre button does not apply the `text-align: center;` style.

Can you please give me more details about how you encountered this bug, using the fiddle? In particular I need to know where your focus is when you're pressing the `text-align: center` button (you can find this using [the element path element in the status bar](https://www.tiny.cloud/docs/configure/editor-appearance/#elementpath)), and what the editor content HTML looks like after you've pressed the button (you can find this by opening the `Tools` menu, and using the `Source Code` button).

If you need to change the HTML or JavaScript in the fiddle to reproduce this bug, please click the "save" button and update me with the new link.

Also note that due to the content css applied by the default TinyMCE skin, `<figure>` elements have the `margin: 1rem auto` style applied to them while inside the editor. This can make it hard to debug issues such as these, as regardless of any `text-align` styles the figure element itself will always be centred within the editor body.

**Comment by lostkeys** [comment] 2024-02-19 14:22
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.

**Closed by lostkeys** 2024-02-19 14:22 UTC
Labels: needs: more info
