### ISSUE TITLE
Link tag not working

### ISSUE THREAD

**Issue by bkadwal** [tinymce/tinymce#7828] opened 2022-05-15 17:11 UTC
**What is the current behavior? Describe the bug**

I am facing issue with link tag with "id" and without "href".
Please have a look at https://codepen.io/bkadwal/pen/wvygvZa
Specified 3 cases over here, but case 1 isn't working.

**What is the expected behavior?**
All cases should behave same.

<img width="1167" alt="Screenshot 2022-05-15 at 10 40 36 PM" src="https://user-images.githubusercontent.com/105602010/168485236-f2aac75b-bdf1-45d5-a2bd-08bf5d4f548a.png">

**Comment by liesahead** [comment] 2022-05-16 10:42
The first item is not a link, so it's not a bug:

![image](https://user-images.githubusercontent.com/32300784/168575923-d95195ee-1d03-48fc-be16-8e393d86c9b8.png)

**Comment by bkadwal** [comment] 2022-05-16 12:25
Updated the same codepen link

    Case 4:: <a style="background-color: #3c3c3c; color: #ffffff; padding: 0.25rem;"> TEST </a>
    This is rendered correctly.

**Comment by liesahead** [comment] 2022-05-18 12:26
@bkadwal , the first item has `TEST` text outside `a` tag, that is why it's rendered differently.

![image](https://user-images.githubusercontent.com/32300784/169038106-3280b1d7-1a30-4627-97e2-65a0694207c9.png)

**Comment by liesahead** [comment] 2022-05-18 12:28
Also, case 4 is different from case 2 and 3.

No underline for text and no options to remove/open link. Which is correct from tinymce side as there's no `href`.

![image](https://user-images.githubusercontent.com/32300784/169038456-d92304da-9db9-4798-9bbc-8442280a1a60.png)

![image](https://user-images.githubusercontent.com/32300784/169038551-8c3f6571-a368-4347-82f7-ac6658ed479c.png)

**Comment by liesahead** [comment] 2022-05-24 12:42
@bkadwal , because in case 1 `TEST` text is outside of anchor element.

![image](https://user-images.githubusercontent.com/32300784/170037257-b5354d9d-db3e-44b0-893b-1c7db3c2356b.png)

**Comment by bkadwal** [comment] 2022-05-26 07:29
@liesahead Its the editor that is changing it to go outside, though I have put it inside <a id='test'> tag i.e <a> Test </a>

**Comment by TheSpyder** [comment] 2022-05-29 22:41
This is a default behaviour but it can be configured:
https://www.tiny.cloud/docs/tinymce/6/content-filtering/#allow_html_in_named_anchor

Note however that in TinyMCE 5 the UI style makes that setting difficult to use, this was fixed in #7593. Updated codepen:
https://codepen.io/thespyder-the-bashful/pen/poaaqda

**Closed by TheSpyder** 2022-05-29 22:41 UTC
