### ISSUE TITLE
Uncaught TypeError: Failed to execute 'setStart' on 'Range': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by God-Liang** [tinymce/tinymce#5077] opened 2019-07-12 07:18 UTC
Official documents have this problem. After the editor adds the form, select the start position of the form and hit enter to report an error

**Comment by ltrouton** [comment] 2019-07-15 23:21
Hi @God-Liang. Thanks for posting! I am a bit unsure on what you mean by ‘form’. If you could please generate a forked fiddle (http://fiddle.tinymce.com) and step by step instructions that allows the issue to be reproduced that would be very helpful.

**Comment by lnewson** [comment] 2019-08-18 03:48
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-08-18 03:48 UTC
Labels: needs: more info
