### ISSUE TITLE
When you toggle a style that is set by style_format, ExecCommand is not triggered 

### ISSUE THREAD

**Issue by JonathanHouck** [tinymce/tinymce#4814] opened 2019-02-06 14:47 UTC
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** When you set a style_format in the Content formatting options, ExecCommand (editor.on('ExecCommand', function (e) { }) is not triggered when you toggle the style.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.** http://fiddle.tinymce.com/7Bgaab/7

**What is the expected behavior?** The ExecCommand should be triggered when you toggle the style.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** Tested in Google Chrome, this worked in version 4.x

**Comment by lnewson** [comment] 2019-03-01 03:39
The cause of this looks to be that the new UI moved away from calling `execCommand('mceToggleFormat`, false, format)`, however I'm not sure if that was intentional or even if it's expected that toggling should trigger a command since it's a UI action. As such I'll have to talk to the team and find out what's expected.

Out of curiosity though and if it's possible to elaborate, I'd like to know what your use case is here?

**Comment by lnewson** [comment] 2019-03-04 00:05
Talked to the team and there wasn't an explicit reason this was changed and was likely just on oversight. I'll log a task for us to revert back to using the `mceToggleFormat` command.

**Comment by wonderbugtiny** [comment] 2019-03-19 23:09
This should now be fixed in 5.0.3. Please let us know if you find any further problems!

**Closed** 2019-03-20 02:06 UTC
Labels: 5.x, resolution: fixed in coming release, status: escalated, status: regression
