### ISSUE TITLE
tinymce table issue

### ISSUE THREAD

**Issue by priyanka-crypto** [tinymce/tinymce#5168] opened 2019-09-19 07:34 UTC
Hi,
 I am using tinymce for table. It's a **CALS** table. tinymce's not supporting the  **multiple tHead** and tBody. 
Is there any option to support multiple head and body.
please help me to do this.

Thanks,

**Comment by lnewson** [comment] 2019-09-19 07:46
Multiple thead elements aren't valid as per the HTML spec, see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table and https://html.spec.whatwg.org/#the-thead-element TinyMCE should work with a single thead with multiple tbody elements and appears to work as expected in this fiddle I created quickly: http://fiddle.tinymce.com/ZQgaab

Does that answer your question? If not can you please provide more details and preferably a fiddle to show the issue you're having.

**Comment by priyanka-crypto** [comment] 2019-09-19 09:02
Yes, thank you!

As per the HTML multiple thead's are not supported.
In this case, I split my table like this in browser
<table>
<thead>
<tr>
<th>Age</th>
<th>Name</th>
</tr>
</thead>
<tbody>
<tr>
<td>name</td>
<td>price</td>
</tr>
</tbody>
<thead>
<tr>
<th>Age</th>
<th>Name</th>
</tr>
</thead>
<tbody>
<tr>
<td>name</td>
<td>price</td>
</tr>
</tbody>
</table>


After changing some action colspan, add row like this  in tinymce my source code converting as below

<table>
<thead>
<tr>
<th>Age</th>
<th>Name</th>
</tr>
<tr>
<th>Age</th>
<th>Name</th>
</tr>
</thead>
<tbody>
<tr>
<td>name</td>
<td>price</td>
</tr>
<tr>
<td>name</td>
<td>price</td>
</tr>
</tbody>
<thead>
</thead>
<tbody>
</tbody>
</table>

I checked valid_children elements. But not working is there any solution?

**Comment by lnewson** [comment] 2019-09-24 21:38
@priyanka-crypto as I previously mentioned that HTML is not valid, as you've included multiple thead elements in a single table. Additionally you've also included a thead after a tbody, which isn't valid either and why TinyMCE moved it to the correct location (before any tbody elements). Since the HTML is invalid, I'm closing this as not a bug.

You can check if your HTML is valid using this tool: https://validator.w3.org/nu/#textarea I can't include a direct link, but if you paste the following into that tool and click `Check` you'll see it produces an error.
```
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Test</title>
</head>
<body>
<table>
  <thead>
  <tr>
    <th>Age</th>
    <th>Name</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>name</td>
    <td>price</td>
  </tr>
  </tbody>
  <thead>
  <tr>
    <th>Age</th>
    <th>Name</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>name</td>
    <td>price</td>
  </tr>
  </tbody>
</table>
</body>
</html>
```

Lastly I should add if you're trying to use a CALS table in HTML, then you probably want to use `th` elements in place of `td` for where the headers should be, instead of trying to use `thead` elements. Here's a basic example: http://fiddle.tinymce.com/ZQgaab/1

**Closed by lnewson** 2019-09-24 21:38 UTC
Labels: needs: more info

**Comment by hampusolsen** [comment] 2024-01-22 09:34
> [...] TinyMCE should work with a single thead with multiple tbody elements and appears to work as expected in this fiddle I created quickly: http://fiddle.tinymce.com/ZQgaab

I would argue that multiple `<tbody>` tags does **not** work properly. Insertion or deletion breaks the table structure when more than a single one is used. The table plugin places all `<tr>` as children in the first  `<tbody>`, leaving the rest childless as shown below. All I did was simply add a new row beneath the first row of the first body.

![image](https://github.com/tinymce/tinymce/assets/55430265/34ed3725-e11d-48dc-9f4b-3b267f39d86c)
_Untouched structure._

![image](https://github.com/tinymce/tinymce/assets/55430265/4499a5bb-cb3d-483a-8b10-0d1fc303baf6)
_Looks fine at first glance after inserting a new row..._

![image](https://github.com/tinymce/tinymce/assets/55430265/a56a4b6b-64cc-49f4-939a-cfd111cf9c30)
_... but structure is completely broken._
