### ISSUE TITLE
Backspace/Delete not working around links since 4.6.

### ISSUE THREAD

**Issue by Luke-SF** [tinymce/tinymce#3632] opened 2017-05-09 22:29 UTC
**What is the current behavior?**

When you have a link on a line, and try to get it to not be its own line, you can't in the current new TinyMCE 4.6: http://codepen.io/anon/pen/zwRBKO
This is inline, with divs.

**What is the expected behavior?**

You should be able to backspace and put the link anywhere you want as in previous versions

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tinymce 4.6. Yes it worked in previous versions. The issue happens in Firefox, Chrome, probably others.

**Comment by fyrkant** [comment] 2017-05-10 06:35
Hi! We are aware of this regression and it will be fixed in an upcoming 4.6.1 release.

**Comment by fyrkant** [comment] 2017-05-11 07:37
Hi @Luke-SF ! This should be fixed now in the 4.6.1 version we releases yesterday, can you try it out and close the issue if it seems to be working?

**Comment by spocke** [comment] 2017-05-15 15:01
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2017-05-15 15:01 UTC
Labels: resolution: fixed in coming release, status: escalated, status: regression, status: verified

**Comment by krishna-babu** [comment] 2017-05-15 17:45
Hi, This issue is still not fixed. I can repro the same in Tinymce Inlite Demo page
Steps
1. Click anywhere inside the RTE
2. Press Enter twice.
3. Press backspace. (Console will have "tinymce.min.js:6 The given range isn't in document.")
4. Cursor moves to start of RTE
