### ISSUE TITLE
IE11(Windows 8 & 10) throws 'access is denied' error for localStorage in tinymce.js

### ISSUE THREAD

**Issue by nileshbhagwat** [tinymce/tinymce#4338] opened 2018-04-12 07:44 UTC
**Actual behavior**

IE11 throws access is denied error for localStorage in tinymce.js, see attached screenshot.

![access_denied](https://user-images.githubusercontent.com/22997240/38662524-4131f66c-3e52-11e8-8f20-67c91d553408.PNG)

**Expected behavior**

There should not be any error while trying to access a page.

**IE11 Version**

![ie_version](https://user-images.githubusercontent.com/22997240/38662536-4a59e024-3e52-11e8-8819-74804f21409e.PNG)

**Possible Root Cause**

https://github.com/tinymce/tinymce/blob/90a829b4ed7655d91f07df15056a805fa43d49f9/src/core/main/ts/api/util/LocalStorage.ts
here localStorage functionality is not guarded within try..catch block

**Possible Solution**

https://github.com/MrSwitch/hello.js/issues/35#issuecomment-50310996

If browser do not support localStorage then use sessionStorage

**Comment by vinayakpatil** [comment] 2018-04-12 07:45
:+1:

**Comment by Athos6885** [comment] 2018-04-12 07:53
+1

**Comment by Athos6885** [comment] 2018-04-12 08:05
In tinyMCE 4.1.7 access to local storage is made properly.

`// Included from: js/tinymce/classes/util/LocalStorage.js

/**
 * LocalStorage.js
 *
 * Copyright, Moxiecode Systems AB
 * Released under LGPL License.
 *
 * License: http://www.tinymce.com/license
 * Contributing: http://www.tinymce.com/contributing
 */

/**
 * This class will simulate LocalStorage on IE 7 and return the native version on modern browsers.
 * Storage is done using userData on IE 7 and a special serialization format. The format is designed
 * to be as small as possible by making sure that the keys and values doesn't need to be encoded. This
 * makes it possible to store for example HTML data.
 *
 * Storage format for userData:
 * <base 32 key length>,<key string>,<base 32 value length>,<value>,...
 *
 * For example this data key1=value1,key2=value2 would be:
 * 4,key1,6,value1,4,key2,6,value2
 *
 * @class tinymce.util.LocalStorage
 * @static
 * @version 4.0
 * @example
 * tinymce.util.LocalStorage.setItem('key', 'value');
 * var value = tinymce.util.LocalStorage.getItem('key');
 */
define("tinymce/util/LocalStorage", [], function() {
	var LocalStorage, storageElm, items, keys, userDataKey, hasOldIEDataSupport;

	// Check for native support
	try {
		if (window.localStorage) {
			return localStorage;
		}
	} catch (ex) {
		// Ignore
	# }`

**Comment by jagshettiwars** [comment] 2018-04-12 08:42
+1

**Comment by spocke** [comment] 2018-04-13 11:31
We are not exactly seeing the same behavior. We disabled local storage on IE 11 using the dom storage security setting and then it's simply not defined. Never seen it producing an exception. Can you setup a fiddle at fiddle.tinymce.com where this can be reproduced or details of what settings your IE 11 version might have that causes this error.

**Comment by suriya-n** [comment] 2018-07-20 05:49
@spocke **I just want to **emphasis** that this issue is not specific IE11 in windows10. It happens with IE in general with "Protected Mode" enabled regardless of the version of the OS.**

I use windows 8 and IE11 and I get the same Access Denied error when "windows.localStorage" is accessed in tinymce.js..

I did some play around in tinymce.fiddle to see from what versions this issues happens and I found out that this happens in most of the recent versions from 4.7.0 to 4.8.0.

it doesn't occur from Version 4.6.7 and all older versions, where access to local storage is made properly, Guarded within try-catch.

This will stop many users who use IE to upgrade to the latest version of tinyMCE.

Please address this in coming release ASAP.

**Comment by vinayakpatil** [comment] 2018-07-20 05:59
Since there was no response on this issue, we added following workaround with https://www.npmjs.com/package/patch-package

```
patch-package
--- a/node_modules/tinymce/tinymce.js
+++ b/node_modules/tinymce/tinymce.js
@@ -25547,7 +25547,18 @@
     }
   };
 
-  var localStorage = window.localStorage;
+  var localStorage = null;
+
+  // Does this browser support localStorage?
+  try {
+    localStorage = window.localStorage;
+  } catch (e) {}
+
+  // Does this browser support sessionStorage?
+  try {
+    if (!localStorage) localStorage = window.sessionStorage;
+  } catch (e) {}
+
 
   var tinymce = EditorManager$1;
   var publicApi = {

```

**Comment by suriya-n** [comment] 2018-07-20 06:42
@vinayakpatil thanks for you comment. though it's a proper workaround, it's always not good to tweak any third party library file.

@nileshbhagwat could you please change the title of the issue like below to remove OS specific:
"IE throws 'access is denied' error for window.localStorage in tinymce.js"

**Comment by nileshbhagwat** [comment] 2018-07-20 13:05
@suriya-n this issue is not reproducible with windows 7, only with windows 8 & 10.

**Comment by fyrkant** [comment] 2018-08-13 10:59
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2018-08-13 10:59 UTC

**Comment by suriya-n** [comment] 2018-08-21 07:08
@fyrkant Thank You!

the issue no longer exists with the latest version - 4.8.2

thanks.
