### ISSUE TITLE
default_target_link still not respected

### ISSUE THREAD

**Issue by eschiebel** [tinymce/tinymce#5036] opened 2019-06-07 21:34 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
setting default_link_target doesn't add attribute to the created anchor.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/YJgaab

**What is the expected behavior?**
<a target="_blank">
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5.0.6

This issue, reported as #4913 , was marked as fixed and closed. It is not fixed.

**Comment by lnewson** [comment] 2019-06-08 10:19
Thanks for the report! I can reproduce this, though it's a little different to the previous report. The previous issue was fixed when a `target_list` exists, however if the list disabled then the value doesn't exist in the dialog and as such is never applied. I'll log an internal ticket to also fix it for when the list is disabled.

**Comment by ultimagecko** [comment] 2019-06-11 19:18
Since I posted in the other linked issue, I figured I might as well post here:

I see you've tagged this as plugin:link. I'd like to note that autolink doesn't seem to make a target regardless of whether there was a defined target_list or target_list:false in 5.0.6.

Just pasting a link doesn't use the default_target_link. If you paste a url then select the link then click on the link button and run through the dialog, you can get a target, but it doesn't truly use the set default.

**Comment by blackcathikari** [comment] 2019-07-17 03:31
@ultimagecko The autolink plugin deals with URLs that are typed into the editor, not pasted URLs. From my testing on fiddle.tinymce.com autolink works as expected with default_target_link. If you would like for the paste event to filter links and add targets, that would need to be a feature request in a new ticket.

**Comment by lnewson** [comment] 2019-08-06 07:42
This issue has been fixed in TinyMCE 5.0.13, which has just been released to the community. Please let us know if you have any further issues.

**Closed by lnewson** 2019-08-06 07:42 UTC
Labels: 5.x, plugin: link, status: escalated, status: regression, type: bug

**Comment by Vrq** [comment] 2022-05-12 17:18
It doesn't work anymore in version 6.X

Here an example: https://fiddle.tiny.cloud/ndiaab

**Comment by lnewson** [comment] 2022-05-12 23:29
Hi @Vrq,

That's because the option was renamed in TinyMCE 6 to `link_default_target` and you can see it works in https://fiddle.tiny.cloud/ndiaab/1 after that's been changed. This can be seen in the TinyMCE 5 -> 6 migration guide here: tiny.cloud/docs/tinymce/6/migration-from-5x/#things-we-renamed

**Comment by Vrq** [comment] 2022-05-13 06:20
Hi @lnewson,

Thanks for the hint! 
It works now when it comes to adding links manually.

However, when copy-pasting links (from Google Sheets for example) - then this value is not respected and links are added without target=_blank

**Comment by lnewson** [comment] 2022-05-13 06:26
Yes, that's expected as the `link_default_target` option only controls the default target for new links created in the editor. Links pasted in are not newly created and the intention is to keep them the same as they are in the source content (as doing that would forcibly change it instead of it being a default). If you want to change them in copied content you could always do it using the `PastePostProcess` event to find all anchor elements and then set the target to whatever you want.
