### ISSUE TITLE
tinymce overflows on DIV in Chrome

### ISSUE THREAD

**Issue by chicagosky** [tinymce/tinymce#3239] opened 2016-10-03 06:20 UTC
This problem is occurring on Chrome 53.0.2785.143 on MacOS Yosemite. I have applied TinyMCE on a DIV tag and when I type all the way to the bottom, instead of scrolling the editor moves up and out of the screen line-by-line. See screenshot below.

I tested this issue on Firefox and did not observe the same problem there. Has anyone else noticed this issue?

![screen shot 2016-10-03 at 1 20 01 am](https://cloud.githubusercontent.com/assets/7997776/19028970/8e574b2e-8907-11e6-8dac-be61f71ebe81.png)

**Comment by chicagosky** [comment] 2016-10-03 06:28
Also occurs on Chrome - confirmed

**Comment by spocke** [comment] 2016-10-03 12:04
We need a way to reproduce this out side your environment. Looks like a integration issue to me rather than a bug. So setup a fiddle at fiddle.tinymce.com where it can be reproduced and we will look at it. Thanks.

**Comment by tinydylan** [comment] 2020-04-26 12:13
Hi,

Since we don't have a way to reproduce this issue, we're unable to proceed and will be closing this issue. If you are able to provide a simple self-contained replication case - e.g. on fiddle.tinymce.com or codepen.io, then we'll be able to investigate further.

Thanks!

**Closed by tinydylan** 2020-04-26 12:13 UTC
Labels: browser: chrome (android), component: ui
