### ISSUE TITLE
"No color" button of background remove its class instead of style.

### ISSUE THREAD

**Issue by vusan** [tinymce/tinymce#3499] opened 2017-02-21 05:25 UTC
Selecting no color ([x] button on background colors) do not remove its inline color, selecting no color will remove its class instead.

This issue found if class is put by program itself.  This is  the [fiddle](http://fiddle.tinymce.com/KJfaab/1) to reproduce the problem.

Version of TinyMce is 4.5.0

**Comment by fyrkant** [comment] 2017-02-22 14:22
Please don't create duplicate issues.

Duplicate of #3489

**Closed by fyrkant** 2017-02-22 14:22 UTC
