### ISSUE TITLE
NS_ERROR_UNEXPECTED when removing editor without focusing

### ISSUE THREAD

**Issue by arunkumartkv** [tinymce/tinymce#3335] opened 2016-11-21 14:16 UTC
Team,
I am getting an error, when I call tinyMCE.remove() without focusing inside the editor. Here is the stack trace of it.

File - /js/tinymce/tinymce.min.js
Line - 5
Column - 0
ErrorMessage - NS_ERROR_UNEXPECTED: 
ErrorName - NS_ERROR_UNEXPECTED
ErrorMessage - 
 ErrorStack - .serialize@/js/tinymce/tinymce.min.js:5:19454

A.prototype.getContent@/js/tinymce/tinymce.min.js:11:23814
A.prototype.save@/js/tinymce/tinymce.min.js:11:22449
A.prototype.remove@/js/tinymce/tinymce.min.js:11:25715
C.remove@/js/tinymce/tinymce.min.js:12:1956
C.remove@/js/tinymce/tinymce.min.js:12:2018

**Comment by fyrkant** [comment] 2016-11-21 14:24
Hi! 

Thank you for your bug report. Are you able to reproduce the error in a [fiddle](http://fiddle.tinymce.com/)?

**Comment by arunkumartkv** [comment] 2016-11-21 14:41
Hi fyrkant,

Here is the fiddle. http://fiddle.tinymce.com/mCfaab

I think it is because I am removing the editor div before destroying tinyMCE.

**Comment by fyrkant** [comment] 2016-11-21 14:50
Yeah the problem is that you are removing the element before removing the tinymce instance, just change the order to 

```js
tinyMCE.remove();$('form').remove();event.preventDefault();
```

And it should work.

**Comment by fyrkant** [comment] 2016-11-21 16:18
Seems like you are pleased with that resolution so I'm closing this issue! If there's anything else you're wondering, please leave a comment and I can open the issue up again. Cheers!

**Closed by fyrkant** 2016-11-21 16:18 UTC
