### ISSUE TITLE
Bold, undo, then redo of pasted text from Word causes corrupted text

### ISSUE THREAD

**Issue by amysutedja** [tinymce/tinymce#2811] opened 2016-03-29 20:45 UTC
Description of Problem:
Some pasted text from Word documents interacts poorly with undo/redo, resulting in strange state and corrupted text.

Steps to Reproduce:
1. Open the following document in Microsoft Word: http://calibre-ebook.com/downloads/demos/demo.docx
2. Copy the contents of the DOCX into TinyMCE: http://fiddle.tinymce.com/Otfaab
3. Bold the fragment "This document demonstrates the ability of the calibre DOCX".
4. Click the Undo button. Notice that the text disappears.
5. Click the Redo button. Notice that the text is now corrupted.

**Comment by spocke** [comment] 2016-03-30 12:09
Please use the paste plugin or better yet the powerpaste plugin since it handles word contents even better. I couldn't reproduce the bug when the paste plugin was enabled. So closing unless I can reproduce it.

**Closed by spocke** 2016-03-30 12:09 UTC
Labels: plugin: paste, type: bug
