### ISSUE TITLE
Adding Image Directly (Without Setting Focus On TinyMCE Gives NotSupportedError)

### ISSUE THREAD

**Issue by faizalshap** [tinymce/tinymce#3272] opened 2016-10-17 12:35 UTC
Steps To reproduce  :
1. init tinyMCE with image Plugin.
2. After load Completed, click directly on the image icon without Setting Cursor anywhere.
3. Enter Image URL in Source and Click OK.
4. See Error Arised in Console.

![image](https://cloud.githubusercontent.com/assets/20452561/19437726/41b7e66e-9494-11e6-83e8-7ce0c754db64.png)

By Adding The Following Code in Plugin.js the issue can be Resolved  : 

```
if (editor.selection.getRng().startOffset == 0) {
                editor.selection.select(tinyMCE.activeEditor.getBody(), true);
                editor.selection.collapse(false);
            }
```

**Comment by lnewson** [comment] 2020-05-09 11:23
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 11:23 UTC
