### ISSUE TITLE
In Firefox, inline format at beginning of multiline paragraph positions cursor at end of previous line.

### ISSUE THREAD

**Issue by fredsdc** [tinymce/tinymce#4267] opened 2018-03-05 14:40 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In Firefox, navigating using arrow keys, the cursor is blocked from going down if it encounters a first word in a different inline format.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Write a paragraph that wraps to multiple lines
2. On the second line of the paragraph, highlight the first word and set it to italic (it could be any line but the first and any inline format).
3. Click anywhere above the line with the italic word and press Home key to go to the beginning of the line.
4. Try to navigate across the italic word using the down arrow on keyboard.

When you get to the word in italic, the cursor is positioned at the end of the previous line and refuses to advance down. You have to click elsewhere or navigate left. It is annoying.

**What is the expected behavior?**

The expected behaviour is, when pressing the arrow down, to go to the next line. Also, the cursor is supposed to be positioned at the beginning of the line.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested the bug and it affects the version demoed at the site (4.7.9) and many previous versions in fiddle. I use Firefox 58 under Ubuntu 17.10. Cromium, at least, maintains expected behavior.

**Comment by lnewson** [comment] 2020-05-08 08:06
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.10. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 08:06 UTC
Labels: browser: firefox, status: escalated, status: verified, type: bug
