### ISSUE TITLE
Ctrl-A doesn't select first <p>

### ISSUE THREAD

**Issue by antonleb** [tinymce/tinymce#2981] opened 2016-06-07 12:50 UTC
1. I enter 1\n2\n3
   element browser show me:

```
<p>1</p>
<p>2</p>
<p>3</p>
```
1. I press Ctrl-A and then enter 1\n2\n3
   element browser show me:

```
<p></p>
<p>1</p>
<p>2</p>
<p>3</p>
```

each step 2 encrease blank `<p>` tags
in result editor send me `&nbsp;` on each blank `<p>`

**Comment by tinydylan** [comment] 2020-04-20 09:20
Hi,

I'm unable to reproduce this issue. In my testing, I wasn't getting the extra paragraphs. Due to the age of this ticket, it's likely that this is an issue we've since fixed.

We'll close the issue for now, but if the issue persists, please let us know.

Thanks!

**Closed by tinydylan** 2020-04-20 09:20 UTC
Labels: component: input/output
