### ISSUE TITLE
Paste HTML loosing style in Chrome

### ISSUE THREAD

**Issue by mtissington** [tinymce/tinymce#4674] opened 2018-11-19 10:27 UTC
I have the following HTML in the clipboard
```
Version:0.9
StartHTML:00000092
EndHTML:00000217
StartFragment:00000123
EndFragment:00000184
<html><body><!--StartFragment--><p><span style="color: #ff0000;">Hello World&nbsp;</span></p><!--EndFragment--></body></html> 
```
When I paste this into tinymce in Edge or Firefox it correctly includes the span with the color.
```
<p><span style="color: #ff0000;">Hello World </span>&nbsp;</p>
```

When I paste into Chrome it looses the span.
```
<p>Hello World&nbsp;&nbsp;</p>
```

Why? Bug?

**Comment by fyrkant** [comment] 2018-12-06 08:14
Are you using the paste plugin?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:41
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:41 UTC
Labels: needs: more info
