### ISSUE TITLE
TinyMCE v5 - When placed in a CSS grid layout, labels appear vertically

### ISSUE THREAD

**Issue by dezertdezine** [tinymce/tinymce#4821] opened 2019-02-11 11:32 UTC
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When placed in a CSS grid layout, labels appear vertically.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Codepen example here:
https://codepen.io/dezertdezine/pen/QYrLKV

**What is the expected behavior?**
Labels should appear horizontally.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0.0
Checked in Chrome 72 / Firefox 65
I'm new to TinyMCE, but I'm not seeing this behaviour in TinyMCE v4.9.2

**Comment by blackcathikari** [comment] 2019-02-12 05:33
Thank you for the Codepen! My initial guess is that this is caused by CSS grid and flexbox interacting badly, since we didn't use flexbox in TinyMCE 4. I'll log this for investigation.

**Comment by lnewson** [comment] 2019-02-21 11:41
If it helps, the cause here looks to be the actual css being used in conjunction with how the menu items, etc... are added to the DOM. TinyMCE 5 adds a "sink" element to the end of the body, which then is used to position all floating elements.

So what's happening is the grid css doesn't allow for the additional dom elements, which then causes the sink element to have a width of 0px. So if you instead wrap the content in a div and move the`hg_grid` class to that div then it works as expected. eg:
```
<body>
  <div class="hg_grid">
    <header>
        <div>
            HEADER TINYMCE TEST
        </div>
    </header>
    <aside>
        <nav>
            <ul>
                <li><a href="#">NAV</a></li>
            </ul>
        </nav>
    </aside>
    <main>
        <h1>TinyMCE Inside CSS Grid Test</h1>
        <form method="post">
            <textarea id="mytextarea">Hello, World!</textarea>
        </form>
    </main>
    <footer>
        <p>FOOTER</p>
    </footer>
  </div>
</body>
```

**Comment by dezertdezine** [comment] 2019-02-21 15:06
Thanks for the explanation. That fix does indeed work, but for now I'm going to stay with v 4.9.3 until v 5 is more mature.

**Comment by misterHippo** [comment] 2020-11-09 06:14
Hi all, 

I've just realised this is what I'm experiencing. All the drop down menus look like this: 
![image](https://user-images.githubusercontent.com/605912/98506079-d8176d80-22ae-11eb-8736-cd988cb0c386.png)

I'm running 5.5.1, is there some way of moving where `.tox` lives? `body` is `display:grid`, and `.tox` is being put as a child of `body`.

**Comment by lnewson** [comment] 2020-11-09 21:08
This issue should be fixed in the upcoming TinyMCE 5.6 release (currently available via the nightly downloads or 5-dev cloud channel).

**Comment by misterHippo** [comment] 2020-11-11 02:06
@lnewson - question; when is 5.6 planned to be released?

**Comment by lnewson** [comment] 2020-11-11 07:14
TinyMCE 5.6 should be released to the community within the next couple of weeks, as we're finalizing the release now.

**Comment by lnewson** [comment] 2020-11-18 06:50
TinyMCE 5.6.0 has now been released to the community :tada:

**Closed by lnewson** 2020-11-18 06:50 UTC
Labels: 5.x, component: ui, resolution: fixed in coming release, status: escalated, type: bug
