### ISSUE TITLE
Add style to element over the custom button in TinyMCE 5?

### ISSUE THREAD

**Issue by nkunic** [tinymce/tinymce#5040] opened 2019-06-14 17:10 UTC
How can I **add style** (etc. padding-left: 10px;) or **css class** to an element over the **custom Button** and **custom Context toolbar** in TinyMCE 5?

This is what I've came so far:

            editor.ui.registry.addButton('addstyle', {
                icon: 'plus',
                tooltip: 'Align image left',
                onAction: 
            });

I am missing what to write on **onAction**?

            editor.ui.registry.addContextToolbar('imagealignment', {
                predicate: function (node: any) {
                    return node.nodeName.toLowerCase() === 'img'
                },
                items: 'addstyle',
                scope: 'node',
                position: 'node'
            });

**Comment by wonderbugtiny** [comment] 2019-07-02 04:28
@nkunic I would like to get more clarity on what you are trying to achieve. Is the question, how to apply styles to a custom toolbar button? Or how to create a custom button that applies styles? It will also be helpful if you could add a [fiddle](http://fiddle.tinymce.com/) to demonstrate your use case. Thank you.

**Comment by mattford** [comment] 2019-07-02 08:43
@wonderbugtiny I think I might be running into this same issue, in previous versions of tinymce we defined buttons like this:
```
editor.addButton('myButton', {
    title: 'My Button',
    classes: 'myClass',
});
```

and this meant we could style the specific button via CSS and also manipulate it via JS (for example showing/hiding buttons in certain situations)

However as far as I can tell there is no way to add a custom CSS class to a toolbar button in 5.x

**Comment by wonderbugtiny** [comment] 2019-07-03 01:07
@nkunic @mattford It is by design that there is currently no option to add styles or classes to custom components. It is to maintain the uniformity in look and feel of the TinyMCE UI. However, we do have a task logged internally to look into adding classes to all individual components. We will let you know when we have an update.
Alternatively, you could choose one of our pre-made Premium Skins and Icon Packs to quickly give TinyMCE a new look. Please note that skins and icon packs will apply to all buttons, not a specific button.

**Comment by mattford** [comment] 2019-07-08 11:05
@wonderbugtiny Thanks for the info. As I say our main use case for this was to show and hide buttons using JS logic rather than adding styles. This use case could be resolved by adding a `setHidden` method to the button API.

**Comment by dotKev** [comment] 2019-10-11 19:45
In v4, we have a few custom and default buttons that we applied custom icons to via css. The icons are already loaded on the page and it's trivial to swap the defaults out via CSS. In v5, we're using title selectors (`.tox-tbtn[title="Insert/edit link"]:before`) but that seems too fragile. A class attribute on `editor.ui.registry.addToggleButton` options or a return to an `icon` attribute that isn't sanitized against an icon pack would be fantastic.

**Comment by lostkeys** [comment] 2020-06-23 08:36
Circling back, it's fragile css overrides that prevents us from adding hocks and crannies into the TinyMCE UI. If we bless developers reaching in and adding their own css to ui elements, we will tie our backs severely when changing the css and fixing html/css bugs ourselves, because we could - and would - break peoples ui. This is especially important for our users using the cloud version of TinyMCE as they will always be using the latest and greatest.
If you absolutely have to, the :nth-child selector is useful.

**Closed by lostkeys** 2020-06-23 08:36 UTC
Labels: 5.x, component: ui, status: escalated, type: feature

**Comment by maheish** [comment] 2020-11-19 15:20
I have a scenario to conditionally display an icon in toolbar at the right end (other icons are left aligned to the toolbar).
Also in tests, it would have been much elegant to assert based on a custom class added to the button.

It will be really helpful if adding custom classes to toolbar buttons are supported!

**Comment by lostkeys** [comment] 2020-11-19 15:25
@maheish Thanks for your insights! For your use case it might be easiest to create your own button outside of TinyMCE and absolute position it on top of TinyMCE on the right side of the toolbar. You can reuse our css classes if you like.

**Comment by OlivierJaquemet** [comment] 2020-11-25 16:38
I have provided a complete workaround for this need in this comment : https://github.com/tinymce/tinymce/issues/6163#issuecomment-733817716

(it's kludge, however it is compatible with I18N, and does not depend on ugly title attribute selector previously mentioned on this thread)

**Comment by joyously** [comment] 2021-11-11 02:53
> For your use case it might be easiest to create your own button outside of TinyMCE and absolute position it on top of TinyMCE on the right side of the toolbar.

This solution is terrible for accessibility! It would also would not respond correctly with the rest of the toolbar on scroll or resize.

> I have provided a complete workaround for this need

Thanks for this (I was thinking of writing it too), but it uses a function that has been deprecated in 5.10.
