### ISSUE TITLE
Underline doesn't match the color of the text

### ISSUE THREAD

**Issue by alserz1** [tinymce/tinymce#4523] opened 2018-08-10 10:15 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Write some text, Format-Underline, write more text, change text color. Underline doesn't change color even though it should.

**What is the expected behavior?**
Underline matches the color of the text.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on TinyMCE v. 4.8.2-101, Chrome 68, Windows 7.

**Comment by fyrkant** [comment] 2018-08-13 07:02
Duplicate of #3751

**Closed by fyrkant** 2018-08-13 07:02 UTC
