### ISSUE TITLE
default_link_target is always set on update

### ISSUE THREAD

**Issue by valse** [tinymce/tinymce#5135] opened 2019-08-28 07:38 UTC
Hi, if I set a default_link_target to "_blank", when it's set I'm unable to remove it.

Even if I start from a link without it, if I open the link dialog and I save it, the default target is applied even if not selected.

Here a demo http://fiddle.tinymce.com/IPgaab/4

**Comment by wonderbugtiny** [comment] 2019-08-29 05:26
@valse Thanks for the report! I have created a ticket internally for us to work on the issue. We will update you once the fix is available.

**Comment by lnewson** [comment] 2019-11-19 22:18
Sorry for the delayed update here, but this issue was fixed in TinyMCE 5.1 which was released last month. Please let us know if you have any further issues.

**Comment by lnewson** [comment] 2019-11-19 22:22
I'm really sorry, but I got the wrong version here, this has been fixed in 5.2 which has yet to be released not 5.1. So reopening the issue, since we've got a few tickets about this now I'll talk to our PM about backporting the fix for 5.1.3.

**Comment by lnewson** [comment] 2019-12-04 04:02
TinyMCE 5.1.3 has just been released to community which contains a fix for this issue. Please let us know if you have any further issues.

**Closed by lnewson** 2019-12-04 04:02 UTC
Labels: 5.x, plugin: link, resolution: fixed in coming release, status: escalated

**Comment by noraab** [comment] 2020-03-12 13:12
@lnewson , I'm sorry to say - but this bug has to be reopened. It is again there in 5.2
You can use the fiddle provided by @valse to reproduce.

Btw: It can even be reproduced using 5.1.3. Can anyone confirm that it has been fixed at anytime?
