### ISSUE TITLE
Fontfamily Pulldown Menu HTML Bug

### ISSUE THREAD

**Issue by akissz** [tinymce/tinymce#9222] opened 2023-12-07 02:11 UTC
Just upgraded from version 4 to 6. The html that is generated by the Fontfamily Pulldown Menu has double quotes around font names with spaces in the font name, this should be single quote only.

**Comment by TheSpyder** [comment] 2023-12-07 06:16
Please follow the issue template.

I'm pretty sure both are valid.

**Comment by TheSpyder** [comment] 2023-12-07 22:15
I'm not sure what you mean. Please provide the details requested in the [issue template](https://github.com/tinymce/tinymce/issues/new?assignees=&labels=type:bug&projects=&template=bug_report.md).

**Comment by akissz** [comment] 2023-12-08 00:13
Version 6.7 currently breaks all proper html if font name has a space. Here is a example of the bad html that version 6.7 creates:

`<span style="font-family: "arial black", sans-serif;">ROCK</span>`

Not sure why this is not clear already for you as the html above is clearly **bad**... but maybe my config is causing a conflict so I am including most of my code also. Also tried entity_encoding as _raw_ and _named_.

```
 tinymce.init({
  selector:'#selector',
  fixed_toolbar_container:'#myid',
  entity_encoding:'named',
  setup:(editor) => {
   editor.setContent({format:''});
  },
  content_style:style,
  resize:false,
  visual:false,
  auto_focus:true,
  menubar:false,
  inline:true,
  theme:'silver',
  add_unload_trigger:false
 });
```

**Comment by spocke** [comment] 2023-12-08 18:30
That is an internal editor state, the data attribute is what will be serialized as the style attribute it was added for performance reasons. You would normally never see that attribute if you use the `editor.getContent()` API to get the editor contents out.
As far as I know tinymce produces valid HTML output and will html entity encode " and ' characters when needed such as this case where the single quotes are in a double quote attribute then it doesn't need to be encoded in valid HTML. This is the HTML code I get when using Chrome and the fiddle I provided `<span style="font-family: 'arial black', sans-serif;">text</span>` that has single quotes in double quote attributes and that is valid HTML.
The old ticket you linked to was closed since we couldn't reproduce that either due to lack of information. If we can't reproduce this then we are likely going to close this one as well. We need a clear definition of what is wrong and a fiddle test case where it produces invalid HTML to be able to accept this as a bug.

**Comment by akissz** [comment] 2023-12-09 18:18
If its easy... Can you show me the tinymce javascript code that inserts the html each time you click on the font family pull down item? I want to look at this javascript then maybe I will find the conflict.

And second, the only way that I can think that double quotes would be inserting is if there was a replace command in a script but there is not anything like that in my code. Is there another form to post this question to help find a resolution?

**Closed** 2023-12-10 15:58 UTC
Labels: needs: more info

**Comment by TheSpyder** [comment] 2023-12-11 03:22
I totally understand this is invalid HTML:
`<span style="font-family: "arial black", sans-serif;">ROCK</span>`

But TinyMCE doesn't create that. If you're seeing it in the output something else is going wrong.

`&quot;` is a perfectly valid quote character to use in a HTML attribute, even when it's part of a CSS value. The most likely source of this is actually the browser, which often adjusts the DOM value when we set the `font-family` CSS attribute. That's why we use `data-mce-style` to record what we _actually_ want, and use it instead of the `style` attribute when serialising.

The key is to look at the source view (or `getContent` output), not the DOM inspector. That's all that matters.

**Comment by TheSpyder** [comment] 2023-12-11 04:01
To answer the question you deleted, the code is here:
https://github.com/tinymce/tinymce/blob/85993d046143358423b0c91f723a01db2fb193e7/modules/tinymce/src/themes/silver/main/ts/ui/core/complex/FontFamilyBespoke.ts#L78-L83

And the default values are here:
https://github.com/tinymce/tinymce/blob/c19a0b94382ec10fbc518a832358c71f7dd9ded2/modules/tinymce/src/themes/silver/main/ts/api/Options.ts#L97-L116

So when `Arial Black` is selected, the command becomes
```
editor.execCommand('FontName', false, "arial black,sans-serif");
```

Which, after a bunch of processing, ends up in a call to:
```
element.style.setProperty("font-family", "'arial black',sans-serif");
```

So yeah. It's the browser.
