### ISSUE TITLE
Version 4.7.4 - Spellchecker and Autosave bug - The autosave plugin believes that a misspelled word is a change in the document

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4127] opened 2017-12-17 05:22 UTC
Click in the Spellchecker Icon, the 'esample' word now should be underlined and now press the link below and you will get a browser message like if the content of the document has been modified. Tested in the latest version of Firefox. In older versions of Firefox, it's necessary to try to refresh the page in order to get that message.

https://codepen.io/lrusso85/pen/mpeaxV

**Comment by lnewson** [comment] 2020-05-08 09:04
This appears to be a duplicate of https://github.com/tinymce/tinymce/issues/4264 and I'm no longer able to reproduce this in TinyMCE 4.9.10 or 5.2.2, so I'm going to close this. If you're still able to reproduce this in the latest version let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:04 UTC
Labels: plugin: spellchecker, status: escalated, status: verified, type: bug
