### ISSUE TITLE
html code mode: can't set style if SPAN has mceNonEditable

### ISSUE THREAD

**Issue by aruben-c** [tinymce/tinymce#3225] opened 2016-09-26 10:49 UTC
Hi,

I have an issue with SPAN tags if it content is non editable: the 'style' attribute is removed, but not classes or 'data-' attribute or innerHMTL content, even if we force it in the html code mode.
But with all other tags (B, I, EM ...), we can force the 'style' attribute in the html code mode if contenteditable=false.
I try to switch to another tag, but when I set again SPAN, the style is removed.

So, currently, it's necessary to create a class to customize a non editable SPAN (but not for other tags!).

Perhaps the good way is to allow changing a non editable SPAN tag in html code mode but not in the wysiwyg view mode.
What do you think?

Thanks,
ARuben

**Comment by lnewson** [comment] 2020-05-09 09:58
Hi,

Sorry for only replying to this now, however I attempted to reproduce this issue using TinyMCE 4.9.10 and 5.2.2 via http://fiddle.tinymce.com/gihaab but it appears to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 09:58 UTC
Labels: component: cE=false
