### ISSUE TITLE
"save" button not enabled after unlink

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2374] opened 2015-08-28 16:52 UTC
Description of problem:
"save" button doesnt get enabled when only doing a "unlink" but nothing more.

Steps to reproduce:
1. open http://fiddle.tinymce.com/QXeaab
2. click the linked text "du"
3. click the "unlink" button

Expected result:
Since this changed the content of the editor, "save" button should get enabled, so I can save my changes

Actual result:
"save" buttons keeps beeing disabled

Tested on FF 45a2 Dev Edition
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7668](http://archive.tinymce.com/develop/bugtracker_view.php?id=7668) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_

> _**Tags:** []_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/QXeaab_

**Comment by tengbretson** [comment] 2015-12-02 20:52
It seems like this is fixed in the 4.3 release

**Comment by blackcathikari** [comment] 2016-07-25 02:10
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 02:10 UTC
Labels: component: ui, origin: tinymce.com, status: verified, type: bug
