### ISSUE TITLE
Special character descriptions overflow modal window

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2168] opened 2015-03-27 12:32 UTC
Description of problem:

Long descriptions of special characters are not fully visible when hovering over boxes in the 'Special character' modal window.

Steps to reproduce:
1. Open Insert > Special character
2. Mouse over the � character (fourth from the end of the top row)

Expected result:

The following text should be visible on the right of the modal window:

"single right-pointing angle quotation mark"

Actual result:

Half of the text is not visible:

"single right-pointing a"

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7454](http://archive.tinymce.com/develop/bugtracker_view.php?id=7454) posted by [robtree](http://archive.tinymce.com/profile.php?name=robtree)_
> 
> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://www.tinymce.com/tryit/basic.php_

**Comment by blackcathikari** [comment] 2016-07-25 01:51
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by robtree** [comment] 2016-07-25 09:15
It's still reproducible in TinyMCE 4.4.0. I can't simplify the reproduction steps any further. Would you mind checking again, please?

**Comment by blackcathikari** [comment] 2016-08-01 03:20
Our apologies @robtree, I can replicate that, yes. I'll reopen this ticket. Thanks for getting back to us. 
- Millie @ TinyMCE

**Comment by fyrkant** [comment] 2017-05-24 14:51
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Closed by fyrkant** 2017-05-24 14:51 UTC
Labels: browser: chrome, browser: firefox, browser: ie, browser: safari, origin: tinymce.com, type: bug

**Comment by robtree** [comment] 2017-05-24 15:02
Sure, there's #3681 now.
