### ISSUE TITLE
(5.x) Editor iframe breaks on iPad 5th/6th Gen + Safari 11

### ISSUE THREAD

**Issue by Paril** [tinymce/tinymce#4846] opened 2019-02-22 17:32 UTC
It's a bit hard to explain this, but the iframe of the editor on this specific version of Safari/iOS combo is messed up greatly. When you focus/type in the editor, the top of it moves up by an odd amount.

Here's a video describing the issue:
https://streamable.com/mhhri

The issue exists on the tinyMCE test page as well:
![](https://i.imgur.com/4BGdOg5.png)

**Comment by samuel9554** [comment] 2019-05-14 02:22
Any idea in which version it should be fix? The issue is getting me crazy since I have to change device to be able to edit a existing textarea.

**Comment by TinyBart** [comment] 2019-07-04 01:35
Hey, @samuel9554 we are working on mobile improvements. I can't give you an exact time frame, but I can assure you that is our high priority.

**Comment by EkimChau** [comment] 2020-02-07 04:01
Hi, 
This issue appears to have been resolved by Safari 12.  This issue does not appear in the latest version of Safari 13x

**Closed by EkimChau** 2020-02-07 04:01 UTC
Labels: 5.x, browser: safari (iOS), status: escalated, type: bug
