### ISSUE TITLE
Anchors removed on hitting backspace in same line (FF)

### ISSUE THREAD

**Issue by susebus** [tinymce/tinymce#2626] opened 2016-01-14 08:08 UTC
On Firefox:
When I set an anchor and hit backspace somewhere in the same paragraph, the anchor-element is deleted.

Tested in tinymce version 4.3.2 in our CMS and in version 4.3.3 in demo on tinymce's homepage

**Comment by dmazilov** [comment] 2016-11-23 09:51
I can confirm this. Anchor-element is deleted also with ctrl+x somewhere in the same paragraph.

**Comment by 5harkY** [comment] 2016-11-23 10:33
Also can reproduce when replace text fragment in the same paragraph by selecting and pasting another text.

**Comment by dmazilov** [comment] 2016-11-23 10:59
Hack solution.
I have custom anchor plugin and I can change anchor content. Now anchor looks like <a class="anchor" ... >&nbsp;</a>. &nbsp; prevents anchor from removing. Option "allow_html_in_named_anchor" have to be enabled.

**Comment by lnewson** [comment] 2020-08-15 08:40
Hi,

I attempted to reproduce this using TinyMCE 4.9.11 and 5.4.1 on Firefox 79.0, however I was unable to reproduce the original issue. It's likely this has been fixed since this issue was originally reported, so I'm going to close this. If you're still able to reproduce the issue using the above versions, let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-08-15 08:40 UTC
Labels: component: keyboard, type: bug
