### ISSUE TITLE
URLs stay as text if bold, italic, underline or strikethrough selected first

### ISSUE THREAD

**Issue by freeads777** [tinymce/tinymce#2952] opened 2016-05-30 02:59 UTC
If you select bold, italic, underline or strikethrough and then type a url (i.e. http://someurl.com) it's not going to turn into a hyperlink.

**Comment by freeads777** [comment] 2016-05-30 11:22
The issue gets resolved if you remove ^ from the pattern:

var f, g = /(https?:\/\/|ssh:\/\/|ftp:\/\/|file:\/|www\.|(?:mailto:)?[A-Z0-9._%+\-]+@)(.+)$/i;

The original one looks like this:

var f, g = /^(https?:\/\/|ssh:\/\/|ftp:\/\/|file:\/|www\.|(?:mailto:)?[A-Z0-9._%+\-]+@)(.+)$/i;

**Comment by lnewson** [comment] 2020-05-09 06:09
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 06:09 UTC
Labels: plugin: autolink
