### ISSUE TITLE
Automatically adding </font> tag where it is not needed

### ISSUE THREAD

**Issue by mansoor93** [tinymce/tinymce#3020] opened 2016-06-22 19:38 UTC
![er1](https://cloud.githubusercontent.com/assets/10684508/16280737/8adc80d6-38da-11e6-8dee-33d7d50e0d8f.png)
![er3](https://cloud.githubusercontent.com/assets/10684508/16280739/8b39ee38-38da-11e6-9eb7-bdf80f6724be.png)
![er2](https://cloud.githubusercontent.com/assets/10684508/16280738/8adcaab6-38da-11e6-9372-90bcae201bd0.png)

The first two images are the HTML provided to TinyMCE, the third is of how it is then changed.

I've tried setting the option convert_fonts_to_spans but it just adds a </span> tag on that position.

**Comment by spocke** [comment] 2016-06-22 19:42
TinyMCE is incapable of producing deprecated HTML unless you configure it to do so. So fonts gets converted to span by default. Please provide a config or a fiddle where this can be reproduced. Thanks.

**Comment by mansoor93** [comment] 2016-06-22 19:52
I've set convert_fonts_to_spans to false just because it was adding a closing span tag, now its adding a closing font tag. We have integrated TinyMCE into Salesforce (Visualforce) so don't really know how to reproduce it in a config or a fiddle. Can i provide you something else? Thanks

**Comment by mansoor93** [comment] 2016-06-22 20:03
Guess i am a fast learner, heres the fiddle to the issue reported. 
http://fiddle.tinymce.com/b1faab
Thank you.

**Comment by spocke** [comment] 2016-06-23 08:29
Not sure I understand the problem here the font element you are referring to gets converted to a span at least in my Chrome browser?

So this:
<font face="arial" color="#cc0000">Signature:</font>
becomes this:
<span style="color: #cc0000; font-family: arial;">Signature:</span>

If you click on the the menu items Tools -> Source

**Comment by mansoor93** [comment] 2016-06-23 18:18
Here is the updated fiddle with comparision to what is the original HTML and what TinyMCE renders:
http://fiddle.tinymce.com/h1faab

Notice How the color is red for the some text in original HTML and its black in TinyMCE.
This is because it adds a </span> tag where it shouldn't

So this 
`<font face="arial" color="#cc0000">Signature:<p>`

becomes this 
`<span face="arial" color="#cc0000" data-mce-style="color: #cc0000; font-family: arial;" style="color: #cc0000; font-family: arial;">Signature:</span>`

**Comment by jayarjo** [comment] 2016-06-26 14:10
It probably happens because `<p>` is not valid child of `<font>` (as well as of `<span>` after conversion). Not sure if we should even fix this, or maybe deal in some other way? Browser seems to be ok with such structure.

WHATWG [states](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2):

> Phrasing content is the text of the document, as well as elements that mark up that text at the intra-paragraph level. Runs of phrasing content form paragraphs.

>Most elements that are categorised as phrasing content can only contain elements that are themselves categorised as phrasing content, not any flow content.

So at least according to specs `<span>` cannot contain `<p>`. `<font>` is not even mentioned there anymore, maybe we should not restrict types of valid children for it anymore, since it's basically a non-existant tag anymore?

**Comment by Afraithe** [comment] 2016-06-26 14:13
Yeah this is asking TinyMCE to create invalid HTML, so really a no-go.

**Comment by jayarjo** [comment] 2016-06-26 15:31
@mansoor93 meanwhile you can "fix" it by supplying the following setting to your configuration:

```javascript
validate: false,
forced_root_block: false,
```

Not sure if there are any implications to this though, @spocke?

**Comment by mansoor93** [comment] 2016-06-27 18:39
@jayarjo Thanks for the explanation and this workaround.

However most of our HTML is generated dynamically so are you sure these settings won't cause any other problems as its implicating that validation is set to off?

**Comment by mansoor93** [comment] 2016-06-27 18:49
@Afraithe It should create valid HTML, but it shouldn't change it by closing the tag upfront, this will make something that is incorrect. shouldn't TinyMCE try to resolve/delete/validate-somehow the invalid tags instead of just putting them out?

**Comment by lnewson** [comment] 2020-05-09 07:18
I'm going to close this because as noted above, the HTML isn't valid as `p` isn't a valid child of `font` or `span` and as such TinyMCE is trying to correct it. If you really need to make this work, then you'll need to tweak the schema via the `valid_children`, `valid_elements` or `extended_valid_elements` options. Here's an example using the fiddle mentioned above: http://fiddle.tinymce.com/h1faab/4

**Closed by lnewson** 2020-05-09 07:18 UTC
Labels: needs: more info, type: bug
