### ISSUE TITLE
Copy/Pasting bullet list don't update (4.7.10 )

### ISSUE THREAD

**Issue by dakicks87** [tinymce/tinymce#4329] opened 2018-04-06 15:20 UTC
Hello,

I am encountering a problem when copy/pasting text containing bullet lists into TINYMCE editor  (4.7.10 ).  Using plugins "paste lists code"
The list appear as they should in the editor. I checked the code the <ul> <li> tags are clean.

The problem is when i submit the changes, the data doesn't update. The text will update when i don't copy / paste. Any ideas why?

**Comment by spocke** [comment] 2018-04-06 16:33
Could you set up a fiddle at fiddle.tinymce.com where we can reproduce this. Also what browser and os is this happening on?

**Comment by spocke** [comment] 2018-04-07 13:53
I couldn't reproduce this one I created a fiddle and copy pasted lists around and it seems to save just fine.
http://fiddle.tinymce.com/spgaab

Hitting the submit button will "save" the data by posting it to a dump html page.

I'm closing this ticket until detailed instructions how to to reproduce this issue is provided. Could be some  server side filtering happening or your end or that I didn't do the exact steps needed to reproduce the issue.

**Closed by spocke** 2018-04-07 13:53 UTC
