### ISSUE TITLE
Window's bottom scrolls to the editor bottom on entering new line.

### ISSUE THREAD

**Issue by simple17** [tinymce/tinymce#8984] opened 2023-08-15 08:07 UTC
When editor's content is more than editor's height, entering a new line scrolls the window.

Steps to reproduce

1. Naviagte to https://www.tiny.cloud/docs/tinymce/6/basic-example/
2. Scroll the page down a little.
3. Scroll to the content bottom.
4. Add a new line to the content.

It affects only v6 not v5 and only the classic mode.

If it's an expected result could somebody highlight the settings to control it? It's really confusing the users.

**Comment by TheSpyder** [comment] 2023-08-20 23:48
Duplicate of #8832

**Closed by TheSpyder** 2023-08-20 23:48 UTC
