### ISSUE TITLE
Bug: Save icon remains disabled when cutting text in a table

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#2878] opened 2016-04-25 07:21 UTC
The save icon (save plugin) remains disabled when you cut a text that it's in a cell. The document changes (because the text was cutted/removed of a cell) but the save icon remains disabled. In any other situations the save plugin works fine.

**Comment by lnewson** [comment] 2020-05-09 05:48
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 05:48 UTC
Labels: plugin: table, type: bug
