### ISSUE TITLE
Floating menu does not follow scroll, when scroll is not body

### ISSUE THREAD

**Issue by SouzaFe** [tinymce/tinymce#8563] opened 2023-03-16 16:15 UTC
**What is the current behavior? Describe the bug**

When the editor is on an element that has scrolling, when opening a floating menu or context menu of the editor, and performing the scrolling on that element, the floating menu does not follow the position of the element to which it should be fixed.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

The issue can be seen at https://fiddle.tiny.cloud/u2iaab

**What is the expected behavior?**

The expected behavior is the same as when scrolling in the body of the document, making the floating menu follow the element that opened it.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tests were performed on Chrome/Windows, with TinyMCE 5 and TinyMCE 6.
The situation was discovered in TinyMCE 5 in React.

**Comment by TheSpyder** [comment] 2023-03-17 03:10
This is a long-standing issue that we tracked in #5097. An option to fix it was just released in TinyMCE 6.4, which was released for open source customers yesterday and should hit cloud stable in a couple of weeks.

If you switch to the cloud "dev" channel and add `ui_mode: 'split'`, the problem is fixed:
https://fiddle.tiny.cloud/u2iaab/3

**Closed by TheSpyder** 2023-03-17 03:10 UTC
