### ISSUE TITLE
Using Mobile theme shows "open book" icon

### ISSUE THREAD

**Issue by mapkyca** [tinymce/tinymce#4040] opened 2017-11-05 21:55 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using tinymce on the iphone you get a grey box with an open book icon in a white circle

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

Visit tinymce with an iphone

**What is the expected behavior?**

Some sort of editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tinymce 4.7.1, browser safari on ios 9.3.5

**Comment by fyrkant** [comment] 2017-11-06 10:44
Hi! 

This is not a bug but the new tinymce mobile skin. Click on the open book icon in the middle to "jump into" the editor, then click the pen icon in the lower right corner to actually start editing.

**Comment by spocke** [comment] 2017-11-06 11:15
Closing this one unless there is an actual bug here. We can re-open this ticket is you provide details on how to reproduce it and if it's an actual bug.

**Closed by spocke** 2017-11-06 11:15 UTC

**Comment by mapkyca** [comment] 2017-11-06 12:26
Thanks for getting back to me!

When I click on the book icon I just get a blank white screen with no pen icon, so I was a little confused! I'll try and find a mac I can plug my phone in to so I can see if there are any errors on the javascript console...

**Comment by RunningLat3** [comment] 2017-12-05 05:29
Hi,

I'm getting this error also can you please check. thank you

**Comment by agupta-elementum** [comment] 2018-02-23 22:10
Hello,

Is there a way to enter the edit mode directly without forcing user to click 2 times (Book icon and edit pen icon)? Similarly, is there a way to attach one of our buttons (outside of tinymce) to the checkmark button in tinymce to exit the edit mode?

**Comment by djmarquette** [comment] 2018-03-01 14:53
I see the same exact behavior reported by mapkyca on November 6, 2017.  

To reproduce: added mobile theme per documentation, open tinyMCE editor and receive the "book icon".  When clicking on the "book icon" there is NO editor available, just an empty white page.  No pen is available, there is NO way to even see let alone edit my content.

Please re-open this bug as it IS a bug.

**Comment by TizFX** [comment] 2018-03-09 10:59
Same error.
The setup code is the following:

```
var tinyplugins = [
	"advlist autolink lists link image charmap print preview anchor",
	"searchreplace visualblocks code fullscreen",
	"insertdatetime media table contextmenu paste code",
	"emoticons",
	"paste",
	"code",
	"image"
];

var tinytoolbar = "insertfile undo redo | copy paste | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | emoticons";
	
var tinyvalidtags = "p,b,strong,i,em,ul,ol,li,th,tr,td,sup,sub,strike,del,s";

tinymce.init({
	selector : "#mytextarea",
	plugins : tinyplugins,
	toolbar : tinytoolbar,     
	menubar : false,
	paste_word_valid_elements: tinyvalidtags,
	paste_data_image: true,
	theme: "modern",
	mobile: {
		theme: "mobile",
		plugins: ["autosave", "lists", "autolink"],
		toolbar: ["undo", "bold", "italic", "styleselect"]
	}
});
```

**Comment by swiffer** [comment] 2018-04-19 04:03
Problem was triggered by a parent element set top overflow: Hidden; in CSS. However switched Back to the old theme as Elements still misaligned and non functional

**Comment by MrMilo** [comment] 2018-04-30 10:00
I'm also interested to know is there anyway I can enter the editor right away without needing to click on book first then click on pencil. Also what's the event of the tick button on the UI, as I'm looking to submit a POST request on that event

**Comment by chadlaughland** [comment] 2018-05-04 13:17
I was getting the blank white screen also on mobile after activating the book icon. A parent element had an "overflow-x: auto" style set on it. After removing this you can now see the toolbar ui and edit as normal.

**Comment by charlesr1971** [comment] 2018-12-31 21:37
Sorry. But I cannot see what the point of the book icon, is? This is just bad UX. When I open TinyMCE, it should just open the mobile editor, straight away! I think the engineers have got a little over excited, and added this, without thinking about it’s implications.

Now, I am also seeing a blank white screen on iOS12. I found out that when I change the TinyMCE toolbar & editor socket to ‘position: fixed’ from ‘position: absolute’, I can now see the toolbar & content.

**Comment by TheSpyder** [comment] 2019-01-02 03:53
The point is to indicate the field should be tapped on to open the editor.

When using a regular form field on mobile the browser zooms in to the element and takes a lot of control over the experience. This is not conducive to using a rich text editor. As such we only support full screen editing on mobile where we can control the experience. The aim is to be as close to native app rich text editing as browsers will allow us to.

**Comment by charlesr1971** [comment] 2019-01-02 07:52
I don’t have a form field? I am opening TinyMCE from a button, that says Open Editor. I don’t know how much more guidance someone needs, other than pressing a button with ‘Open Editor’ on it? The book icon, simply is not required. It just adds an extra step that is not needed. At least, give the developer, a setting, so that we can decide whether to switch this step off or not.

**Comment by charlesr1971** [comment] 2019-01-02 07:56
I found out that the blank white screen is caused if TinyMCE finds a parent element with anything other than ‘overflow:visible’?

**Comment by deep0410** [comment] 2019-04-12 18:18
For anybody still looking for "a" fix..
https://stackoverflow.com/questions/54579110/is-it-possible-to-disable-the-mobile-ui-features-in-tinymce-5#

**Comment by tomvrampio** [comment] 2020-11-11 16:54
> The point is to indicate the field should be tapped on to open the editor.

I understand the desire to make opening the editor a positive action. But it would be great if this was a choice, or at least customisable? I couldn't find any options in the docs. In my opinion the book icon is not obvious as an 'edit' action, and the grey background doesn't fit our theme. For now I will try the [workaround fix above](https://stackoverflow.com/questions/54579110/is-it-possible-to-disable-the-mobile-ui-features-in-tinymce-5#) in order to try and make this experience viable for our users.
