### ISSUE TITLE
Editor retains in the heap after being removed

### ISSUE THREAD

**Issue by riyazahamedr** [tinymce/tinymce#5419] opened 2020-02-21 11:36 UTC
Description of problem:

Steps to reproduce:
1. Open this link https://lastkaj.metagis.se/extjstext/tinymce/index.html
2. Take a heap snapshop using Chrome developer tools profiler (it is showing approximately 9.5 MB)
3. Click window button
4. Again take a heap snapshop using Chrome developer tools profiler (it is showing approximately 16 MB)
5. Close the window (it destroys the window and called tinymce destroy)
6. Again click window button
7. Take a heap snapshop using Chrome developer tools profiler (it is showing approximately 23.5 MB)

Expected result:
The editor should be freed from memory (I tried with tinymce 3.4.4 and 3.5.9)

Actual result:
The editor retains

Once I check the snapshot, the Editor instance is keep on increasing
![editor](https://user-images.githubusercontent.com/5662268/75031497-63a46080-54cc-11ea-90ca-50571d2288d0.png)

**Comment by lnewson** [comment] 2020-02-22 02:39
Thanks for the report, however the page you've linked uses TinyMCE 3 which is no longer supported. I'm going to close this, since it's a version we no longer support, however if you can reproduce the issue with TinyMCE 5 please let us know and we'll reopen this issue.

**Closed by lnewson** 2020-02-22 02:39 UTC

**Comment by MichaelOstling** [comment] 2020-02-23 05:37
Hi,
I have a question related to above issue.
I know TinyMCE 3 is no longer supported. But do you anyhow know developer in your network  that would be interested to solve above issue as a paid task on eg Upwork ?

Kind Regards
Michael
