### ISSUE TITLE
Image plugins in toolbar have not FaildNotice in images_upload_handler method?

### ISSUE THREAD

**Issue by MIKOTO123** [tinymce/tinymce#6599] opened 2021-03-09 01:55 UTC
Is my method of use wrong?

`tinymce.init({
     plugins: [ 'image', 'quickbars'],
   toolbar: ['image'],
  selector: 'textarea#default',
  images_upload_handler:function(blobInfo, succFun, failFun){
   failFun("there is some thing error");
    console.log(123);
    return;
  }
});`

Image plugins in quickbars  have the error notice been given.But the toolbar's image plulgins didn't have any error notice been given.I use the above code to get the following result.

quickbars result:
![image](https://user-images.githubusercontent.com/19549093/110406478-42a1b400-80bd-11eb-9760-318cf5e734bd.png)

toolbar result(didn't have any error notice):
![image](https://user-images.githubusercontent.com/19549093/110406530-5816de00-80bd-11eb-941b-9c645fbe78ae.png)

Hope someone can reply me, thank you.

**Comment by lnewson** [comment] 2021-03-09 01:57
Closing as a duplicate of https://github.com/tinymce/tinymce/issues/6579. This will be fixed in the upcoming TinyMCE 5.7.1 patch release, however the best workaround currently is to downgrade to TinyMCE 5.6.2.

**Closed by lnewson** 2021-03-09 01:57 UTC
