### ISSUE TITLE
Triple-nested <table> in Safari freeze browser

### ISSUE THREAD

**Issue by depanode** [tinymce/tinymce#3995] opened 2017-10-11 15:30 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When paste html-code in source-code editor with triple-nested `<table>`  tag, i.e:
`<table> <tbody> <tr> <td> <table> <tbody> <tr> <td> <table> <tbody> <tr> <td>&nbsp;</td> </tr> </tbody> </table> </td> </tr> </tbody> </table> </td> </tr> </tbody> </table>`
and click OK in Safari - browser freeze and not respond. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

0. Open http://fiddle.tinymce.com/ in Safari
1. Add code plugin in editor-config, plugins field
2. Add code button in editor-config, toolbar field
3. Run fiddle, open source code editor
4. Paste code above
5. Click ok

**What is the expected behavior?**
Not-frozen browser i can work with )

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.7.1
macOS 10.13
Safari 11.0 (13604.1.38.1.6)

**Comment by Georg-Git** [comment] 2017-10-11 16:23
Me too:
Table of death freezes Code Editor.
Safari

http://fiddle.tinymce.com/0agaab/15

**Comment by jayarjo** [comment] 2017-10-15 17:17
Have you tried any other browser? or Windows?

**Comment by Georg-Git** [comment] 2017-10-15 18:00
@jayarjo: Why flagged with plugin: table?

The plugin table is not activated:
http://fiddle.tinymce.com/0agaab/15

I saw a javascript error in plugin: code - and only in Safari.

**Comment by jayarjo** [comment] 2017-10-15 18:40
Oh... sorry... my mistake. Saw it talking about table and acted without paying attention. Don't have Mac myself to check it out. Does it happen on Windows in any browser?

I left it to get verified by others from the team (who got the Mac).

**Comment by jayarjo** [comment] 2017-10-15 18:40
@fyrkant

**Comment by sdkuck** [comment] 2018-03-13 18:01
We are experiencing the same problem.
TinyMCE-react: 2.2.0
TinyMCE: 4.7.9
macOS: 10.13.3
Safari: 11.0.3 (13604.5.6)

**Comment by fyrkant** [comment] 2018-03-27 13:17
Seems like this is an issue with contenteditable and nested tables in safari, and not a problem in TinyMCE, I found this issue on webkit bugzilla: https://bugs.webkit.org/show_bug.cgi?id=183741

So I guess all we can do is wait and see when the safari devs get to fixing it.

**Comment by trevorjay** [comment] 2020-05-25 02:39
I'm closing this issue because I can't reproduce with the current version of Safari (13.1). If there is a regression, please let us know so we can reopen.

**Closed by trevorjay** 2020-05-25 02:39 UTC
Labels: browser: safari, plugin: code, status: escalated, status: verified, type: bug
