### ISSUE TITLE
Tinymce not support properly on edge version 41.16299.248.0

### ISSUE THREAD

**Issue by sandeepChug** [tinymce/tinymce#4373] opened 2018-05-03 11:58 UTC
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** Tinymce not support properly on edge version 41.16299.248.0

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?** Tinymce should be open properly on edge 41.16299.248.0

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?** TinyMCE v4

![edge](https://user-images.githubusercontent.com/10280046/39575133-1523944e-4ef7-11e8-9b57-27ea15a1f36c.JPG)

**Comment by fyrkant** [comment] 2018-05-03 12:09
Does this happen on http://fiddle.tinymce.com/ as well?

**Comment by Daijobou** [comment] 2018-05-07 11:18
Working fine here with Microsoft Edge 41.16299.371.0

**Comment by fyrkant** [comment] 2018-05-08 01:34
Yes this seems to be a problem with the implementation, I'll close this issue. If you can provide a fiddle reproducing the problem I can open it up again.

**Closed by fyrkant** 2018-05-08 01:34 UTC
