### ISSUE TITLE
Calling getContent inside editor.on(change) resets the css for formatting buttons(B/I/U..)

### ISSUE THREAD

**Issue by goyalvarun601** [tinymce/tinymce#2476] opened 2015-11-17 19:21 UTC
editor.on('change', function() {
      var editor = get(_this, 'editor');
      var content =  editor.getContent();
});
The editor.getContent(); call resets the highlighted css of the buttons to default if the user had selected any.

If I call ::
var content = editor.iframeElement.contentDocument.getElementsByTagName('body')[0].innerHTML;

then it is fine but now i get some bogus span tags along with the content.

**Comment by weiluo8791** [comment] 2018-07-25 15:49
Is there any movement for this bug? I am still having this problem on v4.6.3 thanks

**Comment by lnewson** [comment] 2020-08-15 08:27
I attempted to reproduce this using TinyMCE 4.9.11 and TinyMCE 5.4.1, however I was unable to. As such, it's likely this has been fixed since this was originally reported so I'm going to close it. If you're still able to reproduce this issue however, then please let us know and we'll reopen it.

**Closed by lnewson** 2020-08-15 08:27 UTC
Labels: component: input/output, type: bug
