### ISSUE TITLE
Version 4.7.9 - Autosave and Spellchecker - The editor believes that a misspelled word is a change in the document

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4264] opened 2018-03-03 21:09 UTC
Tested in Firefox. Click in the Spellchecker icon and you will see the 'esample' word underlined. Now press F5, and you will see the alert box of leaving the page. An interest thing is that if you activate and then deactivate the spellchecker and you press F5 you won't get any alert message of leaving the page. This last thing didn't happened in the last bug report that I did of this plugin.

Example 1: http://fiddle.tinymce.com/6mgaab
Example 2: http://fiddle.tinymce.com/7mgaab

**Comment by fyrkant** [comment] 2018-04-04 09:32
I'm having problems reproducing this, do you still have this problem with 4.7.10?

**Comment by lrusso** [comment] 2018-04-04 12:49
Yes, tested in Firefox. Just click the Spellchecker Icon and the 'esample' word should be underlined. Now press F5 and you will see the leaving page alert. This doesn't happen if you press the refresh icon, you have to press F5.

http://fiddle.tinymce.com/ipgaab

**Comment by lnewson** [comment] 2020-05-08 08:37
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.11. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 08:37 UTC
Labels: plugin: autosave, plugin: spellchecker, status: escalated, status: verified, type: bug
