### ISSUE TITLE
Edits to pasted text in Source field in insert > media are not retained

### ISSUE THREAD

**Issue by stuartfenn** [tinymce/tinymce#3653] opened 2017-05-16 13:56 UTC
If text is pasted into the source field (in insert > media), and then altered by deleting or adding text manually before hitting OK, then the amendments aren't actually saved, and the originally pasted text can be seen when the source code is viewed.

Steps to Repro
1) Open insert > media, and then paste some text into the source field
2) Without closing the dialog box, delete the pasted text and type something else
3) Press OK
4) View the source, and you'll see that the original pasted text is still present

Reproduced here https://www.tinymce.com/docs/demo/full-featured/

**Comment by lnewson** [comment] 2020-05-02 07:22
Hi,

I'm unable to reproduce this issue using the latest version of TinyMCE, so it's likely we've fixed this since you originally logged this sorry. As such I'm going to go ahead and close this, however if you're still able to reproduce the issue, please let us know and we'll reopen this.

Thanks!

**Closed by lnewson** 2020-05-02 07:22 UTC
Labels: plugin: media
