### ISSUE TITLE
Numbered or Bullet list which contains input texts are not displayed sequentially in iPadOS device.

### ISSUE THREAD

**Issue by shikeiyan** [tinymce/tinymce#6658] opened 2021-03-25 02:41 UTC
**Steps to replicate the issue:**

1. Tap the "Shift" key twice to ensure Caps Lock is turned on.
2. Start typing some text line by line as well as adding some line break in between.
3. Highlight all the text inserted.
4. Format inserted text into numbered/bulleted list by selecting relevant list icon in the toolbar.

**Current Behaviour:**
Missing number or bullet point in some of the input texts.

**Expected Behaviour:**
Numbered or bullet list are displayed sequentially with the input texts.

**You may refer to this video:**
https://user-images.githubusercontent.com/34058332/111276428-4cee2000-8672-11eb-97d9-aa5f32d94767.mov

**Device OS / Browser used:**
Ipad pro IOS 13.6.1 / Safari, Chrome

**Current version used:**

1. @tinymce/tinymce-vue version 3.2.8
2. vue version 2.6.11

Thanks.

**Comment by JamesToohey** [comment] 2021-03-25 05:55
Hi @shikeiyan,

The video you attached appears to contain a mix of <kbd>Shift+Return</kbd> and `CapsLock` + <kbd>Return</kbd> (notice how sometimes there is a blank line between your letters and other times not).

<kbd>Shift+Return</kbd> will insert a new line within the same paragraph, separated by a `<br/>` element, which will result in one list marker per paragraph not per line.

I am not able to reproduce this by hitting <kbd>Shift</kbd> twice to activate Caps Lock and then typing characters separated by hitting <kbd>Return</kbd>.

I'm closing this issue, but if you have additional information or if I've missed something - let me know.

**Closed by JamesToohey** 2021-03-25 05:55 UTC
