### ISSUE TITLE
There is no "Address" in toolbar style whereas the is a shortcut listed in the help

### ISSUE THREAD

**Issue by Naciba** [tinymce/tinymce#9302] opened 2024-01-16 16:50 UTC
## 📝 Provide detailed reproduction steps (if any)
1.Go to help or Press Alt+0 for help (a shortcut to Address  Shift + Alt + 9 is displayed)
2. Go to toolbar > style (headings, inline, blocks, align) (there is no address)

### ✔️ Expected result
shortcut related to "address" shouldn't be displayed in the help because it doesn't exist in toolbar style

### ❌ Actual result
shortcut related to "address" is displayed in the help whereas it doesn't exist in toolbar style

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

## 📃 Other details
- Browser: …
- OS: …
- First affected version: …
- Worked in version: …

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment] 2024-01-16 21:03
Duplicate of https://github.com/tinymce/tinymce/issues/9300

**Closed by TheSpyder** 2024-01-16 21:03 UTC
