### ISSUE TITLE
I can't find what I'm looking for: ui-components/autocompleter.md

### ISSUE THREAD

**Issue by smyxhlyx** [tinymce/tinymce#5575] opened 2020-04-15 18:50 UTC
Is there a way to support two characters for autocomplete trigger? Such as "<<" or "[["

**Comment by lnewson** [comment] 2020-04-16 07:07
This currently isn't possible sorry, without a lot of hacky workarounds, so I'm going to mark this as a feature request.

**Comment by lnewson** [comment] 2020-05-07 11:43
I just realised we actually already have a feature request open for this sorry, so I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5220

**Closed by lnewson** 2020-05-07 11:43 UTC
Labels: 5.x, type: feature
