### ISSUE TITLE
autosave not work after re-position the editor

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3426] opened 2017-01-03 15:15 UTC
I have included plugin "autosave" with toolbar icon "restoredraft".
https://www.tinymce.com/docs/plugins/autosave/

Problem is maybe that I must remove and add the editor, because tinymce not support live re-position of the editor in DOM. I need the editor for many different places, so I move the editor after element X or element Y.

Here a Example: http://fiddle.tinymce.com/hEfaab

Exists here a solution for autosave with remove/add the editor for re-position?

**Comment by Daijobou** [comment] 2017-01-22 11:20
I am still interest in a solution :)

**Comment by Daijobou** [comment] 2017-02-03 11:17
Its possible to save autosave data and insert back after re-position? Exists here a small example? :)

**Comment by Daijobou** [comment] 2017-09-06 09:07
I push this topic, maybe anybody have a solution for me?

**Comment by n0nag0n** [comment] 2017-11-17 00:28
Yeah I'm running into this problem as well... looks like I'll have to do a manual solution.

**Comment by donShakespeare** [comment] 2017-11-17 16:05
You want the last stored content to show when you hit the draft button?
How about, before moving the editor you save the content to a global variable ...?

**Comment by n0nag0n** [comment] 2017-11-17 16:38
That's what I'm doing, building a custom autosave feature because the
plugin won't persist the draft (which blows my mind).

**Comment by donShakespeare** [comment] 2017-11-17 16:50
It may not be a TinyMCE fault at all, but a larger "problem" or behaviour. Think IFRAME!
https://stackoverflow.com/questions/8318264/how-to-move-an-iframe-in-the-dom-without-losing-its-state

You will also notice that if in inline mode (non-iframe), TinyMCE can be moved around with no issue of content state and status.

**Comment by n0nag0n** [comment] 2017-11-17 16:54
And that's a good potential solution I could look into. It just didn't
make sense why localStorage assigned to my domain would disappear when
the mceRemoveEditor command was executed.

**Comment by donShakespeare** [comment] 2017-11-17 17:31
Look in here https://www.tinymce.com/docs/plugins/autosave/
Note:
`autosave_retention`
`autosave_prefix`

You can run a test to see if the key/prefix in localStorage actually gets lost when you destroy the initiating editor.
I use HTML5 Storage Manager All in One to inspect this kind of stuff.

On a same note, I think it might be an expected behaviour (if not a bug) for the editor to do its own cleanup.

I can see the use of preserving localStorage content upon sudden quitting of the browser ...
but what would be the point of leaving content if the editor was intentionally destroyed?
Just a postulation!

**Comment by donShakespeare** [comment] 2017-11-17 17:34
If expected, then it would affect inline mode as well.
Then best bet would be to toggle (hide/show) / empty the editor and then move it around the DOM.
Instead of `destroying` it.

**Comment by n0nag0n** [comment] 2017-11-17 17:39
The point is to prevent an accidental leave of the page where tinymce
is, or to prevent if they were typing something, left their computer,
then was logged out to a different page. When they go back, because
they editor was destroyed, there is no content saved because the
localStorage keys were completely removed :-/ It's ok. I've already
built a workaround with localStorage that's working the way I need it
to.

**Comment by donShakespeare** [comment] 2017-11-17 17:43
Please share

**Closed** 2019-11-14 18:10 UTC
