### ISSUE TITLE
TinyMCE cannot handle "<3" (heart) 

### ISSUE THREAD

**Issue by Hackswell** [tinymce/tinymce#2567] opened 2015-12-17 20:18 UTC
When saving data, we have some customers that like to put a heart <3 into their text fields.  TinyMCE has problems saving and reloading these characters.  It appears to truncate all text after the <3 until the next block, as if it's interpreting this as an opening tag (albiet malformed).

**Comment by spocke** [comment] 2015-12-18 08:54
Properly encode your content. `&amp;lt;` not `&lt;` I guess we need to add some docs somewhere about how to entity encode HTML this issue seems to be reported from time to time.

**Comment by spocke** [comment] 2015-12-18 08:55
So closing since it's not a bug.

**Closed by spocke** 2015-12-18 08:55 UTC

**Comment by toddmay1** [comment] 2015-12-18 18:43
spocke - 
Content is entered into TinyMCE GUI as <3.  
It is displayed as tinymce view source as &lt:3.  
It is sent to CGI and saved as &lt;.  (encoded)

When data is sent back to browser (editing item) it is still encoded as &lt;.
When TinyMCE loads it everything after &lt; is truncated.   

This is evident in the TinyMCE GUI as well as the raw value of e.content.

There is no other entity encoding this data except TinyMCE.   It is encoding it as &lt;.

To duplicate go to example at: https://www.tinymce.com/docs/demo/basic-example/
Enter "Mary had a little < lamb."
Click Tools view source.   
One can see it encoded as &lt and not &amp;&lt; as you indicate.
Text displays fine in TinyMCE.
If one saves what TinyMCE encoded and reloads it, tinyMCE will truncate it when it encounters &lt;

Summary:
&lt;  and &gt;   should be valid encoded statements.   
Attempts to rectify this in a plugin fail because event e.content (before GUI rendering) also truncates.  So it's difficult to create a work around.

Please advise as I lack understanding of how it can not be properly encoded when TinyMCE is doing the encoding.

**Comment by spocke** [comment] 2015-12-21 10:27
This is correct: `<textarea>a &lt;amp; b</textarea>` this is not: `<textarea>a &lt; b</textarea>`

**Comment by toddmay1** [comment] 2016-05-12 18:03
I wanted to update this item with a regex that others can use if you encounter a similar issue.  This fix is in perl, but should work in other languages.

Issue we encountered:
Adding <3 into TinyMCE results in public web display working good.
Attempting to edit item from database results in javascript error.   Even if standard HTML encoding is used to encode <3 into &lt;3 when returned data inside textarea for tinyMCE.

Fix:
You must encode your return results to TinyMCE in javascript friendly encoding (not just HTML encoding).   So if you try and send HTML encoding like &lt;3 to tinyMCE, it will fail.

The fix I used was to simply perform a regex replacement on our database value we are sending back to TinyMCE editing.
$yourTinyMCETextAreaData =~ s/\&(\w+)\;/\&amp;$1\;/ig;

The above regex is simply saying (take standard HTML escaped stuff and make it javascript friendly encoding).   So &lt;3  turns into &amp;lt;3.

The () you see in the regex is telling the regex to remember letters between & and ; like lt, gt, amp, etc.   It then stuffs that into $1.   We then transpose what we used to send &lt3; into &amplt;3

Hope that helps some folks.



There may be a prettier way to do this... But this worked for us.
