### ISSUE TITLE
The emoji is colorless in IE 11 after upgrade from V4.4.3 to V5.0.15

### ISSUE THREAD

**Issue by trudeshm** [tinymce/tinymce#5202] opened 2019-10-11 09:55 UTC
**This is the issue with TinyMCE after upgrade .**

TinyMCE version 5.0.15 :

IE11:

![image](https://user-images.githubusercontent.com/56434696/66642746-e9c3b700-ec4f-11e9-9c35-6a3c0a930831.png)

Chrome:

![image](https://user-images.githubusercontent.com/56434696/66642761-edefd480-ec4f-11e9-945c-b8d10ea6e5e8.png)

**Emoticons should be colorful in IE11 as in chrome**

**The issue has been occurring in TinyMCE v5.0.15 and it works fine for v4.3.3 **

**Comment by ltrouton** [comment] 2019-10-15 03:30
The emoticons plugin in v5 uses native character codes for emojis. As a result, it relies on the browser to render them. Unfortunately, IE11 does not provide coloured emojis. The reason why v4 had emoticons with colour was because they were actually images. Closing this ticket as the expected behaviour occurs. Let us know if you have any other issues.

**Closed by ltrouton** 2019-10-15 03:30 UTC
