### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by spanickar7** [tinymce/tinymce#4419] opened 2018-05-30 05:31 UTC
Enter some characters 
Choose any format like bold, italic,strikethrough, etc
Enter some more characters 
Single click on clear format
  Format not cleared
Double click on clear format
  Format will get cleared

tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8 Uncaught TypeError: Cannot read property 'parentNode' of null
    at g (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at remove (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at Object.remove (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at RemoveFormat (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at zm.execCommand (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at bx.execCommand (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at i.t.cmd.t.onclick (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at qm.c.fire (tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc:8)
    at i.fire (theme.min.js:1)
    at HTMLDivElement.o (theme.min.js:1)

**Comment by Afraithe** [comment] 2018-06-19 14:34
Duplicate of #4414

**Closed by Afraithe** 2018-06-19 14:34 UTC
Labels: status: verified, type: bug
