### ISSUE TITLE
Unable to revert to "System Font" once font of text is changed

### ISSUE THREAD

**Issue by sha2nktiwade** [tinymce/tinymce#8739] opened 2023-05-18 09:47 UTC
**What is the current behavior? Describe the bug**
Once we have changed the Font Style of any selected text, we are unable to revert it back to the "System Font". This option is unavailable in Font Family dropdown menu.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
- Write some text oin TinyMCE editor.
- Change its font to any of the Font family from the dropdown menu option available. For example: "Times New Roman".
- Now, suppose we have to change it back to default, then there is no option available in the dropdown option of "System Font". 

**What is the expected behavior?**
User should have the option in the "Font Family" dropdown menu to undo/revert back to "System Font" once the font of text is changed to any other.

Expected: If we want some text in for example: "Times new Roman" and other text in System Default font, then there is no option to revert back to "System Default" font, once any other option from the dropdown menu is selected. 
"System Font" should also be part of the Font Family dropdown menu.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Using TinyMCE 6.2 version. All the browsers.

**Comment by spocke** [comment] 2023-05-22 12:32
You could just define a new font format name that matches what ever the system font is in this case. Or use `style_formats` instead since those can be toggled on and off. Or use `Remove formats` that should remove all formatting from the current selection.

Made a fiddle where the `System Font` is set to the default content.css font value: https://fiddle.tiny.cloud/s8iaab

I'm closing this since this is by design the font feature will just apply fonts not remove fonts.

**Closed by spocke** 2023-05-22 12:32 UTC
