### ISSUE TITLE
2 text editors different settings api key ?

### ISSUE THREAD

**Issue by MiBuena** [tinymce/tinymce#4052] opened 2017-11-09 09:03 UTC
Hello,

I have 2 Tiny MCE text editors in the same application.

They are not on the same page - on different pages, but with different settings - one of them allows images, the other doesn't.

I made 2 JavaScript files with 2 different tinymce.init configurations and am loading them on different pages. I also registered 1 api key. For the first version - it works and doesn't show the yellow warning message. For the second version, however, it shows the yellow messages which demands me to register a key.

How can I solve the situation? Do I need 2 primary keys or?

**Comment by fyrkant** [comment] 2017-11-09 09:10
What exactly do you mean with different pages? Is it on the same domain but on different routes, like `www.mypage.com/blog/` and `www.mypage.com/twitterclone/` or two totally different domains?

**Comment by MiBuena** [comment] 2017-11-09 10:29
They are on the same domain on different routes:

> www.mypage/messages/create

> www.mypage/letters/create

**Comment by Afraithe** [comment] 2017-11-10 14:15
This might be a caching issue, can you try again and see if this work for you, if it's on the same domain this shouldn't happen. But if you tried it first without the key, and got the message, then added the key, there might be a caching issue there for a little while.

**Comment by MiBuena** [comment] 2017-11-10 17:35
I tried it now again.

I tried deleting row by row to see how it reacts. 

 I started deleting row by row and the message didn't appear initially. The moment I removed part of the toolbar - then the message appeared.

This is the toolbar of the full version:
        "toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',"

I removed " link image" and the message started appearing.

**Comment by MiBuena** [comment] 2018-02-22 10:23
Dears,

does anyone have a solution here?

The message appears also when I remove the second instance and make even the slightest change to the first instance toolbar. 

For example - I remove 1 icon - the message appears. I add the icon back - the message doesn't appear anymore.

What is even more strange is that we are still on localhost and localhost should be referenced by default.
I am using the community version and I have downloaded the tinymce.min.js locally.

Suggestions here?

**Comment by lnewson** [comment] 2020-05-03 23:33
Hi,

I'm unable to reproduce this using a [fiddle](http://fiddle.tinymce.com/) or locally, so it's probable the issue has been fixed. So given we're unable to reproduce the issue and the old age of this ticket, I'm going to close it. If you're still having issues though, then please feel free to log a new issue and we'll try and help figure out what's going wrong.

Thanks!

**Closed by lnewson** 2020-05-03 23:33 UTC
