### ISSUE TITLE
Cursor position in chrome

### ISSUE THREAD

**Issue by Bengt7jqb** [tinymce/tinymce#2891] opened 2016-05-01 23:09 UTC
I have noticed visible cursor is one step ahead from 'real' cirsor position in chrome browser
In firefox its works ok, both visible and real are at same pos
Strange :(

Just updated to 4.3.11 still same problem

**Comment by spocke** [comment] 2016-05-04 11:09
What version of Chrome and on what OS? Need some more details since I wasn't able to reproduce the bug.

**Comment by Bengt7jqb** [comment] 2016-05-05 00:01
Windows 7 pro and Cheome Version 50.0.2661.94 m

Working cursor is 1 or 2 steps after visible cursor  Realy strange
The hpage im using it on is only for administrators for
https://div.radiomuseum-se.data-doc.se/?mode=welcome
so you kant try it where I got the bug  Sorry

https://admin.div.radiomuseum-se.data-doc.se/?admin=collection&action=artiklar 
This URL skuld not work for you :(

But how it locks for me.



Happy to ansver more questions if you have any

Den 2016-05-04 kl. 13:09, skrev Johan Sörlin:
>
> What version of Chrome and on what OS? Need some more details since I 
> wasn't able to reproduce the bug.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/tinymce/tinymce/issues/2891#issuecomment-216830283>
>

-- 
Bengt Samuelsson
Nydalavägen 30 A
SE-35248 Växjö
Sweden

+46(0)707338401

**Comment by Bengt7jqb** [comment] 2016-05-06 03:22
Are you helpt if you can se the file? 
personedit.php

**Comment by Bengt7jqb** [comment] 2016-05-06 03:27
[personedit.php.txt](https://github.com/tinymce/tinymce/files/251502/personedit.php.txt)

**Comment by Bengt7jqb** [comment] 2016-05-08 10:15
Any progress ?

**Comment by spocke** [comment] 2016-05-09 13:30
Tested it on Windows 7 with Chrome: 50.0.2661.94 m and couldn't reproduce it on: https://www.tinymce.com/

**Comment by Bengt7jqb** [comment] 2016-05-09 18:51
> Tested it on Windows 7 with Chrome: 50.0.2661.94 m and couldn't reproduce it on: https://www.tinymce.com/

Did my file helped you?
Or you can make an scount on https://div.radiomuseum-se.data-doc.se/?mode=welcome and I make you ROOT and you can try it on site
After I make you an normal visitor

**Comment by Bengt7jqb** [comment] 2016-05-16 01:03
Mybe this can be the reason ?
**<p class="text">Jobbar nu med att snygga till inloggning.</p>**
And 
<style>
.text {
	color: black;
	font: normal normal 15px Times,arial,sans-serif;
	text-align: justify;
	}
.text:first-letter  {
	color: #000;
	font-size:large;
	font-weight:600;
	text-indent:20px;
	}
</style>

**Comment by Bengt7jqb** [comment] 2016-05-20 03:20
I have played a bit and it is 
"text-indent:20px; " 
this part is the gilty one ;)
Mybe some 'override' to it will help ?

**Comment by barredespace** [comment] 2017-01-05 12:44
Confirmed on Mac OS 10.11.6, TinyMCE 4.4.3 for Chrome 55.0.2883.95, Safari 10.0.2 (11602.3.12.0.1), not FF.
Same symptoms and the culprit definitely is styling of :first-letter pseudo-elements.
The bug vanishes when CSS :first-letter code gets commented out.

**Comment by fyrkant** [comment] 2018-03-22 14:12
Closing this as it seems to be a problem with css and not Tinymce itself.

**Closed by fyrkant** 2018-03-22 14:12 UTC
Labels: needs: more info, type: bug
