### ISSUE TITLE
TypeError: containerElm is undefined

### ISSUE THREAD

**Issue by Andy-QT** [tinymce/tinymce#4888] opened 2019-03-09 16:29 UTC
Hi,

**Do you want to request a *feature* or report a *bug*?**

Javascript error on tinymce.init()

**What is the current behavior?**

![error](https://user-images.githubusercontent.com/2870154/54074046-3ac09680-428e-11e9-9bb5-e45ea721f2af.jpg)

**Current configuration:**

const id = 'editor';

if (tinymce.get(id)) {
	 tinymce.execCommand('mceRemoveEditor', true, id);
}
		
tinymce.init( {
	selector: '#' + id,
	container: '',
	language: '',
	content_css: [
		 '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i'
	],
	min_height: 150,
	height: 'auto',
	width: 'auto',
	menubar: false,
	plugins: [
		'advlist autolink lists link charmap print preview anchor',
		'searchreplace visualblocks code fullscreen pagebreak wordcount',
		'insertdatetime media table contextmenu paste code'
	],
	default_link_target: '_blank',
	toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | fullscreen',
	statusbar: true
			} ).then(() => resolve(tinymce.get(id)), e => reject(e));

### **I found a workaround with changes in configuration:**
Disable one of this configuration parameter:
- statusbar: false
- plugins: (without wordcount)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 4.9.3
Firefox 65.0.2

**Comment by lnewson** [comment] 2019-03-09 23:26
@Andy-QT could you please include a fiddle, or something similar to show how to reproduce the issue? As I've used what you mentioned above (or as close as I can), but I'm unable to reproduce the issue mentioned. Here's the fiddle I used for testing: http://fiddle.tinymce.com/ADgaab

**Comment by Andy-QT** [comment] 2019-03-10 10:02
@lnewson the editor is used in a form which is generated after a user clicks o a table row.
Order of events:
- table row click ( with _.debounce (click, 250) )
- remove form if exists
- append new form in DOM
- apply editor to form element textarea#editor 

The error appears if the event chain is called multiple times.
eg: on refresh table row.

I am trying to write a fiddle in the meanwhile

**Comment by Andy-QT** [comment] 2019-03-10 10:48
@lnewson 
With TinyMCE version 5,0,2 the workaround (configuration changes) does not work anymore. 

**But i guess a have found a hint.**

I also use a Plugin: select2 to enhance input elements. 

And Google Chrome shows this warning: 
https://www.chromestatus.com/feature/5745543795965952
![2019-03-10 11_33_56-Client invoice - Vivaldi](https://user-images.githubusercontent.com/2870154/54083759-8889dd00-4328-11e9-8d81-bfe55ea2093e.jpg)


Firefox browser has errors: 
![2019-03-10 11_37_13-Client invoice](https://user-images.githubusercontent.com/2870154/54083822-1fef3000-4329-11e9-8029-cfcc379836d6.jpg)

**If i remove the select2 plugin from the form, everything works like expected in Firefox browser.**
But i want to use both plugins.

**Comment by lnewson** [comment] 2019-03-13 06:57
@Andy-QT sorry for the delayed response, but looking at the errors it seems as though the editor dom elements might be getting deleted, before the editor has been removed/cleaned up? I'm really not sure though without a reproducer, but the errors are pointing at the fact that it can't find various DOM elements.

**Comment by lnewson** [comment] 2019-03-13 07:08
I found another possible way that this could be happening. Looking at the wordcount plugin, I see that it isn't cancelling async actions when the editor is removed. That'd cause it to potentially attempt to access elements that no longer exist and could potentially produce the errors you're seeing.

However that doesn't really match up with original error and if that was the case, it'd be pretty had to reproduce as you'd have to be editing content and then remove the editor in less than ~300ms. As such that seems as though it's unlikely to be the issue you're running into here.

**Comment by lnewson** [comment] 2019-03-13 07:19
Actually looking into more, that wouldn't be an issue in v5 at least, as the debounced callback fires an event via `editor.fire` and once the editor state is marked as removed, then all fired events do a noop and don't call the relevant handlers. That means that the wordcount plugin wouldn't be trying to update the dom and wouldn't throw such an error.

So I'm afraid I still don't know what would cause this and without a reproducer we're just going to be guessing.

**Comment by Andy-QT** [comment] 2019-03-13 12:33
@lnewson thank you for your response
Because i have a workaround for v4 (disable the wordcount plugin) we can take a look at the v5 error.

The problem is that it is not enough to check if the DOM element exists before the editor gets initalized. 
Therefore i can only do something like this: 
- stop all until the editor is loaded
- or initialize the editor after a timeout ~500ms to be sure the DOM element exists
- or increase the debounce time of my 'append new form in DOM and init editor' function

Here is the fiddle to reproduce the error: 
Test with **Firefox**, because Google Chrome outputs null without an error
 
http://fiddle.tinymce.com/QDgaab/1

**Comment by lnewson** [comment] 2019-03-13 14:08
@Andy-QT that still doesn't appear to be producing any error on Chrome 72, nor Firefox 65. Do I need to do something specific, or use a specific browser/OS combination? If you could provide some steps on how to use the fiddle mentioned that'd be appreciated.

I had tried clicking the create button a few times, but all it does is create the editor and then delete the editor dom elements, which I wouldn't recommend as that won't clean up the editor and that could be why you're seeing these errors. If you want the editor removed, then you should call either `editor.remove()`, `tinymce.remove('#' + id)` or the execCommand approach you already used in `initRTE` which will safely clean up the editor.

I'm also not sure if it was just for the demo, but you seem to be trying to do things in a synchronous manner, when you really should be doing it asynchronously. As an example, you have the promise/callback to know when the editor has initialized via `tinymce.init(settings).then(callback)` but you're not using the callback and instead are relying on timeouts at specific intervals, which may or may not work depending on how fast things happen (that might be why I'm not seeing any errors). Though in your original screenshot you did have a resolve function, which makes me think it might have just been for the demo but I did want to make sure of that?

Anyways, I've updated your fiddle a bit to remove the timeouts and to safely remove the editor, so see if you are still able to reproduce the issue with: http://fiddle.tinymce.com/QDgaab/2 To be honest I'm not quite clear why you have the removeChild, etc... calls but I left them there in case they do serve a purpose.

**Comment by Andy-QT** [comment] 2019-03-13 15:25
@lnewson open the fiddle (http://fiddle.tinymce.com/QDgaab/1) with Firefox 65 (Windows 10) and click the 'create' - button fast multiple times. This should bring up the error in the console.

The setTimeout should simulate the re-init sequence if a user is clicking on a table row (which removes the form and append it again). Therefore it is not possible to prevent a user click before the editor has initialized successfully.

I am using the .then(callback) to set a counter after the editor has initialized but not to prevent other actions.

Maybe it is possible to observe the DOM element and safely remove the editor when it disappears.

The question is know who is doing it wrong, me or tinyMCE :)

**Comment by lnewson** [comment] 2019-03-14 02:18
@Andy-QT if you're manually wiping out the dom elements the editor creates/controls without using the supported remove API then there's really not much we can do about that I'm afraid.

So what I'd suggest is if you want to continue using the single element for the editor and share it across multiple table row clicks, then either make sure the editor is cleaned up via the remove API functions before detaching/removing the dom elements, block user interaction until the editor has initialized or instead of destroying and recreating the editor each time, reuse a single editor instance and just update/reset the content.

In case you do decide to go down the single editor path, resetting the editor content can be bit trickier than it may sound, since you'd need to reset the undo history and dirty state (we want to try and improve that at some stage). Here's an example of what you'd currently need to do to reset the content/state:
```
editor.setContent('my new content');
editor.undoManager.clear();
editor.undoManager.add();
editor.setDirty(false);
```

**Comment by TheSpyder** [comment] 2019-03-14 04:50
Editors are complex beasts, we already provide a safe way to remove the editor element. Removing elements yourself will lead to undefined behaviour. We guarantee all editor elements will be removed when `.remove()` is called.

To expand on the solution @lnewson suggested - just straight up call `remove()` in the setTimeout of your fiddle. The editor API should be accessible from the moment `init` returns, you don't need to wait, although methods that interact with the iframe content won't work straight away.

http://fiddle.tinymce.com/bEgaab/1

Using this it seems to achieve the same effect without any of the promise waits. The only edge case is if someone clicks twice within 150ms, but I made the code check for null before calling `.remove()` at which point I can't make it throw an error and it always ends with no editor on the page.

**Comment by lnewson** [comment] 2019-03-15 00:49
Since the issue appears to be that the editor is not being removed via the supported APIs, I'm going to close this since there's really not much we can do about that. If you are still having an issue after trying the points listed above, let us know and we'll reopen this and investigate further.

**Closed by lnewson** 2019-03-15 00:49 UTC
Labels: needs: more info
