### ISSUE TITLE
Chrome on mobile: disappearing keyboard

### ISSUE THREAD

**Issue by Marliinda** [tinymce/tinymce#5996] opened 2020-09-01 09:45 UTC
**What is the current behavior? Describe the bug**
When using chrome 85.0.4183.81 on mobile, the keyboard disappears when pressing the enter key while typing. You have to tap on the editor again to let the keyboard re-appear.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
You can for example try it in on one of the standard demo's on the tinymce website (such as https://www.tiny.cloud/docs/demo/basic-example/) with the chrome 85.0.4183.81 browser on mobile.

**What is the expected behavior?**
For the keyboard to remain visible whilst typing in the editor.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome 85.0.4183.81

**Comment by lostkeys** [comment] 2020-09-01 09:51
Yeah, I can replicate that too. Thx for the report.

**Comment by Spinball** [comment] 2020-09-01 14:22
I can replicate it.  Using [Xenforo](https://xenforo.com/) (market leading forum software) 2.1 (which uses [Froala](https://froala.com/wysiwyg-editor/)), with Chrome on Andoid, back spacing to delete a space character hides the keyboard.  
Also hitting the Return key hides the keyboard.

Tap in the text box to show the keyboard and then back space and the keyboard hides again.  Tap to bring the keyboard back, type more characters and back space, and when you delete a space character, the keyboard hides again.
Firefox on Android is fine.
Chrome on iOS is fine.
It's a Chrome on Android bug, I think.

**Comment by mckenzielong** [comment] 2020-09-01 16:40
Not sure if this is too valuable to anyone, but the issue is present in Chrome Dev (86.0.4240.7) but not Canary (87.0.4251.0).

**Comment by kaisnb** [comment] 2020-09-04 12:32
For all developers of hybrid apps which uses the Android System WebView, its enough to upgrade to version 86 "Android System WebView Beta" to fix the problem. https://play.google.com/store/apps/details?id=com.google.android.webview.beta&hl=en

**Comment by shu801115** [comment] 2020-09-05 22:53
It seems that your recommendation cannot be installed on some older devices.
Do you have additional ideas for them?

**Comment by shu801115** [comment] 2020-09-05 22:56
Thanks for your proposal, kaisnb.
It seems that your recommendation cannot be installed on some older devices.
Do you have any other ideas?

**Comment by archon810** [comment] 2020-09-09 00:23
Just ran into this and was going to file a bug, but found this report. So it's a bug in Chrome/WebView, basically?

**Comment by jdussouillez** [comment] 2020-09-29 06:12
It seems to be the same bug I had in another text editor (https://github.com/Alex-D/Trumbowyg/issues/1161#issuecomment-700129918).

It's a Chrome bug, fixed in v85.0.4183.127.

See https://bugs.chromium.org/p/chromium/issues/detail?id=1121179

**Closed** 2024-06-14 00:53 UTC
Labels: type: bug, status: verified, component: keyboard, browser: chrome (android), component: mobile
