### ISSUE TITLE
Style tags removed when in inline mode

### ISSUE THREAD

**Issue by glapointe** [tinymce/tinymce#6371] opened 2020-12-28 21:10 UTC
**What is the current behavior? Describe the bug**
When in inline mode if you edit the source and attempt to add a style tag (<style>p{color:red}</style>) it will be immediately removed once saved. If you change it so that it's not in inline mode then it works as expected.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
I've created a fiddle here so you can reproduce it: http://fiddle.tiny.cloud/H1haab - just edit the source and add the style tag and you'll see it's removed; change inline to false and repeat and you'll see it's not removed. Here's the code for reference:
```
<script type="text/javascript">
tinymce.init({
  selector: 'div#default',
  inline: true,
  schema: 'html5',
  valid_children: '+body[style]',
  fixed_toolbar_container: '#container',
  plugins: 'code',
  toolbar: 'code'
});
</script>

<div id="container"></div>
<div id="default">test</div>
```

**What is the expected behavior?**
The style tag should not be removed when in inline mode.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I've tried with the latest version 4 and 5 and both fail. I'm using the latest version of Chrome on Windows 10 to test.

**Comment by lostkeys** [comment] 2020-12-29 07:45
I can confirm this on my end and I have logged an internal bug report and we'll update here when there is a fix for this issue.

**Comment by lostkeys** [comment] 2020-12-29 08:26
Sorry, an update. This is not a bug. The valid children option declares direct child-parent relation, and in this case, the `<style>` tag is not a direct child of `<body>`. If your inline container is a `<div>`, update your config accordinly: `valid_children: '+div[style]',`.

**Closed by lostkeys** 2020-12-29 08:26 UTC
Labels: component: input/output, status: escalated, type: bug

**Comment by glapointe** [comment] 2020-12-29 16:37
@lostkeys Thanks for that clarification and quick response! That solved it - it definitely wasn't clear from the docs that it must be a direct child when defined like that but simple enough change so all good. Thanks again!
