### ISSUE TITLE
Bug - tinymce Preview shows up blank on Safari 

### ISSUE THREAD

**Issue by rohan210** [tinymce/tinymce#4109] opened 2017-12-07 11:59 UTC
I'm using macOS Sierra v10.12.6 with Safari Version 11.0.1 

Steps:
1. Open https://www.tinymce.com 
2. Goto View> Preview on tinymce menu
3. Observe that Preview window is empty
4. Remove the image in tinymce
5. Check preview, observe that preview window is populated with tinymce content.

Error from console everytime preview comes blank:
Sandbox access violation: Blocked a frame at "xxx" from accessing a frame at "null".  The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.

**Comment by lnewson** [comment] 2020-05-08 09:31
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.8. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:31 UTC
Labels: browser: safari, plugin: preview, status: escalated, status: verified, type: bug
