### ISSUE TITLE
Bugs with caret place for noneditable blocks

### ISSUE THREAD

**Issue by Iuriy-Budnikov** [tinymce/tinymce#3026] opened 2016-06-24 14:20 UTC
1. incorrect caret place if remove space before noneditable block
2. impossible to set caret place after noneditable block

You can reproduce it any example with

```
<p>noneditableblock</p>
<p>noneditableblock</p>
<p>noneditableblock</p>
```

**Comment by blackcathikari** [comment] 2016-07-25 03:34
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by Iuriy-Budnikov** [comment] 2016-07-25 09:33
@blackcathikari 
I tested with 4.4.0
It works more better.
But one bug is still here.

![Uploading 94d41468b0214d4c887c6300c7c293d7.png…]()

**Comment by Iuriy-Budnikov** [comment] 2016-07-25 09:37
I can't delete tag p by hit on backspace

**Comment by blackcathikari** [comment] 2016-08-01 03:14
Thank you for the screenshot. I may have reproduced the bug, but I'm not sure. Could you please look at http://fiddle.tinymce.com/x4faab/3 and tell me if you can reproduce the bug there? Also, if you could make your own fiddle that would be very helpful.

To reproduce the bugs I found go to the fiddle I linked and try:

- To test deleting line 1: place caret at the end of line 1 and press backspace twice. In Firefox line 1 is deleted and the caret moves to the last line (bug). In Chrome and IE line 1 isn't deleted, and pressing enter deletes line 1 and the noneditable (may be a bug).
- To test placing caret after the noneditable without focus: reload the fiddle page, click outside the editor, then click on the noneditable. The noneditable should highlight and in IE the editor content jumps so the noneditable is at the top of the editor (may be a bug). Press the right arrow key. In IE the caret moves after the noneditable. In Chrome and Firefox it doesn't (may be a bug). 
- To test placing caret after the noneditable with focus: reload the fiddle page, click on an editable line of text, then click on the noneditable. The noneditable should highlight, and in IE the editor jumps. Press the right arrow key. In IE, Chrome and Firefox the caret moves to the end of the noneditable and the highlighting is removed. 

Are any of those the bug you reported above? I tested this in IE 11, Firefox 47 and Chrome 51 on Windows 7. What environment(s) are you using?

Thanks,
Millie @ TinyMCE

**Comment by Iuriy-Budnikov** [comment] 2016-08-01 07:24
@blackcathikari 
hello. Yes, I able to reproduce it

**Comment by Iuriy-Budnikov** [comment] 2016-08-01 07:28
@blackcathikari 
hello

> Could you please look at http://fiddle.tinymce.com/x4faab/3 and tell me if you can reproduce the bug there? Also, if you could make your own fiddle that would be very helpful.
Yes. I able to reproduce a bug in this example.

>What environment(s) are you using?
I am using latest Mac OS & latest Chrome. The same issue in Safari.

Here the link to video
```
https://drive.google.com/file/d/0B7WiLYDc7RuQYXg2SldRNGhlSkU/view?usp=sharing```

**Comment by Iuriy-Budnikov** [comment] 2016-08-09 13:32
@blackcathikari can you reopen ticket please?

**Comment by blackcathikari** [comment] 2016-08-11 23:29
Sorry @Iuriy-Budnikov, reopening now.

**Comment by lnewson** [comment] 2020-08-15 09:16
Hi,

I attempted to reproduce this using TinyMCE 4.9.11 and 5.4.1, however I'm not able to reproduce the original issue. I could reproduce it in versions mentioned though, so it's likely this has been fixed since this issue was originally reported, so I'm going to close this. If you're still able to reproduce the issue using the above versions, let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-08-15 09:16 UTC
Labels: plugin: noneditable, type: bug
