### ISSUE TITLE
When i use language :  'zh_CN',some not translated

### ISSUE THREAD

**Issue by zotopteam** [tinymce/tinymce#2564] opened 2015-12-17 10:22 UTC
for example:

Your browser doesn't support direct access to the clipboard. Please use the Ctrl+X/C/V keyboard shortcuts instead.

Paste is now in plain text mode. Contents will now be pasted as plain text until you toggle this option off.

It have this item in the langs/zh_CN.js ,but not tanslated

need help ,Thanks!

**Comment by zotopteam** [comment] 2015-12-17 10:23
You have unsaved changes are you sure you want to navigate away? 

this too, i don't know why theme not translated!

**Comment by lnewson** [comment] 2020-05-08 09:42
Hi,

Thanks for reporting this and looking at both the TinyMCE 4 and 5 translations, the missing string is now included. Additionally, when testing out the translations with TinyMCE 4.9.10 and 5.2.2 I was unable to reproduce the issue, so it's likely we've fixed this since this was reported. As such I'll go ahead and close this, but please do let us know if you're still experiencing issues and we'll reopen this.

Thanks!

**Closed by lnewson** 2020-05-08 09:42 UTC
Labels: component: i18n, type: bug
