### ISSUE TITLE
Support for non-svg button images in 5.x

### ISSUE THREAD

**Issue by ScottYeadon** [tinymce/tinymce#5063] opened 2019-07-02 22:49 UTC
In 4.x there was an image property that could point to a non-SVG (e.g. PNG) image which could be used for custom buttons. This property looks to have been dropped for 5.x. Is it possible to put this ability back as lots of effort has gone into making nice PNG buttons, and I'm not sure why it's been decided to support SVG-only icons.

It would be good to have either the image property restored or allow a url in the icon property which could point to a non-SVG image to use for custom buttons

**Comment by emergence75** [comment] 2019-07-03 06:49
take a look
https://www.martyfriedel.com/blog/tinymce-5-creating-a-plugin-with-a-dialog-and-custom-icons

**Comment by ScottYeadon** [comment] 2019-07-03 22:09
Yes, I know how to configure the SVG icons, the issue is that we have custom bitmap images that our users know and are familiar with and we would rather not have to recreate them just because TinyMCE has decided to drop a useful configuration option. Bitmap icons are still used everywhere so it's not like TinyMCE would be supporting marginal/deprecated formats by keeping the 'image' config item.

**Comment by TheSpyder** [comment] 2019-07-04 01:42
This was a deliberate design choice in the 5.x release. I'm sure @lostkeys wrote up some thoughts on this, but I can't find them now 🤔

I've marked it as a regression although there are no plans to reverse the decision at this stage. He's on vacation so I'll leave a note for him to join the discussion when he returns.

**Comment by emergence75** [comment] 2019-07-05 06:29
you can also configure a non svg image

instead of 

editor.ui.registry.addIcon('bubbles', '<svg class="icon"><use xlink:href="custom-icons.svg#bubbles4"></use></svg>');

something like this 

editor.ui.registry.addIcon('bubbles', '<img src="mypath/img/bubbles.png" title="Bubbles">');

i've tried this some time ago and it worked...

**Comment by TheSpyder** [comment] 2019-07-05 06:33
It's probably still true that we aren't sanitising the icon data string. It's still not supported by the design, so it could break in future.

**Comment by TheSpyder** [comment] 2019-08-08 01:09
After some discussion we've accepted that this needs to happen. I don't have a timeline for implementing it yet but it has entered our backlog.

**Comment by Wipqozn113** [comment] 2020-03-05 19:15
@TheSpyder  Any updates on this?

**Comment by TheSpyder** [comment] 2020-03-06 00:22
I'm no longer working on the core editor, unfortunately. @lostkeys is probably the best person to update on this now.

**Comment by lostkeys** [comment] 2020-03-06 06:59
Sorry, there has not been any movement on this. To be honest you would be better off just redrawing the icons as SVG than wait for us to implement a legacy technique. SVG is superior in this regard. They don’t require multiple assets for different resolutions and can be colored at runtime. I’m not saying we’re not going to do it but It’s currently not a very high priority atm.

**Comment by TheSpyder** [comment] 2023-04-26 22:55
Due to a lack of ongoing interest - TinyMCE 5 was released over 4 years ago, and I believe this thread is the only complaint we've had about it - we've shelved our internal tracking ticket and no longer plan to offer anything other than SVG.

**Closed by TheSpyder** 2023-04-26 22:55 UTC
Labels: component: ui, status: regression, status: escalated, 5.x
