### ISSUE TITLE
Problem writing korean characters inside table have attribute align=left   

### ISSUE THREAD

**Issue by changsu-byun** [tinymce/tinymce#5126] opened 2019-08-21 16:12 UTC
**What is the current behavior?Describe the bug**
<div>&lt;table align=right&gt;</div>
<div>&lt;tr&gt;&lt;/td&gt;ㅎ ㅏ ㄱ ㅣㄹ&lt;/tr&gt;</div>
<div>&lt;/tr&gt;</div>
<div>&lt;/table&gt;</div>

IE11 : table align=right or align=left    Problem writing korean characters

but align=center   no Problem writing korean characters

chrom,safari  no Problem writing korean characters 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
ver 3,4,5 same bug
IE

**Comment by wonderbugtiny** [comment] 2019-09-03 04:44
@changsu-byun I was unable to reproduce the issue using IE 11 with TinyMCE 5.0.15. Please provide a video and/or a [fiddle](http://fiddle.tinymce.com/) to help us understand the behaviour you are experiencing. Thank you!

**Comment by lnewson** [comment] 2019-10-15 21:40
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-10-15 21:40 UTC
Labels: needs: more info
