### ISSUE TITLE
TinyMCE 5: Styleselect in quickbars toolbar doesn't show current style

### ISSUE THREAD

**Issue by mabeyj** [tinymce/tinymce#4957] opened 2019-04-24 15:19 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using a styleselect in a quickbars toolbar, the styleselect doesn't show the current style.

![image](https://user-images.githubusercontent.com/773401/56670574-76ba8a00-6689-11e9-923d-5c67470b7d10.png)

![image](https://user-images.githubusercontent.com/773401/56670616-8afe8700-6689-11e9-8777-0d8175f550e4.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/1Ggaab/1

Select text or insert a new line and notice the styleselect in the quickbars toolbar is empty. Compare to the styleselect in the non-quickbars toolbar which does show the current style.

**What is the expected behavior?**

The styleselect should show the current style in quickbars toolbars like it does when a styleselect is used in the normal toolbar.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

* TinyMCE 5.0.0 to 5.0.4
* Tested with Chrome 73, Firefox 66, Edge 18, and IE11 on Windows 10

**Comment by SeriaWei** [comment] 2019-04-25 04:14
I am trying to update TinyMCE to v5 and i found that the `styleselect` doesn't show the current style 
![image](https://user-images.githubusercontent.com/6006218/56709336-48a17c80-6753-11e9-95c7-f45708bdcc62.png)

**Comment by lnewson** [comment] 2019-05-01 03:12
Thanks for the report! I can confirm this is an issue and it looks to be caused by an initial value not being set and relying on nodechange events to populate the value, which won't ever occur for quickbars. I've logged an internal task for us to look into this further.

**Comment by wonderbugtiny** [comment] 2019-06-06 05:18
This has been fixed in 5.0.6. Please let us know if you find any further problems. Thank you!

**Closed by wonderbugtiny** 2019-06-06 05:18 UTC
Labels: 5.x, component: ui, resolution: fixed in coming release, status: escalated, type: bug
