### ISSUE TITLE
flow of text box switch

### ISSUE THREAD

**Issue by gunchanok** [tinymce/tinymce#3046] opened 2016-07-05 04:41 UTC
![screen-shot-2559-07-05-at-11 36 40-am](https://cloud.githubusercontent.com/assets/6848579/16574090/4e5fcf80-42a5-11e6-9bf8-ad2ceab31544.jpg)

**Comment by spocke** [comment] 2016-07-18 07:06
Fixed this issue in the master branch. It's currently not released so either build tinymce from the github source or wait for the nightly build to help us verify that this bug has been resolved. Thanks.

**Comment by spocke** [comment] 2016-07-18 07:06
Duplicate of #3066

**Comment by tinydylan** [comment] 2020-04-20 12:40
This issue has been corrected.

**Closed by tinydylan** 2020-04-20 12:40 UTC
Labels: component: ui, status: verified, type: bug
