### ISSUE TITLE
Unresponsive UI on touch devices

### ISSUE THREAD

**Issue by jose-barata** [tinymce/tinymce#5310] opened 2019-11-07 16:05 UTC
**What is the current behavior?**
None of the menus or buttons is responsive.

**To reproduce:**
* Create a new angular project
* Install @tinymce/tinymce-angular: 3.3.1 and tinymce: 5.1.1
* Follow the steps to use tinymce locally

**Which versions of TinyMCE/TinyMCE-Angular, and which browser / OS are affected by this issue?** 
**Browsers tested:**
* Chrome latest (@07/11/2019)
* Firefox latest (@07/11/2019)

**Dependencies installed:**
@tinymce/tinymce-angular: 3.3.1
tinymce: 5.1.1

**Did this work in previous versions of TinyMCE or TinyMCE-Angular?** Yes, in 5.0.16

**Comment by Georg-Git** [comment] 2019-12-16 08:04
Same problem:
- MS Surface with touch screen
- ext. screens parallel to touchscreen
=> Browser Chrome: tiny menu become unresponsive
=> Browser IE: tiny keeps responsive

**Comment by freitasm** [comment] 2019-12-16 20:43
I have a user who reported a similar problem. His setup is not a Surface but another touch-enabled device:

"HP Pro X2 612 G2 tablet. Works when the tablet's physical integrated keyboard/mouse is plugged in; stops working when not; despite there being a USB connected keyboard and mouse."

**Comment by panfanky** [comment] 2019-12-18 21:39
Confirming that on hp pavilion x360 I can only control the menus by screen touch, not by touchpad clicking.

**Comment by lnewson** [comment] 2019-12-19 09:08
We've just released TinyMCE 5.1.5 to the community. It contains a fix that should resolve this issue where the UI was not working on hybrid devices that accepted both touch and mouse events. Since we aren't able to test on all the devices mentioned here, please let us know if this resolves the issue. Thanks again for letting us know about this and for bearing with us while we sort out the issues.

**Comment by Georg-Git** [comment] 2019-12-19 09:51
Tiny 5.1.5 && MS Surface && Chrome => OK!

**Comment by michaelsoutherton** [comment] 2019-12-19 17:18
Tiny 5.1.5 && MS Surface && (Firefox || Edge Chromium || Edge)  => OK
Thanks!

**Comment by freitasm** [comment] 2019-12-19 20:39
Thanks @lnewson - any idea on when this will be available on Tinycloud please?

**Comment by jamesrtnz** [comment] 2019-12-19 20:42
I am the end-user that reported the issue to @freitasm (above); I'd like to test/verify the update; but I can't find a version of 5.1.5 deployed anywhere to test.  The main "demo" editor on the tiny.cloud landing page still seems to be v5.1.4...

Or if someone can provide a URL to a v5.1.5 deployment, I can check it...

**Comment by lnewson** [comment] 2019-12-19 21:28
Tiny Cloud serves our enterprise version, so it has to go through more stringent QA before it gets updated. I don't have a definitive date at the moment sorry, but given the upcoming holidays it'll likely be sometime in early-mid January. In saying that however 5.1.5 is available on the `5-testing` Tiny Cloud channel so you could use that in the interim.

As for a place to test, our Fiddle has all community TinyMCE versions, as well as our dev/testing/stable cloud channels: http://fiddle.tinymce.com/

**Comment by jamesrtnz** [comment] 2019-12-19 21:33
Totally understand the Enterprise requirements - I work in Enterprise IT myself.

Happy to confirm that v5.1.5 from the Fiddle does indeed resolve the issue I was experiencing.

Thanks very much!

**Comment by palczewski** [comment] 2020-01-07 18:50
@lnewson The menu buttons work now, but right-click does not seem to work (for example, right-clicking on an image or link to edit).

**Comment by lnewson** [comment] 2020-01-08 00:09
@palczewski can I ask that you log a new issue for that? I think I know what might be the cause, but it'll be subtly different to this issue.

Anyways, since the primary issue has been fixed I'm going to close this. If anyone is still having issues, please create a new issue.

**Closed by lnewson** 2020-01-08 00:09 UTC
Labels: 5.x, status: escalated
