### ISSUE TITLE
Why doesnt Firefox/Chrome allow Iframes if I check them with media_url_resolver?

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#6606] opened 2021-03-10 09:37 UTC
I'm implementing a blog content feature with TinyMCE, a WYSIW editor.
I need to check if the user's media upload is a youtube/vimeo video with a regex (see in code).

But it is not working as excpected. In the editor and also in the display content itself it shows this: [Firefox darf diese eingebettete Seite nicht öffnen Zu Ihrem Schutz erlaubt www.youtube.com es Firefox nicht, diese Seite anzuzeigen, wenn sie in eine andere Seite eingebettet ist. Zur Anzeige der Seite muss diese in einem neuen Tab geöffnet werden. Image link down below][1]

Here's the code: 
```
tinymce.init({
            selector: 'textarea#PostContentInput',
            plugins: 'preview paste importcss searchreplace autolink autosave directionality code visualblocks visualchars fullscreen link codesample tabfocus table charmap hr nonbreaking toc insertdatetime advlist lists wordcount image imagetools textpattern noneditable media help charmap emoticons',
            imagetools_cors_hosts: ['picsum.photos'],
            menubar: 'file edit view insert format tools table help',
            toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent | numlist bullist | forecolor backcolor removeformat | charmap emoticons | fullscreen  preview | media image link codesample | ltr rtl',
            toolbar_sticky: true,
            autosave_ask_before_unload: true,
            autosave_interval: '30s',
            autosave_prefix: '{path}{query}-{id}-',
            autosave_restore_when_empty: false,
            autosave_retention: '2m',
            image_advtab: true,
            importcss_append: true,
            file_picker_callback: function (callback, value, meta) {
                /* Provide image and alt text for the image dialog */
                if (meta.filetype === 'image') {
                    callback('https://www.google.com/logos/google.jpg', { alt: "Alternative text if the image doesn't load." });
                }

                // Provide alternative source and posted for the media dialog
                if (meta.filetype == 'media') {
                    callback('movie.mp4', {source2: 'alt.ogg', poster: 'image.jpg'});
                }
            },
            image_advtab: true,
            height: 600,
            media_poster: false,
            table_sizing_mode: 'responsive',
            image_caption: true,
            quickbars_selection_toolbar: 'bold italic | quicklink h2 h3 blockquote',
            noneditable_noneditable_class: 'mceNonEditable',
            toolbar_mode: 'sliding',
            contextmenu: 'link image imagetools table',
            skin: useDarkMode ? 'oxide-dark' : 'oxide',
            content_css: useDarkMode ? 'dark' : 'default',
            content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
            media_url_resolver: function (data, resolve) {
                if (data.url.match(/(http:|https:|)\/\/(player.|www.)?(vimeo\.com|youtu(be\.com|\.be|be\.googleapis\.com))\/(video\/|embed\/|watch\?v=|v\/)?([A-Za-z0-9._%-]*)(\&\S+)?/)) {
                    var embedHtml = '<iframe src="' + data.url +
                    '" width="400" height="400" ></iframe>';
                    resolve({html: embedHtml});
                } else {
                    resolve({html: 'no'});
                }
            }
        });
```

The thing is without the media_url_resolver it shows the content.
Is there any other function that allows only youtube/vimeo links?
What did I do wrong? Please help me, i been stuck with this forever now.

Thanks very much! Best reguards, Tobi

  [1]: https://i.stack.imgur.com/AgowX.png

**Comment by SimonFc** [comment] 2021-03-10 13:09
I think this is due to the processing that the Media plugin's default media embedd logic will put the url through. Without your custom media_url_resolver callback

**Comment by lnewson** [comment] 2021-03-10 21:13
Worth noting this appears to be a duplicate of https://github.com/tinymce/tinymce/issues/6083 and https://github.com/tinymce/tinymce/issues/5587. As @SimonFc said, TinyMCE by default will convert a YouTube URL to the embedded version, so if you're using a custom resolver you'd unfortunately need to duplicate that logic.

**Closed** 2024-06-14 00:51 UTC
Labels: plugin: media, type: question
