### ISSUE TITLE
Characters stripped when pasted into tinymce

### ISSUE THREAD

**Issue by RomanTheCube** [tinymce/tinymce#3480] opened 2017-02-10 01:16 UTC
We have found a bug relating to bullet points and decimal point numbers when pasting content into the TinyMCE editor.

If a bullet point is created in MS Word, and the value of 0.25 is written, eg:

- 0.25

Then you copy this, and paste into the TinyMCE editor, the editor strips the "0." from what is pasted.

For an example, see attached image :
![image](https://cloud.githubusercontent.com/assets/25043249/22810084/afbbd61a-ef8a-11e6-87ba-0470f3935df5.png)

When you paste this content, it should retain the full content without stripping any characters.

**Comment by stevenslack** [comment] 2017-03-09 20:31
+1

**Comment by kknopp** [comment] 2018-01-17 14:36
It actually strips off any value prior to the `.`. So `1.25` becomes `25` and `100.200` becomes `200`.

**Comment by kknopp** [comment] 2018-01-17 14:40
I've seen the above in version 4.7.2, but cannot reproduce on the website front page. What plug-ins are active on the front page so that we can see if one of them fixes it?

**Comment by tvanantwerp** [comment] 2020-01-22 14:37
I've just observed this behavior when using the TinyMCE Advanced plugin (v4.7.11) on a WordPress site (v4.9.13). No other WordPress plugins that should affect the editor are active.

**Comment by tvanantwerp** [comment] 2020-01-22 14:44
I suspect [this](https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/paste/main/ts/core/WordFilter.ts#L192) is where the error lies. There's no code to say, "Oh, we see that this was an unordered bulleted list, so we don't need to also see if this is a numeric bulleted list."

**Comment by metricjs** [comment] 2020-10-30 05:49
Marking as verified as we can replicate this in 5.5

**Closed** 2024-06-15 00:44 UTC
Labels: status: verified
