### ISSUE TITLE
Show invisible characters marks visible text entered immediately after an invisible element

### ISSUE THREAD

**Issue by Stadly** [tinymce/tinymce#3084] opened 2016-07-26 17:45 UTC
When `Show invisible characters` is enabled, text entered after an invisible element is included in the highlight indicating the invisible element.

To reproduce:
1. Go to https://www.tinymce.com/docs/demo/full-featured/.
2. Enable `View | Show invisible characters`.
3. Insert a non-breaking space by going to `Insert | Nonbreaking space`.
4. Type some random text. Observe that the gray background marking the non-breaking space is extended to include the newly typed text.

**Comment by trevorjay** [comment] 2020-05-26 01:09
I can not reproduce this issue in either of the latest versions of the editor. It looks like it was fixed in the 4.6.0 release and was never present in the 5.x.x line. I'm closing this issue. If anyone is still experiencing problems, please let us know and we can reopen.

**Closed by trevorjay** 2020-05-26 01:09 UTC
