### ISSUE TITLE
Textcolor fails to color foreground/background upon selection IE

### ISSUE THREAD

**Issue by Hillyman** [tinymce/tinymce#4410] opened 2018-05-24 15:18 UTC
I have noticed that the TextColor plugin fails to select change the text colors foreground or background upon selection of the new color in IE.

Test: https://codepen.io/anon/pen/GdaPey
Reproduction Steps:
Open the test link in IE
Highlight a block of text (several words/several lines)
Click either the foreground or background color text dropdowns
Select a color

Results:
The color is selected however the highlighted text is left unchanged.
Occasionally only a single word (either first or last) is changed to the newly selected color.
The coloring works if you click the buttons after selection but not immediately upon selection.
This does not occur on chrome.

**Comment by Afraithe** [comment] 2018-06-21 09:44
I can't quite replicate this, can you make a video or something?

What IE? Edge or 11?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:33
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:33 UTC
Labels: browser: edge, browser: ie11, needs: more info
