### ISSUE TITLE
Font formatting whitespace

### ISSUE THREAD

**Issue by ryoullar** [tinymce/tinymce#5154] opened 2019-09-09 20:27 UTC
I'm using TinyMCE version 5.0.11 in my application, and have noticed some odd behavior around how it handles formatting whitespace.
We only provide two font options to the user, Sans Seriff (default) and monospace. This application is occassionally used to enter code snippets, which is why we provide the monospace font (we do not provide the code editor, as that was causing some other issues for our use case).

Some users have complained about how it handles formatting spaces. They want to be able to enter some monospace font spaces to align things, and may move around the document as they are doing this.
I have found the following playing around with this myself:

If you enter a few spaces at the end of the editor, highlight them, then click Monospace, nothing happens. On occasion a second click will get the font to change, but often it does not change no matter how many times you select monospace.

If you enter several space characters, select some of them, then change the font, the whole line changes, not just the selected characters.

I've noticed several occassions where I have entered a few space characters, a carriage return to the next line, and typed some content. After moving my cursor back up, all the space characters on the previous line have been removed.

**Comment by wonderbugtiny** [comment] 2019-09-10 03:26
Hi @ryoullar, I couldn't reproduce the issue in TinyMCE version 5.0.11 using Chrome. Please provide a [fiddle](http://fiddle.tinymce.com/baaaab) and/or a video to help us understand the behaviour you are experiencing. Also, please let us know the OS, browser and browser version you are using. Thank you!

Additionally, you could use both the Code Sample plugin (different from the code editor) and the built-in block formatting option `Pre` to input code snippets into the editor (`Formats > Blocks > Pre`). Below are the respective links to the documentation.
Code Sample plugin: https://www.tiny.cloud/docs/plugins/codesample/
Content formatting options: https://www.tiny.cloud/docs/configure/content-formatting/#built-informats

**Comment by nonplus** [comment] 2020-02-05 19:44
This can be reproduced when the editable content uses `white-space: pre-wrap`. In this case, at least in Chrome, 4 spaces are entered as is (`"    "`), rather than as `"&nbsp; &nbsp; "`).

Selecting these spaces and applying a style (e.g. different font, setting to bold, etc.) appears to be a noop.

http://fiddle.tinymce.com/Tahaab

**Comment by lnewson** [comment] 2020-05-04 04:38
I believe this should be fixed in TinyMCE 5.2.0 or higher, as up until then formatting spaces wasn't possible. We've since added that feature and testing quickly with the fiddle from the comment above, it appears to be working now? Could someone confirm please?

**Comment by metricjs** [comment] 2020-07-22 01:28
I've done some testing too and this seems fixed to me, so I'll close this ticket. If anyone finds any related problems, please feel free to reopen this ticket or make a new ticket.

**Closed by metricjs** 2020-07-22 01:28 UTC
Labels: component: formatting, needs: more info
