### ISSUE TITLE
[4.7.0] Drag icon is misaligned when branding is off

### ISSUE THREAD

**Issue by ucsdmath** [tinymce/tinymce#3982] opened 2017-10-05 15:39 UTC
I just updated from the previous Tiny-MCE (v4.6.7) to Tiny-MCE (v4.7.0). Been updating with each version for 3 years and just noticed a drastic CSS difference in the look.  The CSS coloring and placements of items have changed.  I am adding an image upload to show.
I hope this is helpful, Thank you.
![difference-css](https://user-images.githubusercontent.com/12222464/31236209-60009d62-a9a8-11e7-8c3a-13135b5e2b64.png)

Also, notice the little window expander, and menus seem to be different colors, and spacing.

**Comment by androb** [comment] 2017-10-05 16:00
Thanks, @ucsdmath - this is actually by design :) We wanted to give TinyMCE an updated look and feel. You can certainly revert back to grey (or anything else you want) using the skin capability.

I do notice in your screenshot that the drag icon in the bottom right-hand corner is out of alignment though. If this is a bug you can replicate in a fiddle we can get that fixed.

**Comment by ucsdmath** [comment] 2017-10-05 19:02
Hi Andrew,
I carried over the previous skin: 'lightgray', from v4.6.7 and it worked great!
And I found out why the "Drag Icon" was moved over (or not aligned right) is because I have branding: false,

If branding is turned on (which is the default) then the "Drag Icon" is in the correct location.
I thought the default skin was 'lightgray'. I am guessing the default files for "lightgray" has changed.  Anyway, thank you, I solved the problem by carrying forward the lightgray from version 4.6.7 and everything works perfectly as before.

Thank you,
Daryl

**Comment by androb** [comment] 2017-10-05 19:56
Okay thanks, I am going to leave this bug open but rename it to reflect the issue with drag icon

**Comment by annaephox** [comment] 2017-10-05 22:36
@ucsdmath : thanks heaps for logging this issue! If you have time, I'd be really keen to know your thoughts around why you have reverted back to the "old" lightgrey theme

**Comment by ucsdmath** [comment] 2017-10-06 05:51
Hi Anna,
I am clearly not an expert in interface design. And I may guess you're much better at it than me. However, there are a few principles I have considered from courses in Human Factors Engineering (in college), particularly the Principle of Similarity. I think it is more of a single contrast idea vs. no contrast.  It helps group those controls as a single block object and keeps a division from my data.  Anyway, I am probably over thinking it anyway. Sometimes I just get a feel for certain things. I do not think clear white is the way to go.  Anyway, you guys are doing such great work! Keep going.
All the best,
Daryl

**Comment by ucsdmath** [comment] 2017-10-06 06:06
One other item that I noticed.  By me moving the old **lightgray** skin from Tiny-MCE (v4.6.7) to Tiny-MCE (v4.7.0), I do get the gray theme I was looking for by deleting or replacing it in v4.7.0.

However, I did notice there are some fundamental CSS changes that breaks.  For instance, when I turned **branding: true** the location of the logo/object is not where it should be.  It actually moves to the _left of the window footer section_ (it should be all the way to the right).  It feels as though there are some fundamental CSS structural changes between the latest and previous versions.

**Comment by annaephox** [comment] 2017-10-06 06:14
@ucsdmath : thanks heaps for that feedback, really appreciate it!! I don't have shares in any of the colours, so my question was genuinely just to collect feedback. No agenda :) In that regard, whatever your opinions and preferences are are right... I've added your thoughts to our logs - and I welcome more feedback from the community on this too!

**Comment by Georg-Git** [comment] 2017-10-06 09:51
I am with ucsdmath:
- bad separation of menu from content!
- bad contrast, 
- and the new dimensions disturbing integration of tiny in my existing projects.

=> I moved back to lightgray version 4.6.7.

I would prefer to give the new skin a new name!
And to keep the the old lightgray skin in the distribution packet.

If You set the new skin as default - fine.
But when the skin in init is explicit set to lightgray, then this should be the skin lightgray of version 4.6.7!

**Comment by ucsdmath** [comment] 2017-10-06 12:25
@Georg-Git You stated clearly.  Maybe the new version of **lightgray** could be renamed to **clearwhite** since it does _not have gray_ in it.  One of my concerns is that this was bumped as a feature change (not major) and should not break in production (v4.6.7 vs. v4.7.0).  It should just drop-in as a replacement.

 I have to give credit to them though, over the years, it has worked just like that.  Great tool!

**Comment by fyrkant** [comment] 2017-10-09 13:59
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Comment by Afraithe** [comment] 2017-10-09 13:59
It is true the name isn't quite suitable, an abstract name with no relation to it's look & feel would have been prerered when we change the default skin like this, however it was at least in a .x and not a .x.x release where you can except larger changes but probably not breaking changes (without workarounds).

In terms of the design changes, the contrast follows common guidelines, and are in some cases higher than previous skin. 

We did a survey of customers, and over 60% had changed the background color to white, this was a clear motivation to update the skin. 

I urge you to give the new design some time to grow on you, there are small but subtle changes to improve the user experience.

4.7.1 was released today, we fixed the issue with the branding being missaligned and some other issues.

By the way, thank you for giving us this great feedback and being quick to adopt the latest changes!

**Closed** 2017-10-09 13:59 UTC
Labels: status: escalated, status: verified, type: bug

**Comment by ucsdmath** [comment] 2017-10-09 14:12
@Afraithe Yes, sorry, I misstated suggesting a major change when only minor implementation and minor bug fixes are applied. Thank you for such a quick update.  Great job and 60% is significant.
Thanks again!
