### ISSUE TITLE
Please stop blackcathikari!

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#3082] opened 2016-07-25 11:54 UTC
What's going on here? The user "blackcathikari" close valid tickets with

> Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

This is simply nonsense! All this bugs still exists in 4.4.0

https://github.com/tinymce/tinymce/issues/2161#issuecomment-234819466
https://github.com/tinymce/tinymce/issues/2566#issuecomment-234827195
https://github.com/tinymce/tinymce/issues/2807#issuecomment-234828385
.....

**Comment by alecpl** [comment] 2016-07-25 13:12
Looks like she might be Ephox QA intern/employee. But closing 1000 tickets without really testing them is not nice. Hope @spocke will fix that asap.

**Comment by dsakko** [comment] 2016-07-25 23:20
Hi Daijobou, we are currently looking through historic tickets to check if they are still current for v4.4.0 of Tiny.  We are undertaking testing for each ticket - there are quite a few of them ;) .  You've identified some valid tickets that we were unable to reproduce in that initial testing. Thanks for bringing this to our attention, feedback like yours helps ensure that we can improve the quality of Tiny. Please reopen the tickets you know are still outstanding.  If you have any further replication details that would also be helpful. We’ll review ASAP and if we need any additional info/examples we will get in touch within the tickets.

**Comment by alecpl** [comment] 2016-07-26 06:18
Please, don't bullshit us. How did you test e.g. #2522? It is not fixed and I can't reopen my tickets!!! You transferred the hard work to the community without even informing us before.

**Comment by jayarjo** [comment] 2016-07-26 19:35
@Daijobou #2161 seems to fixed in v4.4.0. Investigating others.

**Comment by Daijobou** [comment] 2016-07-27 10:04
See my answer in ticket #2161 :)

**Comment by starquake** [comment] 2016-08-01 09:14
I understand the need to close old tickets that do not seem relevant anymore. Less tickets means you can focus your time spent on more productive stuff. But I must agree that the tickets are closed to easily.

This ticket: https://github.com/tinymce/tinymce/issues/2953 got closed saying it can not be reproduced anymore. But while testing this @blackcathikari must have seen the video disappearing. (https://github.com/tinymce/tinymce/issues/3097) Ofcourse that bug can't happen anymore if the result is the entire video vanishes.

So: great job closing old irrelevant issues @blackcathikari, but could you please start testing a bit more carefully?

(trying to give this issue a more positive vibe, did I succeed? :-) )

**Closed** 2017-02-06 07:44 UTC
