### ISSUE TITLE
Whitespace is stripped inside PRE tags when it is the editor container

### ISSUE THREAD

**Issue by ellatrix** [tinymce/tinymce#4351] opened 2018-04-19 18:16 UTC
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When using `pre` as the editor container, whitespace is stripped.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/hqgaab

**What is the expected behavior?**

Whitespace shouldn't be stripped in `pre`, even if it is the editor container.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Latest TinyMCE version. Affects all browsers. Not that I know.

**Comment by metricjs** [comment] 2020-05-05 00:46
Hi,
I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.13. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.
Thanks!

**Closed by metricjs** 2020-05-05 00:46 UTC
Labels: status: escalated, status: verified, type: bug
