### ISSUE TITLE
Issue with table arrow keys and linked text selection

### ISSUE THREAD

**Issue by srirampearson** [tinymce/tinymce#4462] opened 2018-06-26 11:04 UTC
Hi Team,

Recently we upgraded the tinymce to the latest version 4.7.13. This issue is working fine in earlier tinymce version.

We are currently facing 2 issues as given below:

1. issue with table arrow keys:
2. issue with linked text selection:

When we press arrow keys within the table, no events got fired. Cursor stays in the same place.

We tried to debug the below path:
\src\code\main\ts\keyboard\ArrowKeys.ts -> line number 26-29

The keyboard up/down/left/events got bypassed and nothing happens when we press these keys.

Workaround for this issue ->
When i try to remove the above lines 26-29, both of these issues getting fixed correctly.

My doubt is whether is it the right fix for this issue? If not, can you please let me know any other better option to address this issue.

Regards,
Sriram

**Comment by srirampearson** [comment] 2018-06-26 11:06
The above fix is done based on the below commit:
commit 40037b4b: TINY-1490: worked on table navigation using arrow keys

**Comment by wonderbugtiny** [comment] 2019-04-08 03:34
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:34 UTC
Labels: needs: more info, plugin: table
