### ISSUE TITLE
Nested Tables and blank line

### ISSUE THREAD

**Issue by bah2002us** [tinymce/tinymce#4681] opened 2018-11-27 06:57 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Clicking on the blank line in a column that has nested table will make caret jump in front of the nested table.
Clicking just above or below the line the caret will be on the blank line but clicking right on it then it will jump.

http://fiddle.tinymce.com/w4gaab

**What is the expected behavior?**
The caret should remain on the line you click on wether on the line or above/below

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

tested on tinymce 4.8.5 and 5 as well and same issue.
testing browsers EDGE, firefox …….. etc

**Comment by fyrkant** [comment] 2018-12-06 08:06
I'm not clear on the problem, can you do a screen recording or something showing where you are clicking?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:44
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:44 UTC
Labels: needs: more info
