### ISSUE TITLE
Error loading font name in firefox

### ISSUE THREAD

**Issue by Jiemenez** [tinymce/tinymce#3458] opened 2017-01-26 19:15 UTC
where there more of one editor and configured  toolbar1: "fontselect" does not allow to load editor, see scene
see: tab 4 al 6
 https://jsfiddle.net/JiemenezM/mqLwL1tc/6/

**Comment by fyrkant** [comment] 2017-01-27 08:44
Duplicate of #3442, and has been fixed in an upcoming release!

**Closed by fyrkant** 2017-01-27 08:44 UTC
