### ISSUE TITLE
Dragging image to change position

### ISSUE THREAD

**Issue by antoniu86** [tinymce/tinymce#2464] opened 2015-11-10 07:52 UTC
If you have an image inside the tinymce which has the src a normal url, dragging it from a place to another inside a bigger text works. If you for example edit the image the src will be a blob:... something. Trying to drag this element to another location inside the text will result in deleting the image. It just disappears. This is reproducible also on the tinymce website and has nothing to do with my custom config.

**Comment by fyrkant** [comment] 2018-03-27 13:41
I can't reproduce this in TinyMCE 4.7.9 so I'm closing this issue, if you still have this problem please open up a new issue with a reproduction in a fiddle.

**Closed by fyrkant** 2018-03-27 13:41 UTC
Labels: plugin: paste, status: verified, type: bug

**Comment by mikkorantalainen** [comment] 2021-12-13 14:30
Is this supposed to work anymore?

Dragging an image to move its position doesn't seem to work even in the official demo at https://www.tiny.cloud/docs/demo/full-featured/

If you try do drag the logo from the start of the text to the table cell into the table within the same editor area you'll only see pink warning with text "Dropped file type is not supported". The drag seems to start successfully and mouse cursor is correct but it seems like it tries to upload the dragged image instead of just moving its position in the source document.

**Comment by MatthijsReyers** [comment] 2023-02-10 12:38
It seems this issue only occurs on Firefox, I have not been able reproduce it on any chromium based browsers...
