### ISSUE TITLE
upload image error

### ISSUE THREAD

**Issue by 454464335** [tinymce/tinymce#5676] opened 2020-05-19 01:42 UTC
Error: Errors: Failed path: (data > src) Could not find valid *strict* value for "value" in { "meta": {} } Input object: { "src": { "meta": {} }, "alt": "", "dimensions": { "width": "", "height": "" }, "fileinput": [ {} ] }

The image can be uploaded successfully, but the image cannot be read. The return value of the uploaded image is {"code":200,"location":"/upload/textarea/1.png"}.

**Comment by lnewson** [comment] 2020-05-21 10:34
@454464335 this isn't really clear what the issue is sorry, nor does it show us how to reproduce the issue. Can you please provide a replication case, such as a [fiddle](http://fiddle.tinymce.com) or similar to demonstrate your issue?

**Comment by lnewson** [comment] 2020-07-14 02:54
Closing due to a lack of additional information. If you can provide the above-requested details, then we'll be happy to reopen this.

**Closed by lnewson** 2020-07-14 02:54 UTC
Labels: needs: more info

**Comment by mirik999** [comment] 2021-02-06 09:23
The issue was created long ago. But maybe someone will get this error again.
I had the same issue , in my case i tried to return number with success method but I had to return a string (url). 
( i wanted to show progess :D )

**Comment by MysticalSam** [comment] 2021-02-14 05:06
I am getting the same issue,

Trying to upload the image from local computer to directory. Image upload is successful but in return the error shows up.

JS

`function tinymce_image_upload_handler(blobInfo, success, failure, progress) {
    var xhr, formData;
    xhr = new XMLHttpRequest();
    xhr.withCredentials = false;
    xhr.open('POST', '/admin/ajax/blog_content_image_upload');

    xhr.upload.onprogress = function(e) {
        progress(e.loaded / e.total * 100);
    };

    xhr.onload = function() {
        var json;

        if (xhr.status === 403) {
            failure('HTTP Error: ' + xhr.status, { remove: true });
            return;
        }

        if (xhr.status < 200 || xhr.status >= 300) {
            failure('HTTP Error: ' + xhr.status);
            return;
        }

        json = JSON.stringify(xhr.responseText);

        if (!json) {
            failure('Invalid JSON: ' + xhr.responseText);
            return;
        }

        success(json.location);
    };

    xhr.onerror = function() {
        failure('Image upload failed due to a XHR Transport error. Code: ' + xhr.status);
    };

    formData = new FormData();
    formData.append('file', blobInfo.blob(), blobInfo.filename());

    xhr.send(formData);
};

tinymce.init({
    selector: 'textarea#tinymce',
    height: 500,
    menubar: false,
    plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table paste code help wordcount'
    ],
    toolbar: 'undo redo | formatselect | ' +
        'bold italic backcolor | alignleft aligncenter ' +
        'alignright alignjustify | bullist numlist outdent indent | ' +
        'removeformat | link image code | help',

    images_upload_url: '/admin/ajax/blog_content_image_upload',
    automatic_uploads: true,

    images_upload_handler: tinymce_image_upload_handler,

    content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
});`

Controller for uploading image:

`            $file = $this->request->getFile('file');

            // If a file is present...
            if ($file) {

                if (!empty($file) && $file->getSize('mb') > 0) {

                    $unique_photo_name = $file->getRandomName();

                    $file->move('../public/uploads', $unique_photo_name);

                    $photo_url_path = base_url('uploads/' . $file->getName());

                    $resp = $photo_url_path; // gives back image name for editor

                    $resp_mes = 'ok';
                } else {
                    $resp_mes = 'Error: Could not upload the file...';
                }
            } else {
                $resp_mes = 'Error: Please pick a file!';
            }
            $return_arr[] = array(
                "location" => $resp
            );
            echo json_encode($return_arr, JSON_UNESCAPED_SLASHES);
`

**Comment by frontYang** [comment] 2021-02-26 02:41
I have also encountered this problem, the solution is to delete the `image_class_list` parameter

**Comment by Datalink-Wouter** [comment] 2021-04-26 07:32
I had the exact same problem and my solution isn't mentioned here.
For anyone that experiences the same:
Make sure that you return a json object in your Upload handler.

In my case (using Laravel as backend), I ended up returning the full URL like this:
`
return json_encode(array('location' => url($handleFilesContract->getPathWithStorage())));
`

This will return an object like: `{ location : 'https/your/uploaded/image/file'}`

**Comment by andysay** [comment] 2022-04-04 10:59
its problem with render component.

**Comment by cezarfloroiu** [comment] 2022-04-11 20:35
For those having the issue, if you were returning a success cb in the images_upload_handler,  look into returning a Promise per the latest change. Happened to me and after making the change it works fine.  The example in the public doc is not uploaded!

- The `images_upload_handler` option is no longer passed a `success` or `failure` callback and instead requires a `Promise` to be returned with the upload result #TINY-8325

**Comment by Ding95** [comment] 2022-04-22 01:02
Have you solved it? It should be a version problem.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/12723947/164576222-22bb03fd-4b99-439f-a3e2-5c0621635789.png">
The [version 6.X ](https://www.tiny.cloud/docs/tinymce/6/upload-images/#example-using-images_upload_handler) return a Promise and the [version 5.X](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler) use callback function.

**Comment by elya-adzz** [comment] 2022-08-18 14:45
I am still having this problem. I am using tinyMCE 6, so I am returning a promise. I have tried returning the location as a string and as a JSON object, and I am still getting this error. Any help is appreciated.

```const handleUploadImages = (blobInfo: any, progress: any) => {
  const fileType = blobInfo.filename().slice(blobInfo.filename().length - 3);
  const name = `${blobInfo.name()}_${new Date().getFullYear()}_${new Date().getMonth()}_${new Date().getDate()}_${new Date().getHours()}_${new Date().getMinutes()}.${fileType}`;

  return new Promise((resolve, reject) => {
    uploadImageToAzure(blobInfo.blob(), name)
      .then((uploadBlobResponse: BlockBlobUploadResponse) => {
        if (uploadBlobResponse.errorCode) {
          reject(
            `An error occurred while uploading:${uploadBlobResponse.errorCode}`
          );
        }
        progress(100);
        resolve(
          JSON.stringify({
            location: uploadBlobResponse._response.request.url.split('?')[0],
          })
        );
      })
      .catch((error) => {
        reject(`An error occurred while uploading:${error}`);
      });
  })
    .then((response) => {
      const response1 = response as string;
      return JSON.parse(response1);
    })
    .catch((err) => {
      throw new Error(err);
    });
}; `

**Comment by danielrsantana** [comment] 2023-01-05 02:23
This error basically is informing the Editor were unable to identify the image URL.

In order to solve this issue, update the code to return a Promise (instead of calling the callback) and certify you are resolving the promise with the correct response property with the image URL (usually from your API response).

Example (check the comment before the `resolve`):

`
  private imageUploaderHandler = (blobInfo, progress) => {
    return new Promise((resolve, reject) => {
      const xmlRequest = new XMLHttpRequest();
      const formData = new FormData();

      xmlRequest.withCredentials = false;
      xmlRequest.open('POST', 'https://your_api_url');

      xmlRequest.upload.onprogress = (e) => {
        progress((e.loaded / e.total) * 100);
      };

      xmlRequest.onload = () => {
        if (xmlRequest.status == 200) {
          const response = JSON.parse(xmlRequest.response);

          // my issue was here. A string is expected and a null value will result in the reported error
          resolve(response.image_url);
        } else {
          reject('HTTP Error: ' + xmlRequest.status);
        }
      };

      xmlRequest.onerror = () => {
        reject('Image upload failed due to a XHR Transport error. Code: ' + xmlRequest.status);
      };

      formData.append('file', blobInfo.blob(), blobInfo.filename());
      formData.append('image', blobInfo.blob());
      formData.append('title', blobInfo.filename());
      xmlRequest.send(formData);
    });
  };
`

**Comment by gspgsp** [comment] 2023-06-09 08:20
> Have you solved it? It should be a version problem. <img alt="image" width="930" src="https://user-images.githubusercontent.com/12723947/164576222-22bb03fd-4b99-439f-a3e2-5c0621635789.png"> The [version 6.X ](https://www.tiny.cloud/docs/tinymce/6/upload-images/#example-using-images_upload_handler) return a Promise and the [version 5.X](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler) use callback function.

wonderful...this solved my problem

**Comment by mariojgt** [comment] 2023-07-22 11:29
My Final solution that is working is this one

images_upload_handler: async (blobInfo) => {
            let formData = new FormData();
            formData.append('file', blobInfo.blob(), blobInfo.filename());
            try {
                const res = await axios.post(usePage().props.upload_media, formData, {
                    headers: {
                        'Content-Type': 'multipart/form-data'
                    }
                });
                if (res.data && res.data.data.url.default) {
                    return res.data.data.url.default;
                } else {
                    throw new Error('Unable to upload image');
                }
            } catch (err) {
                throw new Error('Unable to upload image');
            }
        }

**Comment by ivan-khuda** [comment] 2023-08-08 14:43
I had a similar issue, in my case I solved it by specifying the version with `tinymceScriptSrc`

I am using React wrapper:

```
import { Editor as EditorElement } from "@tinymce/tinymce-react";

const TINY_MCE_SCRIPT_SRC = `https://cdn.tiny.cloud/1/${TINY_MCE_API_KEY}/tinymce/5/tinymce.min.js`;

.....

<EditorElement
  tinymceScriptSrc={TINY_MCE_SCRIPT_SRC}
  initialValue={notifyMessage}
  onInit={(evt, editor) => editorRef.current = editor}
  init={{
    height: 470,
  }}
/>
```

**Comment by TheSpyder** [comment] 2023-08-10 02:10
Or you could convert your image upload handler to promises and continue to use the current release of the editor.

This issue is way off topic, for further concerns please log a new issue.
