### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by PasVV** [tinymce/tinymce#5455] opened 2020-03-03 08:57 UTC
I'm using `@tinymce/tinymce-react` hook and trying to start editor on IE11, but getting an error:
```
SCRIPT5007: unable to get property "getItem" of undefined or null reference
File: theme.min.js (9, 14158)
```

File `theme.min.js` is a cloud file: `"https://cdn.tiny.cloud/1/invalid-origin/tinymce/5.1.6-68/themes/silver/theme.min.js"`.

**How i've got this bug**
1. Install `@tinymce/tinymce-react` and `tinymce` libs to project.
2. Configure editor with settings:
```
<MceEditor
    apiKey="HIDDEN_CODE"
    disabled={disabled}
    value={value}
    init={{
      height: 500,
      menubar: false,
      plugins: [
        'advlist autolink lists link image charmap print preview anchor',
        'searchreplace visualblocks code fullscreen',
        'insertdatetime media table paste code wordcount',
      ],
      toolbar:
        'undo redo | formatselect | bold italic backcolor | \
            alignleft aligncenter alignright alignjustify | \
            bullist numlist outdent indent | removeformat',
      content_css: [
        '//fonts.googleapis.com/css?family=Lato:300,300i,400,400i',
        '//www.tiny.cloud/css/codepen.min.css',
      ],
    }}
    onEditorChange={handleChange}
/>
```

Thank you for any feedback!

**Comment by lnewson** [comment] 2020-03-08 22:14
@Lilliance I tried to replicate this and was unable to. Our automated tests are also passing fine on IE 11, so I suspect it might be related to how your IE 11/Windows OS is configured. Could you include some more information about any settings you may have changed, or restrictions that have been applied? Also make sure that you aren't running in compatibility mode, or something similar as that isn't supported.

Note: I'm wondering if this might be related to https://github.com/tinymce/tinymce/issues/919 as I see one location in the silver theme where we aren't using a fallback local storage, which could be the cause if you are using a profile with dom storage disabled.

**Comment by lnewson** [comment] 2020-04-24 12:13
Closing due to a lack of additional information. If the above details can be provided we'll be happy to reopen this and investigate further.

**Closed by lnewson** 2020-04-24 12:13 UTC
Labels: browser: ie, needs: more info
