### ISSUE TITLE
Version 4.7.10 - Editor bug - Several bugs while adding columns to table

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4317] opened 2018-04-03 23:25 UTC
Tested in Firefox. The initial table width is 450px. Add two columns. Now check the table properties. The form dialog will say 560px and the style textbox in the advanced tab will say 450px.

In older versions of the table plugin, when the user adds a column, the table width remains the same, that would be the right thing.

http://fiddle.tinymce.com/Xogaab

**Comment by trevorjay** [comment] 2020-05-26 01:57
I'm closing this issue as it is a duplicate of #4380 and was fixed in 4.7.13. I am unable to reproduce it in the latest 4 and 5 releases. If anyone experiences a regression, please let us know.

**Closed by trevorjay** 2020-05-26 01:57 UTC
