### ISSUE TITLE
Bug: color does not work if font-size is specified

### ISSUE THREAD

**Issue by marzsocks** [tinymce/tinymce#3513] opened 2017-02-26 10:41 UTC
When font-size and color are specified on the same `<span>`, when a new color is chosen the color plugin wraps the selected span in a new span, instead of just replacing the color in the selected span.

**Example:**

`<span style="font-size:24pt;color:red;">Hello World</span>`

**Expected outcome (after selecting "Hello World" and changing the color):**

`<span style="font-size:24ptcolor:green;">Hello World</span>`

**Actual outcome:**

`<span style="color:green;"><span style="font-size:24pt;color:red;">Hello World</span></span>`

**Comment by lnewson** [comment] 2020-05-09 05:23
Hi, 

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided. Looking back, it appears this may have been fixed by https://github.com/tinymce/tinymce/pull/3510 in TinyMCE 4.5.5. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 05:23 UTC
Labels: component: formatting, status: verified, type: bug
