### ISSUE TITLE
Tinymce Link: "Open Link" in context menu always open link in new window ignoring target

### ISSUE THREAD

**Issue by ant9n19** [tinymce/tinymce#5269] opened 2019-11-19 13:23 UTC
**What is the current behavior? Describe the bug**
I have created link with target "Current Window" (target='_parent'). So if I open context menu and click "Open Link" it always open it in New Window. (It's reproduced in your basic example https://www.tiny.cloud/docs/demo/basic-example/)

**What is the expected behavior?**
It's should be opened in target which I select in "insert Link" form.

**Which versions of TinyMCE?**
5.0.16

**Did this work in previous versions of TinyMCE?**
Yes, it is

**Comment by lostkeys** [comment] 2019-11-19 14:39
I tested it in [this fiddle](http://fiddle.tinymce.com/CVgaab), and I can confirm that the target attribute in the HTML doesn't change when selecting another target in the dialog. It broke between TinyMCE 5.0.13. See the linked fiddle for more details.

**Comment by lnewson** [comment] 2019-11-19 22:17
This issue is a duplicate of https://github.com/tinymce/tinymce/issues/5221 and was fixed in TinyMCE 5.1. So please try upgrading and if you're still having issues let us know.

**Closed by lnewson** 2019-11-19 22:17 UTC
Labels: 5.x, plugin: link, status: regression, status: verified, type: bug

**Comment by lnewson** [comment] 2019-11-19 22:24
I'm really sorry, but I got the wrong version here, this has been fixed in 5.2 which has yet to be released not 5.1. So reopening the issue and since we've got a few tickets about this now I'll talk to our PM about backporting the fix for 5.1.3. However since this is a duplicate I'm going to keep this closed as we're tracking this via the other issue I mentioned in my previous comment.

**Comment by rodaraknia** [comment] 2023-10-11 09:14
This issue is happening on latest version 6!
