### ISSUE TITLE
Image copying problem

### ISSUE THREAD

**Issue by Yaoyo999** [tinymce/tinymce#7543] opened 2022-01-21 02:19 UTC
CTRL v directly pasted large image (binary) into the editor, causing the browser to freeze, hope the official can take a look, thank you

**Comment by hamza0867** [comment] 2022-06-06 03:43
Hi @Yaoyo999  ,

We were not able to reproduce the error you mention in this ticket, can you please provide a replication case, such as on [fiddle](https://fiddle.tiny.cloud/) ?

Thank you

**Comment by lostkeys** [comment] 2024-02-19 14:23
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.

**Closed by lostkeys** 2024-02-19 14:23 UTC
Labels: needs: more info
