### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of undefined in findCommonAncestor

### ISSUE THREAD

**Issue by 9folders-jungho** [tinymce/tinymce#5493] opened 2020-03-11 06:50 UTC
tinyMCE version : 5.2.0

1. setContent 
`
editor.setContent('<p>fdfsdkfj<strong>sdfsdfsdf<em>sdfdsf<span style="text-decoration: underline;">sdfsdfdsf</span></em><span style="text-decoration: underline;">sdfsdf</span></strong><span style="text-decoration: underline;">sdfsdf<em>sdfsd</em></span><em>fsdf<span style="text-decoration: underline;">sdfsdf</span></em><em><span style="text-decoration: underline;">sdfsd<strong>sfdsfsdfsdfasdf</strong></span></em></p><p><em><span style="text-decoration: underline;"><strong>adsfsdfsdaf</strong></span></em><strong><span style="text-decoration: underline;">sdfdsf<em>sdfsdf</em>sdfdsf</span>sdf</strong>sdf<span style="text-decoration: underline;">sdfsdfsdsd<em>fsfsdfsdsdsdfsdf</em>sdfsdfs</span>sdfdssd<strong>fsd<em>sfdsfsdf</em><em>sfsdfsdfsdf</em>ds</strong>fdsfsd<span style="text-decoration: underline;">sdfsdfsdfs<strong>sdfsd<em>sdfdsds</em></strong></span></p><p><span style="text-decoration: underline;"><strong><em>sdfsdfasfsasdf</em>sd</strong><strong>fsdfss[dfsdfsd</strong></span><strong>sfsdf</strong><em><strong>dfsddfsdf<span style="text-decoration: underline;">sdf</span><span style="text-decoration: underline;">sd]fds</span></strong><span style="text-decoration: underline;">dfsdfds</span></em><span style="text-decoration: underline;">sdfsdfsd<strong>sdfsdfsd</strong></span><strong>dsfdsfdsfsd<em>sdfsfsd</em></strong><em>sfsdfsd<span style="text-decoration: underline;">sdfdsfsdfsd</span></em><span style="text-decoration: underline;">sdfsdfsd<strong>sdfsdfsd</strong></span><strong>fsdfds</strong>sdfsd</p>');
`

2. select text in line 3 - "[dfsdfsdsfsdfdfsddfsdfsdfsd]﻿"

3. bold button click.

--> Error occurred
tinymce.js:6996 Uncaught TypeError: Cannot read property 'ownerDocument' of undefined
    at Object.findCommonAncestor (tinymce.js:6996)
    at Object.walk$1 [as walk] (tinymce.js:10576)
    at removeRngStyle (tinymce.js:17790)
    at remove$7 (tinymce.js:17847)
    at toggle (tinymce.js:18857)
    at Object.toggle (tinymce.js:42)
    at EditorCommands.toggleFormat (tinymce.js:25882)
    at mceToggleFormat (tinymce.js:26018)
    at EditorCommands.execCommand (tinymce.js:25751)
    at Editor.execCommand (tinymce.js:27195)

**Comment by lnewson** [comment] 2020-03-11 07:11
Duplicate of  #5488

**Closed** 2020-03-11 07:11 UTC
