### ISSUE TITLE
Can't edit codesample when editor in inline mode

### ISSUE THREAD

**Issue by gkubisa** [tinymce/tinymce#4141] opened 2018-01-05 00:12 UTC
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

The code sample is not updated in the editor after clicking OK in the code sample edit dialog.

The bug can be reproduced since TinyMCE 4.7.0 and only when the editor is in the inline mode.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Go to: http://fiddle.tinymce.com/shgaab/1
2. Insert a code sample
3. Edit the code sample

**What is the expected behavior?**

The code sample is updated in the editor after clicking OK in the code sample edit dialog.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Ubuntu 16.04
Chrome Version 63.0.3239.108 (Official Build) (64-bit)
TinyMCE 4.7.4 BUG
TinyMCE 4.7.0 BUG
TinyMCE 4.6.7 OK

**Comment by lnewson** [comment] 2020-05-08 09:00
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 or 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.5. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:00 UTC
Labels: plugin: codesample, status: escalated, status: verified, type: bug
