### ISSUE TITLE
Cannot Drag & Drop DIV or SPAN element in Table

### ISSUE THREAD

**Issue by GaryStimson** [tinymce/tinymce#3075] opened 2016-07-21 15:14 UTC
Hi,
I'm seeing a problem when dragging and dropping both DIV and SPAN elements inside a table (from cell to cell). I have attached reproducible HTML that when placed inside TinyMCE source you will see the issue. You will find the DIV element will not drag and drop at all (although shows the ghost to drag and drop) and the SPAN element allows to drag but produces both a JS error in TinyMCE code as well as not dropping correctly (sometime works and sometimes deletes the element or places it outside of the table).
Thanks,
[TinyMCE Issue.txt](https://github.com/tinymce/tinymce/files/376346/TinyMCE.Issue.txt)

Gary Stimson
Senior Software Engineer
Labvantage Solutions

**Comment by jayarjo** [comment] 2016-07-24 13:03
Looks like it's `data-mce-selected` intervening. If we could disable it while we drag.

**Comment by GaryStimson** [comment] 2016-07-26 09:32
Any update on this? Is there any workaround I could use?
Thanks,
Gary

**Comment by jayarjo** [comment] 2016-07-26 17:37
The workaround is quite straight-forward, although I'm not sure if it will qualify for the final fix. Here's [the branch with the fix](https://github.com/jayarjo/tinymce/tree/TINY-546), if you know how to build Tiny from source.

**Comment by GaryStimson** [comment] 2016-07-27 16:35
Hi Jayarjo,
Thanks for that. Are you able to provide a link to the information on how to build Tiny from source?
Also are you able to point me to the exact code change so I can temporarily patch our version of Tiny?
Thanks,
Gary

**Comment by HAFRMO** [comment] 2020-05-07 05:19
Hi,
I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.
Thanks!

**Closed by HAFRMO** 2020-05-07 05:19 UTC
Labels: status: verified, type: bug
