### ISSUE TITLE
TinyMCE doesn't work with Ublock Origin

### ISSUE THREAD

**Issue by LarkusManz** [tinymce/tinymce#4587] opened 2018-10-02 07:19 UTC
**Description of problem:**
If you've installed uBlock Origin you cant type into the TinyMCE textarea.

**Steps to reproduce:**
1. Using a Browser like Google Chrome and install the latest version of uBlock Origin
2. Try to type something into TinyMCE -> it doesn't work
3. Add your Page to the whitelist of uBlock and try it again -> it doesn't work

**Affected Browsers:**
- Chromium (Linux) & Google Chrome (Windows)
Version 69.0.3497.100 (Official Build) snap (64-bit)
uBlock Origin v1.17.0
- Opera (Windows)
Version 56.0.3051.31
uBlock Origin v1.17.0

The only browser i tested which works with uBlock Origin and TinyMCE is Firefox (Windows & Linux)
Firefox Version: 62.0
uBlock Version: 1.17.0

**Comment by spocke** [comment] 2018-10-02 07:28
I use uBlock on Chrome on Linux and it doesn't block the iframe here: https://www.tiny.cloud/

**Comment by wonderbugtiny** [comment] 2019-04-08 03:40
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:40 UTC
Labels: needs: more info
