### ISSUE TITLE
Coy paste table with content is pasting text alone

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3896] opened 2017-08-29 16:33 UTC
Hi,

We are using latest version and we faced an issue in Firefox and Edge like copy and paste the table with content is pasting the content alone in Firefox and Edge.

Can anyone please take a look and let me know.

**Comment by dotKev** [comment] 2017-08-29 16:47
Do you have the `paste` plugin enabled?

**Comment by kaviyarasanaspire** [comment] 2017-08-29 16:51
I have just checked in this url

https://www.tinymce.com/docs/demo/full-featured/

**Comment by fyrkant** [comment] 2017-08-30 08:08
This has been fixed and will be a part of the next release that will probably come out later today or some day later in the week. You can check that the nightly release has this fixed in this fiddle: http://fiddle.tinymce.com/3Yfaab

**Comment by kaviyarasanaspire** [comment] 2017-08-30 09:52
Hi,

I still can able to reproduce this issue in nightly version as well. I have updated the fiddle , please check it.

http://fiddle.tinymce.com/3Yfaab

**Comment by fyrkant** [comment] 2017-08-30 09:57
You have to press save on the fiddle to save any updates, and then a number will be added on the url.

**Comment by kaviyarasanaspire** [comment] 2017-08-30 10:35
No, I am not changing anything to the configuration, I am just copy the entire table paste it in the next line and the text only copied.

If you want, I will provide the video

**Comment by fyrkant** [comment] 2017-08-30 13:14
Try this link: http://fiddle.tinymce.com/3Yfaab/1

Open `View -> Help` menu and make sure it says that the version is 4.6.6. Is it still not working?

**Comment by kaviyarasanaspire** [comment] 2017-08-30 14:25
I could not get any help file there, but I found that, but still I am facing the issue

/* Ephox TinyMCE Cloud
 *
 * Copyright 2010-2017 Ephox Corporation. All rights reserved.
 *
 * Version: 4.6.6-123
 */
// 4.6.6 (2017-08-30)"

**Comment by fyrkant** [comment] 2017-08-30 14:30
In what browser and OS are you still having the problem? I can't reproduce it on FF or Edge.

**Comment by kaviyarasanaspire** [comment] 2017-08-30 14:50
Windows 10 Firefox 47.0.2, Edge 38.14393.0.0

**Comment by fyrkant** [comment] 2017-08-30 15:07
Hmm weird! Would really appreciate if you could record a video of the problem.

**Comment by kaviyarasanaspire** [comment] 2017-08-31 12:21
Hi,

Please find the video reference.

**URL:** https://www.screencast.com/t/CVHtBsgYB

Regards,
Kavi

**Comment by spocke** [comment] 2017-08-31 13:06
How are you doing that selection exactly. The default behavior even in firefox is to produce custom table selection with blue background. The firefox built in table selection model is not supported.

**Comment by kaviyarasanaspire** [comment] 2017-08-31 13:18
I just clicked on the right side of the table and dragged to the left side of the table, if you look at the above attached video then you can know.

**Comment by fyrkant** [comment] 2018-03-22 15:26
The table plugin has been rewritten since this issue and I think that fixed it so I'm closing it.

**Closed by fyrkant** 2018-03-22 15:26 UTC
Labels: needs: more info, status: regression, type: bug
