### ISSUE TITLE
No focus indication for tabs on "Table Properties" modal

### ISSUE THREAD

**Issue by simonista** [tinymce/tinymce#3005] opened 2016-06-16 20:36 UTC
The General and Advanced tabs on the Table properties modal do not show any focus indication.  This may be true for other modal dialogs with multiple tabs, but I don't know of others off the top of my head.

Steps to Reproduce:
- Move keyboard focus to the main input area and press alt+f9 to move focus to the menu bar
- Use the arrow keys to move focus to the Table menu and press Enter
- Press Enter (with "Insert Table" focused) to bring up the 'Table properties' modal
- Shift+Tab to get back to the General/Advanced tabs
- Note there is no focus indication
- Press Space to prove that focus actually is there

Reproduced on the current version (at time of filing) on tinymce.com, 4.3.13.

Would you be open to a pull request adding focus indication to these tabs?

**Comment by spocke** [comment] 2016-06-17 07:55
We had some issue with outlines on some browsers that's why we having implemented tab focus. But this might not be an issue anymore was a while since we last attemted it.

**Comment by simonista** [comment] 2016-06-17 22:05
Is there a list of currently supported browsers?

**Comment by spocke** [comment] 2016-06-18 12:54
https://www.tinymce.com/docs/get-started/system-requirements/

We might need to update the IE 8/9 support a bit more features that doesn't work on those.

**Comment by lnewson** [comment] 2020-05-09 07:31
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working now. Additionally, the linked pull request https://github.com/tinymce/tinymce/pull/3479 indicates this was fixed back in October 2017, so I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 07:31 UTC
Labels: component: ui, status: verified, type: feature
