### ISSUE TITLE
TinyMCE 5: Line break does not work in modal windows (in Firefox)

### ISSUE THREAD

**Issue by lufog** [tinymce/tinymce#4664] opened 2018-11-07 08:41 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you open code or codesample modal window, all the text in it is in one line, without line breaks.
This behavior occurs only in Firefox.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1) Open Firefox
2) Go to [TinyMCE Fiddle](http://fiddle.tinymce.com/) set version to **tinymce5-devpreview**
3) Add codesample plugin to plugins (need for testing)
4) Open code or codesample modal window, and write some text with line breaks.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5, Firefox 63.0.1 (64-bit), Windows 10 1809

**Comment by wonderbugtiny** [comment] 2018-11-08 00:54
The line break issue is caused by Firefox not enabling whitespace or newlines within textareas to make white-space work similar to other elements. A fix has been scheduled and will be in a release soon.

**Comment by lnewson** [comment] 2019-02-23 07:52
This issue was fixed in the 5.0 Beta by the looks it and I can't reproduce it using the 5.0 stable release, so I'm going to mark this as resolved. Please let us know if you find any further problems!

**Closed by lnewson** 2019-02-23 07:52 UTC
Labels: 5.x, plugin: code, plugin: codesample
