### ISSUE TITLE
Regression: Style is not removed when sibling span does not have the format and range is collapsed

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3717] opened 2017-06-06 06:26 UTC
Steps to repro:

1. Open jsfiddle.tinymce.com
2. Type text with spaces, e.g.: Testing Rich Text Editing
3. Select all text and apply bold
   -> resulting text: `<p><strong>Testing Rich Text Editing</strong></p>`
4. Put cursor in the middle of last word (no selection, only cursor) and click bold, in order to unbold the word
   -> resulting text: `<p><strong>Testing Rich Text</strong> Editing</p>`
5. Put cursor in the middle of the second to last word (no selection, only cursor) and click italic
   -> resulting text: `<p><strong>Testing Rich <em>Text</em></strong> Editing</p>`
6. Put cursor in the middle of the second to last word again (no selection, only cursor) and click italic

Expected:
Text should not be italic
Actual:
Text does not change format

Checked with previous versions and it used to work in 4.1.9 (from 4.1.10 it is broken)

Seems like findWordEndPoint (called by expandRng) is returning the startContainer to be the text node containing `Testing Rich `, which has no italic applied to it.

Tested with several versions after 4.1.9 including latest.

**Comment by thiagolacerda** [comment] 2017-06-13 16:36
@spocke @fyrkant any updates on this regression?
Thanks!

**Comment by lnewson** [comment] 2020-05-02 09:57
Thanks again for the report! I was able to confirm this issue still exists in all versions of TinyMCE 4. However, it appears as though we've fixed the issue in TinyMCE 5 as I'm now able to remove the italics styles.

Unfortunately there's been a number of changes done in TinyMCE 5, so I'm not exactly sure what would have fixed this and given it's not a critical issue we're unlikely to try to backport it to TinyMCE 4. As such I'd suggest upgrading to TinyMCE 5 to get this issue resolved and on top of that I'm also going to close this since it's fixed in TinyMCE 5. If you can still reproduce the issue in TinyMCE 5, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 09:57 UTC
Labels: component: formatting, status: verified
