### ISSUE TITLE
Editor mangles MathML

### ISSUE THREAD

**Issue by paulschreiber** [tinymce/tinymce#5106] opened 2019-08-04 00:41 UTC
Originally reported as https://github.com/phillord/mathjax-latex/issues/43

With WordPress 5.2.2 and TinyMC 4.9.4, switching from the text editor to TinyMCE and back mangles the tags.

Before:
```
<math>
<mrow>
  <mrow>
        <msup> <mi>x</mi> <mn>2</mn> </msup> <mo>+</mo>
            <mrow>
              <mn>4</mn>
              <mo>&InvisibleTimes;</mo>
              <mi>x</mi>
            </mrow>
    <mo>+</mo>
    <mn>4</mn>
  </mrow>
    <mo>=</mo>
    <mn>0</mn>
</mrow>
</math>
```

After:
```
<math> <mrow></mrow></math>
<mrow>
<msup> <mi>x</mi> <mn>2</mn> </msup> <mo>+</mo>
<mrow>
<mn>4</mn>
<mo>⁢</mo>
<mi>x</mi>
</mrow>
<mo>+</mo>
<mn>4</mn>
</mrow>
<mo>=</mo>
<mn>0</mn>
```

Here's the `extended_valid_elements` we are using:
```
extended_valid_elements:"math[class|id|style|dir|href|mathbackground|mathcolor|display|overflow|xmlns],maction[actiontype|class|id|style|href|mathbackground|mathcolor|selection],maligngroup,malignmark,menclose[class|id|style|href|mathbackground|mathcolor|notation],merror[class|id|style|href|mathbackground|mathcolor],mfenced[class|id|style|close|href|mathbackground|mathcolor|open|separators],mfrac[bevelled|class|id|style|denomalign|href|linethickness|mathbackground|mathcolor|numalign],mglyph[alt|class|id|style|height|href|mathbackground|src|valign|width],mi[class|id|style|href|mathbackground|mathcolor|mathsize|mathvariant],mlabeledtr[class|id|style|columnalign|groupalign|href|mathbackground|mathcolor|rowalign],mlongdiv,mmultiscripts[class|id|style|href|mathbackground|mathcolor|subscriptshift|superscriptshift],mn[class|id|style|dir|href|mathbackground|mathcolor|mathsize|mathvariant],mo[accent|class|id|style|dir|fence|form|href|largeop|lspace|mathbackground|mathcolor|mathsize|mathvariant|maxsize|minsize|moveablelimits|rspace|separator|stretchy|symmetric],mover[accent|align|class|id|style|href|mathbackground|mathcolor],mpadded[class|id|style|depth|height|href|lspace|mathbackground|mathcolor|voffset|width],mphantom[class|id|style|mathbackground],mroot[class|id|style|href|mathbackground|mathcolor],mrow[class|id|style|dir|href|mathbackground|mathcolor],ms[class|id|style|dir|lquote|href|mathbackground|mathcolor|mathsize|mathvariant|rquote],mscarries,mscarry,msgroup,msline,mspace[class|id|style|depth|height|linebreak|mathbackground|width],msqrt[class|id|style|href|mathbackground|mathcolor],msrow,mstack,mstyle[dir|decimalpoint|displaystyle|infixlinebreakstyle|scriptlevel|scriptminsize|scriptsizemultiplier],msub[class|id|style|mathbackground|mathcolor|subscriptshift],msubsup[class|id|style|href|mathbackground|mathcolor|subscriptshift|superscriptshift],msup[class|id|style|href|mathbackground|mathcolor|superscriptshift],mtable[class|id|style|align|alignmentscope|columnalign|columnlines|columnspacing|columnwidth|displaystyle|equalcolumns|equalrows|frame|framespacing|groupalign|href|mathbackground|mathcolor|minlabelspacing|rowalign|rowlines|rowspacing|side|width],mtd[class|id|style|columnalign|columnspan|groupalign|href|mathbackground|mathcolor|rowalign|rowspan],mtext[class|id|style|dir|href|mathbackground|mathcolor|mathsize|mathvariant],mtr[class|id|style|columnalign|groupalign|href|mathbackground|mathcolor|rowalign],munder[accentunder|align|class|id|style|mathbackground|mathcolor],munderover[accent|accentunder|align|class|id|style|href|mathbackground|mathcolor],semantics[definitionURL|encoding|cd|name|src],annotation[definitionURL|encoding|cd|name|src],annotation-xml[definitionURL|encoding|cd|name|src],span[class|id|style],span[class|id|style],span[class|id|style|data-url|data-end|data-plays],div[class|id|style],span[class|id|style],main[class|id|style],button[class|id|style|type|data-target],nav[class|id|style|role],video[class|id|style|autoplay|loop|controls|preload|playsinline|muted|src|data-defer],img[class|id|style|src|srcset|alt|width|height|data-src|loading],section[class|id|style|data-name],span[contenteditable|class|id|style],span[contenteditable|class|id|style]"
```

If you omit the whitespace between tags, it works as expected (tag order and content is preserved).

**Comment by lnewson** [comment] 2019-08-04 07:12
@paulschreiber can you please create a way to reproduce this outside WordPress? As I suspect this might be a problem with the WordPress integration and not TinyMCE directly, as I tried to reproduce this using fiddle: http://fiddle.tinymce.com/tOgaab however I couldn't produce the mangled HTML you've mentioned (Note: `force_root_block` isn't really needed, I just added that so the MathML markup isn't wrapped in a paragraph).

**Comment by connerbw** [comment] 2019-08-12 14:39
Possibly related:

+ https://core.trac.wordpress.org/ticket/13340
+ https://core.trac.wordpress.org/attachment/ticket/13340/13340.diff

Would affect TinyMCE editor in the same way:

+ https://github.com/WordPress/WordPress/blob/28ad3662fc6a7f829b33753785fa3a295bec121f/wp-admin/js/editor.js#L1012
+ https://github.com/WordPress/WordPress/blob/28ad3662fc6a7f829b33753785fa3a295bec121f/wp-admin/js/editor.js#L886

**Comment by lnewson** [comment] 2019-10-15 21:44
Closing this due to lack of additional information or a reproduction case outside of wordpress. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-10-15 21:44 UTC
Labels: needs: more info
