### ISSUE TITLE
Menu bar not properly aligned in firefox

### ISSUE THREAD

**Issue by dsiuvngit** [tinymce/tinymce#8462] opened 2023-02-17 11:49 UTC
The menu bar in the Rich Text Editor sometimes sticks to the bottom of the page.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/125660147/219646073-38037e08-abf6-442c-8c10-8b7493986624.png">

it's expected to stick to the bottom of the rich text area

This issue is present on firefox browser.

**Comment by lostkeys** [comment] 2023-02-22 15:12
Hi @dsiuvngit, can you try to replicate the issue in a [TinyMCE fiddle](https://fiddle.tiny.cloud) so we can make sure the issue is with TinyMCE?

**Comment by lostkeys** [comment] 2024-02-19 14:32
🧹TinyMCE Github backlog cleanup in progress🫧. A long time ago, this issue was labeled "needs more info" but no additional details were given, so we're closing this issue. If you believe this issue was closed in error, please **re-test your issue with the most recent version of TinyMCE** and submit a new ticket.

**Closed by lostkeys** 2024-02-19 14:32 UTC
Labels: needs: more info, component: ui
