### ISSUE TITLE
Spellchecker not working good in tinymce

### ISSUE THREAD

**Issue by Ishanjn** [tinymce/tinymce#2586] opened 2015-12-23 10:40 UTC
Spellchecker not working good; In tinymce Its showing me a popup message again and again with "Spellchecker request error: 0" message. Although i entered correct text. Please check below screenshot:

![tinymce com spellchecker](https://cloud.githubusercontent.com/assets/16400078/11975024/9fb2126c-a98f-11e5-929a-738a9712f7eb.png)

**Comment by spocke** [comment] 2015-12-23 13:01
Seems to be a server issue. We are on it. Thanks for reporting it.

**Comment by Ishanjn** [comment] 2015-12-23 13:32
Okay, Thanks for letting me know. Anyway tiny-mce is the best RTE editor :+1:

**Comment by nori-h** [comment] 2016-07-27 23:54
We have taken a look and this issue appears to be a duplicate of #1087

**Comment by fyrkant** [comment] 2018-03-28 09:38
This has been fixed.

**Closed by fyrkant** 2018-03-28 09:38 UTC
Labels: plugin: spellchecker, status: verified, type: bug
