### ISSUE TITLE
Hyperlinks do not work while the editor is in read-only mode

### ISSUE THREAD

**Issue by jsplaine** [tinymce/tinymce#3836] opened 2017-07-26 18:35 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

As our customers have reported...

Currently, in 4.3.13 (and I assume based on the changelog, >= Version 4.3.8 (2016-03-15)), when clicking on hyperlinks while the editor is in read-only mode, nothing happens.  I.e., hyperlinks are broken when the editor is in read-only mode.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Create a hyperlink in the editor (choose open in new window, for the target),
2. Put the editor in read-only mode
3. Click on the hyperlink

Note, in fiddle, hyperlinks do not work at all (regardless of read-only mode) as can be seen here: http://fiddle.tinymce.com/oWfaab

**What is the expected behavior?**

The link should continue to work.  Read-only mode should not cause the breakage of hyperlinks.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

- Browser/OS agnostic
- Does not work in 4.3.13 (and I assume, based on the changelog, >= Version 4.3.8 (2016-03-15))
- worked in 3.5.8

Here's the change-set which removed the clicking functionality: @spocke 
https://github.com/tinymce/tinymce/commit/778d1381a9e5889070a49c882d3d8f6583029177

**Comment by milestogofromhere** [comment] 2017-12-19 04:15
Would it be possible to make this a configurable setting? TinyMCE is used in a lot of applications and one application we have renders the control in a read-only format and we relied on the links being active. The vendor pointed us to this particular version where the functionality changed.

**Comment by sushan05** [comment] 2018-12-13 10:14
Even, an embedded youtube video cannot be played in readonly mode. I am looking for some workaround.

@jsplaine  - have you found any solution for the **link** issue?

**Comment by nileshbhagwat** [comment] 2018-12-14 00:17
@spocke @fyrkant any update on this?

**Comment by sashless** [comment] 2019-11-13 14:30
To fix that for me i added this to the config

```js

const openLink = (url, target) => {
    if (target !== '_blank') {
        document.location.href = url;

        return;
    }

    const link = document.createElement('a');
    link.href = url;
    link.target = target;
    link.rel = 'noopener';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
};

const config = {
    // ... other settings here
    setup: (editor) => {
        editor.on('init', () => {
            Array.from(editor.getDoc().querySelectorAll('a')).map((el) => {
                el.addEventListener('click', () => {
                    const href = el.getAttribute('href') || '';
                    const target = el.getAttribute('target') || '';
                    openLink(href, target);
                });
            });
        });
    }
};
```

**Comment by lnewson** [comment] 2020-05-02 10:16
Hi,

I'm going to close this sorry, as this is intended behaviour. Links should never work within the editor, as it will navigate the user away from the page and they may lose content. In the latest versions of TinyMCE you can however right click or CTRL+Click to open the link in a new tab/window.

**Closed by lnewson** 2020-05-02 10:16 UTC

**Comment by DaveButland** [comment] 2020-07-17 08:26
I am also experiencing this same issue and I'm sure it didn't us to work like this. I am using TinyMCE to create content as an editor and then rendering that content using TinyMCE in readonly mode. This is much simpler than trying to inject the custom content into my react app and works perfectly apart from the links. You can't lose content when clicking on the link if the editor is in readonly mode...

**Comment by sashless** [comment] 2020-07-17 08:49
@DaveButland I did this to be able to click links in readonly mode.

```

    registerEventHandler = (editor: TinyMCE) => {
        if (this.props.readonly) {
            // tslint:disable-next-line no-inferred-empty-object-type
            editor.on('init', () => {
                editor.getDoc().querySelectorAll('a').forEach((el: HTMLElement) => {
                    el.addEventListener('click', () => {
                        const href = el.getAttribute('href') || '';
                        const target = el.getAttribute('target') || '';
                        this.openLink(href, target);
                    });
                });
            });

            return;
        }
    }

    openLink = (url: string, target: string) => {
        if (target !== '_blank') {
            this.props.globalWindow.location.href = url;

            return;
        }

        const link = document.createElement('a');
        link.href = url;
        link.target = target;
        link.rel = 'noopener';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };

**Comment by manoj-mass** [comment] 2020-08-20 12:32
@sushan05 Following worked for me for embedded media, such as youtube videos.

```
                  editor.on('init', () => {
                    Array.from(editor.getDoc().querySelectorAll('.mce-object-iframe')).map((el: any) => {
                      el.addEventListener('click', () => {
                        el.setAttribute('data-mce-selected', '2')
                    });
                    });
                  });
```
