### ISSUE TITLE
queryCommandState('justifyfull') never returns true

### ISSUE THREAD

**Issue by rafdulaf** [tinymce/tinymce#4374] opened 2018-05-03 14:31 UTC
This is a reopen of issue 1632 that does still apply in 4.7.11

Description of problem: I am trying to use the TinyMCE API to query the state of the text selection, but I am never able to determine if the text is using the justify format

Steps to reproduce:

Type some text in a paragraph
tinymce.activeEditor.execCommand('justifyfull')
tinymce.activeEditor.queryCommandState('justifyfull')
Expected result: queryCommandState would return true

Actual result: false is returned.

left, center, and right all work as expected

**Comment by rafdulaf** [comment] 2018-05-03 14:33
Upon my investigations this is due in the FormatRegistry that it is registered for "alignjustify" but requested at "alignfull"

**Comment by lnewson** [comment] 2020-05-05 00:27
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.13. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-05 00:27 UTC
Labels: status: escalated, status: verified, type: bug
