### ISSUE TITLE
Since upgrading, custom plugin insert of iframe is messed with..

### ISSUE THREAD

**Issue by CaMer0n** [tinymce/tinymce#2777] opened 2016-03-11 21:48 UTC
A custom plugin which inserts a (bootstrap) wrapped iframe,  no longer functions correctly after upgrading from **within** version 4. Do I need to modify the command or configuration, or is this a bug? This custom plugin also relates to this request: https://github.com/tinymce/tinymce/issues/2711

Thanks. 

### Command Used: 
`top.tinymce.activeEditor.execCommand('mceInsertRawHTML',false,html);`

### Value of 'html' used above:
`<div class="embed-responsive embed-responsive-16by9 "><iframe width="560" height="315" style="background-size: 100%; background-image: url('http://i1.ytimg.com/vi/dKrVegVI0Us/mqdefault.jpg'); border: 0px;" class="embed-responsive-item" src="//www.youtube.com/embed/dKrVegVI0Us" allowfullscreen="allowfullscreen"></iframe></div>`

### Editor DOM Result: 
`<div class="embed-responsive embed-responsive-16by9 "><span style="background-size: 100%;background-image: url(http://i1.ytimg.com/vi/dKrVegVI0Us/mqdefault.jpg);border:0px" data-mce-object="iframe" class="mce-preview-object mce-object-iframe" data-mce-p-allowfullscreen="allowfullscreen" data-mce-p-src="//www.youtube.com/embed/dKrVegVI0Us" data-mce-p-class="embed-responsive-item" contenteditable="false"><iframe src="//www.youtube.com/embed/dKrVegVI0Us?" allowfullscreen="allowfullscreen" width="560" frameborder="0" height="315"></iframe><span class="mce-shim"></span></span></div>`

### Expected Editor DOM Result: 
`<div class="embed-responsive embed-responsive-16by9 "><iframe width="560" height="315" style="background-size: 100%; background-image: url('http://i1.ytimg.com/vi/dKrVegVI0Us/mqdefault.jpg'); border: 0px;" class="embed-responsive-item" src="//www.youtube.com/embed/dKrVegVI0Us" allowfullscreen="allowfullscreen"></iframe></div>`

**Comment by spocke** [comment] 2016-03-14 08:10
You can avoid this by disabling:
https://www.tinymce.com/docs/plugins/media/#media_live_embeds

The output content is exactly the same as input it's just within the editor it becomes wrapped in a span to handle contentEditable=false and live previews.

**Comment by spocke** [comment] 2016-03-14 08:10
Closing since this is by design.

**Closed by spocke** 2016-03-14 08:10 UTC

**Comment by CaMer0n** [comment] 2016-03-14 17:42
@spocke Thank you. :+1:

**Comment by herrvigg** [comment] 2017-09-14 21:52
Hello,
i just found this post and i had the same issue, with a video wrapper (div) above the iframe. I tried to disable the live preview but instead i got a huge blue block which was not much better. But after struggling a bit i finally found a solution to get both the live preview AND the video wrapper!

I don't know exactly what your embed-responsive class does here with the CSS, but i suppose it does stuff like `position: absolute` for managing the size of the iframe. But this is then messed up with the tiny-mce preview inserted between them. My idea is simply to undo the conflicting style by passing some CSS to tinyMCE affecting the `mce-preview-object-iframe`. For instance:
```
.embed-responsive .mce-preview-object-iframe {
  position: unset;
}
```
This CSS can be sent through a file to be loaded by tiny-MCE through the `content_css` attribute on init. You might also have to handle the version for potential cache problems. 

It might sound a bit complicated but i'm very happy now with this solution - all live and under control in edit mode!
Hope it helps.
