### ISSUE TITLE
Return duplicates empty divs

### ISSUE THREAD

**Issue by blairzotron** [tinymce/tinymce#5504] opened 2020-03-13 13:50 UTC
When you have content wrapped in a `<div>`, instead of `<p>`, hitting the Enter Key causes TinyMCE to create a new `<div>` with the same style and classes.

If you start with this example:
`<div class="example">`_Sample text, put cursor here and hit enter..._ **this part of sentence is moved to a new div**`</div>`

And hit the Enter Key in that sentence you get:
`<div class="example" style="padding: 20px;">`_Sample text, put cursor here and hit enter..._ `</div>`
`<div class="example" style="padding: 20px;">`**this part of sentence is moved to a new div**`</div>`

**Comment by lostkeys** [comment] 2020-03-16 09:46
This is expected. The content has to have some wrapper and you're basically substituting `<p>` for `div`. In what way are you using TinyMCE that this becomes a problem?

**Comment by lnewson** [comment] 2020-03-16 09:56
It's worth noting there is the [`keep_styles`](https://www.tiny.cloud/docs/configure/content-filtering/#keep_styles) setting which can partly control this behaviour. However that setting is for handling creating blank new lines, not when breaking up a paragraph.

**Comment by blairzotron** [comment] 2020-03-16 16:27
Thanks for your response.

I use divs for organizing content into blocks that are responsive/mobile-friendly. I realize now that if I put a `<p>` inside the `<div>`, it duplicates the `<p>`, which is fine, however, the only way that I seem to be able to get a `<p>` inside the `<div>` is by viewing the source code and manually inserting it... in other words, using the _Format > Format > Blocks_ menu simply changes my `<div>` to a `<p>` instead of letting me have `<div><p>content</p></div>`

Ultimately, I wish there was a setting like:

- _Enter key should insert a `<br>` when inside a `<div>` instead of duplicating the `<div>`_ 
- ".myExampleClass always needs to have a `<p>` inside it"

![TinyMCE-Div-P-Issue](https://user-images.githubusercontent.com/5322175/76778643-f01f0780-6788-11ea-8d28-287b09236b5e.gif)

**Comment by lostkeys** [comment] 2020-03-17 15:44
Nested elements in this way is unfortunately not possible to do in TinyMCE in a reliable way. It is on our radar but it wont be addressed in the immediate future. There is a lot of use cases we need to consider to design a flexible and usable api for this kind of block behavior. 

At this time I can only recommend you to use inline mode and create your own "block creation" functionality outside of TinyMCE. You would build a function that inserts a block and accomanying functions for move it around and delete it. Inside each block you would have an TinyMCE inline instance which would take care of the text editing inside each block.

I'll tag this as a feature request and as have it as a use case.

**Comment by blairzotron** [comment] 2020-03-23 14:27
Is it currently possible to **always** use a `<p>` instead of duplicating the current block element?
E.g. `<div class="example"> Existing content... hit [ENTER]</div>`
 _becomes_  
`<div class="example">Existing content... <p>&nbsp;</p></div>`

**Comment by lostkeys** [comment] 2020-03-23 14:30
I'm not sure I follow, sorry...

**Comment by blairzotron** [comment] 2020-03-23 14:49
In TinyMCE 3 you could use `force_p_newlines : true;`   What is this now?

The real issue I'm having is that hitting enter duplicates the current block element including its class. 
E.g. `<div class="example"> Existing content... [hit ENTER]</div>` **becomes** 
`<div class="example"> Existing content...</div><div class="example">&nbsp;</div>`

I can't tell all of my users to select the new div, go to formats, Clear Formatting and change the Div to a P whenever they hit enter.

**Comment by blairzotron** [comment] 2020-04-09 15:32
I have solved the newline issue, by adding an _enter-key_ handler in **editor.setup** (doesn't work if implemented anywhere else):
```
editor.on("keydown", function(e){
    if( e.which=="13" || e.keyCode=="13" ){
         editor.insertContent("<br> ");  //put a space at the end to reposition cursor
         e.preventDefault();
   }
});
```
There really should be an option like _**"always use `<p>` or `<br>`"**_ when they hit enter? It seems like an obvious option to have, especially, given that it was part of 3.x and 4.x, namely:  **_"forced_root_block: p"_** and **_"force_p_newlines: true"_**.   Why was this removed and replaced with **_"br_in_pre"_** which is far less common... who uses `<pre>` anyway? https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#br_in_pre  

**BUG:** The "end_container_on_empty_block" option does not work with nested divs; it skips the immediate block-wrapper and completely removes it's parent block element. 
https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#end_container_on_empty_block

**Comment by jacoping** [comment] 2020-05-06 14:11
I also have a problem with this. What I don't understand is why other block elements like headings do not behave like this. If i hit RETURN at the end of an `h1 ` I get a new empty `p`. If I hit RETURN at the end of a `div` I get a new empty `div`.
Allright it's expected and not a bug, but is it possibile to change this behavior?
https://codepen.io/jacoping/pen/QWjQNxZ

**Comment by blairzotron** [comment] 2020-05-06 16:06
Add the bolded code below to fix your issue; this is the only way I know 
to change the "default behavior" (there really should be an option to do 
this, like there used to be in 3.x, namely, "force_br_newlines 
<https://www.tiny.cloud/docs-3x/reference/configuration/Configuration3x@force_br_newlines/>: 
true")

tinymce.init({
   selector: 'textarea#format-custom',
   height: 500,
   plugins: 'table wordcount code',
   content_css: '//www.tiny.cloud/css/codepen.min.css',
   menubar: false,
   toolbar1: 'code styleselect',
   visualblocks_default_state: true,
   content_style: 'h1 {background-color: #cce} div {background-color: 
#ecc; border: 1px solid black};',
   formats: {
   },
   style_formats: [
     { title: 'H1', block: 'h1' },
     { title: 'DIV', block: 'div' },
   ],
*  setup: function(editor){**
**            //ENTER KEY HANDLER**
**            editor.on("keydown", function(e){**
****
**                //TURN ENTERY KEY INTO <br>**
**                if( e.which=="13" || e.keyCode=="13" ){**
**                    editor.insertContent("<br> ");**
**                    e.preventDefault();**
**                }**
**          });**
**    }*
});

**Comment by jacoping** [comment] 2020-05-11 09:43
Thank you @blairzotron!

**Comment by mariojsnunes** [comment] 2020-07-08 17:17
Thank you so much @blairzotron !
I wanted to add a div on iframes, to make them responsive with this css trick https://blog.theodo.com/2018/01/responsive-iframes-css-trick/
Was facing the same issue as mentioned.
Your workaround saved me!

Still, I would like to reinforce to the team that a definite solution would be great.

**Closed** 2024-06-15 00:40 UTC
Labels: type: feature
