### ISSUE TITLE
Alternatives Source option in Insert/Edit video popup is not working fine

### ISSUE THREAD

**Issue by Ishanjn** [tinymce/tinymce#2633] opened 2016-01-16 07:39 UTC
First of all, I doesn't found any documentation regarding "Alternative Source" and "Poster" option. As far as i understand it's a way to define secondary video link if Source link is not working (I am not sure, its only my understanding).
So, Can you please notify me, use of these options?

I want to point-out an issue with "Alternatives Source", "Poster" options, when i put any link (video link) into text-box for these option and submit. And reopen Insert/Edit video popup both option showing empty. Means my previously inserted link not exist into text-box.
![tinymcepopupoption](https://cloud.githubusercontent.com/assets/16400078/12371160/f7868022-bc4f-11e5-953b-bd5e9e22d33d.png)

**Comment by spocke** [comment] 2016-01-18 07:26
Youtube doesn't support poster nor alt source since it's an iframe not a video element. So closing this one since it's by design.

**Closed by spocke** 2016-01-18 07:26 UTC

**Comment by mrdnote** [comment] 2017-12-05 05:40
It's not working for mp4 video's on an own server either. The alternative source is just not inserted into the html.
