### ISSUE TITLE
Inability to edit content of element within element

### ISSUE THREAD

**Issue by davidearl** [tinymce/tinymce#3516] opened 2017-02-27 14:00 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have implemented a menu added to tinymce which inserts canned bits of HTML, the idea being that a non-HTML person can add more complex and customized elements than basic tinymce editing supports. For example, they might have "button" on the menu which inserts a link that looks like a button, in their house colours, with the words "change me" to change for what they want the button to say. See example http://codepen.io/anon/pen/RKzOPg 

If you put the cursor after 'change me' (which is where it is by default) and type, the new characters appear after and outside the link but in the inserted paragraph. Similarly if you put the cursor before the 'c', the new text appears before and outside the link but inside the inserted paragraph. If you select all of 'change me', and then type (i.e. to replace that text), the link gets removed completely and you're just left with unlinked text that you typed. If you backspace over "change me" it removes the 8 characters 'e', 'm' etc, but if you backspace over the remaining 'c' it removes the link altogether. These are all despite the bar below the editor showing "p » a" suggesting to me (though meaningless to a non-HTML-savvy user) that the cursor is positioned inside the anchor element.

It appears that the only way to replace the placeholder text is to reposition the cursor somewhere in the middle of "change me", say after the "c", type the new text, then delete forwards to remove "hange me" and then move to the start delete the "c" (either after and backspace or before and delete). It also seems inconsistent with how <strong> elements work, in that if you put the cursor at the end of bold text and type, the new characters are inside the <strong>.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.

http://codepen.io/anon/pen/RKzOPg 

**What is the expected behavior?**

It should be possible to replace or remove the text by backspacing over it, or selecting it all and re-typing it.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

4.5.2 (though I think it is probably in any v4, don't know about earlier).

**Comment by lnewson** [comment] 2020-05-09 10:42
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 10:42 UTC
