### ISSUE TITLE
Regression: bold/italic/underline does not work with ctrl+a selection in IE

### ISSUE THREAD

**Issue by thiagolacerda** [tinymce/tinymce#3983] opened 2017-10-05 17:25 UTC
User can't untoggle bold/italic/underline when formatting is applied after selecting all text with ctrl+a.

Steps to repro:
1. open http://fiddle.tinymce.com/Abgaab
2. select all content of the editor using ctrl+a
3. press bold (or italic or underline)
4. leaving the text selected, press the same button again to untoggle the format

Expected:
Text should revert its format back
Actual
Text format does not change

This seems to only affect IE and I can confirm that was introduced in v4.6.6

**Comment by lnewson** [comment] 2020-05-03 23:22
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the fiddle provided. I was able to reproduce it in TinyMCE 4.6.6 though, so it's likely the issue has been fixed since this was originally reported. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-03 23:22 UTC
Labels: browser: ie, status: escalated, status: verified, type: bug
