### ISSUE TITLE
Media Plugin

### ISSUE THREAD

**Issue by neotropic2023** [tinymce/tinymce#3052] opened 2016-07-07 22:28 UTC
This is the first time I am attempting to use the Media plugin. 
Everything runs fine until I save the document, then it gets convert into:

img data-mce-p-poster="https://www.pets4you.com/pages/souths-shepherds/images/video-poster.jpg" data-mce-p-controls="controls" data-mce-html="_%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Csource%20src%3D%22https%3A//www.pets4you.com/pages/souths-shepherds/images/Video.mp4%22%20type%3D%22video/mp4%22%20/%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%3Csource%20src%3D%22https%3A//www.pets4you.com/pages/souths-shepherds/images/Video.ogg%22%20type%3D%22video/ogg%22%20/%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20_" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-mce-object="video" class="mce-object mce-object-video" height="320" width="568"

it is supposed to be 

```
<video width="570" height="320" controls="controls">
<source src="https://www.pets4you.com/pages/souths-shepherds/images/Video.mp4" type="video/mp4" />
<source src="https://www.pets4you.com/pages/souths-shepherds/images/Video.ogg" type="video/ogg" />
</video>
```

Why is that?

Version 4.3.11
Will check out 4.4.0 (Does it in both)

**Comment by neotropic2023** [comment] 2016-07-07 22:53
Made myself a work around to replace that _whatever_ code with what it is supposed to be. 
But this should not save like that after editing.

**Comment by woshihoujinxin** [comment] 2016-07-13 16:04
I also have the same question, this is my embed code:
`<embed height="415" width="544" quality="high" allowfullscreen="true" type="application/x-shockwave-flash" src="http://static.hdslb.com/miniloader.swf" flashvars="aid=2510951&page=1" pluginspage="http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash"></embed>`,
but after I put it into the textarea and save it, when I open to edit the emebed code, it changed like this `<embed src="http://static.hdslb.com/miniloader.swf" type="application/x-shockwave-flash" width="544" height="415" />`
I don't know how to fix it.

**Comment by cantuket** [comment] 2018-01-14 23:04
@neotropic2023 Can you show us how you did this? I've now spent 7hrs trying to disable converting images to base64 data. Insanely frustrating!!!!!

Also none of these options work for me...
```
media_live_embeds: true,
media_poster: false,
```

**Comment by Cryde** [comment] 2018-12-18 08:22
@cantuket I have the same issue.

**Comment by jycoldhands** [comment] 2019-12-25 02:03
@cantuket 
To this day, the media_live_embeds attribute still has no effect.
I feel quite depressed.

**Comment by lnewson** [comment] 2020-04-26 11:22
I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5540 as TinyMCE currently only supports live embeds for iframe based embeds, such as those used by Youtube. So when a live embed isn't supported, TinyMCE will render a placeholder instead while editing the content. This should be replaced with the original embed when getting the content out of the editor, but if that isn't working please do let us know.

**Closed by lnewson** 2020-04-26 11:22 UTC
Labels: plugin: media, type: bug
