### ISSUE TITLE
Tinymce removing elements

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2206] opened 2015-05-03 13:22 UTC
Hi,
I dont know if this is a bug but certainly causes me a lot of problems. Suppose you have the HTML codes below in your tinymce with default configuration:
OPTION 1)
&ltg;div style="background:#FF0000;">HI&ltg;/div>
OPTION 2)
&ltg;div style="background:#FF0000; float:left;">HI&ltg;/div>

In the first case, when I select the word HI, hit the BACKSPACE key and type a new text everything will work fine, I mean, the element with background "#FF0000" will be kept, as expected.
In the second case, if I select the word HI, hit the BACKSPACE key and type a new text the element with background "#FF0000" will disappear.
This is not an expected result cause in both cases I would like the element to be kept. The "bug" can also be reproduced if you click right on the right of the letter I and press 2 times BACKSPACE.
Can I expect this to be solved in future versions or is there any fix to that which I can try here?
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7493](http://archive.tinymce.com/develop/bugtracker_view.php?id=7493) posted by [gilperon](http://archive.tinymce.com/profile.php?name=gilperon)_

> _**Tags:** [firefox msie safari chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by nicoladj77** [comment] 2016-01-18 23:19
This is a duplicate of #2510 and should be closed

**Comment by blackcathikari** [comment] 2016-07-25 01:55
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 01:55 UTC
Labels: browser: chrome, browser: firefox, browser: ie, browser: safari, origin: tinymce.com, type: bug
