### ISSUE TITLE
[I18N] Some translations are missing for spellchecker plugin

### ISSUE THREAD

**Issue by OlivierJaquemet** [tinymce/tinymce#3893] opened 2017-08-29 09:31 UTC
Some I18N strings of the spellchecker plugin are not translated at all.

**To reproduce** : 
- Configure any version of TinyMCE (for example the edge on this day) : 
    - to use any language but the default english version
    - with the spellchecker plugin properly configured, 
    - with the spellchecker button in the toolbar
- Access the editor which must not contain any text spelling error (and empty text is fine)
- Click the Spellcheck button

**BUG** : message "No misspellings found." is displayed, and not translated
**Expected** : message should be translated in the current language selected

**Explanation** : 
Some strings of the spellcherk plugin are NOT in the I18N resource provided :
https://www.transifex.com/moxiecode/tinymce/plugin-spellchecker/

**Comment by OlivierJaquemet** [comment] 2018-01-17 15:57
@spocke Is there's any chance you could upload an updated english resource file from the spellchecker plugin, so the community (me included) could translate the missing messages ?

**Comment by lnewson** [comment] 2020-05-09 08:56
I'm closing this as a duplicate of https://github.com/tinymce/tinymce/issues/3178. This is still missing in transifex though, but we'll be uploading it as part of TinyMCE 5.3 so it should be available to be translated within a couple weeks.

**Closed by lnewson** 2020-05-09 08:56 UTC
Labels: component: i18n, status: escalated
