### ISSUE TITLE
Error on iPhone Safari

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2386] opened 2015-09-03 18:06 UTC
The error I'm getting is:
TypeError: undefined is not an object (evaluating 'a.createRange')

The only code I have is:
tinyMCE.remove();
tinymce.init({
selector:       'textarea#'+textareaId,
...

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7680](http://archive.tinymce.com/develop/bugtracker_view.php?id=7680) posted by [shakedal](http://archive.tinymce.com/profile.php?name=shakedal)_
> 
> _**Tags:** [safari safari6]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by joe-hache** [comment] 2016-03-24 08:42
Having the same error in both iPhone and iPad

Under iPad, although the editor has been removed, this bug occurs in the same time : https://github.com/tinymce/tinymce/issues/2699

**Comment by FabriceGaudin** [comment] 2016-06-09 11:01
Same error on iPad Safari

**Comment by fyrkant** [comment] 2017-05-26 12:53
I am closing this issue due to old age. 

If you still have this issue in the latest version of TinyMCE please [open up a new issue](https://github.com/tinymce/tinymce/issues/new) or leave a comment here.

**Closed by fyrkant** 2017-05-26 12:53 UTC
Labels: browser: safari, browser: safari (iOS), origin: tinymce.com, type: bug

**Comment by FabriceGaudin** [comment] 2017-05-30 14:07
FYI, I can't reproduce it on iPad Safari
