### ISSUE TITLE
TinyMCE 5: file_browser_callback error

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4791] opened 2019-01-23 20:19 UTC
See http://fiddle.tinymce.com/3Agaab

It works with nightly, but not TinyMCE 5. There's no file browser icon in Image dialog. There's also an error in console.

**Comment by lnewson** [comment] 2019-01-23 21:52
The file_browser_callback was deprecated in v4 and removed in v5. The file_picker_callback is the replacement setting for this functionality. Anyways, this is a duplicate of #4773 so closing this.

**Closed by lnewson** 2019-01-23 21:52 UTC

**Comment by alecpl** [comment] 2019-01-24 06:01
I see. It's been added in 4.1.0. However, I couldn't find a word in documentation about removal. The option is still in doc for v5.

**Comment by TheSpyder** [comment] 2019-01-24 06:08
The docs for v5 are still in progress, they've been updated to remove that setting but not published yet.

I freely admit it was not very _well_ deprecated, but it definitely was.
https://www.tiny.cloud/docs/configure/file-image-upload/#file_picker_callback
https://github.com/tinymce/tinymce/blob/82be0c338ed8f43f250044113fb666ecaf930fe5/changelog.txt#L1019
