### ISSUE TITLE
Cannot read properties of null (reading 'getStart') on Delete 

### ISSUE THREAD

**Issue by kevinfr06** [tinymce/tinymce#7552] opened 2022-01-24 16:37 UTC
Repro step :
1. Select all text in editor (CTRL + A) (same problem occurs when selecting all text with mouse or keyboard)
2. Press Delete Or Suppr key

Result : The editor control disappears and the following error occurs : 
plugin.min.js:4 Uncaught TypeError: Cannot read properties of null (reading 'getStart')
    at X (plugin.min.js:4:6931)
    at _x.<anonymous> (plugin.min.js:4:15110)
    at rx.fire (tinymce.min.js:4:357993)
    at _x.fire (tinymce.min.js:4:361357)
    at ax (tinymce.min.js:4:360131)
    at Object.e (tinymce.min.js:4:360583)
    at ui.executeHandlers (tinymce.min.js:4:59391)
    at HTMLBodyElement.o (tinymce.min.js:4:56525)

I use tinymce-angular 5.0.1, with chrome on Windows 10 and angular 13.0.2.
I had the same problem with version 4 of tinymce.

Regards,

Kevin

**Comment by hamza0867** [comment] 2022-04-27 09:22
Hello @kevinfr06 

I was not able to reproduce the issue. Can you please provide a fiddle reproducing the issue ?

Thanks

**Comment by lnewson** [comment] 2022-06-05 23:24
As there's been no update on this for some time I'm going to close it. If the requested information above can be provided we'll be happy to reopen this issue.

**Closed by lnewson** 2022-06-05 23:24 UTC
Labels: needs: more info
