### ISSUE TITLE
Sometimes whitespace removed before link insertion

### ISSUE THREAD

**Issue by Koc** [tinymce/tinymce#2743] opened 2016-02-29 15:00 UTC
#2595 still occurs in 4.3.4 using mozilla firefox 43. Video with bug https://www.youtube.com/watch?v=lfBHjiglp3s&feature=youtu.be&hd=1

**Comment by spocke** [comment] 2016-02-29 16:06
I can't reproduce it here:
http://fiddle.tinymce.com/1qfaab

I double clicked on a word like "aaaa" and made a link without any removal of whitespace.

**Comment by fyrkant** [comment] 2018-03-22 14:16
No answer on how to reproduce so I'm closing this, if you still have the problem open up a new issue with a clear reproduction.

**Closed by fyrkant** 2018-03-22 14:16 UTC
Labels: browser: firefox, needs: more info, plugin: link, type: bug
