### ISSUE TITLE
The Bullet and Numbered list are not aligned correctly with the contained text

### ISSUE THREAD

**Issue by amlsoft** [tinymce/tinymce#8961] opened 2023-08-04 12:06 UTC
**The Bullet and Numbered list are not aligned correctly**
 1. Add a bullet list and numbered list in the editor
 2. Change the alignment for both the bullet and numbered list (centre align and right align)
 3. Observe only the text is aligned correctly but not the bullets and numbers

**Comment by TheSpyder** [comment] 2023-08-07 00:14
Try searching next time.

Duplicate of #8441

**Closed by TheSpyder** 2023-08-07 00:14 UTC
