### ISSUE TITLE
Pass original filename to images_upload_handler: TinyMCE

### ISSUE THREAD

**Issue by alexkasina** [tinymce/tinymce#3652] opened 2017-05-16 11:10 UTC
I have this in set up,

    tinymce.init({
    selector: "textarea",
    automatic_uploads: true,
    images_reuse_filename: true,
   
    images_upload_handler: function (blobInfo, success, failure) {
    var xhr, formData;
    xhr = new XMLHttpRequest();
    xhr.withCredentials = false;
    xhr.open('POST', '/cloud/tinymce/');

    xhr.onload = function() {
      var json;

      if (xhr.status != 200) {
        failure('HTTP Error: ' + xhr.status);
        return;
      }

      json = JSON.parse(xhr.responseText);

      if (!json || typeof json.location != 'string') {
        failure('Invalid JSON: ' + xhr.responseText);
        return;
      }

      success(json.location);
    };

    formData = new FormData();
    formData.append('file', blobInfo.blob(), blobInfo.filename());

    xhr.send(formData);
    },
    });

When I upload an image, with name like `cauliflower_chorizo.png`, its renamed to `blobid0.jpg` `https://s3-us-west-1.amazonaws.com/happyherbivoretest/2017/05/blobid0.jpg`. 
Is there a way to upload the image with it's original name `cauliflower_chorizo.png`?

**Comment by Afraithe** [comment] 2017-05-16 13:02
What version of TinyMCE are you running?

**Comment by alexkasina** [comment] 2017-05-16 13:08
V4 [here is the file image upload docs](https://www.tinymce.com/docs/configure/file-image-upload/)

**Comment by Afraithe** [comment] 2017-05-16 13:12
V4 tells us nothing, is it CDN/Cloud/SDK version? What 4.5.3? 4.1? 4.6? 4.6.1?

**Comment by alexkasina** [comment] 2017-05-16 13:15
@Afraithe  Version: 4.6.1-57  https://cloud.tinymce.com/stable/tinymce.min.js

**Comment by jayarjo** [comment] 2017-05-16 13:43
@alexkasina, ff you log `blobInfo.filename()` you will see that it is original filename. It is not clear from the code excerpt what do you do to that image though.

How does it end up on Amazon S3?

**Comment by alexkasina** [comment] 2017-05-16 14:00
@jayarjo I am using django backend. I get the file in the post request and save it to s3. The file name comes with a different name such as `blobid1.png`, I have logged `blobInfo.filename()` and after editing the image it shows me the name is `imagetools0.png`, [Check](http://www.awesomescreenshot.com/image/2500225/d2ed1cb4cb3c0268c4ea2b1470fc4efe)

**Comment by jayarjo** [comment] 2017-05-16 16:46
I can't reproduce it locally. Can you put the demo of this issue on some publicly accessible host?

**Comment by alexkasina** [comment] 2017-05-16 19:00
@jayarjo  http://57a3a468.ngrok.io/admin/article/post/add/  Login as u/n: admin, p/w: admin  then drag drop and edit an image.

**Comment by jayarjo** [comment] 2017-05-17 09:22
Was it temporal? Doesn't seem to be available at the moment.

**Comment by jayarjo** [comment] 2017-05-17 09:37
But since you mention drag and drop now (apparently from the desktop?), filename in such case is auto-generated by Paste plugin (I assume that you have it enabled, although you didn't mention it in your code excerpt). 

I will mark this as feature request.

For now you could try [file-picking approach](https://www.tinymce.com/docs/configure/file-image-upload/#file_picker_callback), instead of drag and dropping.

**Comment by alexkasina** [comment] 2017-05-17 10:45
@jayarjo @Afraithe  Ok, thanks, I will result into renaming the files into unique names before upload as suggested [here](https://www.tinymce.com/docs/get-started/upload-images/#imageuploaderrequirements), but this will mean every edit is uploaded as a new file. If the files had their filenames it would have been better since after editing, the edited file is sent to the server with the same name and replace the initial file hence avoid duplicates.

On the same, after drag and drop, the image is not getting uploaded yet I have `automatic_uploads=true`, 
check here  http://57a3a468.ngrok.io/admin/article/post/add/ 
Login as u/n: admin, p/w: admin 
drag drop you'll see it doesn't fire but after editing an image, it does.
View source to see my `tinymce.init.js` settings.

**Comment by jayarjo** [comment] 2017-05-20 18:10
We've scheduled the fix for this, so it should make it to the next release.

**Comment by spocke** [comment] 2017-05-23 13:13
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2017-05-23 13:13 UTC
Labels: resolution: fixed in coming release, type: feature

**Comment by jayarjo** [comment] 2017-06-06 10:07
Related: https://github.com/tinymce/tinymce/issues/2918

**Comment by trungtruc056** [comment] 2021-06-03 08:14
Hi @spocke, I'm using TinyMCE version 5.3.2 and I have the same issue with @alexkasina , it's not fixed yet. Please check it. Thank you!

**Comment by sbridgett** [comment] 2023-04-11 10:36
> But since you mention drag and drop now (apparently from the desktop?), filename in such case is auto-generated by Paste plugin (I assume that you have it enabled, although you didn't mention it in your code excerpt).

Yes, I think the cause is the powerpaste plugin in Tiny version 6:

**When I include 'powerpaste' in the editors plugins list:**
 
When I drag a file called "_original_filename.png_" onto the editor, the 'blobInfo' parameter passed into my '_images_upload_handler_' has filename() of "_blobid0.png_" and the '_blobInfo.blob()_' is a "**Blob**" object containing only the size and MIME type:

**In my 'images_upload_handler'**
```
tinymce.get('tiny_editor').hasPlugin('powerpaste',true): true

blobInfo.filename(): blobid0.png    blobInfo.blob(): Blob {size: 80550, type: 'image/png'}   typeof(blobInfo.blob()): object   blobInfo.blobUri(): blob:http://127.0.0.1:8000/a110f3e5-7687-4e88-92f2-08d40fef0b2f
```

**On server:  'tiny_editor_image_upload'**
The filename uploaded to my '_tiny_editor_image_upload_' function on webserver is"_blobid0.png_":
```
request.FILES:  <MultiValueDict: {'file': [<InMemoryUploadedFile: blobid0.png (image/png)>]}>
request.FILES['file']:  blobid0.png
```



**Whereas without the 'powerpaste' plugin:**
The blobInfo.filename() is "_mceclip0.png_", but the '_blobInfo.blob()_' is a **File** object containing the _original filename_, _lastModified_ date, size, etc: 

```
tinymce.get('tiny_editor').hasPlugin('powerpaste',true): false

blobInfo.filename(): mceclip0.png    blobInfo.blob(): File {name: 'original_filename.png', lastModified: 1681113074000, lastModifiedDate: Mon Apr 10 2023 08:51:14 GMT+0100 (British Summer Time), webkitRelativePath: '', size: 80550, …}   typeof(blobInfo.blob()): object   blobInfo.blobUri(): blob:http://127.0.0.1:8000/ad0699dc-08e8-48eb-a85b-5951a6c795fa
```

**On server:  'tiny_editor_image_upload'**
```
request.FILES= <MultiValueDict: {'file': [<InMemoryUploadedFile: original_filename.png (image/png)>]}>
request.FILES['file']= original_filename.png
```

**Comment by TheSpyder** [comment] 2023-04-13 06:57
@sbridgett for premium plugin issues please [log a support case](https://support.tiny.cloud/hc/en-us/requests/new) and we will look into that for you.

**Comment by mikkorantalainen** [comment] 2024-03-13 19:13
@spocke Could you re-open this issue? The latest code still loses the filename before images_upload_handler is called. You can try this with the official "image" plugin.
