### ISSUE TITLE
global$7 is not a constructor

### ISSUE THREAD

**Issue by adminbmbc** [tinymce/tinymce#5417] opened 2020-02-20 15:12 UTC
Tinymce is rendering an error when an iframe is used. Uncaught (in promise) TypeError: global$7 is not a constructor. Any hint please?

**Comment by lnewson** [comment] 2020-02-20 21:14
@adminbmbc I'm afraid this isn't enough to go on, so we're unable to assist here. Please include some more information about how to reproduce the issue, such as:
- a [TinyMCE fiddle](http://fiddle.tinymce.com)
- a stack trace
- what OS/browser you're using

Another thing to check, is that if you're self hosting that you aren't experiencing a caching issue, so try to see if you can reproduce the issue in a private/incognito window. If you are experiencing a caching issue, then make sure you configure your servers caching rules appropriately or consider adding a cache busting strategy such as adding a (`cache_suffix`](https://www.tiny.cloud/docs/configure/integration-and-setup/#cache_suffix).

**Comment by lnewson** [comment] 2020-04-24 12:12
Closing due to a lack of additional information. If the above details can be provided we'll be happy to reopen this and investigate further.

**Closed by lnewson** 2020-04-24 12:12 UTC
Labels: needs: more info
