### ISSUE TITLE
Table plugin does not work correctly in jquery ui modal

### ISSUE THREAD

**Issue by csharperperson** [tinymce/tinymce#4878] opened 2019-03-05 13:02 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Table plugin behavior is not normal when using any modal (bootstrap or jqueryui). When selecting a size, the cells do not highlight correctly to show what you are selecting. You can still select a table size, and it will be that size, but it doesn't highlight correctly. Also, when using the table quick controls inside the editor, it throws an error of **Node cannot be null or undefined**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
[Demo](http://fiddle.tinymce.com/1Dgaab)

**What is the expected behavior?**
Expected behavior should be the same as when the table plugin is being used in the [full featured example](https://www.tiny.cloud/docs/demo/full-featured/)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested this in all 5.x versions of TinyMCE on Chrome and IE 10+.

**Comment by lnewson** [comment] 2019-03-06 07:06
Thanks for the report! I can reproduce the cell highlighting issue and what's weird is if you open the menu and then focus some other application and then come back it does work.

I was unable to reproduce the error you mentioned though, but it's not clear what you mean by "table quick controls". Would you be able to clarify that? I guessed it was the table context toolbar, but that didn't produce the mentioned errors. In saying that however, the context toolbar buttons didn't appear to be working correctly either (though they did work in 5.0.0, so it seems something has regressed).

**Comment by csharperperson** [comment] 2019-03-06 12:11
Right, it was the table context toolbar. I noticed the error didn't appear either, so it may be a little different than my local project where I originally saw the error, but figured it would still be good to report for the information anyways.

**Comment by lnewson** [comment] 2019-03-13 00:51
@csharperperson while looking at your new issue, I realized I missed something on this and that our docs for integration with JQuery are missing the new class selector for TinyMCE 5, which was interfering with the focus.

Here's an updated example that works for me on Chrome and IE 11: http://fiddle.tinymce.com/1Dgaab/1

**Comment by lnewson** [comment] 2019-03-15 00:42
Closing this one as well, since it seems it was just the docs missing the required selector. However if it's still not working for you after making that change, let us know and we'll reopen and investigate further.

**Closed by lnewson** 2019-03-15 00:42 UTC
Labels: 5.x, plugin: table, type: bug
