### ISSUE TITLE
Clicking Justify selecting all the text

### ISSUE THREAD

**Issue by kaviyarasanaspire** [tinymce/tinymce#3894] opened 2017-08-29 11:18 UTC
Hi,

While clicking justify toolbar button is selecting all the text in the line, can anyone please take a look at it and let me this is working as designed or is there any configuration there.

Issue is reproducible in the tinymce demo site as well.

**Comment by spocke** [comment] 2017-08-29 12:09
Seems to be working in the nightly version so this will be fixed once we make a new release.

**Comment by spocke** [comment] 2017-08-31 09:08
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2017-08-31 09:08 UTC
Labels: component: formatting, resolution: fixed in coming release, status: verified, type: bug
