### ISSUE TITLE
TinyMCE v5.3.1 CSS visibility:hidden on every textarea tag

### ISSUE THREAD

**Issue by arnofly** [tinymce/tinymce#5718] opened 2020-06-01 18:17 UTC
Hi,

TinyMCE v5.3.1 tinymce.min.js file apply "visibility: hidden" style on every textarea tag even if  TinyMCE  is not initialized. After initialization with a right selector (if you want to keep some "standard" textarea tags) the problem still persist.

To temporary fix this bug, just add in your CSS the simple rule below:
``` CSS
textarea {
    visibility: visible !important;
}
```
Thx

**Comment by lnewson** [comment] 2020-06-02 03:28
@arnofly I checked using http://fiddle.tinymce.com/8khaab and there's definitely no TinyMCE CSS or code adding `visibility: hidden` to all textareas. I should note that on init TinyMCE will hide the textarea it replaces by adding the `display: none` style which is expected, otherwise both the editor and textarea would be visible.

Anyways, since this isn't caused by TinyMCE it's likely a bug elsewhere and I also suspect the editor wasn't showing for you due to the configuration issue mentioned in #5719 (as the theme loads the CSS that overrides `visibility: hidden` on the editor div). As such I'm going to close this, but if you can provide a reproduction case using fiddle or similar, then we'll be happy to reopen this.

**Closed by lnewson** 2020-06-02 03:28 UTC
