### ISSUE TITLE
Failed to execute 'querySelectorAll' on 'Element' compatibility SyntaxError

### ISSUE THREAD

**Issue by Edgaraszs** [tinymce/tinymce#9702] opened 2024-06-13 13:48 UTC
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.
1. Set up tinymce https://developer.mozilla.org/en-US/docs/Web/CSS/:not?ref=serpapi#browser_compatibility on these browser versions where `:not` Selector list argument is not supported e.g. Chrome <= 87
2. Type in the text editor, and observe errors in the browser console

### ✔️ Expected result
*What is the expected result of the above steps?*

Not producing SyntaxError `Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element'`

### ❌ Actual result
*What is the actual result of the above steps?*

![image](https://github.com/tinymce/tinymce/assets/55696268/ae2d995a-e001-4f0d-9df4-3764a9ad5e28)

### ❓ Possible solution
*If you have ideas, you can list them here. Otherwise, you can delete this section.*

 Avoid using :not with selectors that involve nested elements (:not(element element))

## 📃 Other details
- Browser: https://developer.mozilla.org/en-US/docs/Web/CSS/:not?ref=serpapi#browser_compatibility
- First affected version: chrome <= 87
- Worked in version: chrome >87

**Comment by TheSpyder** [comment] 2024-06-14 01:40
Duplicate of #9201

As [noted in our documentation](https://www.tiny.cloud/docs/tinymce/latest/support/#supported-web-browsers-table) the oldest version of Chrome we support is extended stable. That was 118 when we added the code that throws the error you see, and as of June 2024 is [`126`](https://chromereleases.googleblog.com/2024/06/stable-channel-update-for-desktop.html).

Sorry.

**Closed by TheSpyder** 2024-06-14 01:40 UTC
