### ISSUE TITLE
Cannot read property 'body' of undefined

### ISSUE THREAD

**Issue by valchanin** [tinymce/tinymce#2722] opened 2016-02-23 13:40 UTC
Sometimes exception occurs in
`getBody: function() { return this.bodyElement || this.getDoc().body; }`

`getDoc` returns undefined.
`getDoc` should return .document for iframe. But sometimes iframe is not created.

iframe is created by the following method:

```
/**
* Initializes the editor this will be called automatically when all plugins/themes and language packs are loaded by the rendered method.
This method will setup the iframe and create the theme and plugin instances.
*
* @method init
*/
init: function() {
```

So I think getBody is called before all plugins are loaded.

**Comment by spocke** [comment] 2016-02-25 12:32
Make sure you properly remove editor instances when you update html.

For example:
tinymce.remove();
myDiv.innerHTML = '<textarea></textarea>';
tinymce.init({selector: 'textarea'});

**Comment by volchanin** [comment] 2016-02-26 12:25
> Make sure you properly remove editor instances when you update html.

It does not help.
I trying to init tinymce for textarea that contains text.

```
tinymce.remove();
tinymce.init(initOptions);
```

but sometimes issue occures.

**Comment by spocke** [comment] 2016-02-26 12:44
Most of the cases I've seen where this is happening is when editors gets clobbered without calling tinymce.remove first. Seems like an implementation issue unless you can provide a way for us to reproduce it at fiddle.tinymce.com or though other means.

**Comment by asiegfried** [comment] 2016-06-29 13:01
I have git cloned the project, made a bower install and open the demo/index.html. I get this error too on chrome/opera and a `this.getDoc(...) is undefined` on firefox.

**Comment by anmarcek** [comment] 2016-07-12 09:56
+1

**Comment by mishabar1** [comment] 2016-07-14 08:22
+1

**Comment by ersandeepranjit** [comment] 2016-08-02 06:03
Same Issue here with 4.4.1 version of Tiny mce  when used on Angular 2 RC 4

**Comment by ivorobkalo** [comment] 2016-08-02 09:35
+1

**Comment by BenRoe** [comment] 2016-08-09 19:35
+1 with Angular 1.5.8 and angular-ui-tinymce 0.0.15 (tinymce-dist 4.3.0)

**Comment by DAbrashin** [comment] 2016-08-10 06:10
+1

**Comment by vovashevchenko** [comment] 2016-08-10 06:15
+1

**Comment by dmitriyK1** [comment] 2016-08-10 06:23
+1

**Comment by spocke** [comment] 2016-08-10 06:49
This seems to be a third party issue where the body is accessed before the editor it initialized. Initialization is done async there seems to be a pull request for it here for modern versions of tiny.
https://github.com/angular-ui/ui-tinymce/pull/280

One could also bind the init event and defer the toggleDisable execution until the body is found.

We can't however fix this on our side since this line would still break if we just return null from the getBody function before it has a iframe or body.

https://github.com/angular-ui/ui-tinymce/blob/master/src/tinymce.js#L49

**Comment by vzinoviev** [comment] 2016-08-10 06:55
+1

**Comment by valenburm** [comment] 2016-08-10 07:01
+1

**Comment by vpalamarchuk** [comment] 2016-08-10 07:06
+1

**Comment by alejandromagnorsky** [comment] 2016-08-15 00:32
+1

**Comment by mfilip** [comment] 2016-08-25 14:20
The solution is simple for the getDoc() == undefined and for error with getBody. You need to modify angular ui directive in way like that:
`function toggleDisable(disabled) {
          if (disabled) {
            ensureInstance();

            if (tinyInstance) {
              tinyInstance.getBody().setAttribute('contenteditable', false);
            }
          } else {
            ensureInstance();
//before was if (tinyInstance && !tinyInstance.settings.readonly) {
            if (tinyInstance && !tinyInstance.settings.readonly && tinyInstance.getDoc()) {
              tinyInstance.getBody().setAttribute('contenteditable', true);
            }
          }
        }`
So when you add additional check for getDoc there error is disapear at least for this was working.

**Comment by e-anka** [comment] 2016-08-28 08:55
@mfilip it works for me, thank you!

**Comment by mfilip** [comment] 2016-09-01 20:41
No problem @e-anka I just debug what is returned by the object ;) and try to make it sure that we have proper data there also if you have problem with ng-disabled you can add little above that code same check and should work.

**Comment by abelski21** [comment] 2016-09-19 17:15
I have the same issue here, not using angularjs though. Sometimes the error appears when tinymce.remove(this.global.tinymce_editor);

I think there's a timing issue after initializing tinymce.

Any updates on this?

**Comment by abelski21** [comment] 2016-09-20 16:08
I'm using tinymce 4.4.1, and I'm seeing this error when calling tinymce.remove(this.global.tinymce_editor). 

Is there an issue when there's a a lot of existing tinymce editors active when creating a new one? Let's say we're initializing another tinymce editor in a different element. Should it matter? I usually encounter the console error "Cannot read property 'body' of undefined" when calling tinymce.remove(this.global.tinymce_editor) after tinymce.init().

**Comment by spocke** [comment] 2016-09-26 07:06
It's usually when editors gets clobbered by something else we loose the reference to the iframe and the document. So make sure you call remove before the DOM where the editor lives gets updated or deleted.

**Comment by abelski21** [comment] 2016-09-27 17:20
Yes, I'm currently doing that in my code but unfortunately I'm getting this error when calling tinymce.remove(). I'm always having this error saying "Uncaught TypeError: Cannot read property 'body' of null", pointing to the getBody(). Is there a way to get rid of this error?

**Comment by jaunic** [comment] 2016-11-29 11:07
+1

Adding a delay of a few hundred ms via setTimeout allows it to work but is obviously not a stable or acceptable longterm solution. It also outlines that my actual usage of the tinymce is correct (and not a result of editors not being correctly removed or similar) - Using a callback is a potential solution for first time setting but would require me to rearchitect the knockout app setting it. This wasn't an issue in tinymce 3.x

**Comment by PandaWood** [comment] 2017-09-29 07:11
@jaunic Thanks I can't reproduce this issue myself but we have 34 users getting it, 85 times, in the last 2 months. We just new-up the editor, render() and setContent(content)
The setContent method is already delayed via setTimeout waiting for 500ms, and still the error persists.
Something to do with slow machines I suspect.

**Comment by fyrkant** [comment] 2018-03-29 11:49
Is anyone still having this problem?

**Comment by Afraithe** [comment] 2018-05-08 00:49
There is an official Angular wrapper project now (tinymce-angular). Closing this ticket, any Angular related issues should be open in that project.

**Closed by Afraithe** 2018-05-08 00:49 UTC
Labels: component: integration, needs: fix by 3rd party, status: verified, type: bug

**Comment by PandaWood** [comment] 2018-05-08 00:54
@Afraithe probably fair, though I'm not using Angular - is there an assumption that everyone here is using Angular?
