### ISSUE TITLE
Page not responding when TinyMCE enabled

### ISSUE THREAD

**Issue by Rodion7777** [tinymce/tinymce#2773] opened 2016-03-11 11:07 UTC
steps:
1  add  text below as raw to TinyMCE editor (html tab)

<p>
    <strong style="color: rgb(0, 0, 0); font-family: verdana, arial, helvetica; font-size: 15px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; tex

2 change TinyMCE mode to UI editor (Result tab)

3  wait

example: [http://fiddle.tinymce.com/6rfaab/1](http://fiddle.tinymce.com/6rfaab/1)

browser: Crome 48.0.2564.116 (64-bit)

**Comment by spocke** [comment] 2016-03-11 13:25
Yes, the regexp html parser we use goes nuts if the HTML isn't HTML.

**Comment by blackcathikari** [comment] 2016-07-31 23:10
I believe this is a duplicate of #2186. Could you please take a look and let us know if not? Thanks,
Millie @ TinyMCE

**Comment by Rodion7777** [comment] 2016-08-01 06:57
Hi! Yes it's looks like the same trouble!

**Comment by blackcathikari** [comment] 2016-08-02 23:09
Thank you for checking @Rodion7777. 
- Millie @ TinyMCE

**Comment by lnewson** [comment] 2020-05-08 10:28
Hi,

I attempted to reproduce this issue using TinyMCE 4.9.10 and 5.2.2 using the provided fiddle, however it appears to be working as expected and the issue mentioned above has been closed as fixed. So it's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 10:28 UTC
Labels: component: input/output, status: verified, type: bug
