### ISSUE TITLE
unable to get/set content from tinymce textArea

### ISSUE THREAD

**Issue by ghost** [tinymce/tinymce#3993] opened 2017-10-11 06:28 UTC
In Angular4 I m generating textboxes dynamically by using ngFor (i.e. those id are txt_0,txt_1..)  after that I'm initializing tinymce to that textboxes using element Selector "textbox" now I'm unable to get/set the content by using controlid which I have assigned to text boxes (i.e.  txt_0,txt_1..).

tinymce.get(" txt_0").getContent(); // Im unable to get/set the content of  txt_0

When I m trying with following code textbox and its content is identified with some random id's like "mce_30, mce_31...." but I have given the control id's as " txt_0, txt_1..."

for (inst in tinyMCE.editors) {    
  if (tinyMCE.editors[inst].getContent)    
   alert("inst: "+inst+" "+tinyMCE.editors[inst].getContent());
}

**What is the expected behavior?**
I want to get/set the content by using the control id which I have given to it. (i.e. tinymce.get(" txt_0").getContent())

I'm using tinymce.min.js (4.7.1 (2017-10-09))

**Comment by jayarjo** [comment] 2017-10-15 11:07
Seems to work for me: http://fiddle.tinymce.com/zcgaab. Btw you seem to have an extra space before id here:

```js
tinymce.get(" txt_0").getContent(); // Im unable to get/set the content of txt_0
```

**Comment by tinydylan** [comment] 2020-04-21 13:16
As we are unable to reproduce this issue, we will be closing it. If you encounter the issue again, please let us know and we'll look into it.

**Closed by tinydylan** 2020-04-21 13:16 UTC
Labels: resolution: works for me
