### ISSUE TITLE
autoresize_min_height doesn't accept low values

### ISSUE THREAD

**Issue by basickarl** [tinymce/tinymce#2945] opened 2016-05-25 18:22 UTC
[http://codepen.io/basickarl/pen/pbzPBQ](http://codepen.io/basickarl/pen/pbzPBQ)

The codepen above illustrates that the autoresize autoresize_min_height property seems to be buggy. The normal height value is working as you can see.

**Comment by blackcathikari** [comment] 2016-07-29 05:11
I believe this is a duplicate of #2097. Could you take a look please and let me know if you disagree? Thanks,
Millie @ TinyMCE

**Comment by mesche** [comment] 2016-11-30 12:39
I think the problem is not the resize plugin itself. It is caused by the tinymce "bodyHeight" method.

https://github.com/tinymce/tinymce/blob/master/js/tinymce/classes/util/Quirks.js
> editor.contentStyles.push('body {min-height: 150px}');

Dirty hack:
For me It works when you set it to a smaller min-height and add the setting  "autoresize_bottom_margin: 1"

**Comment by correalucas** [comment] 2016-12-07 19:10
> Dirty hack:
> For me It works when you set it to a smaller min-height and add the setting "autoresize_bottom_margin: 1"

It worked for me too, thank's @mesche

**Comment by lnewson** [comment] 2020-05-02 05:11
Hi,

I've tested this locally and I'm no longer able to reproduce the issue in the latest version of TinyMCE. It's worth noting however that the default `autoresize_margin_bottom` is `50px` so I had to set that to 0 as well since it adds 50px of padding. Looking back at the changes, it appears to have been fixed in TinyMCE 5.0 as we now remove the min-height when autoresize is enabled. If you're still able to reproduce this use the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 05:11 UTC
Labels: plugin: autoresize, type: bug
