### ISSUE TITLE
Do not copy text that consists of several paragraphs when you press Shift + Delete

### ISSUE THREAD

**Issue by PavelTuk** [tinymce/tinymce#4529] opened 2018-08-16 09:17 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
The selected text consisting of several paragraphs is not placed on the clipboard when you press Shift + Delete.
The selected text consisting of one paragraph  is placed on the clipboard when you press Shift + Delete.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Select several paragraphs of text and click Shift + Delete.
The text does not fit on the clipboard.

**What is the expected behavior?**
The selected text consisting of any number of paragraphs is placed on the clipboard when you press shift + delete

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE - 4.7.7 and demo on the official website.
Browser - Mozilla Firefox.
OS - Windows 7

**Comment by fyrkant** [comment] 2018-08-17 07:39
Duplicate of #3369

**Closed by fyrkant** 2018-08-17 07:39 UTC
