### ISSUE TITLE
Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector

### ISSUE THREAD

**Issue by SuperChuck83** [tinymce/tinymce#9255] opened 2023-12-15 10:24 UTC
**this problem is reproductible in your storybook https://tinymce.github.io/tinymce-react/?path=/story/editor--iframe-editor**

**What is the current behavior?**

we use tinymce-react in our project,
since the 6 december 2023, tinymce react failed to init in chrome 87 to 119.
the problem comes from the component "Editor".
with the error above in the browser console:
"Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector"

**What is the expected behavior?**
should work on older version of chrome. ( <120 )

Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-react?

**Version**
"@tinymce/tinymce-react": "4.3.0"
or
"@tinymce/tinymce-react": "4.3.2"

chrome vesion : 87 to 119., it's working on the chrome V120 and after.

**Comment by hwjfqr** [comment] 2023-12-23 05:39
I also encountered this issue. By reverting the TinyMCE version to 6.6, the error disappeared, and the problem was resolved.

**Comment by TheSpyder** [comment] 2024-01-15 04:13
Duplicate of https://github.com/tinymce/tinymce/issues/9201#issuecomment-1829267205

**Closed by TheSpyder** 2024-01-15 04:13 UTC
