### ISSUE TITLE
When using table_style_by_css the border property does not work as expected

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2220] opened 2015-05-11 15:19 UTC
When using table_style_by_css the border property does not work as expected

Steps to reproduce:
1. Open an editor with table_style_by_css: true
2. Add a new table
3. Edit the table
4. In the border field type 3
5. Click OK

Expected result:
A table has been added with a 3px border.

Actual result:
The table has been added, but with no border.

It does work, however if you type the full CSS i.e. 3px solid black. This is not very usable especially for one of the "general" rather than "advanced" properties.

Also the border-color now only works for the outer border of the table; it does not propagate to the cells.
I think what is missing here is that there needs to be 3 independant properties: border-width, border color and border style. 
This should also apply to the cell properties dialog, we should also be able to enter border-width, border color and border style here.

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7507](http://archive.tinymce.com/develop/bugtracker_view.php?id=7507) posted by [adrianmag](http://archive.tinymce.com/profile.php?name=adrianmag)_
> 
> _**Tags:** [firefox msie safari chrome table]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/fMeaab_

**Comment by ktroendle** [comment] 2016-03-02 00:31
I see the same behavior when using the TinyMCE demos.
Can not set table borders. You have to manually edit the Table Properties -> Advanced -> Style to get borders on tables.  There should be a style control AND there should be a default border color. So if you select Border 1, it should select a default color of black or grey.

**Comment by nori-h** [comment] 2016-07-29 04:49
I believe this is similar to #1333. Could you have please have a look and let us know if not? Thanks,
Nori @ TinyMCE

**Comment by nori-h** [comment] 2016-08-01 00:23
We've looked into this and believe this to be a duplicate of #2268. Could you please have a look and let us know if you disagree? Thanks, the TinyMCE Team.

**Comment by blackcathikari** [comment] 2019-08-26 02:46
I believe this is functionally a duplicate of #4002, especially since I believe that the only part of this that hasn't been fixed in the latest versions of TinyMCE 4 and 5 is the cell width part. Please let me know if you believe otherwise, else we will close this ticket soon in favour of #4002 .

**Comment by lnewson** [comment] 2020-04-20 09:51
Closing in favour of #4002 as noted above since there's been no additional feedback.

**Closed by lnewson** 2020-04-20 09:51 UTC
Labels: browser: chrome, browser: firefox, browser: ie, browser: safari, origin: tinymce.com, type: bug
