### ISSUE TITLE
Large base64 images are not loaded in the tinyMCE editor.

### ISSUE THREAD

**Issue by angel-venchev-toptal** [tinymce/tinymce#5557] opened 2020-04-06 18:08 UTC
**What is the current behavior? Describe the bug**
When I drag and drop an image in the editor it's automatically converted to a base64 image and is displayed. Whenever I save the html from the editor and reload it again. The image is not displayed. I've tried this with a 2.4MB image and a 3.8MB image

The issue is similar to this one: #2105

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
I cannot provide a sample in the fiddle since it does not support storing the result on the server.

**What is the expected behavior?**
Images should be shown even after reload

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
@tinymce/tinymce-react: 3.5.0
Tested on Chrome on Windows and on Safari on Mac OS

**Comment by lincolndennis** [comment] 2020-04-09 21:02
@angel-venchev-toptal 

Can you confirm exactly what version of TinyMCE you are using?

Also does this only occur when images are dragged and dropped? What about if an image is added via the Insert Images dialog, or via a paste, etc.? 

If this is an issue with TinyMCE itself, saving to an actual server shouldn't be require to reproduce it, since TinyMCE does not actually directly interact with your server. Executing the `.save()` method saves the contents from an editor out to the `<textarea>` or `<div>` element that got converted into an editor instance. This method will move the HTML contents from the editor into that textarea or div by `.getContent()`.

Alternatively, when the `<form>` is submitted, TinyMCE 5 will `POST` the content in the same way as a normal HTML `<textarea>` would. Either way, the logic for actually saving (and retrieving) content on the server is custom code.

Here is a very simple Fiddle to start. Can you modify with your configuration to reproduce this behavior?
http://fiddle.tinymce.com/5fhaab

**Comment by angel-venchev-toptal** [comment] 2020-04-09 21:30
Thank you for your response. I will spend some time on this tomorrow and I'll let you know once I get to a reproducible situation.

**Comment by spocke** [comment] 2020-04-10 06:22
Could be related to this issue what we recently fixed. https://github.com/tinymce/tinymce/issues/5425

**Comment by angel-venchev-toptal** [comment] 2020-04-14 10:59
@lincolndennis 
I am able to reproduce it. Here's the updated fiddle: http://fiddle.tinymce.com/5fhaab/1
I've only added the `paste_data_images: true` option and then I am drag and dropping [this photo](https://www.dropbox.com/s/vnz8skbyb5pw8pl/Screenshot%202020-04-01%20at%2012.15.15.png?dl=0) in full size in the editor then on reload the photo won't load.

**Comment by lnewson** [comment] 2020-04-21 10:41
@angel-venchev-toptal I'm still unable to reproduce the issue using the above fiddle with Chrome on Linux. Are there some specific steps that are required to reproduce this?

Here's what I did:
1. Download the full-sized image linked above
2. Drag from my file browser to the editor
3. Click Save Content and Clear Editor
4. Click Load Content
5. The image is successfully reloaded

I've also verified that the content being stored is definitely base64 encoded by adding a console.log when saving.

Also can you testing using `5-dev`? As Spocke mentioned above, it's possible this has been fixed in 5.3.0 which is still under development.

**Comment by lnewson** [comment] 2020-05-02 02:31
Thanks for the extra details @angel-venchev-toptal. I was also able to reproduce it and can confirm it's been fixed in 5.3.0 as Spocke mentioned above by testing using the 5-dev channel.

If you want to test yourself using the react wrapper, you can use the [`cloudChannel`](https://www.tiny.cloud/docs/integrations/react/#cloudchannel) property to use `5-dev` instead of `5-stable`. Do note however that 5-dev isn't considered stable so I wouldn't use it for production systems at this stage.

**Closed** 2020-05-04 12:30 UTC
Labels: resolution: fixed in coming release

**Comment by hturner1994** [comment] 2023-01-17 12:42
Hi I have just stumbled across this as I am having the same issue and was wondering if you had found if any of the new versions offer a solution. It seems that version 6 just doesn't even load the image at all if its too big.
