### ISSUE TITLE
 lists_indent_on_tab configuration is not working

### ISSUE THREAD

**Issue by ramchaitanyap** [tinymce/tinymce#6746] opened 2021-04-14 07:05 UTC
> *affected page: https://www.tiny.cloud/docs-4x/plugins/lists/*

As per doc we are using lists_indent_on_tab setting on numbered lists for version 4.4.3
Steps:
-Use https://fiddle.tiny.cloud/R9haab
-Give numbered list like 
   1.a
   2.b
-Press tab 
Actual: See that focus is still in numbered list
Expected: Focus should go to button sample

**Comment by lnewson** [comment] 2021-04-18 23:53
Closing as a duplicate of the issue you've already logged in the TinyMCE repo: https://github.com/tinymce/tinymce/issues/6741.

**Closed by lnewson** 2021-04-18 23:53 UTC
