### ISSUE TITLE
Spellchecker ignores children of non-editable parent.

### ISSUE THREAD

**Issue by vaandr** [tinymce/tinymce#4725] opened 2018-12-23 01:14 UTC
**Do you want to request a *feature* or report a *bug*?**
**BUG**
**What is the current behavior?**
Elements with 'contenteditable=true' are ignored if their parent is non-editable (i.e. 'contenteditable=false').
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
A page with the following HTML source will not be checked for spelling errors:
`<div contenteditable="false"><div contenteditable="true"><p>This is a text with speling erors.</p></div></div>`
**What is the expected behavior?**
DomTextMatcher.ts should pick up text of editable children regardless of a non-editable parent.
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on 4.8.5 and since there are no recent changes, issue probably occurs in the latest version.

**Comment by lnewson** [comment] 2020-05-04 07:12
Closing, as this is a duplicate of https://github.com/tinymce/tinymce/issues/4650

**Comment by lnewson** [comment] 2020-05-04 07:14
Oops, sorry I misread, as that one is about search and replace, this is about spellchecker. They are likely related, but not the same bug. I'll reopen this sorry!

**Closed** 2024-06-15 00:41 UTC
Labels: type: bug, status: verified, plugin: spellchecker
