### ISSUE TITLE
Removing editor with Angular 4

### ISSUE THREAD

**Issue by Robouste** [tinymce/tinymce#4009] opened 2017-10-17 12:37 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
doing this : 

`tinymce.remove(this.editor);`

generates this error : 

> ERROR Error: Node cannot be null or undefined

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

I cannot use the fiddle since it's an angular project.
I have an `*ngIf` on my TinyMCE component. When it's destroyed, the error above pops up.

**What is the expected behavior?**

Being able to destroy the tinymce instance

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Using 4.7.1
Angular 4.4.3

**Comment by Robouste** [comment] 2017-10-18 08:30
Additional infos: 
the line `tinymce.remove(this.editor);` is done inside `ngOnDestroy`. It looks like this is working fine when the `*ngIf` condition changes. But if I go to an other page (so when I go through the routing), the error pops out and my page is blank. 

For now, I fixed it with an ugly `try catch` on the remove line.

**Comment by fyrkant** [comment] 2017-10-18 08:47
Can you setup a demo project somewhere else than a fiddle? Maybe just a barebones version in a git repo? It's really hard to get to the bottom of what the problem is without seeing any code.

**Comment by Robouste** [comment] 2017-10-18 09:14
I've created a git but I couldn't reproduced the error, so I guess there is something else that causes it.

I'll update this post if I find more.

**Comment by fyrkant** [comment] 2017-10-19 08:02
Ok, closing this but will open it up again if you find a way to reproduce.

**Closed by fyrkant** 2017-10-19 08:02 UTC
Labels: needs: more info

**Comment by doender** [comment] 2017-10-20 10:49
I have the same problem:
```
Error: Node cannot be null or undefined
  at Object.s [as fromDom](/scripts.8fafff4fec7693979dee.bundle.js:2:17642)
  at Object.l [as defaultView](/scripts.8fafff4fec7693979dee.bundle.js:4:26871)
  at p(/scripts.8fafff4fec7693979dee.bundle.js:6:19465)
  at Object.y [as store](/scripts.8fafff4fec7693979dee.bundle.js:6:19719)
  at C.<anonymous>(/scripts.8fafff4fec7693979dee.bundle.js:11:29606)
  at n.u [as fire](/scripts.8fafff4fec7693979dee.bundle.js:9:12265)
  at C.fire(/scripts.8fafff4fec7693979dee.bundle.js:9:13353)
  at Object.nodeChanged(/scripts.8fafff4fec7693979dee.bundle.js:10:11659)
  at C.nodeChanged(/scripts.8fafff4fec7693979dee.bundle.js:11:22559)
  at C.<anonymous>(/scripts.8fafff4fec7693979dee.bundle.js:10:27480)
  at n.u [as fire](/scripts.8fafff4fec7693979dee.bundle.js:9:12265)
  at C.fire(/scripts.8fafff4fec7693979dee.bundle.js:9:13353)
  at Object.add(/scripts.8fafff4fec7693979dee.bundle.js:10:28140)
  at C.d(/scripts.8fafff4fec7693979dee.bundle.js:10:26249)
  at n.u [as fire](/scripts.8fafff4fec7693979dee.bundle.js:9:12265)
  at C.fire(/scripts.8fafff4fec7693979dee.bundle.js:9:13353)
  at C.save(/scripts.8fafff4fec7693979dee.bundle.js:11:24734)
  at C.remove(/scripts.8fafff4fec7693979dee.bundle.js:11:28006)
  at Object.remove(/scripts.8fafff4fec7693979dee.bundle.js:12:4787)
  at e.Q5hH.e.ngOnDestroy(/0.70f1edd60958f75f1342.chunk.js:1:336955)
```

I will try to find a way to make this reproducible. 
Is there any other way than setting up a complete project?

**Comment by bago** [comment] 2018-03-10 15:04
I'm experiencing similar issues with latest tinymce in a SPA where I instantiate dozen of inline tinymce concurrently. It seems everything works fine with tinymce <= 4.5.8 and it randomly breaks on >= 4.6.0 versions.

I also see other weirds behaviours around and not only this Node cannot be null while removing.. it seems the editor are initialized with wrong references. I've not been able to make it reproducible via fiddle but I wanted to share the version number delimiting the issue.

Can others confirm they are also using multiple editable in the same page and inline mode and that downgrading to 4.5.8 fixes it?

**Comment by supergnuen** [comment] 2018-03-16 10:28
I have the exact same scenario as @bago

Downgrading to 4.5.8 seems to fix the issue.

**Comment by fyrkant** [comment] 2018-03-16 10:33
It's hard to know what the problem is without a clear reproduction, but my recommendation is to check out our [Official Angular wrapper](https://github.com/tinymce/tinymce-angular) if you're using tinymce with angular and open up an issue on  that repo if you have any problems.

**Comment by supergnuen** [comment] 2018-03-16 11:19
@fyrkant I'm not using Angular, so this should probably be opened as a new issue.

**Comment by bago** [comment] 2018-03-16 12:58
I'm also not using Angular, but Knockout. In my app I have many "inline" tinymce instances and with Tinymce 4.6.0+ I sometimes have errors.
Turned out most of them disappeared after I removed custom "style_formats" and custom plugins (it seems something changed in 4.6.0 wrt to that management) but I still see some of them when instantiating many tinymce or when disposing them, with tinymce from 4.6.0 to 4.7.9. I downgraded to 4.5.8 and I don't see that issue.

**Comment by fyrkant** [comment] 2018-03-16 13:00
Please create a new issue for that with some steps to reproduce then we can take a look at it.

**Comment by balaabhinav** [comment] 2018-03-26 10:32
I am facing similar issue to @bago . Any updates on this?

**Comment by fyrkant** [comment] 2018-03-26 10:33
@balaabhinav I need some help with a clear reproduction to be able to take a look at what's wrong.

**Comment by cassianomon** [comment] 2018-04-05 11:30
@bago @balaabhinav @supergnuen Create another issue since this one is clearly saying **Removing editor with Angular 4**

**Comment by bago** [comment] 2018-04-05 12:10
Sure, I just added that this is not an issue with Angular, but with the dynamic removal of multiple editors (whatever tool you use).
I can open in assie for Vue, one for jQuery, one for Knockout.. and for "put any js library that you use together with tinymce" ;-)

**Comment by bago** [comment] 2018-04-24 12:15
@jhorowitz-firedrum successfully created a fiddle for a "Node cannot be null or undefined" exception: #4355
Of course I can't tell if the issue is the same or not. Maybe @Robouste can try to apply the suggested changed in the tinymce sourcecode to see if his error disappear or not.

**Comment by jhorowitz-firedrum** [comment] 2018-04-24 13:36
@bago I believe it to be the same as the one you are experiencing.
I replicated the error and came up with my fix within my fork of the [Mosaico master branch](https://github.com/voidlabs/mosaico/commit/5b5fdfe1cdacfd0b4089f592b0d5696d2177e918) by clicking somewhere within the editor immediately after Knockout bindings have completed but before TinyMCE instances have finished initializing.

**Comment by cassianomon** [comment] 2018-04-25 16:43
@bago @jhorowitz-firedrum please open a new issue for this bug if it's outside of Angular, this one is not being watched by the moderators.

**Comment by chislin** [comment] 2018-07-17 14:14
Check this one https://github.com/tinymce/tinymce-angular/blob/master/tinymce-angular-component/src/editor/editor.component.ts#L130

I used `NgZone.runOutsideAngular` method too and it solved the problem.

**Comment by andreash92** [comment] 2019-02-26 14:20
@chislin I don't understand how _editor.component.ts Line 30_ relates to _NgZone.runOutsideAngular_.

Can you be more specific pls? Thanks

**Comment by chislin** [comment] 2019-02-27 12:23
> @chislin I don't understand how _editor.component.ts Line 30_ relates to _NgZone.runOutsideAngular_.
> 
> Can you be more specific pls? Thanks

https://github.com/tinymce/tinymce-angular/blob/c6e2c330061fec89b701ad4111e40049a0afd058/tinymce-angular-component/src/editor/editor.component.ts

**Comment by chislin** [comment] 2019-04-12 12:40
Editor now seems to be removing as it should without any error inside NgZone after version 5
