### ISSUE TITLE
Media Plugin: Source URL does not update when pressing "Ok" directly after changing the URL

### ISSUE THREAD

**Issue by cirkuitnet** [tinymce/tinymce#3755] opened 2017-06-19 21:27 UTC
If a media object is embedded on the page (i.e. a YouTube video), and you attempt the edit the source of the media using the "Insert/edit media" dialog in TinyMCE, the changes you make to the "Source" field within the "General" tab will not take effect if you leave the cursor in the "Source" field and click "Ok".

You must click outside the "Source" field (to trigger the blur event on the input box), THEN click "Ok" to accept the changes. It seems if the blur event is not triggered before pressing "Ok", then the changes are not applied.

This is easily reproducible using the Basic Example on TinyMCE's website:
https://www.tinymce.com/docs/demo/basic-example/

1. Embed a YouTube URL on the page, such as: https://www.youtube.com/watch?v=JWmPzBC3ke4
2. Click the video in the editor to select it
3. Clicking the menu "+" and choose the "Media" option
4. Change the Source text in the General tab to *anything* else
5. With the cursor STILL in the Source input box, click "Ok"
The source of the video will not update.

**Comment by lnewson** [comment] 2020-05-02 09:21
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely we've fixed the issue since this was originally reported, so I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 09:21 UTC
Labels: plugin: media
