### ISSUE TITLE
Cell border styles can't be set correctly

### ISSUE THREAD

**Issue by CiroXM** [tinymce/tinymce#4002] opened 2017-10-14 17:38 UTC
**Do you want to request a *feature* or report a *bug*?**
bug and feature

**What is the current behavior?**
Link test: https://www.tinymce.com/docs/demo/full-featured/
table properties border, only applied within the limits of the table. Cell properties have no border size option. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1 - Open demo, https://www.tinymce.com/docs/demo/full-featured/
2- set border of table "A simple table to play with" to 1 and change color border in advanced
3 - only the outer border is colored and cell properties do not have border property

**What is the expected behavior?**
When apply border in table, the whole table must have border. Or that it is possible to change the border in the cell. Something like https://i.ytimg.com/vi/MazsC5pjVF0/maxresdefault.jpg

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Firefox 56, Win 10

**Comment by fyrkant** [comment] 2017-10-16 08:21
I'm not sure I understand the issue, maybe the problem you see it because of the `content_css` setting the table styles so the table properties settings don't apply? Can you create a [fiddle](http://fiddle.tinymce.com/) instead of the codepen showing the problem?

**Comment by blackcathikari** [comment] 2019-08-26 01:58
I just had a quick look at this and I believe this is fully fixed in TinyMCE 4.9 (cell border styles are available via the advanced tab of the cell properties dialog) and partially fixed in TinyMCE 5.x (same, except there is no option for setting border width). Please let us know if you can replicate anything other than the cell border width problem.

**Comment by lnewson** [comment] 2020-04-20 09:57
Cell border width has been added to the table cell dialog in TinyMCE 5.1 and I can confirm this works on [fiddle](http://fiddle.tinymce.com/).

However as noted in the original report, this doesn't appear to be working on our docs website. This appears to be because the sites content CSS is overriding the border styles. As this isn't an issue with TinyMCE directly, I'm going to close this and I'll open an internal website issue to get our site CSS fixed.

**Closed by lnewson** 2020-04-20 09:57 UTC
Labels: 5.x, plugin: table, type: feature
