### ISSUE TITLE
Window resize ERROR in FIREFOX browser

### ISSUE THREAD

**Issue by Andy-QT** [tinymce/tinymce#5463] opened 2020-03-04 09:41 UTC
**What is the current behavior? Describe the bug**
Initialise the editor to an element and remove the parent element (eg: the form which contains the editor)
After that resize the browser window -> **Error** 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

http://fiddle.tinymce.com/gdhaab/5

**What is the expected behavior?**
Google CHROME browser does not throw an error

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest version 5.2

**Comment by lnewson** [comment] 2020-03-04 10:05
You're detaching the editor target element and editor container from the DOM while it's potentially initialising by removing the parent and therefore all the children as well and that is not going to end well. Additionally TinyMCE doesn't support running on detached nodes, so I'm going to close this as not a bug. If you can replicate the issue without using a detached node as the target element then please let us know and we'll reopen this.

**Closed by lnewson** 2020-03-04 10:05 UTC

**Comment by lnewson** [comment] 2020-03-04 10:08
Also this is related to https://github.com/tinymce/tinymce/issues/2671, so make sure you're calling `editor.remove()` if you're going to remove the parent or target elements.
