### ISSUE TITLE
cancel button get cut

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2368] opened 2015-08-24 13:35 UTC
Description of problem:

Steps to reproduce:
http://fiddle.tinymce.com/vseaab/2

1. click the editable text
2. open "paragraph" format select
3. select "Preformatted"

Expected result:
like in tiny 4.1 the button was still fully visible

Actual result:
-> cancel button moves to the right, because of the longer "Preformatted" label and is not visible as a whole.

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7662](http://archive.tinymce.com/develop/bugtracker_view.php?id=7662) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_

> _**Tags:** []_
> _**Status:** Verified_
> _**Resolution:** None_
> _**Attached URL:** http://fiddle.tinymce.com/vseaab/2_

**Comment by blackcathikari** [comment] 2016-08-01 01:39
We've investigated this problem and we can't reproduce it in TinyMCE v4.4.0, so I'm going to close this report. If this is still happening for you with TinyMCE v4.4.0, let me know and I can reopen it. Thanks,
Millie @ TinyMCE

**Closed by blackcathikari** 2016-08-01 01:39 UTC
Labels: component: ui, origin: tinymce.com, status: verified, type: bug
