### ISSUE TITLE
Spamming ctrl+v with image in clipboard will paste image into document despite paste-plugin directives.

### ISSUE THREAD

**Issue by Sopkillen** [tinymce/tinymce#3502] opened 2017-02-23 12:10 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
paste-plugin has directive not to allow pasting an image, but in Firefox if I spam ctrl+v with an image in clipboard I will be able to paste it after a random number of attempts.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.
http://fiddle.tinymce.com/rKfaab
Just go to an image file on your file system. Select it, press ctrl+c.
Go to editor, press ctrl+v a number of times. Eventually the image will get pasted into the document.

**What is the expected behavior?**
The image not getting pasted.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest TinyMCE, Firefox, don't know.

**Comment by fyrkant** [comment] 2017-03-13 15:37
Hi @Sopkillen ! I sat down to take a look at this issue today but I can't seem to reproduce it anymore (I could reproduce it when I labeled this issue). Maybe something changed in a firefox update? Are you still able to reproduce this?

**Comment by lnewson** [comment] 2020-05-09 05:14
As mentioned above, I can't reproduce this either using Firefox 76.0, so it's likely something that was fixed in Firefox or some fix in TinyMCE that resolved this since the issue was logged. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

**Closed by lnewson** 2020-05-09 05:14 UTC
Labels: plugin: paste, status: verified, type: bug
