### ISSUE TITLE
Some escaped string can't be rendered correctly

### ISSUE THREAD

**Issue by peterzhangsnail** [tinymce/tinymce#5569] opened 2020-04-14 07:11 UTC
**What is the current behavior? Describe the bug**
Escaped string like "\&lt;DOCTYPE html\&gt;" can't be rendered correctly, making adding code example inconvenient.
[fiddle demo](http://fiddle.tinymce.com/Dfhaab/2)

**What is the expected behavior?**
Escaped string can be correctly rendered

**Which versions of TinyMCE, and which browserOS are affected by this issue?**
TinyMCE: 5.2.1
OS: windows 7
browser: chrome

**Did this work in previous versions of TinyMCE?**
Not sure.

**Comment by lnewson** [comment] 2020-04-14 07:16
Closing this as a duplicate of https://github.com/tinymce/tinymce/issues/5559 and https://github.com/tinymce/tinymce/issues/5522. You need to properly encode the content inside the textarea. I've fixed the linked fiddle for you here: http://fiddle.tinymce.com/Dfhaab/3

**Closed by lnewson** 2020-04-14 07:16 UTC

**Comment by peterzhangsnail** [comment] 2020-04-14 07:46
@lnewson Thanks for your help. But there's a unique need in my project that I only need the inside content to be escaped, which means keeping its wrapper element the way it is. Is it possible?

**Comment by lnewson** [comment] 2020-04-14 07:52
It's a browser requirement for textareas as noted in #5559. You could use the `setContent` API instead of rendering the content in a textarea if that works. If not then we'd need to see a small demo of what you are trying to do to be able to give any other suggestions.

**Comment by peterzhangsnail** [comment] 2020-04-14 10:38
@ This is a brief look of my work. And why I only need the content to be escaped. [simple demo](http://fiddle.tinymce.com/Dfhaab/4)
![新建 Edraw Document](https://user-images.githubusercontent.com/20182319/79215952-f3d4a580-7e7e-11ea-9591-1a38c03afe86.png)

**Comment by lnewson** [comment] 2020-04-14 20:07
@peterzhangsnail we'd need to see a code based example, as the picture doesn't show how you're initialising the editor or getting any content out of the editor.

**Comment by peterzhangsnail** [comment] 2020-04-17 12:33
@lnewson After some googling about the process of Serializing HTML fragments, I finally figured out what's going on here. TinyMCE renders using the innerHTML property of the textarea element as its source, I guess. It turns out I just need to escape all the & in the HTML file before send it to the client. Sorry for being an idiot this whole time.
