### ISSUE TITLE
Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector.

### ISSUE THREAD

**Issue by daniicamanalang** [tinymce/tinymce#9557] opened 2024-04-12 12:30 UTC
## 📝 Provide detailed reproduction steps (if any)
Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud) or similar.

1. On your react app, use the latest version of tinymce react (6.8.3)
2. Open your page with a tiny editor on a Chrome Browser v85

### ✔️ Expected result
You should be able to see tiny editor without any issues

### ❌ Actual result
The site throws an error (as tittled), and couldn't view the tiny editor.

## 📃 Other details
- Browser: Chrome v85
- OS: all OS
- Worked in version: Chrome > v85

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by TheSpyder** [comment] 2024-04-15 06:54
Duplicate of #9201

As [noted in our documentation](https://www.tiny.cloud/docs/tinymce/6/support/#supported-web-browsers-table) the oldest version of Chrome we support is extended stable. That was 118 when we released TinyMCE 6.8.3, and recently updated to [`122`](https://chromereleases.googleblog.com/search/label/Extended%20Stable%20updates).

Sorry.

**Closed by TheSpyder** 2024-04-15 06:54 UTC
