### ISSUE TITLE
Space is not preserved before a noneditable element

### ISSUE THREAD

**Issue by Antontelesh** [tinymce/tinymce#3706] opened 2017-05-31 08:09 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After inserting content with noneditable element, the space before the new content is getting moved to a position right after the inserted content. Please, see the jsfiddle below.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

https://jsfiddle.net/Girafa/gar54mka/

**What is the expected behavior?**

The space should not be moved

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

TinyMCE version: 4.6.3 (did not check other versions)
OS: macOS Sierra 10.12.3
Browser: Chrome 58

**Comment by lnewson** [comment] 2020-05-08 09:24
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:24 UTC
Labels: component: cE=false, status: escalated, status: verified, type: bug
