### ISSUE TITLE
How to auto load editor interface, skip first step.

### ISSUE THREAD

**Issue by xiaohuilam** [tinymce/tinymce#4845] opened 2019-02-22 09:59 UTC
i want to skip this screen,
![image](https://user-images.githubusercontent.com/6964962/53234660-00220000-36cb-11e9-8795-573b835bccd1.png)

and go into the second screen,
![image](https://user-images.githubusercontent.com/6964962/53234845-6c9cff00-36cb-11e9-83ed-c353e47a9a6b.png)

my code
```javascript
        tinymce.init({
            selector: 'textarea',
            theme: 'mobile',
            autofocus: true,
            toolbar: [ 'undo', 'redo', 'bold', 'italic', 'image',  ],
            plugins: ['autosave',],
            mobile: {
                theme: 'mobile',
            },
            images_upload_url: location.href,
            automatic_uploads: true,
        }).then(function (selectors) {
            window.editor = selectors[0];
            $('.tinymce-mobile-content-tap-section').trigger('click');
        });
        $('textarea').focus();
```
and it does not work.

**Comment by lnewson** [comment] 2019-02-25 01:52
This is something we're else others have requested as well, however we've not yet had the bandwidth to look into this. In case it helps, the idea behind showing the mentioned overlay was detailed here: https://github.com/tinymce/tinymce/issues/4040#issuecomment-450783361

Anyways we already have a tracker for this, so I'm going to close this as a duplicate of our existing issue: https://github.com/tinymce/tinymce/issues/4372

As for your attempt to workaround the overlay, it's not working because the click event isn't used with mobile devices and instead listens to touchstart/touchend events, so you'd need to simulate those.

**Closed by lnewson** 2019-02-25 01:52 UTC
