### ISSUE TITLE
Formatting lost on backspace bug.

### ISSUE THREAD

**Issue by IeuanSkinner** [tinymce/tinymce#3471] opened 2017-02-03 10:41 UTC
I've noticed some odd behaviour with TinyMCE editors (4.2.5) that seems to be present in the most recent versions and was wondering if this is a bug and/or changeable behaviour.

Basically what I'm seeing is that if I have a line of formatted text and press return (more than once) midway through that sentence and then hit backspace the formatting for that text is lost.

The HTML at each stage looks like thus:

Formatted line:

`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;" id="ext4-ext-gen4618">I am a line of text</span><br data-mce-bogus="1"></p>`

After 2 carriage returns (as expected):

`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;" id="ext4-ext-gen4618">I am a line </span></p>`
`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;"><br data-mce-bogus="1"></span></p>`
`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;" id="ext4-ext-gen4618">of text.</span><br data-mce-bogus="1"></p>`

Once backspace is hit (with caret at front of last line) it becomes:

`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;">I am a line </span></p>`
`<p>of text.<br></p>`

As you can hopefully see all of the formatting was stripped from the "of text." line and this is not what I'd want to see, what I'd like is for it to look as it would after a single carriage return keeping its formatting ie:

`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;">I am a line </span></p>`
`<p><span style="font-family: 'arial black', sans-serif; font-size: 14pt;" data-mce-style="font-family: 'arial black', sans-serif; font-size: 14pt;">of text.</span></p>`

Any insight you have would be appreciated.

Video of the problem: https://www.youtube.com/watch?v=-9AHNo-E4NY

**Comment by alexandrlich** [comment] 2017-03-29 15:44
Yes we have exactly the same problem - backspace removes styles (colors) applied to the selected text, frustrates our alpha users so we ended up postponing the release.

**Comment by MagicMicah** [comment] 2017-10-24 01:18
I am working to try and fix #3817 at the moment. I think these might be related

**Comment by spocke** [comment] 2018-05-12 07:00
I'm unable to reproduce this issue anymore we have done lots of improvements to the delete/backspace behavior. And in 4.6.3 we fixed an issue that seems to be related to this case. So I'm closing this ticket. If you can still reproduce this then please provide detailed instructions and possible a fiddle so that we can reproduce it. Then we will re-open the ticket. Thanks

**Closed by spocke** 2018-05-12 07:00 UTC
Labels: component: formatting, status: verified, type: bug

**Comment by thanhnguyen92** [comment] 2018-12-03 08:51
@spocke I still able to reproduce it with latest version: https://codepen.io/thanhnguyen92/pen/EOMweo
`https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc`

**Comment by ryoullar** [comment] 2019-09-09 20:20
I am also experiencing this bug in version 5.0.11

**Comment by Curi0sity** [comment] 2020-01-30 08:33
As a workaround, I had solved it using the keydown event:
`ed.on("keydown",function(evt) {
                if (evt.keyCode == 8 || evt.keyCode == 46)  //backspace or delete
                {
                    var elem = tinyMCE.activeEditor.selection.getNode();
                    if (elem.textContent.length <= 1) {
                        evt.preventDefault();
                        evt.stopPropagation();
                        jQuery(elem).html('&#65279');  // inserting Zero Width No-Break Space
                        return false;
                    }
                }
            });`

Hope this helps.
