### ISSUE TITLE
Media plugin has no file picker

### ISSUE THREAD

**Issue by logarytm** [tinymce/tinymce#4675] opened 2018-11-21 12:13 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Although `file_picker_types` is set to `file image media` and `file_picker_callback` works with images and links, the media insertion dialog does not show the ![file picker button](https://user-images.githubusercontent.com/2938672/48840467-02ed1c00-ed8f-11e8-8eae-baecaa3b6bc4.png) thinger, and does not make it possible to select a video file using the file picker.

**What is the expected behavior?**

The media dialog should behave consistently with the image and link dialogs, and allow utilization of the file picker.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

5.x Dev Preview

**Comment by logarytm** [comment] 2018-11-21 12:54
This is my current configuration:

```js
tinymce.init({
	relative_urls: false,
	remove_script_host: false,
	document_base_url: app.baseUrl,
	file_picker_callback: function openFilemanager(cb, value, meta) {
		var win = window.open('filemanager?callback=filePickerCallback', '_blank', 'menubar=no,location=no,resizable=yes,status=no,width=750,height=500');
		
		window.filePickerCallback = function (url) {
			url = toAbsoluteUrl(url);
			cb(url, { source1: { value: 'test' } });
		};
	},
	selector: 'textarea[data-editor]',
	plugins: [
		'anchor autolink autoresize autosave charmap code codesample colorpicker',
		'contextmenu directionality emoticons fullscreen help hr image imagetools insertdatetime',
		'link lists media nonbreaking pagebreak paste preview print save searchreplace table',
		'template textcolor textpattern toc visualblocks visualchars wordcount',
	],
	toolbar: 'undo redo | formatselect | bold italic strikethrough forecolor backcolor | link filemanager template | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent | removeformat',
	templates: 'resources/src/js/tinymce/templates.js',
	content_css: 'Admin/resources/src/js/tinymce/templates.css',
	valid_children: '+body[style]',
	valid_classes: {
		'a': 'button button-yellow button-next',
	},
	setup: function (editor) {
		editor.ui.registry.addButton('filemanager', {
			text: 'Link to file',
			predicate: () => !!getSelectedLink(editor),
			onAction: function () {
				var anchor = getSelectedLink(editor);
				if (anchor === null) {
					alert('You haven\'t selected any link!');
					return;
				}

				var win = window.open('filemanager?callback=filePickerCallback', '_blank', 'menubar=no,location=no,resizable=yes,status=no,width=750,height=500');

				window.filePickerCallback = function (url) {
					editor.focus();
					url = toAbsoluteUrl(url);
					editor.dom.setAttribs(anchor, { href: url });
					editor.selection.select(anchor);
					editor.undoManager.add();
				};
			}
		});
	},
});
```

**Comment by blackcathikari** [comment] 2019-01-07 02:10
@logarytm Hi, I just had a look at this and unfortunately I can't replicate it. Though I did modify your config slightly to get it to work on our fiddle. Could you please have a look at this, and let me know if something I've changed might have done it? http://fiddle.tinymce.com/Y7gaab

Changes were:
- removing the document_base_url property since I don't have the app variable
- removing predicate in the button config (that isn't a valid property - see https://www.tiny.cloud/docs-beta/ui-components/typesoftoolbarbuttons/)
- removing var anchor and the if based on it, since I don't have the getSelectedLink function

Also, if this is no longer a problem for you, please let us know. It'd be great to know it's been fixed already.

**Comment by wonderbugtiny** [comment] 2019-04-08 03:41
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:41 UTC
Labels: 5.x, needs: more info
