### ISSUE TITLE
Image in first position of bullet list is not removed when backspacing.

### ISSUE THREAD

**Issue by jeffreymolina** [tinymce/tinymce#3269] opened 2016-10-14 15:06 UTC
1.  Add the source below to the editor.
2.  Set cursor to end of text.
3.  Hit backspace key to remove all text and image.

Issue:  Text and bullet are removed but image is not removed.

Source:
```html
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<ul>
<li><img src="https://lh4.ggpht.com/wKrDLLmmxjfRG2-E-k5L5BUuHWpCOe4lWRF7oVs1Gzdn5e5yvr8fj-ORTlBF43U47yI=w300" alt="" width="20" height="20" />This is a test</li>
</ul>

</body>
</html>

```

**Comment by jayarjo** [comment] 2016-11-06 13:36
Why would you add `html`, 'head`, etc? I believe they will get stripped in default configuration.

Can you please provide more details, browser model version, tinymce configuration or even fiddle maybe? 'cause it works in Chrome for example.

Here's a pen that you could fork: http://codepen.io/jayarjo/pen/BQydLm.

**Comment by tinydylan** [comment] 2020-04-20 13:20
We will be closing this issue, as we have been unable to reproduce it. If the issue still occurs, please respond with more details, in order to help us track it down.

Thanks!

**Closed by tinydylan** 2020-04-20 13:20 UTC
Labels: resolution: works for me, status: verified
