### ISSUE TITLE
Autofocus and autoscrolling cannot be disabled

### ISSUE THREAD

**Issue by ChristianRich** [tinymce/tinymce#2949] opened 2016-05-27 00:50 UTC
There is no possible way of disabling autofocus and autoscrolling to the tinymce component after initialisation.

**Comment by spocke** [comment] 2016-05-27 14:02
Could you provide us with a fiddle of this at fiddle.tinymce.com since I don't know of it being auto focused. If you however execute commands on an instance the focus will be moved to that editor instance.

**Comment by Tohmua** [comment] 2018-07-31 07:40
Managed to reproduce something similar to this.

http://fiddle.tinymce.com/Gxgaab

By calling the `execCommand` the editor takes focus even without the `auto_focus` property. This caused us issues when upgrading TinyMCE from `3.4.7` to `4.8.0`.

Managed to get around this by setting the font-type + size in CSS instead and just removing these `execCommand` command calls.

**Comment by lnewson** [comment] 2020-05-09 06:21
I'm going to close this because of its age and because a fiddle wasn't provided for the original issue, but if you can still reproduce this in the latest versions of TinyMCE please feel free to log a new issue.

With regards to the `execCommand` point mentioned above, that is expected as if you're running a command then you're normally trying to edit content. You can disable this however by setting the `skip_focus: true` property in the `args` passed to `execCommand`. eg: http://fiddle.tinymce.com/Gxgaab/1

**Closed by lnewson** 2020-05-09 06:21 UTC
Labels: needs: more info, type: bug
