### ISSUE TITLE
Bundling with Webpack fails on undefined global variable tinymce

### ISSUE THREAD

**Issue by crmtestresco** [tinymce/tinymce#5491] opened 2020-03-10 14:37 UTC
**What is the current behavior? Describe the bug**
TinyMCE does not work when bundled with Webpack.
The error is: 

```
plugin.js?01dd:12 Uncaught ReferenceError: tinymce is not defined
    at eval (plugin.js?01dd:12)
    at Object.eval (plugin.js?01dd:2519)
    at eval (plugin.js?01dd:2519)
    at Object.../node_modules/tinymce/plugins/image/plugin.js (emailEditor.bundle.js:978)
    at __webpack_require__ (emailEditor.bundle.js:727)
    at fn (emailEditor.bundle.js:101)
    at eval (index.js?26ab:7)
    at Object.../node_modules/tinymce/plugins/image/index.js (emailEditor.bundle.js:967)
    at __webpack_require__ (emailEditor.bundle.js:727)
    at fn (emailEditor.bundle.js:101)
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
1. Install with npm `npm install tinymce`.
2. Have working configuration with Webpack, Typescript and Babel
3. Use very similar code to example provided by TinyMCE [https://www.tiny.cloud/docs-4x/advanced/usage-with-module-loaders/](https://www.tiny.cloud/docs-4x/advanced/usage-with-module-loaders/)

```
import tinymce from "tinymce/tinymce";
import "tinymce/plugins/image";
import "tinymce/plugins/link";

var editorContent = ""
var initContentCallback = null;

function init_content(inst) {
        inst.setContent(editorContent ? editorContent : "");
        if (initContentCallback) {
                initContentCallback.call(inst, inst);
        }
}

function initEditor(content, height, callback) {
        debugger;
        editorContent = content;
        initContentCallback = callback;
        tinymce.init({
                selector: "textarea",
                height: height,
                plugins: ["textcolor", "image", "link"],
                toolbar1: "undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | fontselect fontsizeselect styleselect | forecolor backcolor | image link",
                menubar: false,
                statusbar: false,
                auto_focus: "emailContent",
                init_instance_callback: "init_content",
                paste_data_images: true,
                image_description: false
        });
}
```

It looks to me that the problematic line is this [one](https://github.com/tinymce/tinymce/blob/59748a11303fb7cf00fdb8c9392dcb082ee9d965/modules/tinymce/src/core/main/js/GlobalsTemplate.js#L1). It references global `tinymce` variable which is not defined.

**What is the expected behavior?**
TinyMCE correctly works when bundled with Webpack.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Latest version (5.2.0). I do not know if it worked in previous versions.

**Comment by lnewson** [comment] 2020-05-04 00:57
@crmtestresco sorry for the late reply, however this is going to be hard to diagnose without a replication case, so are you able to setup something small to show how to reproduce this? It's also worth mentioning it's expected that a global will be created, so that indicates something might be going wayward with your bundling configuration.

Another point I'd like to raise, is you've linked to the TinyMCE 4 docs, but you're trying to use TinyMCE 5 so that might be part of your issue. Here's the relevant v5 docs: https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/ (it's largely the same, but does have some important differences).

**Comment by lnewson** [comment] 2020-06-08 20:45
Closing due to a lack of additional information. If you can provide the information requested above then we'll be happy to reopen this issue.

**Closed by lnewson** 2020-06-08 20:45 UTC
Labels: needs: more info
