### ISSUE TITLE
Codesample plugin removes HTML , Android Tag on Edit

### ISSUE THREAD

**Issue by rebootcode** [tinymce/tinymce#3134] opened 2016-08-17 22:39 UTC
Hi,

This plugin removes all code and content between 

```<any_markup_tag> content here </any_markup_tag>```

How to repeat :- 

1. Provide any HTML, Android layout code and Store it in DB.
2. Bring all content from DB and See, all codes are gone.
3. To Test it live. Visit http://w3clan.com , Go to My Blog. Add Post with `HTML` code and Submit it, Once submitted, It will return you to edit page with all `markup` gone.

**Comment by spocke** [comment] 2016-08-19 07:47
This is usually encoding problems not a bug in the code sample plugin.
http://fiddle.tinymce.com/v5faab

Closing since I can't reproduce this. If you still think it's a problem then provide us with a fiddle that reproduces the issue and we re-open this one. Thanks.

**Closed by spocke** 2016-08-19 07:47 UTC

**Comment by rebootcode** [comment] 2016-08-19 11:49
There you go :- 

http://fiddle.tinymce.com/w5faab

In this fiddle, you can see markup tags are getting  stripped.

**Comment by rebootcode** [comment] 2016-08-19 13:43
Oh! That's encoding issue. I just realized.

Thanks @spocke :+1:
