### ISSUE TITLE
Tab key does not advance to the next field as the control is embedded with TinyMCE editor

### ISSUE THREAD

**Issue by rakeshkrishnan** [tinymce/tinymce#5159] opened 2019-09-11 09:18 UTC
**What is the current behavior? Describe the bug**

The TinyMCE control is embedded in our application as one of many fields in a page form. When the user attempts to use the Tab button to change the field focus, they cannot advance past the TinyMCE control. This issue began when we upgraded from version 4.7.4 to version 4.8.5

**What is the expected behavior?**

Tab key should advance the focus to the next field in TinyMCE version 4.8.5

**Comment by alecpl** [comment] 2019-09-11 12:27
https://www.tiny.cloud/docs-4x/plugins/tabfocus/

**Comment by rakeshkrishnan** [comment] 2019-09-16 06:12
Tab focus plugin has been used already. But still no help

**Comment by ltrouton** [comment] 2019-09-17 04:22
I am unable to reproduce the issue through some preliminary testing ([Fiddle](http://fiddle.tinymce.com/FQgaab)). Could you please provide a forked fiddle that is simplified as much as possible but still able to show the issue occurring. Thanks.

**Comment by lnewson** [comment] 2019-10-15 21:27
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-10-15 21:27 UTC
Labels: needs: more info
