### ISSUE TITLE
On click on ok, in case of the failure callback popup in image_upload_handler, the image_upload popup should be there

### ISSUE THREAD

**Issue by SIMRAN88** [tinymce/tinymce#5684] opened 2020-05-20 09:50 UTC
**on click of ok, popup is not retained**

the popup should retain,

tinymce 5.2.1
![image](https://user-images.githubusercontent.com/12448024/82432256-67388b00-9aad-11ea-962b-b2d7baa95933.png)

**Comment by lnewson** [comment] 2020-05-21 10:39
@SIMRAN88 this isn't clear what the issue is sorry. From doing some testing and from what I can see in the image I'd guess you'd like the image dialog to stay open if an image upload fails, is that correct?

**Comment by SIMRAN88** [comment] 2020-05-21 13:26
yes @lnewson , you are correct.

**Comment by lnewson** [comment] 2020-05-21 13:30
Thanks for confirming @SIMRAN88! Looking back, this didn't occur in TinyMCE 4.x, so it appears this is a bug/regression introduced in TinyMCE 5. I'll log a bug in our internal tracker to get this fixed.

**Comment by lnewson** [comment] 2020-05-27 04:55
We've just released TinyMCE 5.3.1 to the community, which includes a fix for this issue. Please let us know if you continue to experience any issues.

**Closed by lnewson** 2020-05-27 04:55 UTC
Labels: 5.x, plugin: image, resolution: fixed in coming release, status: escalated, status: regression, type: bug
