### ISSUE TITLE
Cursor not placed on left side of element in nested contenteditable scenario's

### ISSUE THREAD

**Issue by krishna-babu** [tinymce/tinymce#6633] opened 2021-03-16 20:22 UTC
**What is the current behavior? Describe the bug**
Cursor is not placed when clicked on left of element A which is nested under element B. Both elements A & B are set to contenteditable=true

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
[Fiddle link](https://fiddle.tiny.cloud/C7haab/5)

Demo of issue
![CursorOnLeft](https://user-images.githubusercontent.com/12712808/111374530-769b4d00-865a-11eb-92ed-dfded986b774.gif)

**What is the expected behavior?**
Cursor to be placed on left of elements just like how it works on right side.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?
Latest stable 5.7

**Comment by JamesToohey** [comment] 2021-03-25 01:00
Hi @krishna-babu, this appears to be a duplicate of #6456 so I'm going to close this so we can track it in one place.

**Closed by JamesToohey** 2021-03-25 01:00 UTC
