### ISSUE TITLE
Bug in latest release 4.6.4 - content_css loaded from CDN

### ISSUE THREAD

**Issue by j-page** [tinymce/tinymce#3744] opened 2017-06-14 11:01 UTC
As of the latest release the Tiny MCE instances are trying to load the style sheets specified in "content_css" from the CDN.

**Comment by fyrkant** [comment] 2017-06-14 12:55
Hmm, I cant reproduce this, it works as it should for me. Can you show some code/make a [fiddle](http://fiddle.tinymce.com/) that reproduces it?

**Comment by j-page** [comment] 2017-06-14 13:00
I believe this jsfiddle shows the issue.

It's pretty much boilerplate that we use everywhere, I can't see anything wrong with it, but all of our sites are currently having the same issue.

**Comment by fyrkant** [comment] 2017-06-14 13:11
Do you need the `document_base_url: ""` setting? It works if I remove it.

**Comment by j-page** [comment] 2017-06-14 13:15
Interesting. No, we probably don't need that.

The behaviour still seems a bit off, but I'm happy that we should be able to resolve the issue we're experiencing by removing it. 

Thanks for looking at it.

**Comment by fyrkant** [comment] 2017-06-15 10:25
I know that some code handling the loading of the content_css were changed in the last release so maybe that brought on the change in behaviour, but I don't think this is a bug in TinyMCE but actually the incorrect document_base_url setting. Closing this issue, but write a comment if you still have a problem and I can open it again.

**Closed by fyrkant** 2017-06-15 10:25 UTC
Labels: needs: more info
