### ISSUE TITLE
Uncaught TypeError: blobInfo.blob is not a function

### ISSUE THREAD

**Issue by sywa08** [tinymce/tinymce#3574] opened 2017-04-07 07:31 UTC
Hi

I'm sorry but even formData.append("file", blobInfo.blob(), blobInfo.filename()); doesn't work for me as of today in April 2017.
The JS is broken with the message "Uncaught TypeError: blobInfo.blob is not a function". It is undefined if I remove the "()". and then the same error is shown on file. Plus, whatever I pass in success, it is always undefined.
Here is how my handler:
images_upload_handler: function (blobInfo, success, failure) { upload(blobInfo, success, failure); }
The upload function is in a javascript file which is included and the it gets called. then the upload function looks like this:

function upload(blobInfo, success, failure) { var formData = new FormData(); var formId = blobInfo.id; formData.append("file", blobInfo.blob(), blobInfo.filename()); formData.append("formId", formId);

Things do not follow and still some bits are missing and/or broken.
I am using TinyMCEv4 by the way.

Any thoughts or inputs?

**Comment by spocke** [comment] 2017-04-10 14:45
Wasn't able to reproduce it here: http://fiddle.tinymce.com/uNfaab need more details.

**Comment by sywa08** [comment] 2017-04-11 09:29
What more details should I provide? Because I don't think there is more to provide here.

**Comment by sywa08** [comment] 2017-04-11 09:31
Moreover, I didn't understand your code completely. How are you debugging it? What shall one do to invoke the upload function?
In my code, it is invoked when someone edits an image and presses the Save button in the editor.

**Comment by spocke** [comment] 2017-04-11 09:57
Images are automatically uploaded the fiddle just displays the blob size in the console when it's loaded. I need a similar sample fiddle that can illustrate the bug to be able to reproduce and escalate this one.

**Comment by z1lk** [comment] 2017-10-26 01:07
I had this problem and bypassed it. Leaving some notes here in case it helps you all work through this issue. There appears to be some confusion in this thread.
My task was to upload images to S3 from TinyMCE, without using a server-side upload handler, but rather using Javascript alone. Initially I tried using these options:
```javascript
images_upload_url: '/',
images_upload_handler: /* custom handler function to upload to S3 */
```
Setting `images_upload_url` triggers the upload tab in the Insert Image dialog, and the custom upload handler is passed images uploaded through that tab. This worked in my local development environment but not in a staging environment.
The final working solution was to use only the `file_picker_callback` option. My custom handler gets a file via a hidden file input field, uploads the file to S3, and returns the file URL to the image dialog via the callback.

**Comment by lnewson** [comment] 2020-05-02 07:02
Closing due a missing reproduction case for this issue and I was unable to reproduce it as well testing locally. If someone can provide a way to reproduce this using fiddle or similar, then please feel free to log a new issue.

Thanks!

**Closed by lnewson** 2020-05-02 07:02 UTC
Labels: component: upload, needs: more info, type: bug
