### ISSUE TITLE
Safari Crashes When I Use Code Plugin To Add Certain HTML

### ISSUE THREAD

**Issue by sslgeorge** [tinymce/tinymce#3716] opened 2017-06-05 16:26 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug:

**What is the current behavior?**
Safari browser becomes unresponsive and eventually crashes

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Steps:
1. Install tinymce 4.6.2 using npm/yarn  `yarn add  tinymce@4.6.2`
2. Create a html file with the code below
```
<html>
    <head>
        <title>Safari Deliverance</title>
        <link rel="stylesheet" href="node_modules/tinymce/skins/lightgray/skin.min.css">
        <link rel="stylesheet" href="node_modules/tinymce/skins/lightgray/content.min.css">
        <script type="text/javascript" src='node_modules/tinymce/tinymce.js'></script>
        <script>
            tinymce.init({ 
                selector:'textarea',
                plugins: "code",
                menu: {
                    tools: {title: 'Tools', items: 'spellchecker code'}
                }
            });
        </script>
    </head>
    <body>
        <h1>Delivering Safari From Evil Spirits</h1>
        <textarea type="text" class='tinymce'>
    </body>
</html>

```
3. Open the HTML file in Safari browser 
4. Click on the Tools menu on the menu bar and select `Source Code`
5. Insert the code below in the pop up menu displayed 

```
<table >
    <tbody>
        <tr>
            <td >
                <table >
                    <tbody>
                        <tr>
                            <td >
                                <table >
                                    <tbody>
                                        <tr>
                                            <td ></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </td>
        </tr>
    </tbody>
</table>
```
6. Click on `Ok`
7. Browser may become unresponsive, else repeat 3 - 6 (This behaviour does not happen every time, but it happens enough to be a really big issue)

**What is the expected behavior?**
The modal menu display closes and the textarea is updated with whatever changes were made

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
**TinyMce Version:** 4.6.2
**Browser:** Safari Version 10.1.1 (12603.2.4)
**OS:** macOS Sierra version 10.12.5
@spocke 
@gavdoug

**Comment by lnewson** [comment] 2020-05-02 09:46
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. I was able to reproduce it in TinyMCE 4.6.2 on Safari though, so it's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 09:46 UTC
