### ISSUE TITLE
Image resize handles positioned incorrectly when editing a scaled contenteditable element

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2417] opened 2015-10-05 16:47 UTC
Description of problem:
The image resize handles are positioned incorrectly when editing content that is inside a scaled (CSS transform) contenteditable element.

Steps to reproduce:
1. Create a contenteditable &ltg;div>
2. Apply a scale to the &ltg;div>
2. Instantiate an inline TinyMCE editor
3. Insert and image
4. Click on the image to bring up the resize handles
5. Notice that the handles are placed incorrectly.

Expected result:
The handles should appear in the correctly scaled positions.

Actual result:
The top/left position of the handles are not in the correct places.
> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7711](http://archive.tinymce.com/develop/bugtracker_view.php?id=7711) posted by [thePHPdev](http://archive.tinymce.com/profile.php?name=thePHPdev)_

> _**Tags:** [firefox safari chrome firefox safari9 chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by linux-man** [comment] 2016-06-02 01:08
Until a correct fix is committed, I managed this issue calculation the scale factor, saving it on a global window variable and editing lines 15539/40:
```
left: (targetWidth * handle[0] / window.cssScale + selectedElmX) - (handleElm.offsetWidth / 2),
top: (targetHeight * handle[1] / window.cssScale + selectedElmY) - (handleElm.offsetHeight / 2)
```
I posted to compete in the "Worst Hack of the Year" contest (and later remember what I've done).

**Comment by blackcathikari** [comment] 2016-07-25 02:12
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 02:12 UTC
Labels: browser: chrome, browser: firefox, browser: safari, browser: safari9, component: ui, origin: tinymce.com, type: bug

**Comment by samatcolumn** [comment] 2023-03-08 20:53
@metricjs it's easy to reproduce this, just add the following CSS to the body:

```
transform: scale(2.0);
transform-origin: 0, 0;
```
