### ISSUE TITLE
Error on inserting a table if the id attribute is forbidden by valid_elements

### ISSUE THREAD

**Issue by thorn0** [tinymce/tinymce#2546] opened 2015-12-10 10:20 UTC
Steps to reproduce:
1. set the valid_elements options to such a value that the id attribute isn't allowed
2. insert a table
3. see the error in the console

Fiddle: http://fiddle.tinymce.com/Plfaab

The cause of the problem is in `plugins/table/classes/Plugin.js`:

``` js
  editor.insertContent(html);         // insertContent sanitizes HTML,
  tableElm = editor.dom.get('__mce'); // so tableElm is null here!
  editor.dom.setAttrib(tableElm, 'id', null);
```

**Comment by blackcathikari** [comment] 2016-07-25 03:10
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Comment by thorn0** [comment] 2016-07-26 00:01
You can reproduce it with 4.4.0 as well using the fiddle link above. Please reopen.

**Comment by dsakko** [comment] 2016-07-26 07:12
Apologies for that. Thanks for re-checking and I'll re-open for you now.

**Comment by fyrkant** [comment] 2018-03-27 13:54
Can't reproduce this in the latest version of TinyMCE so I'm closing this issue, if you still are having problems with this please open up a new issue.

**Closed by fyrkant** 2018-03-27 13:54 UTC
Labels: plugin: table, type: bug
