### ISSUE TITLE
TinyMCE 5: Emoticons depend on font family

### ISSUE THREAD

**Issue by alecpl** [tinymce/tinymce#4879] opened 2019-03-05 16:13 UTC
Steps:
1. Goto the editor on https://www.tiny.cloud/
2. Create a new document.
3. Insert "smile" emoticon (the first icon in the second row).
4. Change font type to "Georgia".
5. Insert "smile" emoticon again.

Result: Two emoticons, one black/white and one colored.
Expected: Two black/white emoticons.

I expect exactly the selected icon to be inserted, which means it probably have to be wrapped in a span element with predefined font.

Additionally, imo the emoticons are too small. Could we have a way to make them bigger than the surrounding text, automatically?

**Comment by TheSpyder** [comment] 2019-03-06 06:14
This seems linux specific; on macOS and windows the emoji are the same regardless of font used. They also match the font size of the surrounding text.

http://fiddle.tinymce.com/4Dgaab/2
![smiles in two fonts mac](https://user-images.githubusercontent.com/298292/53859868-db168100-402a-11e9-969c-f817b6c02c23.png)
![smiles in two fonts windows](https://user-images.githubusercontent.com/298292/53859871-deaa0800-402a-11e9-8432-331ddd79c092.png)

Not sure what to do about this one 🤔

**Comment by lnewson** [comment] 2019-03-12 03:50
I was able to reproduce the icons being different on Fedora in Firefox but not in Chrome, so it may not be Linux specific. That is likely because Firefox does bundle a fallback emoji font (Twemoji Mozilla), which is also likely related to why this doesn't happen on Mac as it also bundles an emoji font (Apple Color Emoji).

One other issue I did note, is that the emoticons won't even show unless you have specific fonts installed on your OS. In my case, when I removed one of the fonts I had installed, then the emojis didn't render and I ended up with just a empty square instead. As such I've logged an internal issue to see if we can find a solution that works more consistently across OS's etc...

**Comment by TheSpyder** [comment] 2019-03-12 04:20
If someone deletes their emoji font I'm not sure there's much we can do. I don't want to go back to the image emoticons picker from v4, and applying a font fallback to every emoji just in case seems like overkill.

**Comment by androb** [comment] 2019-03-12 16:53
I agree. Closing for now

**Closed by androb** 2019-03-12 16:53 UTC
Labels: 5.x, plugin: emoticons, status: escalated

**Comment by wuhao775373334** [comment] 2019-09-23 09:05
我的表情加载，在chrome底下无法正常显示表情，在firefox下是可以正常加载的，我想知道我该怎么处理呢？谢谢。。。

**Comment by TheSpyder** [comment] 2019-09-23 09:45
@wuhao775373334 sorry we only speak English. Google translate gave me some idea of what you're saying, and I'm not sure why Chrome wouldn't display emoji while Firefox does. It's all down to the fonts installed on your system and how browsers display them; there isn't much the editor can do while we're using unicode characters.

**Comment by wuhao775373334** [comment] 2019-09-24 07:46
@TheSpyder  Thank you for your reply，I think it's probably the best way to use a set of characters defined by myself. emmm，anyway，thank you。
