### ISSUE TITLE
Constrain proportions in the image plugin does not work correctly

### ISSUE THREAD

**Issue by Paradinight** [tinymce/tinymce#4013] opened 2017-10-19 03:27 UTC
The example on the [homepage ](https://www.tinymce.com/) work, but the [example](https://www.tinymce.com/docs/demo/image-tools/) in the documentation does not work.

If you update the height the width is not updated. example image http://via.placeholder.com/350x150

**Comment by fyrkant** [comment] 2017-10-19 07:18
Seems to work for me, can you elaborate?

**Comment by Paradinight** [comment] 2017-10-19 07:35
If you change the height from 150px to 75px the width does not change. If you change the height again, it change the width. But the result is wrong.

It only works, if you change the width.

IE 11 / Chrome / FF same problem. Tinymce Version is 4.7.1

**Comment by Paradinight** [comment] 2017-10-19 07:53
The tinymce homepage use 4.6.7 and the documentation the 4.7.1.
4.7.1. does not work.

**Comment by fyrkant** [comment] 2017-10-19 08:01
Still can't reproduce it, see this fiddle: http://fiddle.tinymce.com/Ncgaab

The resize inputs only update on blur, so you have to click out of one input or tab over to the next one for it to update, is that the problem maybe?

**Comment by Paradinight** [comment] 2017-10-19 08:06
Insert -> image -> Source  http://via.placeholder.com/350x150 or  the google image-> height to 75px (or other). It does not work.

**Comment by fyrkant** [comment] 2017-10-19 08:14
Oh ok now I could reproduce it, it only happens on initial insert, not on images already in the editor! Sorry for being slow to get it!

**Comment by Paradinight** [comment] 2017-10-19 08:21
Image in the editor have the same bug. If you change the height in work, but if you do it again, it does not work.

**Comment by fyrkant** [comment] 2017-11-08 15:35
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2017-11-08 15:35 UTC
Labels: plugin: image, status: escalated, type: bug
