### ISSUE TITLE
theme: 'silver' 

### ISSUE THREAD

**Issue by huashaoZhao** [tinymce/tinymce#5088] opened 2019-07-22 09:24 UTC
After I set the theme:'silver'attribute, the form plug-in does not show.
![QQ图片20190722175831](https://user-images.githubusercontent.com/18644852/61624330-fc5ecd80-acaa-11e9-80e3-317c944c48da.png)
![QQ图片20190722175950](https://user-images.githubusercontent.com/18644852/61624331-fd8ffa80-acaa-11e9-8165-0118f644a371.png)

**Comment by lnewson** [comment] 2019-07-22 09:53
@huashaoZhao can you please provide more details, such as console logs, browser details, etc... and preferably a [fiddle](http://fiddle.tinymce.com) showing how to replicate the issue? It also be helpful if you can clarify what you mean by "form" plugin, as TinyMCE doesn't come with a form plugin, so I'm guessing it's a custom plugin?

**Comment by huashaoZhao** [comment] 2019-07-22 10:01
> After I set the theme:'silver'attribute, the form plug-in does not show.

![QQ图片20190722175831](https://user-images.githubusercontent.com/18644852/61624200-ba358c00-acaa-11e9-9959-3fb3f40b2cf7.png)
![QQ图片20190722175950](https://user-images.githubusercontent.com/18644852/61624204-bd307c80-acaa-11e9-8441-ec42cf1cf460.png)

**Comment by lnewson** [comment] 2019-07-22 10:10
Ahh I see you're using mobile. That is currently expected, as per https://www.tiny.cloud/docs/mobile/#configuringtheplugins only the autolink, autosave and list plugin is supported on mobile. As such I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/4848

I should note that issue should be resolved if you use the latest nightly build, as the change to only filter by theme instead of platform was merged to master on Friday, meaning it should be possible to use all plugins on mobile with the silver theme. In saying that though, it's not guaranteed to work since at the moment only the three supported plugins are tested. We plan to support a lot more and improve the silver theme on mobile in 5.1.

**Closed by lnewson** 2019-07-22 10:10 UTC
Labels: needs: more info
