### ISSUE TITLE
Link target can't be changed to "Current" for existing links

### ISSUE THREAD

**Issue by noraab** [tinymce/tinymce#5221] opened 2019-10-29 11:50 UTC
**What is the current behavior? Describe the bug**

If I edit an existing link in TinyMCE and change the "Open link in..." option from "New Window" to "Current Window", the change isn't saved (neither in HTML nor in edit link dialog if I open it again).

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

* In your [online Demo](https://www.tiny.cloud/docs/demo/full-featured/), create a link with "Open link in..." set to "New Window".
* Close the "Insert/Edit Link" dialog
* Edit the existing link and set "Open link in..." to "Current Window"
* Close the "Insert/Edit Link" dialog
* Open the dialog again and see that the value of "Open link in..." is not saved
* Inspect the HTML-Code of the TinyMCE content and see that there still is the "target=_blank" set 

**What is the expected behavior?**
* HTML is updated and "target=_blank" should be removed

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Version: 5.0.14 and following

**Comment by noraab** [comment] 2019-10-29 11:50
Probably related to [this issue](https://github.com/tinymce/tinymce/issues/5135).

**Comment by lnewson** [comment] 2019-11-04 11:18
I can confirm this is the same issue as https://github.com/tinymce/tinymce/issues/5135 and I've added this case to our internal tracker.

**Comment by lnewson** [comment] 2019-11-19 22:18
Sorry for the delayed update here, but this issue was fixed in TinyMCE 5.1 which was released last month. Please let us know if you have any further issues.

**Comment by lnewson** [comment] 2019-11-19 22:38
I'm really sorry, but I got the wrong version here, this has been fixed in 5.2 which has yet to be released not 5.1. So reopening the issue and since we've got a few tickets about this now I'll talk to our PM about backporting the fix for 5.1.3.

**Comment by lnewson** [comment] 2019-12-04 04:02
TinyMCE 5.1.3 has just been released to community which contains a fix for this issue. Please let us know if you have any further issues.

**Closed by lnewson** 2019-12-04 04:02 UTC
Labels: 5.x, resolution: fixed in coming release, status: escalated, type: bug

**Comment by plainnany** [comment] 2019-12-09 09:31
@lnewson hi，I use `@tinymce/tinymce-react`，beause tinymce license, I have to use self-hosted tinymce file, so when bug fixed, I have to download all tinymce file and update self-hosted files, is there an easier way?

**Comment by lnewson** [comment] 2019-12-09 09:56
@plainnany no if you're using self-hosted then you'll need to download and update the relevant resources to receive fixes, like you're already doing. If you use npm packages then that would likely be easier as you'd just need to update the version you're using, but that'll depend on your build/packaging process.

**Comment by plainnany** [comment] 2019-12-09 10:00
@lnewson fine, thanks
