### ISSUE TITLE
Maximum call stack size exceeded when inserting content

### ISSUE THREAD

**Issue by garyfagan1987** [tinymce/tinymce#3436] opened 2017-01-11 12:20 UTC
Hi there,

I'm seeing a "Maximum call stack size exceeded" when inserting content in Google Chrome. I'm only seeing this when "inline" is set to true. Please see the link below, one editor works, the other one doesn't.

https://codepen.io/garyfagan1987/pen/BpjQZg

Thanks

**Comment by fyrkant** [comment] 2017-01-20 13:27
I think this is related to #3047 and #3300.

**Comment by mattford** [comment] 2018-01-16 11:42
I am working on the same codebase as @garyfagan1987 and this issue appears to have been related to a modal being open covering the editor we were inserting into. This triggered a loop of focusin/focusout events, causing the maximum call stack error.

I can't seem to reproduce the issue on the codepen anymore, so it might be possible for this issue to be closed.

**Comment by tinydylan** [comment] 2020-04-26 12:50
Hi,

I'm unable to reproduce this issue. I tested in Firefox 75 and Chrome 81 on macOS 10.15.4, and Chrome 81 on Windows 10 (via Parallels).

I'll be closing the issue for now. If it still occurs, please let us know and we'll reopen. 

Thanks!

**Closed by tinydylan** 2020-04-26 12:50 UTC
