### ISSUE TITLE
unable to remove focus of tinymce editor

### ISSUE THREAD

**Issue by SivaPrakashK90** [tinymce/tinymce#4032] opened 2017-10-31 09:38 UTC
Hi,
I'm using TinyMCE in angular4 and I'm generating the TinyMCE editors dynamically in a loop by default focus is switching to newly created TinyMCE editor at last focus is maintained with last TinyMCE editor
and the page is scrolling down for each editor generation. I want to remove the focus of TinyMCE editors and page scrolling. and focus should be set to a button.

**Comment by spocke** [comment] 2017-11-02 16:00
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. It's some how auto focusing make sure that there is no api calls like execCommand etc that fire on the actual editor since that would move focus to that editor.

**Comment by SivaPrakashK90** [comment] 2017-11-15 05:54
Hi there I'm unable to reproduce the  issue but in my local when I'm able to reproduce this when I keep a breakpoint and wait for some time, in that case, it is TinyMCE is maintaining focus 
in my local in using TinyMCE_4.3.10 in fiddle it is TinyMCE_4.7.2
 I![tinymce_focus](https://user-images.githubusercontent.com/32359417/32821067-89b0ee54-c9f7-11e7-830b-231c8fb33e98.png)
 don't know the exact reason for that

**Comment by spocke** [comment] 2017-11-15 08:21
We can't work on this issue unless we can reproduce it. I will close this ticket until we get that information then we can reopen the ticket. I haven't seen any other focus issues similar to this so it might be something in the integration code.

**Closed by spocke** 2017-11-15 08:21 UTC
Labels: needs: more info, type: bug
