### ISSUE TITLE
Scroll to last tinymce when url ends with "#"

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2427] opened 2015-10-19 16:56 UTC
Description of problem:

Steps to reproduce:
1. Add a tinymce on a page with a scrollbar
2. Load the page with a final "#" at the end ('http://example.com/#')

Expected result:
Get the page refreshed without scrolling
Actual result:
The page is refreshed and automatically scrolled to the tinymce

Bug already noticed in forum: http://www.tinymce.com/forum/viewtopic.php?pid=106909

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7727](http://archive.tinymce.com/develop/bugtracker_view.php?id=7727) posted by [Fabrice](http://archive.tinymce.com/profile.php?name=Fabrice)_

> _**Tags:** [chrome chrome scroll]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by sebastien-mignot** [comment] 2015-11-25 17:55
@spocke Hi. Any news on this issue ? Is this something that has a chance of being solved in the near future ?

**Comment by s1c-design** [comment] 2015-11-29 21:14
Hello... I can confirm this about Chrome (Firefox has no such issue).
If the URL ends with a hashtag, for example if the user clicks on a <a href="#"> element, then when TinyMCE renders it causes the vertical scroll bar to change position!

I wasted 2 full days trying to figure out what was the problem until I found Lizard's response on http://stackoverflow.com/questions/3301059/tinymce-mcetoggleeditor-scroll-focus-issue

If you remove all href="#" from you anchor elements you should be okay.

**Comment by sebastien-mignot** [comment] 2015-11-29 22:29
@s1c-design The fact that it scrolls when we use "#" is the bug. If we don't use it anymore, we indeed won't see the bug, but that doesn't help us much :/ We need "#".

**Comment by spocke** [comment] 2015-11-30 01:39
Verified this one it's very very weird it has to do when the iframe content being produced and it auto scrolls to that. I think it's a chrome bug.

**Comment by Kitamo** [comment] 2016-01-18 09:17
Having same issue, we also need '#' at the end of url. Currently we have implemented workaround but still looking for fix from rather chrome or tinyMCE.

**Comment by spocke** [comment] 2016-01-18 10:21
This can easily be avoided by blocking the default link behavior of #.

**Comment by sebastien-mignot** [comment] 2016-01-18 10:40
@spocke Could you explain what you mean by "blocking the default link behaviour of #" please ?

**Comment by Kitamo** [comment] 2016-01-18 10:43
+1 to sebastien-mignot, also would like to know :)

**Comment by spocke** [comment] 2016-01-18 11:12
if a link with # is used to generate tinymce then just use something like:
```<a href="#" onclick="init();event.preventDefault();">init editor</a>```

The preventDefault call blocks the native scroll to # logic in the browser. What I think is happening is that Chrome tries to scroll to the top of the iframe document when the editor is initialized in the same link.

**Comment by Kitamo** [comment] 2016-01-18 11:23
Thanks for response :+1: , but not our case unfortunately.

**Comment by spocke** [comment] 2016-01-18 11:27
Ok, then provide steps to reproduce that. Thanks.

**Comment by sebastien-mignot** [comment] 2016-01-18 11:37
@spocke Thank's for the response, but indeed you are describing basic html links, which is not what anyone using tinyMCE in his platform/saas product/etc. is doing. The default case is usually to make a navigation inside the app with javascript and onHashChange, so the browser don't reload the page each time the user clicks.

Steps to reproduce : 
You bind an event on window.onhashchange : 
```
window.onhashchange = function () {
    //check the new hash, and change the main screen of the app
}
```
And then everywhere on your app, you have items (buttons for instance, that are not only <href> elements, but can be divs too), on which you bind an event (with jQuery or your other framework of choice, we use Jsdom but it's all the same), that does the work logic (saving to db, getting some other infos...), and then does ```window.location.hash = "#appProfile";``` or something equivalent. And oftentime the convention for the Home app or the main page is ```window.location.hash = "#";```, and thus there is this bug every time we want to use tinyMCE on the main page of the app.

**Comment by Kitamo** [comment] 2016-01-18 12:00
Yeap, @sebastien-mignot 's answer fully describes  what we use hash for - to not reload page and just scroll to required element.

**Comment by spocke** [comment] 2016-01-18 12:01
document.location.hash="" would scroll the browser to the top anyway. So I guess one should always avoid any navigation to "#" in any application page.

**Comment by spocke** [comment] 2016-01-18 12:02
So the case is if you initialize tinymce while navigating to "#" on a page regardless how it's doing that though location or links.

**Comment by sebastien-mignot** [comment] 2016-01-18 12:14
@spocke no, setting location.hash to "" or "#" doesn't scroll on my app, it just does the event I binded.
But as you said next, indeed the problem is when we initialize tinymce, not when we change the hash. So we already are on the "#" page, there we load tinyMCE (without changing the hash or anything), and there there is the bug

**Comment by spocke** [comment] 2016-01-18 12:33
Ok I have a potential fix: https://github.com/tinymce/tinymce/commit/9cb88a7f90d411f335ef82de1bfeddd20519aa0d

This one is very very strange. Chrome scrolls to <link> elements in iframes if they are produced at the same time as the "#" navigation occurs so this fix just delays the loading of the CSS so might produce flicker if the CSS takes to long to load. Have no idea how to do both things here since no matter what I set on the iframe id, name etc it still scrolls to it.

**Comment by FabriceGaudin** [comment] 2016-01-18 14:23
@spocke This fix solves my problem, thank you.

**Comment by sebastien-mignot** [comment] 2016-01-18 14:52
@spocke yes, thank's a lot

**Comment by Kitamo** [comment] 2016-01-18 16:19
Thanks @spocke, that really helps!
As I understand this fix will be part of future TinyMCE release (4.3.4), right?

**Comment by spocke** [comment] 2016-01-18 16:29
Yes. This will be part of the next patch release.

**Comment by blackcathikari** [comment] 2016-07-25 02:14
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 02:14 UTC
Labels: browser: chrome, component: ui, origin: tinymce.com, status: verified, type: bug
