### ISSUE TITLE
directionality: 'rtl', dose not work on 'preview'.

### ISSUE THREAD

**Issue by mlibre** [tinymce/tinymce#3854] opened 2017-08-02 15:32 UTC
i set directionality: 'rtl' in the tinymce config file, but it dose not work on preview.

![a](https://user-images.githubusercontent.com/8473036/28881252-ca4faf50-77bc-11e7-95cf-6fbd4c1d5cc1.gif)

config file:
[tinymceInit.txt](https://github.com/tinymce/tinymce/files/1194427/tinymceInit.txt)

version: 4.6.4
OS: Linux

**Comment by lnewson** [comment] 2020-05-02 10:29
Hi,

I was able to confirm this issue still exists in all versions of TinyMCE 4. However, it appears as though we've fixed the issue in TinyMCE 5 as the preview dialog now displays the RTL content correctly. Here's a fiddle to demonstrate: http://fiddle.tinymce.com/6hhaab/2

Unfortunately there's been a number of changes done in TinyMCE 5, so I'm not exactly sure what would have fixed this and given it's not a critical issue we're unlikely to try to backport it to TinyMCE 4. As such I'd suggest upgrading to TinyMCE 5 to get this issue resolved and on top of that I'm also going to close this since it's fixed in TinyMCE 5. If you can still reproduce the issue in TinyMCE 5, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 10:29 UTC
Labels: 4.x, plugin: preview
