### ISSUE TITLE
Table Toolbar appears without table and position also wrongly

### ISSUE THREAD

**Issue by gopsur1975** [tinymce/tinymce#4528] opened 2018-08-14 10:33 UTC
**Do you want to request a *feature* or report a *bug*?*
   Report a bug which is happens in Chrome version >=67 and works fine in version 62 
**What is the current behavior?**
   Table Toolbar appears without table and position also wrongly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
![image](https://user-images.githubusercontent.com/11853725/44086834-879a10b8-9fdb-11e8-84e7-aaf56f03a62e.png)

**What is the expected behavior?** 
Table toolbar should not show without table 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Works Chrome version 62 and not worked >67

**Comment by fyrkant** [comment] 2018-08-14 10:34
Please create a fiddle with a clear reproduction.

**Comment by wonderbugtiny** [comment] 2019-04-08 03:40
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:40 UTC
Labels: needs: more info
