### ISSUE TITLE
file_picker_callback: callback return different value for empty and selected text

### ISSUE THREAD

**Issue by bes-internal** [tinymce/tinymce#5675] opened 2020-05-18 18:22 UTC
file_picker_callback generate diffent code if text selected (make link) and empty text (insert at cursor)

http://fiddle.tinymce.com/Yihaab
Steps to reproduce:
1. Click on link icon
2. Click on upload icon
3. selet file with space in name
4. save and show source code
5. get something like `<p><a href="a b.pdf">a b.pdf</a></p>`. First result.
6. type some in editor, select text, repeat steps 1-4
7. get something like `<p><a href="a%20b.pdf">sdf</a></p>`. Second result.
First and second result differ!

v5.2

**Comment by lnewson** [comment] 2020-05-19 01:47
@bes-internal I can confirm this is a known issue with the link plugin, as it's currently ignoring the `text` value returned by the file picker callback. We already have an issue about this however, so I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/5457

**Closed by lnewson** 2020-05-19 01:47 UTC
