### ISSUE TITLE
Build customizer contains old version 4.3.2 instead of 4.3.10

### ISSUE THREAD

**Issue by robfaas** [tinymce/tinymce#2874] opened 2016-04-22 11:26 UTC
The build customizer on the tinymce.com site contains old version 4.3.2 instead of 4.3.10 https://www.tinymce.com/download/custom-builds/

**Comment by acshef** [comment] 2016-04-22 15:23
Duplicate of #2868.

**Comment by Afraithe** [comment] 2016-04-28 22:46
This has been fixed.

**Closed by Afraithe** 2016-04-28 22:46 UTC
Labels: component: website, type: bug
