### ISSUE TITLE
Since 4.6.7 popup window can't be closed

### ISSUE THREAD

**Issue by gwleuverink** [tinymce/tinymce#3939] opened 2017-09-21 13:00 UTC
Since version 4.6.7 It is not possible to close a TinyMCE window with `parent.tinyMCE.activeEditor.windowManager.close();`

In version 4.6.6 and below this works just fine.

Steps to reproduce:
Use `tinyMCE.activeEditor.windowManager.open` inside `file_browser_callback` to open a window. 

If an item inside this window is clicked, some logic is executed and the window should be closed with `parent.tinyMCE.activeEditor.windowManager.close();`.

While step debugging it is clear that in version 4.6.6 this closes the window, but in 4.6.7 nothing happens.

This issue exists on the latest versions of Chrome, Firefox, Safari and Edge. (Explorer & Opera not tested)

**Comment by spocke** [comment] 2017-09-21 13:07
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Seems to work fine when I try it though. Thanks

**Comment by gwleuverink** [comment] 2017-09-21 14:20
Hi @spocke. Thanks for your quick reply. [This fiddle](http://fiddle.tinymce.com/9agaab/7) demonstrates the behaviour.

A new window is opened when you click icon to insert an image. After the window is opened, click the 'close window' button. In our real use-case this would be an image in a file manager.

If you first try this in version 4.6.6 it will work. But run the same code in version 4.6.7 it behaves differently. It looks like the code closes the first popup window (the one with the image properties) instead.

**Comment by afalchetti** [comment] 2017-09-25 02:38
Hi, I'm having a similar issue: clicking "select" on a django-filebrowser popup does nothing (because windowManager.getParams() returns an empty object).
After some digging, I noticed that 08080825d1c99a10f795d2843a4e44ceb7d67420 changes the behaviour of getTopMostWindow(). Before it chose the [last element of windows](https://github.com/tinymce/tinymce/commit/08080825d1c99a10f795d2843a4e44ceb7d67420#diff-2b4d1500471c6c56aaccb532670b3babL49), now it chooses the [first one](https://github.com/tinymce/tinymce/commit/08080825d1c99a10f795d2843a4e44ceb7d67420#diff-b32538f9c60cbb8c9988b01b0d1b90a0R93). Both calls (getParams and close) depend on this function. I'm guessing that's the bug.

I've changed it back and my code works.

**Comment by spocke** [comment] 2017-09-25 07:59
Yes, there is a bug with the windowmanger getTopMostWindow. We will correct that.

**Comment by fyrkant** [comment] 2017-10-03 12:44
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2017-10-03 12:44 UTC
Labels: component: ui, status: escalated, status: verified, type: bug

**Comment by gwleuverink** [comment] 2017-10-03 12:45
Thanks!
