### ISSUE TITLE
Format text before insert link 

### ISSUE THREAD

**Issue by FSGrtz** [tinymce/tinymce#7524] opened 2022-01-17 19:49 UTC
**What is the current behavior? Describe the bug**
When I format a text before inserting a link, it doesn't work

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1. Type some text
2. Format this text, for example changing the font size
3. Insert a link (in current window or new one)
4. Click in the link
5. Nothing happens

**What is the expected behavior?**
Open link

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Chrome in version 97.0.4692.71
Current tinyMCE version 5.10.2

HTML with formatting before inserting the link:
`<p><a title="test" href="https://www.google.com/"><span style="font-size: 10pt;">test</span></a></p>`

HTML with formatting after inserting the link:
`<p><span style="font-size: 10pt;"><a title="test" href="https://www.google.com/">test</a></span></p>`

with the formatting before inserting the link, the a tag ends up being the span's parent

**Comment by hamza0867** [comment] 2022-05-01 10:55
Hello @FSGrtz ,

Thank you for the report. However, what you are describing here, is the intended behavior. If you want to open a link you should instead use ctrl+click ( or cmd+click on Mac ) or use the right click and then open link command.

I am closing this issue as it is not a bug.

**Closed by hamza0867** 2022-05-01 10:55 UTC
