### ISSUE TITLE
Embedding doesn't work when using media_url_resolver ('X-Frame-Options')

### ISSUE THREAD

**Issue by PeraMika** [tinymce/tinymce#6083] opened 2020-10-05 23:25 UTC
Embedding doesn't work when using [media_url_resolver](https://www.tiny.cloud/docs/plugins/media/#media_url_resolver) (in my case, I'm using it to return HTML to embed YouTube videos that is slightly different from TinyMCE's default HTML for embedding YouTube videos). 

Chrome shows this error: 
> Refused to display 'https://www.youtube.com/watch?v=a3ICNMQW7Ok' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

and Firefox (81.0.1):

> The loading of “https://www.youtube.com/watch?v=a3ICNMQW7Ok” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“.

But if I don't use `media_url_resolver` - then there are **no** issues, embedding works OK. 

This is the setup:

```javascript
tinymce.init({
    selector: "textarea",
    menubar: false,
    plugins: [
        "media",
    ],
    toolbar: "media",
    media_dimensions: false,
    media_alt_source: false,
    media_poster: false,
	media_url_resolver: function (data, resolve/*, reject*/) {
	  if (data.url.indexOf('youtube') !== -1) {
		  var embedHtml = '<iframe src="' + data.url + '" width="100%" height="359" frameborder="0" allowfullscreen></iframe>';
		  console.log(embedHtml);
		  resolve({html: embedHtml});
	  } else {
		  resolve({html: ''});
	  }
  }
});
```
`console.log` gives: 
```html
<iframe src="https://www.youtube.com/watch?v=a3ICNMQW7Ok" width="100%" height="359" frameborder="0" allowfullscreen></iframe>
```
**FIDDLE:** http://fiddle.tinymce.com/0uhaab

**What is the expected behavior?**

When using `media_url_resolver` - embedding should also work (as it already works when not using it).

I'm using:
-  TinyMCE 5.4.2
-  Browsers: Firefox 81.0 (64-bit); Chrome 85.0.4183.121 (64-bit);
-  OS: Windows 7 (64-bit)

**Comment by FilipQL** [comment] 2020-10-05 23:40
The same issue is also on Linux Mint 19.2 ("Tina"): 

![screenshot](https://user-images.githubusercontent.com/18264428/95142689-90179f00-0774-11eb-8813-8590e508771d.png)

(on both Firefox 81.0 (64-bit) && Chromium 85.0.4183.121)

**Comment by lnewson** [comment] 2020-10-05 23:57
Closing as a duplicate of #5587. This is a browser protection and isn't something we can fix. Also as noted in that issue, the default media resolver will convert youtube URLs to the embed equivalent, which does have the relevant server headers.

**Closed by lnewson** 2020-10-05 23:57 UTC
