### ISSUE TITLE
Key events are not triggering in mobile web browsers

### ISSUE THREAD

**Issue by developeronboard** [tinymce/tinymce#5615] opened 2020-04-28 10:58 UTC
Currently am using V4.5.7,  ` editor.on('keyup',function(){alert("tiny");});`  this alert was not trigerring in android mobile browsers. any suggestions please.

**Comment by lnewson** [comment] 2020-04-28 11:03
I'm sorry, but TinyMCE 4.5 is no longer supported. TinyMCE 5 is our supported community version and TinyMCE 4.9.x is only receiving bug fixes for major issues. I'd suggest upgrading and seeing if that fixes your issue. I'm going to go ahead and close this since it's not a version we are supporting, but if you can reproduce on a supported version then please let us know and we'll reopen this issue.

I should also add that Android devices don't send key events, as they use an IME for input instead. As such so you'll need to listen to either composition or `input` events.

**Closed by lnewson** 2020-04-28 11:03 UTC
