### ISSUE TITLE
Browser crash highlighting with contentEditable=false as last element

### ISSUE THREAD

**Issue by jeffhoffman1** [tinymce/tinymce#4504] opened 2018-07-26 22:27 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
If an element with contentEditable=false is the last element in the editor, and a user attempts to select/highlight the text starting with the cursor just to the right of the non-editable element the entire browser crashes. Takes a couple tries to play with the cursor positioning but easy to reproduce.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
http://fiddle.tinymce.com/hxgaab/1

**What is the expected behavior?**
Chrome not to crash.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Tested on windows and mac, did not work in previous versions

**Comment by bdjnk** [comment] 2018-07-30 17:42
A potential workaround is to use `<input type="button" value="..." ...>` instead of and inline elements with `contentEditable="false"`, as shown here http://fiddle.tinymce.com/hDdaab

**Comment by jeffhoffman1** [comment] 2018-07-30 19:01
Neat. I've been adding a hidden element with a space inside of it at the end of my content, but that looks like a good approach.

**Comment by nathguen** [comment] 2018-08-14 20:41
@bdjnk It's a neat idea. Unfortunately, that solution can't be used when the `<input ... />` needs to be a child of a custom component that needs to be uneditable as a whole.

For now, it seems adding a space at the end of the content seems to work. It still feels like a hacky solution for an otherwise safe use case. It'd be nice if the creators of TinyMCE can provide some sort of solution for this.

**Comment by RadiantPunch** [comment] 2018-08-30 18:15
I've been having issues with Chrome crashing when developing custom plugins for TinyMCE in WordPress. I've noticed it crashing when double clicking on certain elements in the editor like `<meter>` when I right click on certain contenteditable/noneditable elements, though I can't really figure out what the pattern is with that. It seems kind of random.

**Comment by bdjnk** [comment] 2018-09-06 12:56
Excellent point @nathguen, and good suggestion @jeffhoffman1. I'd be interested to see how you're implementing this solution. Here's my take on the least obtrusive way to resolve this bug in a manner similar to what you describe http://fiddle.tinymce.com/Pzgaab

**Comment by lnewson** [comment] 2020-08-15 09:41
Hi,

I attempted to reproduce this using TinyMCE 4.9.11 and 5.4.1 on Chrome 84.0.4147.125, however I was unable to reproduce the original issue. It's likely this has been fixed since this issue was originally reported, either in TinyMCE or in Chrome, so I'm going to close this. If you're still able to reproduce the issue using the above versions, let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-08-15 09:41 UTC
