### ISSUE TITLE
Text highlighted on alignment

### ISSUE THREAD

**Issue by andtrobs** [tinymce/tinymce#4235] opened 2018-02-20 16:04 UTC
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
If the cursor is placed at the end of a line of text and one of the text alignment buttons is clicked, the text is aligned correctly but highlighted. This means that if the user types, aligns and continues typing the highlighted text is overwritten. If a text alignment button is used with the cursor placed anywhere but the end of the line the text is not highlighted.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
* Type text
* Leave cursor at end of line
* Align right

**What is the expected behavior?**
Not to highlight the text

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Using fiddle this seems to affect current and previous versions

**Comment by tinydylan** [comment] 2020-04-21 13:39
Hi,

I tested out this scenario on this [demo page](https://www.tiny.cloud/docs/demo/full-featured/) and I'm unable to reproduce the issue. I'm not seeing any text being selected when I change the alignment.

I'm closing this issue for now. If the issue still occurs for you, please let us know.

Thanks!

**Closed by tinydylan** 2020-04-21 13:39 UTC
Labels: component: formatting, status: escalated, status: regression, status: verified, type: bug
