### ISSUE TITLE
Inlite editor breaks dialogs from other editors in Chrome + TinyMCE 4.7

### ISSUE THREAD

**Issue by mcaskill** [tinymce/tinymce#4263] opened 2018-03-02 19:46 UTC
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behaviour?**

On Chrome, dialogs are frequently broken when at least one Inlite editor is present alongside a classic editor.  
Works fine if the inline editor does not use Inlite).

You will either have a blank dialog backdrop OR the dialog is created where the first toolbar button is.

**Minimal demo of the problem and screen capture.**

http://fiddle.tinymce.com/amgaab

![tinymce-amgaab](https://user-images.githubusercontent.com/29353/36918372-b4a75628-1e27-11e8-9850-2a08061f17e5.png)

**What is the expected behavior?**

The dialog should open in the proper location in the DOM and render its contents appropriately.

**Which versions of TinyMCE, and which browser / OS are affected by this issue?  
Did this work in previous versions of TinyMCE?**

Bug tested on:
- macOS 10.13
- Google Chrome 64.0.3282.186
- TinyMCE 4.7.* (and edge)

Works fine on:
- Firefox 48
- TinyMCE 4.6.*

Works fine on Firefox.

**Comment by donShakespeare** [comment] 2018-03-24 22:16
Same here, in the presence of any of my hidden stripped-down TinyMCE instances that I use to accomplish background stuff, the main inlite themed editor goes kaboom.

This is me trying to access the image dialog
![image](https://user-images.githubusercontent.com/5103329/37869530-280e8226-2f76-11e8-9c85-7d319ecfd100.png)

**Comment by ben-mckernan** [comment] 2018-09-13 06:48
I have also run into this issue. It seems to be caused by having two themes loaded on the same page, not necessarily the inlite theme. For example I can reproduce it with "modern" and "modern-copy". The theme that has its dialog opened first will function correctly whilst the second theme's dialog will break.

This issue also seems to be related to #4263

**Comment by SimonFc** [comment] 2019-07-24 09:52
I'm closing this since the issue is limited to Tiny 4. If you encounter any similar issues when using the themes for Tiny 5 then open up a new issue so that we can take a look at it. Thanks!

**Closed by SimonFc** 2019-07-24 09:52 UTC
Labels: status: escalated, status: verified, type: bug
