### ISSUE TITLE
Merging two cells - issues in Firefox

### ISSUE THREAD

**Issue by WarwickGoatee** [tinymce/tinymce#4914] opened 2019-03-26 15:50 UTC
**Do you want to request a *feature* or report a *bug*?**
This is possibly a bug with TinyMCE, possibly a bug with Firefox, but I thought it worth registering with you in case it's the former.

**What is the current behavior?**
When you drag across two cells in a table then try to merge them in Firefox, it doesn't work. If you drag across more than two, it does work, the look of the selection changing slightly. If you drag across more than two, then back to two, it works then as well.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Drag across two cells in Firefox and try to merge them as described above. I've reproduced this on the full featured example on your site.

**What is the expected behavior?**
That it would merge two cells without any extra dragging needed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
Firefox only as far as I know. I'm on Ubuntu, but I've had colleagues on other OSes reporting a similar issue.

**Comment by wonderbugtiny** [comment] 2019-03-27 00:37
I couldn't replicate this issue using Firefox on Ubuntu, Windows or MacOS. Could you please provide us with a video of the problem so, we can try and replicate it?

Another thing to investigate in the meanwhile would be to check if any browser extension you have might interfere with rich text editing or selection. Thank you.

**Comment by lnewson** [comment] 2019-06-24 03:37
Closing due to inactivity. If you can provide the details requested above, then we're more than happy to re-open this issue.

**Comment by noraab** [comment] 2019-06-28 15:28
Hi @wonderbugtiny and @lnewson ,
I'm experiencing the same issue on Firefox 67.0.4 (64-bit) on Windows.

Merging of two cells doesn't work.
If I select a third cell and than go back to two cells, it works.
Can be reproduced on your[ full featured demo site](https://www.tiny.cloud/docs/demo/full-featured).
I recorded a short video:
![2-cell-merge-firefox](https://user-images.githubusercontent.com/39309050/60353323-1833c400-99ca-11e9-9f7a-21852a4c171e.gif)

Could you please reopen this issue?

**Comment by lnewson** [comment] 2019-06-28 22:28
Thanks @noraab for the video, I can also reproduce the issue using Firefox on Mac so I'll reopen it.

**Comment by hxnam0509** [comment] 2019-07-23 04:52
Hi @wonderbugtiny , @lnewson 
I am experiencing this bug too.
I am using Firefox 68.0.1 on macOS Mojave 10.14.5

**Comment by wonderbugtiny** [comment] 2019-07-23 21:49
HI @hxnam0509 , I have logged a ticket internally for us to work on the issue. We will update you when a fix is available.

**Comment by blackcathikari** [comment] 2019-08-26 02:36
A small note: the table cell context toolbar is also anchored to the wrong cell when you try to select across two cells.

**Comment by itajackass** [comment] 2019-11-12 15:57
Not fix yet?

**Comment by blackcathikari** [comment] 2019-11-12 23:02
Not yet, unfortunately. We are planning work on tables, but there's no timeframe on a fix for this specific issue yet.

**Comment by wiejakp** [comment] 2021-01-07 18:37
Just FYI, i'm having same issue in version Version 4.9.11. I'm having this issue when table is empty though.

**Comment by vcluopeng** [comment] 2021-01-20 09:51
Version 5.6.2 still has this problem
Firefox 85

**Closed** 2021-01-27 08:04 UTC
Labels: browser: firefox, plugin: table, status: escalated, status: verified
