### ISSUE TITLE
Use tinymce to add image function, the image is added successfully, but the image size cannot be adjusted

### ISSUE THREAD

**Issue by munitioner** [tinymce/tinymce#6159] opened 2020-10-31 03:13 UTC
Use tinymce to add image function, the image is added successfully, but the image size cannot be adjusted

![20201031111010](https://user-images.githubusercontent.com/14157458/97769957-06d46c00-1b6a-11eb-9cba-94cb3fa5d9c7.png)

**Comment by lnewson** [comment] 2020-10-31 03:20
Hi @munitioner, can you please provide a reproduction case for this issue? At a glance, it looks like you're missing some CSS files, which is what would normally show the resize handles.

**Comment by munitioner** [comment] 2020-10-31 03:44
My development environment is Vue，I install the these two plugins and zh_CN.js
"@tinymce/tinymce-vue": "^3.2.3",  
"tinymce": "^5.5.1",
![20201031114214](https://user-images.githubusercontent.com/14157458/97770443-4c933380-1b6e-11eb-9ba0-44c7fd9b2d36.png)

plugins:
          "lists advlist paste image imagetools colorpicker textcolor wordcount contextmenu autoresize table media link preview fullscreen hr",
        toolbar:
          "undo redo | formatselect | forecolor backcolor bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | numlist bullist outdent indent preview fullscreen | image table link | removeformat hr paste",

**Comment by lnewson** [comment] 2020-10-31 03:53
That's not a reproduction case and doesn't show the rest of your code, so I'm afraid we can't provide much assistance from just that screenshot. Given it's a vue project, maybe you could create a reproduction case using codesandbox?

Also, this previous community post maybe useful to you, as it shows how to load the CSS. I mention this, as based on the above screenshot it seems like you might be missing the Content UI CSS: https://github.com/tinymce/tinymce/issues/2836#issuecomment-544790987

**Comment by munitioner** [comment] 2020-10-31 04:54
Thanks for your answer
my codesandbox project https://codesandbox.io/s/async-surf-srhqk?file=/src/App.vue
I introduced Content UI CSS in the project, but it seems the same as before, still can’t change the image size

**Comment by lnewson** [comment] 2020-10-31 06:04
@munitioner the above code sandbox shows that you're still missing the relevant TinyMCE content styles. I've forked your code sandbox to add the content styles as per my link in my previous comment: https://codesandbox.io/s/wispy-shadow-jvbq2?file=/src/App.vue

Does that solve your issue?

**Comment by munitioner** [comment] 2020-10-31 06:23
Thank you for your answer, its solve my issue,
Have you installed @vue/cli-plugin-babel plugin in the codesandbox？

**Comment by lnewson** [comment] 2020-10-31 06:51
No, the only changes I made were the following lines:
```
import contentUiCss from "!!raw-loader!tinymce/skins/ui/oxide/content.css";
import contentCss from "!!raw-loader!tinymce/skins/content/default/content.css";
```

```
content_style: contentUiCss.toString() + contentCss.toString(),
content_css: false,
skin: false,
```

Anyways, since this has solved your issue I'm going to close this issue.

**Closed by lnewson** 2020-10-31 06:51 UTC
Labels: needs: more info

**Comment by munitioner** [comment] 2020-10-31 11:57
Thank you for your answer
There is another problem. I set the height and width of tinymce, but it did not succeed.
my codesandbox project https://codesandbox.io/s/async-surf-srhqk?file=/src/App.vue

**Comment by munitioner** [comment] 2020-10-31 13:00
#### Although adding the following code can solve my problem, I want to know why such a problem occurs, whether it is a tinymce problem or a vue problem

``` javascript
import contentUiCss from "!!raw-loader!tinymce/skins/ui/oxide/content.css";
import contentCss from "!!raw-loader!tinymce/skins/content/default/content.css";
```
``` javascript
content_style: contentUiCss.toString() + contentCss.toString(),
content_css: false,
skin: false,
```

**Comment by lnewson** [comment] 2020-10-31 22:22
It's neither problem, just more a misunderstanding of how things work when bundling using a module loader. TinyMCE runs inside an iframe to ensure the content is sandboxed, so the content css can't be bundled into the root page CSS like the skin.css file. That means you either need to host the content css and set the [skin_url](https://www.tiny.cloud/docs/configure/editor-appearance/#skin_url) and [content_css](https://www.tiny.cloud/docs/configure/content-appearance/#content_css) settings to point to the static location, or bundle the content CSS like in the above.

I should add we're aware the module loader documentation is lacking in this area and have https://github.com/tinymce/tinymce-docs/issues/1466 open to improve that.

**Comment by munitioner** [comment] 2020-11-01 04:06
Thanks for your reply, thanks again

**Comment by munitioner** [comment] 2020-11-01 04:44
How to add the right mouse button to tinymce to copy and paste？
