### ISSUE TITLE
"default_link_target:'_blank'" of autolink plugin doesn't work in IE

### ISSUE THREAD

**Issue by hayashiyasufumi** [tinymce/tinymce#7453] opened 2021-12-08 09:04 UTC
Initialized as below, but in IE, default_link_target does not work.
`tinymce.init({
selector: '#mytextarea',
height: 800,
plugins: 'link, autolink',
default_link_target: '_blank'
});`
In IE, a tag created by autolink. No target attribute.
`<p><a href="http://www.google.com/">http://www.google.com/</a></p>`
In Edge, a tag created by autolink.
`<p><a href="http://www.google.com/" target="_blank" rel="noopener">http://www.google.com/</a></p>`

tinymce version is 5.10.2.

**Comment by landtastic** [comment] 2021-12-21 01:33
Hi, unfortunately we are dropping IE 11 support in our next release. See https://www.tiny.cloud/blog/tinymce-6-0-remove-internet-explorer-11-support/ for more information. I'm going to close this since we are no longer accepting IE 11-specific bug reports, but if you can reproduce the issue on a supported browser then please let us know and we'll reopen this issue. If you have any feedback or concerns about TinyMCE dropping support for IE, please use https://github.com/tinymce/tinymce/discussions/7309.

**Closed by landtastic** 2021-12-21 01:33 UTC
Labels: resolution: wont fix
