### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getRng' of null

### ISSUE THREAD

**Issue by anormal81** [tinymce/tinymce#3782] opened 2017-07-03 08:04 UTC
Hi,

found a bug in tinymce 4.6.4.
We add an inline editor to the page and remove/destroy them after usage. remove does not unbind the document mouseup event, because in unregisterDocumentEvents the editorManager.activeEditor is still set.

Each click on the page now gives the error: "Uncaught TypeError: Cannot read property 'getRng' of null" in function documentMouseUpHandler, registered as DOM.bind(document, 'mouseup', documentMouseUpHandler);

Problem seems to be, that "f.fn.tinymce = function(a) {" first creates the editors and then renders them. Both (create and render) add the editor to the list EditorManager.editors. Function "removeEditorFromList" only removes the editor by id and the first editor instance found. 

removeEditorFromList must remove all instances with the same id or the render function should not add the editor again.

**Comment by brunomlopes** [comment] 2017-07-28 14:32
We've hit the same issue. I've isolated our case to a sample at https://github.com/brunomlopes/jquery.tinymce-issue , which can be seen in runtime at http://brunomlopes-jquerytinymce-issue.azurewebsites.net/

**Comment by oleghind** [comment] 2017-08-11 17:21
I have the same problem, is there any workaround?

**Comment by spocke** [comment] 2017-08-11 17:54
Are you using the jquery plugin? It has a known bug that we have scheduled work on to fix this sprint. Just want to verify that it's the same issue.

**Comment by oleghind** [comment] 2017-08-11 18:05
yes I am using jquery plugin, is there any ETA? maybe I should just wait

**Comment by fyrkant** [comment] 2017-08-31 10:18
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2017-08-31 10:18 UTC
Labels: status: escalated, status: verified, type: bug

**Comment by mlorant** [comment] 2017-09-11 13:59
By last version you mean 4.6.6, right? We're getting it since we upgraded from 4.6.4 to the last version. Well some of my users are getting it and the error is push up to Sentry: 
```
TypeError: Cannot read property 'getRng' of undefined
  at Object.p.focus (/npm/tinymce@4.6.6/tinymce.min.js:14:2157)
  at p [as execCommand] (/npm/tinymce@4.6.6/tinymce.min.js:10:99)
```
I have been able to reproduce it in local using the non-minified version. The error is raised when executing `tinymce.execCommand('mceFocus', false, tinymce_node_id);` on an inline editor... Is it related or another independant error?

**Comment by mtilokani** [comment] 2018-04-16 09:37
Hi, I am facing the same issue.

https://github.com/tinymce/tinymce/issues/4343

Please help me solve this.

**Comment by marhyno** [comment] 2019-01-10 22:09
Hi this bug still persists, // version 4.9.2

**Comment by iliyanz** [comment] 2019-11-30 18:00
Check your themes. This error I got when i was missing **modern** theme.

**Comment by mikeelemuel** [comment] 2020-12-03 15:52
Issue is still happening on version 5

**Comment by jshprz** [comment] 2021-05-04 09:05
Been stuck on this issue. Is there any update on this?

**Comment by dgwyer** [comment] 2021-05-05 17:39
Same here. Got the same issue. Is there any news on an update?

**Comment by omarzina** [comment] 2021-05-31 16:16
I was just about to post "same issue here", but realized that I was getting a previous error because I was trying to bind `init` to an undeclared function 🤦 
Posting it nonetheless in case it helps anyone.

This one was the culprit I didn't notice:
> Uncaught Error: Assertion Failed: could not find a suitable method to bind

That caused this later:
> tinymce.min.js:9 Uncaught TypeError: Cannot read property 'getRng' of undefined
    at ym (VM563 tinymce.min.js:9)
    at FE.focus (VM563 tinymce.min.js:9)
    at YN.execCommand (VM563 tinymce.min.js:9)
    at FE.execCommand (VM563 tinymce.min.js:9)
    at Class.imageUpload (component.js:170)
    at Class.send (action_support.js:15)
    at Class.superWrapper [as send] (utils.js:364)
    at glimmer.js:8540
    at instrument (index.js:141)
    at glimmer.js:8539

**Comment by JMLucas96** [comment] 2024-03-05 10:40
Same issue here, 
`Uncaught TypeError: Cannot read properties of undefined (reading 'getRng')`
Magento 2.4.3-p3 tinyMCE4Adapter.js

**Comment by SBeausoleil** [comment] 2024-06-18 19:41
I have the same issue with tinyMCE v5.10.9. This time when calling `focus()`.
```
tinymce.min.js:9 Uncaught TypeError: Cannot read properties of undefined (reading 'getRng')
    at tinymce.min.js:9:351552
    at mceFocus (tinymce.min.js:9:351924)
    at lx.execCommand (tinymce.min.js:9:348723)
    at qx.execCommand (tinymce.min.js:9:369055)
    at qx.focus (tinymce.min.js:9:367337)
```

**Comment by Faris-Shariff** [comment] 2024-06-27 10:02
Uncaught TypeError: Cannot read properties of undefined (reading 'getRng')

This issue is occuring from version 4.8.0 onwards.
