### ISSUE TITLE
Problem with Chrome copy and paste Tinymce V 4.3.8

### ISSUE THREAD

**Issue by serialgit** [tinymce/tinymce#2818] opened 2016-04-01 14:41 UTC
If I copy and paste in the textarea in Chrome, is added `<div> </ div> `with each new line.

Tested on Firefox and Safari, no problem

Can you help me figure out how to fix it

Thanks

**Comment by spocke** [comment] 2016-04-01 16:42
Couldn't reproduce it here: https://www.tinymce.com/

**Comment by serialgit** [comment] 2016-04-01 17:18
No, it just happens without the use of paragraphs.

To see the problem you need to set:

`entity_encoding : 'raw',
 force_br_newlines : true,
 force_p_newlines : false,
 forced_root_block : ''`

**Comment by Daijobou** [comment] 2016-04-04 11:30
You can add a example with http://fiddle.tinymce.com/

I can't see div tags with copy&paste text from plain text editor to tinymce and I use the same setting in my system. When you copy text from a HTML website, its copy the HTML behind too. To prevent this, use the setting http://archive.tinymce.com/wiki.php/Configuration:paste_as_text or write a own filter.

@spocke 
Can you plesae look in this ticket https://github.com/tinymce/tinymce/issues/2634 
I would appreciate for a short answer, that alignment will be fixed in a next version or forced_root_block is not supported anymore. thank you, for you hard work!

**Comment by serialgit** [comment] 2016-04-04 13:44
Hi, Daijobou, 
I have recreated the problem in fiddle: http://fiddle.tinymce.com/hufaab
Test on Chrome to see the problem.

The problem is not in the copy from HTML web pages , simply by copying it from textedit ( mac ) and pasting it in the editor (plain text)

Paste the text with new line and carriage returns

Thanks

**Comment by Daijobou** [comment] 2016-04-04 13:55
You are right! My mistake, I use 4.3.7 and not 4.3.8. In your example I can reproduce the error.

You should add "code" in plugins to see the source. ^^

**Comment by serialgit** [comment] 2016-04-04 14:00
I previously had the 4.2.6 , the same problem, I upgraded hoping it was an old bug , but no change.

**Comment by Daijobou** [comment] 2016-04-04 14:49
Strange, in my Version 4.3.7 I can't reproduce this bug in chrome, but in fiddle in 4.3.7 is this bug.

**Comment by serialgit** [comment] 2016-04-04 14:51
Not often use Safari, I do not like it particularly, but I see now that the same problem exists in Safari.
So between Safari, Chrome and Firefox only works correctly on Firefox

**Comment by serialgit** [comment] 2016-04-04 14:53
So you say that in your project with tinymce v . 4.3.7 does not have the errorre but on fiddle the same version yes?

**Comment by serialgit** [comment] 2016-04-04 14:54
However , the problem is real and can be seen on the fiddle link I posted before

**Comment by Daijobou** [comment] 2016-04-04 16:08
Founded.... you need "paste" in plugins section and the bug is gone.

http://fiddle.tinymce.com/hufaab/1

**Comment by serialgit** [comment] 2016-04-04 16:38
Great Daijobou!!!!
Good job!
Thank you very much :-)

**Comment by blackcathikari** [comment] 2016-07-25 03:25
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 03:25 UTC
Labels: needs: more info, plugin: paste, type: bug

**Comment by rpaidipati** [comment] 2016-12-02 05:57
@Daijobou, I still see paste doesn't work in your fiddle http://fiddle.tinymce.com/hufaab/1

![image](https://cloud.githubusercontent.com/assets/22950957/20824355/3a7e5218-b882-11e6-9ade-34fb4480a32b.png)

**Comment by vikas-garg** [comment] 2017-08-18 04:52
Remove "Paste" from the plugins list, then it would start working.

**Comment by elitedesignsoftware** [comment] 2017-12-06 06:49
vikas-garg gave the right answer!

**Comment by harleenarora** [comment] 2021-07-26 04:36
@illuminz-development I have removed "Paste" from the plugins list, I got same issue. How to solved this issue?
