### ISSUE TITLE
htaccess conflict

### ISSUE THREAD

**Issue by Boffice** [tinymce/tinymce#4832] opened 2019-02-14 19:53 UTC
I am rewriting assets folder from mysite.com/demo/assets to mysite.com/assets via htaccess placed in /demo/assets folder.
code:
RewriteBase /demo/assets/
RewriteRule ^(.*)$ /assets/$1 [L,NC]

all the js libraries css files and images are routed normally. but unless i put tinymce library manually to the /demo/assets folder (which should be empty), some of the main js functions of the website are not working mainly ones that are using onclick method.

There are no errors in apache or chrome console. 

Build
// 4.8.1 (2018-07-26)

**Comment by Boffice** [comment] 2019-02-14 20:11
i did additional workaround and strangely problem is in tinymce/langs folder which contains only readme.md. this is very very strange

**Comment by lnewson** [comment] 2019-02-26 05:07
@Boffice I've tried to reproduce this locally using Apache HTTPD 2.4, but I wasn't able to reproduce the issue and everything appeared to be working fine. Is there a working example you could provide to demonstrate the issue?

**Comment by wonderbugtiny** [comment] 2019-04-08 03:49
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:49 UTC
Labels: needs: more info
