### ISSUE TITLE
Image center align - is there any fix?

### ISSUE THREAD

**Issue by Vartex05** [tinymce/tinymce#4007] opened 2017-10-17 10:53 UTC
Iam running latest version of tinyMCE in my application, the problem is, align center on image doesnt work - it works only in editor, but when i save it and display saved html in other page, the center align doesnt work. I was googling and it looks like, that this issue lasts for very long, is there any fix to this?
It would really help :)

**Comment by spocke** [comment] 2017-10-18 13:17
Seems to be working fine this is the code that gets produced if you type "ab" and insert an image between the a and the b it renders properly outside the editor:
https://jsfiddle.net/su6d6h4m/

We need more details here to be able to reproduce it. Could be something specific with the css on your site. Closing this until such details are provides.

**Closed by spocke** 2017-10-18 13:17 UTC

**Comment by Vartex05** [comment] 2017-10-18 19:47
It works fine in this case, problem is, when u in tiny mce editor change size of the font. For example in blank tinymce textare u begin with text and set size to 36pt, then u enter and insert image on new row. In this case inside p tag with center-align it inserts also span and then image. And that could be the problem.
