### ISSUE TITLE
Failed to load content css errors in 4.6.x

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#3763] opened 2017-06-23 10:59 UTC
Since upgrading to version 4.6.x, I occasionally get the "Failed to load content css" error for the /tinymce/skins/lightgray/content.min.css file. It is totally random (different behavior for the same and all html/css files are loaded on a local machine. So far, I can't find a pattern that could cause it. I also tried changing the settings.maxLoadTime value, but the error messages still appear.

Is there a way to at least hide these error messages?

**Comment by snimavat** [comment] 2017-07-03 14:12
I have exactly same issue, and here's the plnkr that reproduces the issue
http://embed.plnkr.co/6QCok7akLU0rJtjOc2Eg/

Steps:
1. open above plunk
2. click open dialog botton, and see tinymce in dialog works
3. close the dialog
4.click open dialog button again, and notice the error` Failed to load content css: https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.6.4/skins/lightgray/content.min.css`

**Comment by snimavat** [comment] 2017-07-03 14:24
This definitely has some thing to do with jquery version, if i change the jquery version to 1.12.0 the failed to load css error goes away, but when i use jquery 3+, the error comes up

**Comment by petko** [comment] 2017-07-03 14:52
I use jquery 3,x too (3.2.1).

**Comment by snimavat** [comment] 2017-07-03 14:55
Looks like FF bug, see my comments at the end https://bugzilla.mozilla.org/show_bug.cgi?id=1371910

**Comment by petko** [comment] 2017-07-03 15:29
It happens under Chrome for me..

**Comment by snimavat** [comment] 2017-07-03 15:45
Looks like the error comes up from this block.
https://github.com/tinymce/tinymce/blob/4c668199fd6cdd50979e9531e83b563753a2d21f/src/core/src/main/js/dom/StyleSheetLoader.js#L181

Seems the StyleSheetLoader.js is probably not compitible with new FF !

**Comment by tpianta** [comment] 2017-07-17 21:01
Seeing the same issue in Firefox only.

**Comment by jtrost** [comment] 2017-08-02 17:51
After downgrading to 4.5, I have not seen this issue at all.

**Comment by Afraithe** [comment] 2017-08-02 18:18
How are you all loading TinyMCE? Locally, via cdn or our cloud?

**Comment by spocke** [comment] 2017-08-02 18:26
The above plnkr doesn't work with an older version of tiny but do work with an older version of jquery so I think this isn't tiny related but rather something that the dialog library is doing or jquery. Tiny just adds a link to the head and listens for the onload or onerror events.

If we could get a isolated case where it's failing without a bunch of dependencies we can look into it. The provided example breaks the editor on the second load. I think it's clobbering the editor this is something that a lot of these dialog frameworks do they basically set innerHTML of the div to something new then the iframe state gets blown away nothing we can do about that since the browser can't know what was in that iframe that got destroyed.

**Comment by jtrost** [comment] 2017-08-02 18:39
@Afraithe I'm loading tinymce via the [tinymce-rails gem](https://github.com/spohlenz/tinymce-rails), and the files are served locally.

After fiddling with my Rails setup, I discovered that disabling [turbolinks](https://github.com/turbolinks/turbolinks) mitigated this issue. At least in my case, it appears that there is some incompatibility between turbolinks and tinymce. In addition, this error only occurs in Firefox. I do not see this error in Chrome (even when turbolinks is enabled).

**Comment by jtrost** [comment] 2017-08-02 19:16
@spocke Here is a failing case in Firefox 54.0.1 with minimal dependencies: https://jsfiddle.net/5yyy7LLg/7/ I see it in about 20% of the page loads, so click _Run_ a few times if you don't see the error right away.

It includes tinymce 4.6.5 and turbolink 5.0.3.  When you run the fiddle, you should see a red error box that says:
````Failed to load content css: https://cdnjs.cloudflare.com/ajax/libs/tinymce/4.6.5/skins/lightgray/content.min.css````

Once that box is closed, you will see this text instead of the editor: 
````{"error": "Please use POST request"} ````

I believe this is a jsfiddle-specific error due to the first line: ````Turbolinks.visit(window.location.pathname);````

But if you were to run this code outside of jsfiddle, you would see the editor instead.

**Comment by rcurrier666** [comment] 2017-08-21 22:11
I found a work-around. Hosting TinyMCE locally rather than loading from the cloud works with FF. Two downsides; I have to rebuild and republish my app to get updates, and this increases the size of the bundle that has to be pushed to the client browser from my server. But it allows me to continue on with TinyMCE.

**Comment by rcurrier666** [comment] 2017-08-21 22:13
I found a workaround. Hosting TinyMCE locally rather than loading from the cloud works. Two downsides; I have to rebuild and republish my app to get updates, and this increases the size of the bundle that has to be pushed to the client browser from my server. But it allows me to continue on with TinyMCE.

**Comment by frenkel** [comment] 2017-08-22 06:38
We're already doing that, so it doesn't fix it for me.

**Comment by spocke** [comment] 2017-08-22 07:00
We are going to make a new release with a fix for this one. It appears that firefox will just cancel any loading stylesheet if you navigate to another page without any proper error so it's impossible to detect when or why that happens so we will just remove the notifications for css files.

**Comment by rcurrier666** [comment] 2017-08-22 07:02
I can see why the defect hasn't been fixed, it's not consistent. Loading from disk fixed it for me, others changed the version of jquery, others used 4.5 of TinyMCE (I suspect the error message just isn't in that version since the msg went away but the editor still didn't work), others have seen the problem in browsers other than FF. This is the kind of bug that causes programmers to change careers! In my case, the problem only happened when the textarea was enbedded in a Bootstrap modal.

**Comment by rcurrier666** [comment] 2017-08-22 07:06
@spocke, I'd be happy to help test the new release to see if it fixes more than just your particular test cases. I have a fairly large Meteor app with multiple editors embedded in Bootstrap modal dialogs. Just let me know the URL and I'll give it a shot.

**Comment by spocke** [comment] 2017-08-22 07:08
Yes issues like this that are random are likely async problems somethings loads and something happens while it's loading and that is the case here. If the stylesheet in in the loading state and something happens to the document that being loaded the error will appear. That could be that the editor is clobbered a lot of these dialog frameworks just sticks innerHTML in there and then tiny gets blown away without any way of knowing that it happened the other one is that firefox is cancelling stylesheet loads if you navigate to another page.

A fix for this should be in the nightly build that we produce where the message is simply not shown. It's also as a nightly on fiddle.tinymce.com but might be easier to test it locally.

**Comment by fyrkant** [comment] 2017-08-31 09:39
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2017-08-31 09:39 UTC
Labels: browser: firefox, status: escalated, status: verified, type: bug

**Comment by frenkel** [comment] 2017-08-31 12:39
Seems to remove the error message indeed, but the TinyMCE editors are now empty instead of showing the correct content. Anybody else have this also? Or did it fix your problems and is my bug related to my own code?

**Comment by spocke** [comment] 2017-08-31 13:03
No clobbering can't be resolved since if an iframe gets replaced the browser won't keep the state and there is nothing a js library can do about that. So if your page is using say elm.innerHTML = elm.innerHTML and the elm contains an tinymce editor the editor iframe gets destoryed and an empty editor appears.

The fix we made here is about getting rid of css loading error messages especially in firefox where it will produce such an error message if the iframe gets destroyed while it's being loaded or if the user navigates to another page while it's being loaded.

**Comment by frenkel** [comment] 2017-08-31 13:20
I think you're misunderstanding me. The page is loaded with (for example), this as HTML: `<textarea class="tinymce">Example</textarea>`, but the TinyMCE showns a blank area as content when this HTML is loaded using Turbolinks.

**Comment by spocke** [comment] 2017-08-31 15:05
Yes, that is integrations issue with turbolinks not tinymce. If it clobbers the html when you click on links you need to cleanup editor instances then re-add them.

So something like this might work:
```javascript
document.addEventListener("turbolinks:before-render", function() {
  tinymce.remove();
})
```

But since this is third party integration it goes beyond the bug tracker here.

**Comment by frenkel** [comment] 2017-10-04 12:09
@spocke If it is an integration issue with Turbolinks, wouldn't it happen in all browsers? It happens only in Firefox.

**Comment by frenkel** [comment] 2017-10-04 12:16
@spocke That is exactly the kind of code we already had in place to make it all work correctly together with Turbolinks. This used to work fine in Firefox and still works fine in all other browser. However, in Firefox we now get empty & disabled Tinymce editors. I'll try to set up a simple application so you can reproduce this.

**Comment by frenkel** [comment] 2017-10-04 12:34
I've created a sample project:
https://github.com/frenkel/firefox_tinymce_bug
The last commit adds tinymce to page three. After cloning, run `bundle install` and `bin/rails s`. Now open `http://localhost:3000/` in Chrome and click page one, then two, then three and repeat it once. Page three should show a working TinyMCE editor. Try the same process in Firefox: the second time you visit page three it shows an empty TinyMCE editor with the "Powered by TinyMCE" label half off-screen.

**Comment by rcurrier666** [comment] 2017-10-04 17:23
I don't know much about how Ruby works, but is the TinyMCE gem loading 
TinyMCE from the cloud or from a local copy of the code? My app is in 
Meteor and moving from the cloud to a local copy fixed the Firefox 
issue. I believe there is something in the cloud package that Firefox 
doesn't like, but was never able to figure out what. The patch that was 
provided removed the error message, but the editor still doesn't work.

Using a local copy means that I don't get the latest version of TinyMCE, 
but I can live with that.
