### ISSUE TITLE
When I select all the content in the editor and delete it, the browser will be stuck and will report the "Maximum call stack size exceeded" error. 

### ISSUE THREAD

**Issue by chiuwingyan** [tinymce/tinymce#5123] opened 2019-08-21 06:44 UTC
When I select all the content in the editor and delete it, the browser will be stuck and will report the "Maximum call stack size exceeded" error. Why is that? 

Versions: 4.x and 5.x versions will be like this

Device: chrome 

My code:
    
```
        const _this = this;
        const setting = {
            selector: '#' + _this.id,
            language: 'zh_CN',
            forced_root_block: 'span',
            init_instance_callback: editor => {
                // EDITOR = editor
                console.log('Editor: ' + editor.id + ' is now initialized.');
                if (_this.value) {
                    editor.setContent(_this.value)
                }
                editor.on('KeyUp SetContent', () => {
                    console.log('change')
                    let content = editor.getContent();
                    if(content == ''){
                        content = '<div>1</div>'
                    }
                   // console.log('content',typeof content)
                    this.onEditorChange(content);
                });
            },
            content_style: `
                *                         { padding:0; margin:0; }
                html, body                { height:100%; }
                img                       { max-width:100%; display:block;height:auto; }
                a                         { text-decoration: none; }
                iframe                    { width: 100%; }
                p,div                     { line-height:1.7; margin: 0px; }
                table                     { word-wrap:break-word; word-break:break-all; max-width:100%; border:none; border-color:#999; }
                .mce-object-iframe        { width:100%; box-sizing:border-box; margin:0; padding:0; }
                ul,ol                     { list-style-position:inside; }
            `,
            insert_button_items: 'image link | inserttable',
            end_container_on_empty_block: true,
            plugins: ['advlist link image', 'textcolor paste textcolor colorpicker'], // 配置
            toolbar_items_size: 'small',
            menubar: false,
            fontsize_formats: '8px 10px 12px 14px 16px 18px 20px 22px 24px 26px 28px 30px 32px 34px 36px 38px 40px 42px',
            block_formats: 'Paragraph=p;Heading 1=h1;Heading 2=h2;Heading 3=h3;Heading 4=h4;Heading 5=h5;Heading 6=h6;',
            toolbar1: 'insertfile undo redo | formatselect | link unlink | uploadimg image media', // 工具栏1
            toolbar2:
                ' fontsizeselect | forecolor backcolor | fontselect bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | outdent indent | removeformat', // 工具栏2
            // 图片上传
            images_upload_handler: function(blobInfo, success, failure) {
                // failure(blobInfo)
                // _this.$emit('on-ready', blobInfo.blob().size, blobInfo.blob())
                if (blobInfo.blob().size > _this.maxSize) {
                    failure('文件体积过大');
                }
                if (_this.accept.indexOf(blobInfo.blob().type) >= 0) {
                   
                } else {
                    failure('图片格式错误');
                }
            }
        };
        Object.assign(setting, _this.setting);
        window.tinymce.init(setting);

```

**Comment by ltrouton** [comment] 2019-09-06 04:13
The issue you are experiencing is most likely caused by `forced_root_block: 'span'` in the editor config. `forced_root_block` ([docs](https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block)) only supports block elements ([HTML Block Elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements)). You can also set `forced_root_block: false` which will not generate any block tags as noted in the documentation. Although, it should be noted that will significantly limit the functionality of the editor. Let us know if this was helpful.

**Comment by ltrouton** [comment] 2019-11-12 03:18
Closing this as assuming the issue has been resolved. If you are still having troubles, then we're more than happy to reopen this ticket.

**Closed by ltrouton** 2019-11-12 03:18 UTC
