### ISSUE TITLE
Unable to insert column in table with no more width left

### ISSUE THREAD

**Issue by noraab** [tinymce/tinymce#5251] opened 2019-11-12 08:58 UTC
**What is the current behavior? Describe the bug**
When I have a table with a fixed width, having two columns using all the fixed width, I can't insert a column anymore. No feedback is provided.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Use this fiddle and try to insert a new column into the existing table.
http://fiddle.tinymce.com/OUgaab/6

**What is the expected behavior?**
Not sure - but at least I would expect some kind of feedback that gives an indication to the user why the new column couldn't be added.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce5-cloud-stable

**Comment by lostkeys** [comment] 2019-11-12 13:02
I can verify the behavior in the linked fiddle. While one could argue that there is no space left to put in columns the issue still applies if I make the columns narrower than the table, leaving space for more columns. The issue is also there is `content_css` is set to false (to rule out the default skin)

**Comment by lnewson** [comment] 2019-11-12 20:09
I can replicate this in TinyMCE 4 as well, so it seems to have been around for a while.

**Comment by lostkeys** [comment] 2020-10-15 06:24
Circling back to this issue. A fix for this was released in TinyMCE 5.5. The new option [table sizing mode](https://www.tiny.cloud/docs/plugins/table/#table_sizing_mode) allows for more options for working with table widths.

**Closed by lostkeys** 2020-10-15 06:24 UTC
Labels: plugin: table, type: bug
