### ISSUE TITLE
target attribute of a link does not change unless url also changes

### ISSUE THREAD

**Issue by kassenov** [tinymce/tinymce#5155] opened 2019-09-10 04:09 UTC
**What is the current behavior? Describe the bug**
Targe attribute is not getting changed.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

1. Enter a link, go to Insert/Edit Link and set Open link in... to be New Window. 
2. Click Save. 
3. Open Insert/Edit Link again and change Open link in... to Current Window. 
4. Click Save. 
5. The target attribute of the link still be _blank.

**What is the expected behavior?**

Target attribute should change when changed in Insert/Edit Link pop-up.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
5 but it works on 4.8.5

**Comment by wonderbugtiny** [comment] 2019-09-10 04:50
Hi @kassenov, thanks for the report! We are aware of the issue and are working on a fix. I am closing this ticket as a duplicate of #5135. We will update the ticket when a fix is available. Please let us know if you have any other questions or concerns.

**Closed by wonderbugtiny** 2019-09-10 04:50 UTC
