### ISSUE TITLE
fontselect breaks editor on firefox with hidden instances

### ISSUE THREAD

**Issue by richinnz** [tinymce/tinymce#3442] opened 2017-01-17 01:59 UTC
See fiddle - http://fiddle.tinymce.com/OGfaab
If you have multiple instances on a page and there is a hidden one (usually first one that will get shown when the user is ready for it) then the editors are not shown because fontselect breaks .  Error is possibly that the fontFamily variable is 'not defined' and therefore dies in this function: Adding the check appears to solve it - maybe?

var normalizeFontFamily = function (fontFamily) {
        // 'Font name', Font -> Font name,Font
        return (fontFamily) ? fontFamily.replace(/[\'\"]/g, '').replace(/,\s+/g, ',') : ''; 
    };

**Comment by fyrkant** [comment] 2017-02-02 12:59
Fixed in yesterdays 4.5.3 release.

**Closed by fyrkant** 2017-02-02 12:59 UTC
Labels: browser: firefox, resolution: fixed in coming release, status: verified, type: bug

**Comment by t0v1n** [comment] 2017-06-08 18:17
Confirmed that this issue was fixed in 4.5.3, but it seems to be present again in 4.6.3

**Comment by fyrkant** [comment] 2017-06-09 07:24
@t0v1n You are able to reproduce it with the same fiddle linked above using 4.6.3 in Firefox?
