### ISSUE TITLE
image_caption unable to link caption in inline editor

### ISSUE THREAD

**Issue by sitecarp** [tinymce/tinymce#4486] opened 2018-07-11 22:24 UTC
When an image is given a caption through the "image_caption" feature, hyperlinks within the caption do not work. The interface allows you to attempt a hyperlink on all or a portion of the caption, but the source code remains unmodified once the hyperlink is applied. I am using CDN `<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>`.

**Note:** This is similar to, but distinct from the resolved issues [#3596](https://github.com/tinymce/tinymce/issues/3596)/[#3478](https://github.com/tinymce/tinymce/issues/3478)

**Comment by sitecarp** [comment] 2018-07-16 19:52
Thanks for testing @SimonFc . Maybe there's a newer version of the 4.x CDN? I know about the "cloud" CDN option, but it utilizes different setup, and causes undesired toast messages.

I'm using `<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>` for the CDN. The issue is browser-independent. Tested on the latest Chrome 64-bit, Firefox and Edge on Windows 10.

**Comment by SimonFc** [comment] 2018-07-17 09:16
No worries!
The CDN you're using is resolving Tiny to 4.8.0 so the latest version. So that I understand you correctly, you're unable to change part or all of the caption with the Link plugin? Perhaps something differs in our setups or am I misunderstanding you?

See if you can replicate the issue here http://fiddle.tinymce.com/Xvgaab

**Comment by sitecarp** [comment] 2018-07-18 01:31
@SimonFc I just discovered that the latest downloadable version, 4.8.0 works properly on this issue, but it's not ideal because of its different appearance. [#4495](https://github.com/tinymce/tinymce/issues/4495)

**Comment by sitecarp** [comment] 2018-08-30 00:58
Hi @SimonFc, do you know if there is a progress update on this?

**Comment by sitecarp** [comment] 2018-09-15 00:17
I see this issue still has the "needs: more info" label. Do I need to provide more information?

**Comment by SimonFc** [comment] 2018-09-15 17:48
Hi @sitecarp, sorry for the late respons. That label was for earlier so I'll remove it. At the moment our main focus is on developing new features so I can't say anything certain about when we'll get to this issue. (It is in our internal backlog though)

**Comment by sitecarp** [comment] 2018-09-15 17:57
@SimonFc Okay, yeah, I understand. I just wanted to make sure I'd adequately identified the problem. Thanks!

**Comment by SimonFc** [comment] 2019-07-30 13:30
@sitecarp I can't reproduce the issue using Tiny 5 version 5.0.12 so I'll be closing this. (Tiny 4 will only receive fixes for critical issues)

**Closed by SimonFc** 2019-07-30 13:30 UTC
Labels: plugin: image, status: escalated, status: verified, type: bug
