### ISSUE TITLE
noneditable plugin, character directly after <span class='mceNonEditable'></span> does not get removed at backspace,but moves cursor instead.

### ISSUE THREAD

**Issue by rasmuslinden** [tinymce/tinymce#5709] opened 2020-05-29 01:59 UTC
When inserting text directly after a span containing mceNonEditable, the first character directly after the span is not removed, but the cursor moves instead.

Replication steps
http://fiddle.tinymce.com/hkhaab

insert a span into the editor:
-tinyMCE.activeEditor.execCommand('mceInsertContent', false, '<span class="mceNonEditable">HELLO</span>');
-add any text, and try backspace deleting one char at a time.

**What is the expected behavior?**
The character would get removed.

tinyMCE V5,Firefox 76.0.1 (64-bit), Chrome Version 83.0.4103.61 (Official Build) (64-bit), osx 10.15.4 (19E287)

**Comment by lnewson** [comment] 2020-05-29 02:31
Thanks for the report @rasmuslinden and I can confirm this is a known issue. Since #5679 already exists for this issue, I'm going to close this as a duplicate of #5679.

**Closed by lnewson** 2020-05-29 02:31 UTC
