### ISSUE TITLE
CodeMirror+TinyMCE4: html inserted into style tags at cursor position

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2009] opened 2014-11-28 08:15 UTC
Description of problem:
Using the plugin from http://www.tinymce.com/forum/viewtopic.php?id=31302.
Tested using CodeMirror 4.4.1 & 4.8.1 and CodeMirror-TinyPlugin 1.3

Steps to reproduce:
1. open code-window
2. insert some &ltg;style> tag into the source of the page, like
&ltg;style type="text/css">
.haha {
color: red;
}
&ltg;/style>
3. position the cursor so code is highlighted (e.g. right before the closing curly brace)
4. close code-window using "OK"
5. open code-window again

Expected result:
code looks like before closing

Actual result:
a span element was created at cursor position which actually destroys the markup, since &ltg;span> is not allowed mixed with css selectors

&ltg;style type="text/css">&ltg;!--
.haha {
color: red;
&ltg;span id="CmCaReT">&ltg;/span>}
-->&ltg;/style>

> _**Legacy information imported from TinyMCE bug tracker:**_
>
> _[#T7283](http://archive.tinymce.com/develop/bugtracker_view.php?id=7283) posted by [clxstaab](http://archive.tinymce.com/profile.php?name=clxstaab)_

> _**Tags:** [firefox chrome]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by thomich** [comment] 2015-11-06 09:56
Hey

As i can't contact maintainer of http://www.avoid.org/codemirror-for-tinymce4/ i try it here, maybe we can solve it....

There is a similar problem with JS in html code...

With style in html code, if cursor position in editor not set and you open html code with codemirror plugin:
Uncaught NotSupportedError: Failed to execute 'createContextualFragment' on 'Range': The range's container is 'style', which is not supported.

If you set cursor position in editor to any place, not error..

If you set cursor in html code inside style definition, it adds the <span id="CmCaReT"></span> code.

Same happens if you have JS code in html.

Workaround if you have style definitions in html code > set cursor position anywhere out of style definition before closing html code, same if you have JS in html code.

Tested JS problem on http://www.avoid.org/codemirror-for-tinymce4/.
Tested style problem only locally, cause for adding style definitions i added following to tinymce init:
valid_elements: "*[*]",
valid_children: '+body[style]',

Thanks
thomi

**Comment by blackcathikari** [comment] 2016-07-25 01:35
Hi, we've investigated this issue and cannot reproduce it in TinyMCE v4.4.0. Thanks, the TinyMCE Team.

**Closed by blackcathikari** 2016-07-25 01:35 UTC
Labels: browser: chrome, browser: firefox, origin: tinymce.com, type: bug

**Comment by WebVeteran** [comment] 2016-09-09 05:16
I believe this is fixed with:
https://github.com/christiaan/tinymce-codemirror/pull/21/files
https://github.com/christiaan/tinymce-codemirror/pull/20/files

**Comment by thomich** [comment] 2016-09-09 05:36
thanks to all for working on things we always love ;)
