### ISSUE TITLE
textpattern plugin index size error when particular pattern typed by user

### ISSUE THREAD

**Issue by vijayaganeshk** [tinymce/tinymce#3278] opened 2016-10-18 21:36 UTC
URL : https://www.tinymce.com/docs/demo/full-featured/
sample input :  **_EDIT**_  or  "**_EDIT**_ "
Note: please make sure that one empty space is given at the end of the word.
tinyMCE type: Full Featured version
Error: Once you type any one word mentioned in sample input and give empty space at the end of the word then open browser developer console, you can notice exception that says index size error.
Attached screenshot with an error. Please let me know if you need more details.
![tinymce - textpattern_format_error](https://cloud.githubusercontent.com/assets/20564085/19497185/2e0e0768-9559-11e6-8e88-0eee1548101a.png)

**Comment by lnewson** [comment] 2020-04-26 12:33
Hi,

I'm unable to reproduce this using TinyMCE 4.9.10 or 5.2.2. It's likely we've fixed this issue since it was originally reported, so I'll go ahead and close this issue. If you're still able to reproduce this in the latest version however, then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-04-26 12:33 UTC
Labels: plugin: textpattern, status: verified, type: bug
