### ISSUE TITLE
Inconsistent positioning of cursor

### ISSUE THREAD

**Issue by krishna-babu** [tinymce/tinymce#6634] opened 2021-03-16 20:32 UTC
**What is the current behavior? Describe the bug**
Issue occurs when click occurs in between two content editable sections. The cursor is placed at start of tinymce root element

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

[Fiddle link](https://fiddle.tiny.cloud/D7haab/3)

Demo of Issue:
![CursorInconsistency](https://user-images.githubusercontent.com/12712808/111375769-e3fbad80-865b-11eb-8851-6e59e01235ac.gif)

**What is the expected behavior?**
Cursor to be placed end of previous or start of next element.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?Latest stable 5.7

**Comment by JamesToohey** [comment] 2021-03-25 01:00
Hi @krishna-babu, this appears to be a duplicate of #6456 so I'm going to close this so we can track it in one place.

**Closed by JamesToohey** 2021-03-25 01:00 UTC
