### ISSUE TITLE
why can't the toolbar follow the mouse?

### ISSUE THREAD

**Issue by Maxatom** [tinymce/tinymce#5644] opened 2020-05-08 09:42 UTC
**What is the current behavior? Describe the bug**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment] 2020-05-08 09:47
I'm going to close this sorry, as the details in the template haven't been filled out and as such there's no information except for the vague title to go on. Please log a new issue with the required information.

As a side note, I suspect you may want our "Sticky Toolbar" feature where the menu bar/toolbar will follow as you scroll down the page. Details on that feature can be found here: https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_sticky

**Comment by Maxatom** [comment] 2020-05-08 10:11
I user "Sticky Toolbar" , but it can't work.  when the mouse pointer is in the bottom the div, the toolbar is still in the top.  
I use tinymce in vue like this:
```
              :init= "{
                images_upload_url:'/afanti-console/travelInfo/yjy/image/upload',   
                images_upload_base_path: '',
                images_upload_credentials: true ,
                language: 'zh_CN',
                placeholder:'在这里输入资讯内容',
                toolbar_sticky: true
              }" 
```

**Comment by Maxatom** [comment] 2020-05-08 10:12
> I'm going to close this sorry, as the details in the template haven't been filled out and as such there's no information except for the vague title to go on. Please log a new issue with the required information.
> 
> As a side note, I suspect you may want our "Sticky Toolbar" feature where the menu bar/toolbar will follow as you scroll down the page. Details on that feature can be found here: https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar_sticky

I user "Sticky Toolbar" , but it can't work. when the mouse pointer is in the bottom the div, the toolbar is still in the top.
I use tinymce in vue like this:

             ```
 :init= "{
                images_upload_url:'/afanti-console/travelInfo/yjy/image/upload',   
                images_upload_base_path: '',
                images_upload_credentials: true ,
                language: 'zh_CN',
                placeholder:'在这里输入资讯内容',
                toolbar_sticky: true
              }" 
```

**Comment by lostkeys** [comment] 2020-05-08 10:52
Hm. Sticky toolbar is ment to dock the toolbar at the top of the screen if the editor starts moving out of the screen so the toolbar is always visible if the editable area is visible.

Is it perhaps the context toolbars you are after? Try selecting some text here: https://www.tiny.cloud/docs/demo/editor-dfree/

**Comment by Maxatom** [comment] 2020-05-09 06:22
> Hm. Sticky toolbar is ment to dock the toolbar at the top of the screen if the editor starts moving out of the screen so the toolbar is always visible if the editable area is visible.
> 
> Is it perhaps the context toolbars you are after? Try selecting some text here: https://www.tiny.cloud/docs/demo/editor-dfree/

Thank you, I got it. 
but it still can't work. if the editor is very long and i put the mouse pointer at the bottom of the editor.  the toolbar is sitll at the top of the editor, not at the top of the screen. 
blow is my code : 
```
    <div class="tinymec-editor">
            <editor
              :disabled=false
              :init= "{
                images_upload_url:'/afanti-console/travelInfo/yjy/image/upload',   
                images_upload_base_path: '',
                images_upload_credentials: true ,
                language: 'zh_CN',
                placeholder:'在这里输入资讯内容',
                menubar: false,
                toolbar_sticky: true
              }"
              :inline=true
              language='zh_CN'
              model-events= ""
              plugins="link image"
              tag-name="div"
              v-model="travelInfoDetail.content"
            />
          </div>
```
is there anything wrong?

**Comment by lostkeys** [comment] 2020-05-11 06:09
I can't see any issues with your config. Can you reproduce the issue in a [fiddle](http://fiddle.tinymce.com) and/or provide a screen recording?

**Comment by lnewson** [comment] 2020-06-08 20:57
Closing due to a lack of additional information. If you can provide the information requested above then we'll be happy to reopen this issue.

**Closed by lnewson** 2020-06-08 20:57 UTC
Labels: needs: more info, type: question
