### ISSUE TITLE
Label in "styles" option

### ISSUE THREAD

**Issue by mbooh** [tinymce/tinymce#8737] opened 2023-05-17 08:55 UTC
Strange label in "styles" option in Optimizely CMS 12.19, TinyMCE version 6

More info can be found here:
https://world.optimizely.com/forum/developer-forum/cms-12/thread-container/2023/5/label-in-styles-option-in-tinymce-4-2/

Not sure if it is a Optimizely bug or Tiny bug?

**Comment by spocke** [comment] 2023-05-17 10:52
The `format` key is for pre registered formats so the other properties except `title` are ignored and since the first one is `p` then it will match against any paragraph and the first block in the editor is normally a paragraph so then that will be selected since it selects the first matching format. You could use `block` or `selector` instead if you want to apply a class to a paragraph.

For more details check the documentation on style_formats: https://www.tiny.cloud/docs/tinymce/6/user-formatting-options/#style_formats

I'm closing this since from what I can see this is by design. If you still think it's a bug then I can re-open it.

**Closed by spocke** 2023-05-17 10:52 UTC

**Comment by kinglozzer** [comment] 2023-11-14 11:30
@spocke I have a similar issue to this - we use the block_formats to let users choose h1, h2 etc, and use style_formats to allow them to modify styles for things. For example:

```js
{
  block_formats: 'Paragraph=p;Heading 1=h1;Heading 2=h2;Heading 3=h3',
  style_formats_autohide: true,
  style_formats: [
    {
      title: 'Button',
      selector: 'a',
      classes: 'button'
    }
  ]
}
```

Despite the fact that “Paragraph” is not an option in the `style_formats` dropdown, it still always defaults to saying Paragraph as the label when no styles are selected.

I’m working around this for now by adding `{ title: 'Format', selector: '*' }` so that the dropdown always says “Format”, but that’s not ideal because it obviously then never changes when a format _is_ selected.
