### ISSUE TITLE
angular ng build --prod  --build--optimizer fail

### ISSUE THREAD

**Issue by chenguanbo** [tinymce/tinymce#5243] opened 2019-11-08 13:05 UTC
```
ERROR in ../node_modules/tinymce/tinymce.js
Module build failed (from ../node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js):
Error: Invalid IIFE Structure
    at updateEnumIife (E:\code\question\frp-fe\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:309:15)
    at visitBlockStatements (E:\code\question\frp-fe\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:81:61)
    at visitor (E:\code\question\frp-fe\node_modules\@angular-devkit\build-optimizer\src\transforms\wrap-enums.js:33:26)
    at visitNode (E:\code\question\frp-fe\node_modules\typescript\lib\typescript.js:62205:23)

```
### 
ng serve worked 
ng build --prod  --build--optimizer fail 

my env：

```
"@tinymce/tinymce-angular": "^3.3.1",
 (   
"tinymce": "http://download.ephox.com/tinymce/community/tinymce_nightly.tgz",
or
"tinymce": "^5.0.3",
both fail
)

```

i have read  other ng build error issue i dont understand " import min" mean

i have import anything like:
angular json :
  assets:
```
              { "glob": "**/*", "input": "node_modules/tinymce/skins", "output": "/tinymce/skins/" },
              { "glob": "**/*", "input": "node_modules/tinymce/themes", "output": "/tinymce/themes/" },
              { "glob": "**/*", "input": "node_modules/tinymce/plugins", "output": "/tinymce/plugins/" },
```
 scripts
 `             "node_modules/tinymce/tinymce.min.js",`

component:
```
import 'tinymce/tinymce';
import 'tinymce/plugins/paste/plugin';
import 'tinymce/plugins/link/plugin';
import 'tinymce/plugins/autoresize/plugin';
import 'tinymce/plugins/lists/plugin';
import 'tinymce/plugins/table/plugin';
import 'tinymce/plugins/preview/plugin';
import 'tinymce/plugins/contextmenu/plugin';
import 'tinymce/plugins/legacyoutput/plugin';
import 'tinymce/plugins/help/plugin';
import 'tinymce/plugins/colorpicker/plugin';
import 'tinymce/plugins/textcolor/plugin';
import 'tinymce/plugins/fullscreen/plugin';
import 'tinymce/plugins/noneditable/plugin';
declare var tinymce: any;
```

Thanks for reading my  issue

**Comment by lincolndennis** [comment] 2019-11-08 19:53
Is this the best place for this report? Should this issue be reported to the Angular Component repo?
https://github.com/tinymce/tinymce-angular

**Comment by lnewson** [comment] 2019-11-08 20:19
Closing this as a duplicate of https://github.com/tinymce/tinymce/issues/4165. The issue is primarily on the Angular side of things (see the other issue for more details), however if you make sure to upgrade to at least 5.0.9 then that might fix it for you.

**Closed by lnewson** 2019-11-08 20:19 UTC
Labels: type: question

**Comment by lnewson** [comment] 2019-11-08 20:42
Also to use the minified version of TinyMCE when bundling via a module loader, you need to change your imports not add the resources to your assets. eg:

```
import 'tinymce/tinymce.min';
...
```
