### ISSUE TITLE
FF. User can remove content from noneditable elements if user selects 

### ISSUE THREAD

**Issue by versusvirus** [tinymce/tinymce#5880] opened 2020-07-10 11:33 UTC
**What is the current behavior? Describe the bug**
User can remove content from noneditable elements. It ruins some of the editor features.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**
1.Visit http://fiddle.tinymce.com/johaab
2.Select some part of contenteditable content with noneditable content, then press delete or backspace.

**What is the expected behavior?**
User can edit only editable elements.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.*, FF 89

**Comment by lnewson** [comment] 2020-07-11 05:27
This is expected behaviour, as noneditable just means you cannot edit the content inside of the noneditable element. You're still free to move the block around or delete it if necessary. If you meant that you can edit the content inside of the noneditable, then can you please provide more details, as I was unable to reproduce that?

Also I'm guessing you may have meant Firefox 79 Beta? as 89 doesn't exist.

**Comment by lnewson** [comment] 2020-08-09 13:40
As there's been no reply for a month I'm going to close this. If you're still having troubles, then could you please include the details requested above and then we'll be happy to reopen this.

**Closed by lnewson** 2020-08-09 13:40 UTC
Labels: needs: more info
