### ISSUE TITLE
Cannot apply formats to anchor 

### ISSUE THREAD

**Issue by LingSpb** [tinymce/tinymce#6691] opened 2021-03-31 10:43 UTC
Currently, it seems no format can be applied to an anchor.

Steps to reproduce:
1. Open tinymce full featured demo https://www.tiny.cloud/docs/demo/full-featured/
2. Add an anchor
3. Select the new added anchor and try to add any format to it
Expected: Formats should be applied to the anchor
Actual: No format is applied

**Comment by JamesToohey** [comment] 2021-04-01 06:21
Hi @LingSpb,

I followed your steps and I was able to apply formats to an anchor (i.e. unable to replicate your issue).

Could you provide the version of your web browser? In addition, a video of the problem could also be helpful.

**Comment by LingSpb** [comment] 2021-04-01 07:11
![tinymce anchor](https://user-images.githubusercontent.com/4546284/113256626-b3597c00-92c9-11eb-8ea0-ab467094d48d.gif)

Hi @JamesToohey,

I attached hereby a short video to show how I reproduce the issue.
As you can see, after selecting Format > Background color, the selected background color isn't applied (and no style added to the anchor html element).

**Comment by ashfordneil** [comment] 2021-04-07 03:54
Thanks for this detail @LingSpb. Because the anchor element is marked as `contenteditable="false"` the TinyMCE formatter will not apply formats to it by design. I've marked this use case (applying formats specifically to anchor elements added by the anchor plugin) as a feature request for our product team to look into.

**Comment by lostkeys** [comment] 2021-06-11 09:00
Hey @LingSpb! In order to better understand your feature request, can you elaborate on your use-case? The current anchor inserts an icon for you as an author to know it's there, and the icon will be filtered out from the editor on submit. So it's not really any point in formatting it, because it isn't content.

**Closed** 2024-06-14 00:51 UTC
Labels: type: feature, needs: more info, plugin: anchor
