### ISSUE TITLE
Mobile Edit State

### ISSUE THREAD

**Issue by ludwich** [tinymce/tinymce#5079] opened 2019-07-15 06:39 UTC
When in mobile and edit is set to a state i cant edit when i toggle the edit state the first time.

**What is the expected behavior?**
It should work as the web tinymce and feel that the state has changed

5.0.11 of tinymce on Ios, android

**Comment by ltrouton** [comment] 2019-07-16 01:49
Hi @ludwich. I would like to get more clarity on the issue you are experiencing. It will be helpful if you could please provide a video or a forked fiddle(http://fiddle.tinymce.com) with steps to reproduce. Thank you!

**Comment by lnewson** [comment] 2019-08-18 03:48
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-08-18 03:48 UTC
Labels: needs: more info
