### ISSUE TITLE
id="title" stripped from element in tinymce 7

### ISSUE THREAD

**Issue by nora-sj** [tinymce/tinymce#9613] opened 2024-05-02 17:28 UTC
## 📝 Provide detailed reproduction steps (if any)

1. reproducible in tinymce basic example https://www.tiny.cloud/docs/tinymce/latest/basic-example/
2. go to source code editor
3. add `id="title"` to an element
4. save

### ✔️ Expected result
- the `id="title"` is saved onto the element

### ❌ Actual result
- id="title" is stripped from the element

this affects any new or existing content with `id="title`, other ids seem to work fine

## 📃 Other details
- Browser: chrome
- OS: mac
- First affected version: 7
- Worked in version: 5

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by spocke** [comment] 2024-05-02 17:53
This seems to be by design. We use DOMPurify to sanitise the HTML it has a rule that `id` and `name` can't reference things that exists in the document so `title` in this case exists on the document. So name your ID something else than that should work.

Closing this since it's by design and not a bug.

**Closed by spocke** 2024-05-02 17:53 UTC

**Comment by TheSpyder** [comment] 2024-05-03 05:30
Specifically this is a DOM Clobbering attack. DOMPurify has an explanation in their security goals documentation:
https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model
