### ISSUE TITLE
can not read property 'removeAllRanges' of null

### ISSUE THREAD

**Issue by manishjaingit** [tinymce/tinymce#5325] opened 2019-12-21 15:34 UTC
**I am adding any data in the editor and while using move in formbuilder feature so it is giving me error**

** I gets an error in console after moving the tinymce block, and all data i put inside the editor gets remove after move, you can see in this screenshot: https://www.screencast.com/t/XngoXHelRL7
as i am using https://formbuilder.online/ and instead of TextArea of paragraph, i am using tinyMCE editor by moving its area it is giving me error also removing all content.
 **

**Data should be the same as i written in box although i am moving tinymce editor **

** I am using 4.8.1 (2018-07-26) in TinyMCE and jquery form builder **

**Comment by lnewson** [comment] 2020-05-04 03:47
I'm sorry, but there's really not enough information here for us to help out here. Can you please include a small reproduction case, or some way for us to see what's going on. It'd also be helpful to include browser details, as it might be a problem specific to certain browsers.

It's likely what's happening here, based on the information given, is you're manipulating the DOM element TinyMCE is rendered in which will cause the inner iframe element to reload. This is not supported, so when the DOM needs to be moved, deleted, etc... you need to ensure to destroy the TinyMCE instance and reinitialise it when once the dom element has been reconnected or moved to the new position.

**Comment by lnewson** [comment] 2020-06-08 20:47
Closing due to a lack of additional information. If you can provide the information requested above then we'll be happy to reopen this issue.

**Closed by lnewson** 2020-06-08 20:47 UTC
Labels: needs: more info
