### ISSUE TITLE
Table cell property - width - inline style format

### ISSUE THREAD

**Issue by vr1e** [tinymce/tinymce#3974] opened 2017-10-04 12:48 UTC
**Do you want to request a *feature* or report a *bug*?**
This is a bug.

**What is the current behavior?**
There is a bug in current way TinyMCE is setting cell width property inside table plugin.
The width of the cell is set this way: style="width: 100px;"
The actual inline style should be in this format: width="70%" without "style".
When set with style it doesn't get saved or displayed properly in front end.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Here is a demonstration of the bug: http://fiddle.tinymce.com/7bgaab

**What is the expected behavior?**
The actual inline style should be in this format: width="70%" without "style".

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE v4.7.0

**Comment by spocke** [comment] 2017-10-06 13:32
It's correct according to the HTML5 specifications. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table#attr-width

So I'm closing this one since it's the expected behavior.

**Closed by spocke** 2017-10-06 13:32 UTC
