### ISSUE TITLE
the icon of toolbar is missing , my version is 5.3.1

### ISSUE THREAD

**Issue by kqy520** [tinymce/tinymce#5753] opened 2020-06-09 02:14 UTC
**What is the current behavior? Describe the bug**
![image](https://user-images.githubusercontent.com/28554158/84098504-02cc7400-aa3a-11ea-9ea3-b63b86e794ff.png)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by lnewson** [comment] 2020-06-09 02:37
Closing again, as you haven't included the details again, as previously requested in https://github.com/tinymce/tinymce/issues/5752. Please fill out the details requested in the template.

Also as I mentioned in https://github.com/tinymce/tinymce/issues/5752 the cause will likely be you aren't including the `icons/default/icons.js`/`icons/default/icons.min.js` files in your distribution.

**Closed by lnewson** 2020-06-09 02:37 UTC
