### ISSUE TITLE
The option forced_root_block_attrs not working when remove Numbered list / Bullet list

### ISSUE THREAD

**Issue by laeeqwtb** [tinymce/tinymce#5167] opened 2019-09-18 11:29 UTC
I have used **forced_root_block_attrs** option to apply **data-editor=1** attribute to P tags like below:

```
forced_root_block : 'p',
forced_root_block_attrs: {
	'data-editor': '1'
},
```
The above code applying **data-editor=1** correctly to P tag when added after Enter key press. But when created a **Numbered list / Bullet list** and then remove Numbered list / Bullet list by clicking Numbered list / Bullet list icon from editor tools. In that case P tag applied to content without applying data-editor attribute to P tag. 

**Steps to reproduce issue:**

1- Create **Numbered list / Bullet list** in editor
2- Select all Numbered list / Bullet list content and remove Numbered list / Bullet list by clicking Numbered list / Bullet list icon from editor tools.

You can check this on TinyMCE fiddle:

http://fiddle.tinymce.com/SQgaab/

**Expected behavior:**

The **data-editor** attribute should be apply to **P** tag when remove Numbered list / Bullet list by clicking Numbered list / Bullet list icon from editor tools.

**Comment by lnewson** [comment] 2019-10-20 08:47
It looks like the cause is this line: https://github.com/tinymce/tinymce/blob/master/modules/tinymce/src/plugins/lists/main/ts/core/TextBlock.ts#L25 as it's not doing a case insensitive check, which then causes the attributes to never be set. So if you change the fiddle to use an uppercase `P` that seems should largely work, eg: http://fiddle.tinymce.com/SQgaab/3

**Comment by lnewson** [comment] 2020-02-14 23:26
TinyMCE 5.2.0 was released to the community earlier this week, which contained a fix for this issue. Please let us know if you have any further issues.

**Closed by lnewson** 2020-02-14 23:26 UTC
Labels: plugin: lists, status: escalated, type: bug
