### ISSUE TITLE
TinyMCE remove span style

### ISSUE THREAD

**Issue by mikaGI-coder** [tinymce/tinymce#5336] opened 2020-01-08 13:02 UTC
**What is the current behavior? Describe the bug**

Hello,

I have a problem with TinyMCE inline editor and angular 7.

When I provided this html to the editor:

```
<div class="page">
    <div class="info-tiers-top-right">
        <p class="mb-0 editable mce-content-body" id="mce_0" contenteditable="true" style="position: relative;" spellcheck="false"><span style="font-size: 24pt;" data-mce-style="font-size: 24pt;">{{AdresseTiers}}</span></p>
        <p class="mt-50 editable mce-content-body" id="mce_2" contenteditable="true" style="position: relative;" spellcheck="false">{{VilleAdresseAgence}}, le {{DateEmissionAgValidee}}</p>
    </div>
    <div class="editable mce-content-body" id="mce_3" contenteditable="true" style="position: relative;" spellcheck="false"><p class="mb-0 mt-25"><strong>Objet : </strong>CONVOCATION</p><p class="m-0"><strong>{{MentionAR}}</strong></p><p class="mt-0"><strong>{{NumeroAR}} </strong></p><p><strong>Copropriétaire: </strong> {{NumeroTiers}} {{CiviliteTiers}} {{NomTiers}} {{PrenomTiers}} <br>{{CareOfTiers}}</p><p class="mt-25"><strong>Mandat de syndic :</strong> {{NumeroMandatImmeuble}}</p><p class="mt-25 mb-0"><strong>Immeuble</strong></p><p class="m-0">{{NomImmeuble}}</p><p class="m-0">{{AdresseImmeuble}}</p></div>
    <div class="editable mce-content-body" id="mce_4" contenteditable="true" style="position: relative;" spellcheck="false"><p class="mt-25">{{FormulePolitesse2Tiers}},</p><p>Le syndic vous prie de bien vouloir assister à <strong class="text-uppercase">L'{{TypeLongAssemblee}}</strong> des copropriétaires qui aura lieu le <strong>{{DateAssemblee}} à {{HeureDebutAssemblee}} précises</strong>, à l'adresse suivante :</p><p class="text-center mb-0 mt-25"><strong>{{AdresseSalle}}</strong></p><p class="mt-25">Nous vous prions de croire, {{FormulePolitesse1Tiers}}, à l'expression de nos sentiments distingués.</p><p class="text-center mt-35">{{Signataire}}</p></div>
</div>
```

He transforms it this way: 

```
<div class="page">
    <div class="info-tiers-top-right">
        <p class="mb-0 editable mce-content-body" id="mce_9" contenteditable="true" style="position: relative;" spellcheck="false"><span>{{AdresseTiers}}</span></p>
        <p class="mt-50 editable mce-content-body" id="mce_10" contenteditable="true" style="position: relative;" spellcheck="false">{{VilleAdresseAgence}}, le {{DateEmissionAgValidee}}</p>
    </div>
    <div class="editable mce-content-body" id="mce_11" contenteditable="true" style="position: relative;" spellcheck="false"><p class="mb-0 mt-25"><strong>Objet : </strong>CONVOCATION</p><p class="m-0"><strong>{{MentionAR}}</strong></p><p class="mt-0"><strong>{{NumeroAR}} </strong></p><p><strong>Copropriétaire: </strong> {{NumeroTiers}} {{CiviliteTiers}} {{NomTiers}} {{PrenomTiers}} <br>{{CareOfTiers}}</p><p class="mt-25"><strong>Mandat de syndic :</strong> {{NumeroMandatImmeuble}}</p><p class="mt-25 mb-0"><strong>Immeuble</strong></p><p class="m-0">{{NomImmeuble}}</p><p class="m-0">{{AdresseImmeuble}}</p></div>
    <div class="editable mce-content-body" id="mce_12" contenteditable="true" style="position: relative;" spellcheck="false"><p class="mt-25">{{FormulePolitesse2Tiers}},</p><p>Le syndic vous prie de bien vouloir assister à <strong class="text-uppercase">L'{{TypeLongAssemblee}}</strong> des copropriétaires qui aura lieu le <strong>{{DateAssemblee}} à {{HeureDebutAssemblee}} précises</strong>, à l'adresse suivante :</p><p class="text-center mb-0 mt-25"><strong>{{AdresseSalle}}</strong></p><p class="mt-25">Nous vous prions de croire, {{FormulePolitesse1Tiers}}, à l'expression de nos sentiments distingués.</p><p class="text-center mt-35">{{Signataire}}</p></div>
</div>

```

Here is the init of TinyMCE : 

```
 this.editor = tinymce.init({
                selector: '.editable',
                extended_valid_elements: '*[*]',
                menubar: false,
                inline: true,
                plugins: ["quickbars"],
                toolbar: [
                    'undo redo | bold italic underline | fontselect fontsizeselect | forecolor backcolor | alignleft aligncenter alignright alignfull | numlist bullist outdent indent | quickimage | template'
                ]
            });

```

**What is the expected behavior?**

Spans should retain their attributes

**Which versions of TinyMCE, and which browser / OS are affected by this issue?

Angular 7
TinyMCE 5.1.4
TinyMCE Angular 3.3.1
Chrome  78.0.3904.70

**Comment by SimonFc** [comment] 2020-01-14 20:14
Hi!

First thing, it doesn't look like you're using [tinymce-angular](https://github.com/tinymce/tinymce-angular)? (considering how you initialize TinyMCE)

Secondly, it looks like you're initializing TinyMCE on elements that are created and managed by Angular? (everything in your templates are created and managed by Angular)

At this point I don't think anything is certain. As an example, you have the interpolation `{{AdresseTiers}}` and I imagine that editing this/the containing element could lead to some unexpected behavior since you're not meant to modify the DOM directly when using Angular.

I would recommend taking a closer look at our tinymce-angular integration and see if you can accomplish what you need to do with the help of that instead! You can read about it [here](https://www.tiny.cloud/docs/integrations/angular/).

**Comment by lnewson** [comment] 2020-02-23 19:02
Closing this as the information requested above hasn't been provided, so we can't investigate any further. We'll be happy to reopen this if you're still having issues and can provide the requested information.

**Closed by lnewson** 2020-02-23 19:02 UTC
Labels: needs: more info
