### ISSUE TITLE
unlink doesn't show in contextmenu

### ISSUE THREAD

**Issue by lnprieto** [tinymce/tinymce#4253] opened 2018-02-27 11:08 UTC
Hi

I use TinyMCE 4.7, last production version, 

``plugins: "contextmenu directionality link image ",
    contextmenu: "image link unlink openlink | align removeformat",
``

But here is the contextmenu 
![image](https://user-images.githubusercontent.com/28725030/36725430-97cae57e-1bb6-11e8-86ff-1a508740585d.png)

No way to see Unlink appear

Any Idea ?
Thank you

**Comment by fyrkant** [comment] 2018-03-19 13:46
Hi! 
This is not available because there's no menu item for the unlink action, only a button. I will fix this and add a menuitem for unlink, it will be a part of the next release.

**Comment by lnprieto** [comment] 2018-03-20 07:04
Hi
Thank you very much for the answer and the future menu item
Best regards

**Comment by lnewson** [comment] 2020-04-28 13:03
Looking back at the changelog it looks as though this was fixed in TinyMCE 4.7.10 and I can confirm it also works in the latest version of TinyMCE 4. I'm going to go ahead and close this, but please let us know if you are still having issues and we'll reopen the issue.

Thanks!

**Closed by lnewson** 2020-04-28 13:03 UTC
Labels: status: escalated, status: verified
