### ISSUE TITLE
p::first-letter doesn't work

### ISSUE THREAD

**Issue by Olli** [tinymce/tinymce#3506] opened 2017-02-24 14:26 UTC
**Do you want to request a *feature* or report a *bug*?**
It's a bug report.

**What is the current behavior?**
TinyMCE doens't show the ::first-letter formatings from the custom CSS file in the editor field. After "Clear Format" it works.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

add .mce-content-body p::first-letter { background-color: yellow } to the custom CSS .

**What is the expected behavior?**
correct formatting of the first letter according to the CSS file.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I use Firefox 51.0 and TinyMCE 4.1.10 but I'd tryed it with the developer console on the actual 4.3 demo. Same results.

**Comment by lnewson** [comment] 2020-05-09 10:48
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2 using http://fiddle.tinymce.com/iihaab, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 10:48 UTC
