### ISSUE TITLE
Tinymce menu dropdown multi language translation is not working

### ISSUE THREAD

**Issue by murtaza427** [tinymce/tinymce#6170] opened 2020-11-02 10:35 UTC
Hi there,
             i am currently using tinymce multi language for English and Arabic. Which is working fine for menu but when i click menu items that appears in dropdown they are not translated in required language. they are always translated with default language
![Tinymce](https://user-images.githubusercontent.com/73825833/97858460-016d5200-1d21-11eb-9342-cf98eed857eb.png)

**Comment by lnewson** [comment] 2020-11-02 10:48
I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/6131. TinyMCE doesn't support rendering editors in multiple locales and we haven't been able to find a good use case for that yet. If you have one, please add it to the linked issue.

**Closed by lnewson** 2020-11-02 10:48 UTC
