### ISSUE TITLE
"Image Title" not translated with language pack

### ISSUE THREAD

**Issue by Hawkeye1909** [tinymce/tinymce#3631] opened 2017-05-09 20:20 UTC
In image plugin the label "Image Title" is not translatable. Analogous to issue #1025.

**Comment by lnewson** [comment] 2020-04-26 12:50
Hi,

I'm unable to replicate this issue in the latest version of TinyMCE (5.2.2). Given that the way translations are handled for plugins was overhauled in TinyMCE 5, this may have been what fixed this issue. Alternatively it may have been fixed by another change since you reported this issue.

However, since we're unable to replicate it anymore I'll go ahead and close this issue. If you're still able to reproduce this in the latest version however, then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-04-26 12:50 UTC
