### ISSUE TITLE
TinyMCE 4.6.x slower to load?

### ISSUE THREAD

**Issue by petko** [tinymce/tinymce#3651] opened 2017-05-16 10:20 UTC
Since I upgraded to 4.6.x, it seems that tinyMCE loads slower or something was changed for it to look so.

I hide certain UI elements in `init` (toolbar, status bar) and make the editor full screen. In 4.5.x everything went smoothly and these elements were hidden properly. Now in 4.6.x there is a certain delay before they are hidden, so the user is presented with an unpleasant flash of these elements, before they are hidden.

This is the code I use:
```
      editor.on('init', function() {
        editor.getBody().style.backgroundColor = backgroundColor;
        $('div.mce-toolbar').toggle();
        $('div.mce-toolbar-grp').toggle();
        $('div.mce-statusbar').toggle();
        $('div.mce-edit-area').css('border', 'none');
        editor.execCommand('mceFullScreen');
        ...
```
I toggle visibility instead of removing these elements in the settings, because I want to be able to show them later.

Does anybody else experience this and what could be causing it?

**Comment by spocke** [comment] 2017-05-16 11:17
There was one change regarding initialization where the editor now waits for the content_css file to load before it initializes. So if you want to avoid foc hide the elements before the tinymce.init call.

**Comment by petko** [comment] 2017-05-16 12:44
It seems to me that these elements are not available before the `init` call, so I should hide them via the content_css (or other css file)? Is that right?

**Comment by spocke** [comment] 2017-05-16 13:08
We need a way to reproduce this issue. Can you setup a fiddle or similar so that we can try to reproduce this. Thanks.

**Comment by petko** [comment] 2017-05-17 13:30
I've created two fiddles for the new and for the old version:
4.6.1 (flashing): http://jsfiddle.net/petko/ekLcddvf/
4.5.7 (not flashing): http://jsfiddle.net/petko/dgyxno2j/

**Comment by spocke** [comment] 2017-05-22 09:55
This seems like a very specific use case and can be avoided by using css:
```css
div.mce-toolbar, div.mce-toolbar-grp, div.mce-statusbar {
  display: none;
}
```
The init is now slightly more delayed since we wait for the content css to be fully loaded. Since this is by design and not really a bug I'm closing this one.

**Closed by spocke** 2017-05-22 09:55 UTC
Labels: needs: more info
