### ISSUE TITLE
Inline style duplicate with data

### ISSUE THREAD

**Issue by ZeGregg** [tinymce/tinymce#2508] opened 2015-11-27 14:44 UTC
HI,

Is it normal behaviour when for example formatting text to get `<p style="text-align: center;" data-mce-style="text-align: center;”>`

I mean having 2 text-align: center

Regards

**Comment by cauburtin** [comment] 2015-11-28 20:54
I wonder also the point of  those data-mce-attr if they always reflect the attr

    <span style="color: rgb(153, 51, 0); font-size: 18pt; background-color: rgb(255, 204, 153);" data-mce-style="color: #993300; font-size: 18pt; background-color: #ffcc99;">editable </span>

**Comment by spocke** [comment] 2015-11-30 01:44
Yes, this is by design for performance reasons and also to work around blink/webkit bugs. Some browsers mess up the style attribute and we also need to serialize that.

**Comment by spocke** [comment] 2015-11-30 01:44
Closing since this is more of a question than a bug/feature.

**Closed by spocke** 2015-11-30 01:44 UTC

**Comment by cauburtin** [comment] 2015-11-30 09:48
ok, thanks :)
