### ISSUE TITLE
Inline editor color picker can be off bottom of the screen.

### ISSUE THREAD

**Issue by StartingDreams** [tinymce/tinymce#4277] opened 2018-03-14 14:41 UTC
What it currently does:
When you have an inline editor with a color picker that is at the bottom of the window, most of the color picker is off the bottom of the screen.

Demo of problem:
http://fiddle.tinymce.com/xngaab

What it should do:
When the color picker is to close to the bottom to display, it should open up instead of down.

This is a problem in the current version of tinymce (4.7.9)

Tested in:
Chrome: 64.0.3282.186
Firefox: 58.0.2

**Comment by metricjs** [comment] 2020-05-05 02:46
Hi,
I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.10. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.
Thanks!

**Closed by metricjs** 2020-05-05 02:46 UTC
Labels: status: escalated, status: verified, type: bug
