### ISSUE TITLE
The link option is not working properly for Safari.

### ISSUE THREAD

**Issue by Julyanajs** [tinymce/tinymce#5656] opened 2020-05-11 18:05 UTC
**What is the current behavior? Describe the bug**
001- Open the modal to see all options using the safari browser.
002- Click with the right button and select the option to add the link.
Return:
When the user clicking to add a link using the Safari browser the modal will be opened but the option "text to display" will not appear to fill out and even if the user fills out all other fields the link will not appear at the screen after to save.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Safari - version 13.0.5

**Comment by lnewson** [comment] 2020-05-12 05:52
@Julyanajs, I tried to reproduce this but I was unable to. Can you please create a [fiddle](http://fiddle.tinymce.com/), or a short video showing how to reproduce the issue?

**Comment by lnewson** [comment] 2020-06-08 20:55
Closing due to a lack of additional information. If you can provide the information requested above then we'll be happy to reopen this issue.

**Closed by lnewson** 2020-06-08 20:55 UTC
Labels: needs: more info
