### ISSUE TITLE
Problem with page plugins/opensource/visualchars.md

### ISSUE THREAD

**Issue by jasperf** [tinymce/tinymce#7088] opened 2021-08-09 01:39 UTC
Is there a way to show `<br>` with the visualchars plugin? Or to show a hard enter has been pressed creating a new `<p>` just like most text editors? This is not mentioned in the documentation. It seems that we can only have tabs show, but enters, or shift enters are not shown with a symbol. Nor spaces for that matter.

> *affected page: https://www.tiny.cloud/docs/plugins/opensource/visualchars/*

**Comment by lnewson** [comment] 2021-08-09 01:48
Closing as a duplicate of https://github.com/tinymce/tinymce/issues/7087

**Closed by lnewson** 2021-08-09 01:48 UTC

**Comment by jasperf** [comment] 2021-08-09 02:00
@lnewson thanks. Thought I did not add it properly or that it had been removed when I checked in docs so added a new one. Never mind this ticket now.
