### ISSUE TITLE
Custom format classes not being applied correctly

### ISSUE THREAD

**Issue by vtt** [tinymce/tinymce#5554] opened 2020-04-04 17:30 UTC
I have the following custom formats:
```
        formats: {
          h1: { block: 'h1', classes: 'title is-1' },
          h2: { block: 'h2', classes: 'title is-2' },
          h3: { block: 'h3', classes: 'title is-3' },
          h4: { block: 'h4', classes: 'title is-4' },
          h5: { block: 'h5', classes: 'title is-5' }
        }
```
When choose H1, the classes become "title is-1" - this is correct.
Then I choose H2, the classes become "title is-1 is-2" - not correct
Then I choose H3, the classes become "title is-1 is-2 is-3" - not correct
Then I choose H1 again, the classes become "title is-1 is-2 is-3"

Only the first instance is the element rendered properly; all other instances the element is rendered like H3 even though choosing H1 should remove "is-2 is-3"

**Comment by spocke** [comment] 2020-04-04 18:25
You can use attributes: {class: "your class"} to set a specific class classes just appends. Hope this helps closing this ticket since this is by design and can be avoided with configuration.

**Closed by spocke** 2020-04-04 18:25 UTC

**Comment by vtt** [comment] 2020-04-04 18:35
Thanks for the explanation; please consider updating the documentation to say that "classes" only appends and do not remove, and to use attributes feature to set specific classes for the style.

**Comment by tylerkelly13** [comment] 2020-04-06 05:57
I'm going to move this ticket to tinymce-docs to remind us to fix the documentation.
