### ISSUE TITLE
The background color is applied to the wrong text.

### ISSUE THREAD

**Issue by amesure** [tinymce/tinymce#3839] opened 2017-07-27 13:37 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
The background color is applied to the wrong text.

http://fiddle.tinymce.com/yWfaab
1 - I write two words.
2 - I select the first one with a double click and change the font size.
3 - I select the second one with a double click and change the back color.
=> Result: The color is changed for the two words...

**What is the expected behavior?**
Only the color of the second word should change.

**Comment by lnewson** [comment] 2020-05-02 10:19
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. I was able to reproduce it in the linked fiddle though, so it's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 10:19 UTC
