### ISSUE TITLE
I can't find what I'm looking for: api/tinymce/tinymce.shortcuts.html

### ISSUE THREAD

**Issue by ghazpar** [tinymce/tinymce#6564] opened 2021-02-25 14:24 UTC
I am trying to disable the alt-0 shortcut used by the help plugin. I have tried to remove both 'alt+0' and 'alt+48', but the remove call returns false and the shortcut remains. Why can't I remove this shortcut?

I want to disable this shortcut, because on a French-Canadian mac keyboard, the alt+0 key combination conflicts with the ] character, and I need to be able to enter this key in the editor.

Of course, I could remove the help plugin to solve my issue, but I would prefer to keep the help functionality in a menu while allowing my users to enter ] characters.

Many thanks in advance for your help.

**Comment by JamesToohey** [comment] 2021-03-03 05:45
Closing as a duplicate of #6561

**Closed by JamesToohey** 2021-03-03 05:45 UTC
