### ISSUE TITLE
Inlite toolbar may be overlapping browser window

### ISSUE THREAD

**Issue by MarcelvdM** [tinymce/tinymce#4670] opened 2018-11-14 15:11 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently the toolbar sometimes overlaps the browser window width.
![bildschirmfoto 2018-11-14 um 16 02 41](https://user-images.githubusercontent.com/45041122/48490934-c1a4bb80-e826-11e8-9e3b-4f2ac0ba0791.png)

**What is the expected behavior?**
Instead of being outside of the visible area it should spit up into a second line.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
I have tried this in the latest TinyMCE 4.8.5. Older versions seem to have the same problem.

Is it planned to change the current implementation of having fixed width and height values everywhere, or is there already someone who build up a bugfix for that?

**Comment by spocke** [comment] 2018-11-14 15:53
I wasn't able to reproduce this in TinyMCE v5.

**Comment by wonderbugtiny** [comment] 2019-04-08 03:41
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:41 UTC
Labels: needs: more info

**Comment by MarcelvdM** [comment] 2019-09-06 13:21
Sorry for the missing information. I couldn't reproduce it for a while, but I found out recently that this was a problem with my own configuration. The contentArea wasn't defined the right way, so the toolbar couldn't be displayed at the right position.
