### ISSUE TITLE
Webpack 2 and Angular 2 compability?

### ISSUE THREAD

**Issue by IAMtheIAM** [tinymce/tinymce#3247] opened 2016-10-05 20:07 UTC
When using Unminified TinyMCE with webpack 2 and angular2, error is thrown and the app dies:

`Error: Zone.js has detected that ZoneAwarePromise`(window|global).Promise`has been overwritten`

If I use minified version. that error is not thrown, however

`Factory.ui` is undefined

Feature request: Make TinyMCE compatible with module bundlers like webpack and work with angular2

**Comment by IAMtheIAM** [comment] 2016-10-05 21:27
Just so you know, your competition over at CKeditor is leaving TinyMCE in the dust!

They have a ready to use [CKeditor angular2 component](https://github.com/chymz/ng2-ckeditor), just plug and play. Works with webpack.

Why can't you guys do the same? I'll have to use CKeditor since it is modern software.

**Comment by fyrkant** [comment] 2016-10-06 11:38
Have you configured Webpack like it says in #2836 to use the imports-loader and exports-loader? Then you shouldn't have to add it to the head tag. 

If you are using [angular-cli](https://github.com/angular/angular-cli) you can easily, without using any special loaders, use tinymce without having to add it to the head-tag by adding the path to TinyMCE to the `angular-cli.json` file, like it says in the [documentation here](https://github.com/angular/angular-cli#global-library-installation). 

So you would first install tinymce with `npm install --save tinymce`, then add `"../node_modules/tinymce/tinymce.js"` to your `angular-cli.json` and it should be available globally in your project. 

Typescript will however complain that it "cannot fint name 'tinymce'" so you would have to add something like, either directly in the file or to your `typings.d.ts`:

```ts
declare var tinymce: any;
```

To get the skins working you could then copy the skins folder from `node_modules/tinymce/skins' to `src/assets/skins` and configure TinyMCE when you initialize it with the url like this: 

```js
tinymce.init({
      selector: '#your-selector',
      skin_url: '/assets/skins/lightgray'
});
```

`angular-cli` will then be smart enough to copy along the assets both while developing with the dev server using `ng serve`, but also when you build your project with `ng build`.

**Comment by kiddy2910** [comment] 2016-10-11 07:03
@fyrkant Awesome solution. It's working to me. Thanks a lot.

**Comment by JT-Bruch** [comment] 2016-10-13 17:31
@fyrkant I'm getting a `Uncaught module definition dependecy not found: tinymce/util/Tools`, is this common?

I followed the instructions here [https://www.tinymce.com/docs/integrations/angular2/](url) and also above and no luck.

**Comment by fyrkant** [comment] 2016-10-14 07:45
Hi @JT-Bruch !

Do you have your code up on github or somewhere so I can take a look at it? What plugins are you importing?

**Comment by fyrkant** [comment] 2016-10-14 08:04
And what version of angular-cli are you using?

**Comment by JT-Bruch** [comment] 2016-10-14 14:13
Yep!
@fyrkant its on my repo - Just-A-Dev-Blog, although give me a minute to push my changes.

beta-17

**Comment by fyrkant** [comment] 2016-10-14 14:29
I suspect that something went wrong, that you missed some step maybe when you upgraded to the latest version of angular-cli because I'm getting this error when I clone down your repo and try starting the dev server:
<img width="646" alt="screen shot 2016-10-14 at 16 26 53" src="https://cloud.githubusercontent.com/assets/8655649/19391067/20b4c164-922b-11e6-9b6c-3b974ac7d773.png">

**Comment by JT-Bruch** [comment] 2016-10-14 14:32
Hrmm interesting.  Let me nuke my repo and try again.

**Comment by JT-Bruch** [comment] 2016-10-14 14:43
Just nuked, re-cloned and not having that issue.  When you clone & then do npm install you will have to clean three changes in node_modules, I have some custom workarounds in there.    

The only thing I can think of is maybe you have an older global version of CLI?  Just went looking at both the local & global and I'm the following.

`PS C:\TestProjects\Just-A-Dev-Blog> ng version
angular-cli: 1.0.0-beta.17
node: 6.3.1
os: win32 x64`

**Comment by thehashrocket** [comment] 2016-10-14 16:59
i'm getting the tools error as well.

`main.bundle.js:74851 Uncaught module definition dependecy not found: tinymce/util/Tools`

Currently, I'm using:

```
angular-cli: 1.0.0-beta.16
node: 6.4.0
os: darwin x64
```

**Comment by fyrkant** [comment] 2016-10-14 20:23
Sorry guys, when I'm trying it out now at my computer at home I also get the error. It works without the paste and table plugins, though. I'll check what I did differently at my computer at work on monday!

**Comment by fyrkant** [comment] 2016-10-14 20:36
You can see my "working" example [here](https://github.com/fyrkant/ng-tiny) and deployed [here](https://fyrkant.github.io/ng-tiny/).

**Comment by fyrkant** [comment] 2016-10-17 08:20
Hi again @JT-Bruch, @thehashrocket and everyone! 

Sorry for the mixup, apparently I was using the nightly build at work and that's why it didn't work like expected for you guys... But the good news is I found another way to get it working!

Instead of importing them in the component file, add the paths to the plugins to the `scripts` in your `angular-cli.json` just like you already did with tinymce, then it should be working! 

See [here](https://github.com/fyrkant/ng-tiny/blob/master/angular-cli.json) for my working examples `angular-cli.json` file, and [here](https://fyrkant.github.io/ng-tiny/) for a deployed version. 

So sorry for the mess, I will be updating the documentation today!

**Comment by fhinchey** [comment] 2016-11-28 21:13
I have this working here: http://plnkr.co/edit/7lvxl88HjGQLMRl72GgF?p=preview

But how do I get model binding?

**Comment by mdudek** [comment] 2016-11-29 07:31
I have integrated tinymce into my Angular2/Webpack2 project, but it stopped working with tinymce v4.5 . I tried to migrate to 4.5, but still can't find a way how to load it using webpack.

**Comment by fyrkant** [comment] 2016-11-29 08:19
@mdudek Have you seen [this](https://www.tinymce.com/docs/advanced/usage-with-module-loaders/)? It should be possible to import tinymce, plugins and themes without the use of the exports/imports-loader with 4.5. Do you have you code on github so maybe I can take a look?

**Comment by ASHFAQPATWARI** [comment] 2016-12-29 11:02
Tinymce works fine with import of plugins and themes inside angular component except `paste` and `table` plugin.

**Comment by fyrkant** [comment] 2017-02-02 12:59
@ASHFAQPATWARI Have you tried with the latest version of TinyMCE (4.5.3)?

**Comment by mdudek** [comment] 2017-02-02 13:02
I can confirm that it's working fine with 4.5.3.

**Comment by fyrkant** [comment] 2017-02-06 09:05
Great, then I am closing this (but if anyone else still have any issues just write a comment and I can open it up again)!

**Closed by fyrkant** 2017-02-06 09:05 UTC
Labels: resolution: fixed in coming release

**Comment by adhamankar** [comment] 2017-05-18 03:14
TinyMCE works perfect with the setup along with the skin configured. Now when I try to use the theme: "inlite" I get following error

`zone.js:169 Uncaught TypeError: Theme is not a constructor
    at initTheme (eval at webpackJsonp.134.module.exports (addScript.js:9), <anonymous>:43422:26)`

Like skins, i also tried to copy the theme folder but unable to use the inlite theme

**Comment by fyrkant** [comment] 2017-05-19 11:01
@adhamankar Are you importing the inline theme? If not, try adding this: 
```js
import 'tinymce/themes/inlite';
```

**Comment by rodhoward** [comment] 2017-07-31 06:52
I found that I also needed to switch to absolute paths. Otherwise if I drilled into an angular path then refreshed and navigated back to my other tab with the html editor on it the editor wouldn't find the styles any more.

```json
            relative_urls: false,
            document_base_url: Utils.baseUrl,
            skin_url: 'assets/tinymceSkins/lightgray',
```

**Comment by areeba88** [comment] 2017-12-29 07:05
@fyrkant i am using the tinyMCE, run it successfully on separate project with Angular 4,5 generated with angular-cli using the build process of JHipster. with tinyMce 4.7.4 and node 5.3.0 i am providing the accurate path of tinymce styles ,which is, in a folder defined in the asset:"folder" in angular-cli.json but it isn't picking it.  I also follow all the path defined in this documentation [https://www.tinymce.com/](url)
having these errors, 

> 
![img_28122017_151128_0](https://user-images.githubusercontent.com/3445703/34431387-925db85a-ec90-11e7-859c-a5aa11c76ccf.png)


![img_28122017_154343_0](https://user-images.githubusercontent.com/3445703/34431392-9557db12-ec90-11e7-962d-62ad5022474c.png)

**Comment by AJamal79** [comment] 2018-05-01 12:31
I used the previous solution but didn't want to install Utils to my project so modified it to this

`relative_urls: false,
            document_base_url: '/',
            skin_url: 'assets/skins/lightgray',`
