### ISSUE TITLE
Toolbar is incorrectly positioned in inline mode when inside scroll container

### ISSUE THREAD

**Issue by benelliott** [tinymce/tinymce#6358] opened 2020-12-18 10:04 UTC
**What is the current behavior? Describe the bug**

When using inline mode in a scroll container, the toolbar is not repositioned when the container is scrolled.

Re-opening of #4839 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

https://fiddle.tiny.cloud/p1haab

**What is the expected behavior?**

The inline toolbar should update its position when the container is scrolled.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

All browsers, all TinyMCE versions

**Comment by mattford** [comment] 2020-12-18 15:58
Actually this is slightly different to #4839, in that bug the issue was that if you scrolled down in the container and then clicked in the tinymce editor, the toolbar would appear offscreen. I think I am going to reopen that issue as it was occurring in the `modern` theme, not `mobile`

**Comment by lnewson** [comment] 2021-01-03 23:36
Hi @benelliott, sorry it seems that was incorrectly closed as a `mobile` theme issue, instead of a `modern` theme issue. That being said though we currently have #5097 open as the feature request to support rendering TinyMCE inside a scrollable container so I'm going to close this as a duplicate of that.

Lastly, I should also add that TinyMCE 4 is no longer supported, which is what provided the `modern` theme: https://www.tiny.cloud/blog/tinymce-4-support-window/

**Closed by lnewson** 2021-01-03 23:36 UTC

**Comment by GraemeFulton** [comment] 2021-04-29 14:35
use `fixed_toolbar_container`


`tinymce.init({
  selector: 'textarea',  
  inline: true,
  fixed_toolbar_container: '#scrollable-area' // change this value according to your HTML
});`

https://www.tiny.cloud/docs/configure/editor-appearance/#fixed_toolbar_container
