### ISSUE TITLE
Links are not visible for editing 

### ISSUE THREAD

**Issue by rahulcse1** [tinymce/tinymce#2576] opened 2015-12-21 15:19 UTC
Links are not visible for editing.
You easily replicate issue by creating blog. ENter any link then try to update the same blog. link will be not be visible. 
http://www.techwalk.me/

**Comment by spocke** [comment] 2015-12-21 15:30
This seems like an implementation issue and not a bug. The autolink plugin will create links automatically when you type. Closing this one. Will re-open if it's a bug we can fix.

**Closed by spocke** 2015-12-21 15:30 UTC

**Comment by rahulcse1** [comment] 2015-12-21 15:42
can you please let me know what am i missing ? any configuration or something ?

**Comment by spocke** [comment] 2015-12-21 15:59
plugins: 'autolink' will generate links when you for example type www.google.com into the editor.

**Comment by rahulcse1** [comment] 2015-12-21 16:42
spocke i want to update the same link again. so when i am going in edit mode, already saved link is not  there. that's actual issue. 
Please check attached doc once.


[issue.pdf](https://github.com/tinymce/tinymce/files/68716/issue.pdf)

**Comment by spocke** [comment] 2015-12-22 09:03
Can it be reproduced here fiddle.tinymce.com is so send me a fiddle that reproduces the issue. Thanks.
