### ISSUE TITLE
Some of the applied styles get resetted once you remove the last char in a line.

### ISSUE THREAD

**Issue by solygen** [tinymce/tinymce#4005] opened 2017-10-16 08:15 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Some of the applied styles get resetted once you remove the last char in a line.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

https://codepen.io/tinymce/pen/NGegZK

1. remove editors content
2. write something and press enter
3. write something more, change style (e.g. color to red, italic, strikethrough) and continue writing
4. press enter to force a new line break (new styles still applied)
5. write a single character (still styled as expected) and then press backspace once
6. start writing again
7. some of the styles are resetted (color, strikethrough) others are not (bold, italic, background)

**What is the expected behavior?**

7. all styles are still applied

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

Tested latest version with Chrome 61 on Mac

**Comment by lnewson** [comment] 2020-05-08 09:27
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 and 5.2.2 using the details provided, however looking back at the changelog it appears this issue was fixed in TinyMCE 4.7.2. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 09:27 UTC
Labels: status: escalated, status: verified, type: bug
