### ISSUE TITLE
[5.0.1] [Inline] quickbars_insert_toolbar sometimes persists after editor closes

### ISSUE THREAD

**Issue by jordanade** [tinymce/tinymce#4853] opened 2019-02-28 01:19 UTC
I'm getting behavior where the quickbars_insert_toolbar is sometimes still showing even after the inline editor is blurred. Can't quite pin down when it happens—about half the time it seems.

**Comment by lnewson** [comment] 2019-02-28 03:57
@jordanade thanks for the report! I've tried to replicate this myself, however as of 5.0.1 I'm unable to (I was able to replicate it in 5.0.0). Would you please be able to provide a fiddle or something similar to show how to reproduce the issue? Additionally it'd be helpful if you could provide what browser, etc... you're using as it maybe a browser specific issue.

**Comment by DRoet** [comment] 2019-02-28 14:31
I had the same issue using `vue.js` and `5.0.1`, however I fixed it by calling 
`tinymce.get(this.textareaId).remove()`
instead of:
```tinymce.remove(`#${this.textareaId}`)```

So I guess it might have been a virtual DOM issue for me

**Comment by wonderbugtiny** [comment] 2019-04-08 03:50
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:50 UTC
Labels: 5.x, needs: more info, plugin:inlite
