### ISSUE TITLE
closing last of multiple open dialog caret position is lost

### ISSUE THREAD

**Issue by bah2002us** [tinymce/tinymce#4682] opened 2018-11-27 07:14 UTC
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
using custom filebrowser and closing it with window.top.tinymce.activeeditor.windowmanager.close the caret position in the editor is lost.

**What is the expected behavior?**
expected behaviour would be that the caret maintains its position

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
tinymce 4.8.5
browser EDGE

**Comment by fyrkant** [comment] 2018-12-06 08:10
I don't think this is a problem with tinymce but with your custom filepicker, but if you can create a reproduction in a fiddle I can take a look at it.

**Comment by wonderbugtiny** [comment] 2019-04-08 03:45
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:45 UTC
Labels: needs: more info
