### ISSUE TITLE
With forced_root_block false in 4.3.13, trying to delete last image gives "Uncaught TypeError: Cannot read property 'nodeName' of null"

### ISSUE THREAD

**Issue by mutatron** [tinymce/tinymce#2989] opened 2016-06-10 16:28 UTC
This is a new issue since 4.1.3. In our app, we have forced_root_block set to false. When an image is the last element on the page, if you try to delete it you get: "Uncaught TypeError: Cannot read property 'nodeName' of null", unless it's the only element on the page.

If you wrap it in another element you don't get this error, and the image deletes. If there's any other item after the image, even a single character, you don't get the error and the image deletes.

So for example if you open the source and put this in:
`a <img src="http://ridgeaviation.ie/images/czaw-SportsCruiser-pic01.jpg" alt="" width="400" height="300" />b
`
you can then delete the image from the UI.

But with this:
`a <img src="http://ridgeaviation.ie/images/czaw-SportsCruiser-pic01.jpg" alt="" width="400" height="300" />
`
you can't.

If you put "&nbsp;" at the end, you won't be able to delete because the editor apparently trims the space, But if you put "&zwnj;" at the end it doesn't get trimmed, is invisible, and you can delete the image.

Here's the html:

```
<!DOCTYPE html>
<html>
<head>
  <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  <script>
tinymce.init({
    selector:'textarea',    toolbar: "fontselect fontsizeselect | bold italic underline| bullist numlist outdent indent | alignleft aligncenter alignright alignjustify | forecolor backcolor | link  anchor code",
    menubar: "edit insert view format table tools",
  plugins: [
    'advlist autolink lists link image charmap print preview hr anchor pagebreak',
    'searchreplace wordcount visualblocks visualchars code fullscreen',
    'insertdatetime media nonbreaking save table contextmenu directionality',
    'emoticons template paste textcolor colorpicker textpattern imagetools'
  ],
  image_advtab: true,
force_br_newlines: true,
force_p_newlines: false,
forced_root_block: false
  });
</script>
</head>
<body>
  <textarea>Easy (and free!) You should check out our premium features.</textarea>
</body>
</html>
```

**Comment by mutatron** [comment] 2016-07-05 21:06
I found a fix for this, in tinymce.js, line 32042:

    function deleteRangeBetweenTextBlocks(rng) {
        var startBlock, endBlock, caretNodeBefore, caretNodeAfter, textBlockElements;

        if (rng.collapsed) {
            return;
        }

        //startBlock = dom.getParent(RangeUtils.getNode(rng.startContainer, rng.startOffset), dom.isBlock);
        startBlock = dom.getParent(RangeUtils.getNode(rng.startContainer, rng.startOffset));
        endBlock = dom.getParent(RangeUtils.getNode(rng.endContainer, rng.endOffset), dom.isBlock);

Just remove dom.isBlock from the dom.getParent() call for startBlock. This seems to have no side effects. I hope someone on the TinyMCE project will be able to give this a look and see if it's a viable fix.

**Comment by mutatron** [comment] 2016-07-29 21:09
This is still a bug as of 4.4.1.

**Comment by Jules2010** [comment] 2017-01-12 10:45
This is also still a bug in 4.5.2, however the above fix doesn't work for me.

In chrome, I get an error around line 39840 where body is null.

				if (body.nodeName == 'TABLE') {
					content = '<tr><td>' + padd + '</td></tr>';
				} else if (/^(UL|OL)$/.test(body.nodeName)) {
					content = '<li>' + padd + '</li>';
				}

**Comment by lnewson** [comment] 2020-05-09 07:39
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2 using http://fiddle.tinymce.com/fihaab, however it appeared to be working as expected. It's likely the issue has been fixed since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 07:39 UTC
Labels: component: keyboard, type: bug
