### ISSUE TITLE
how can i upload my local image to my server with tinymce?

### ISSUE THREAD

**Issue by GitCod-Man** [tinymce/tinymce#2568] opened 2015-12-18 05:35 UTC
is there any way to upload local image ?thanks

**Comment by spocke** [comment] 2015-12-21 10:08
Yes, drag drop. Check the image upload documentation.
Closing this one since it's not a bug report or feature request.

**Closed by spocke** 2015-12-21 10:08 UTC

**Comment by fatemap** [comment] 2016-01-04 11:48
I am using free version of tinymce and drag and drop of a jpg on local mc is not working. 
Is it supported only in the paid version?
