### ISSUE TITLE
[Violation] reports in dev console

### ISSUE THREAD

**Issue by Daijobou** [tinymce/tinymce#4327] opened 2018-04-05 07:22 UTC
In Opera Dev Console I see this "Violation" reports for tinymce.js (example http://fiddle.tinymce.com)

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Source: tinymce.js:850

[Violation] Avoid using document.write().
Source: tinymce.js:23809

[Violation] 'load' handler took 242ms
Source: VM51 tinymce.js:7248

[Violation] 'setTimeout' handler took 54ms
Source: VM51 tinymce.js:4642

**Comment by fyrkant** [comment] 2018-04-05 08:39
Duplicate of #4312

**Closed by fyrkant** 2018-04-05 08:39 UTC
