### ISSUE TITLE
lesser than character causes display error in editor

### ISSUE THREAD

**Issue by vprokop** [tinymce/tinymce#3123] opened 2016-08-11 08:57 UTC
When using lesser than character in Wiris math editor, save the result and reopen the editing form, I get the error stating "Error converting from MathML to accessible text" at the fomula place. The formula x <4 appears in MathML as following:
`<p><math xmlns="http://www.w3.org/1998/Math/MathML"><mi>x</mi><mo>&#160;</mo><mo>&#60;</mo><mn>4</mn></math></p>`

**Comment by spocke** [comment] 2016-08-11 11:36
Make sure that < is encoded as &amp;lt;

**Comment by vprokop** [comment] 2016-08-11 15:19
Hi,
I am using Wiris editor to use the lesser than character. The Wiris editor
produces:

<p><math xmlns="http://www.w3.org/1998/Math/MathML
"><mo>&#60;</mo></math></p>

I have no control over how the lesser than character will be represented in
HTML produced by Wiris and TinyMCE. Unfortunatelly the problem persist.

Best regards,
Vaclav

**Comment by donShakespeare** [comment] 2016-08-13 11:55
If you are going to do complex things like Math, I advise you to use Markdown or some other pure text and not Rich Text.
And yes, awesome TinyMCE supports Markdown.
Try my awesome plugin
https://github.com/donShakespeare/twExoticMarkdownEditor

**Comment by lnewson** [comment] 2020-05-09 08:03
Hi,

I attempted to replicate this using the Wiris demo here: http://www.wiris.com/plugins/demo/tinymce4/php/ and I'm unable to reproduce this issue.  It's likely the issue has been fixed either in the Wiris plugin or in TinyMCE itself since this was originally reported and as such I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll investigate this issue further.

Thanks!

**Closed by lnewson** 2020-05-09 08:03 UTC
Labels: component: input/output, type: bug
