### ISSUE TITLE
Zero-width spaces are used in Khmer

### ISSUE THREAD

**Issue by sovichet** [tinymce/tinymce#2859] opened 2016-04-17 16:12 UTC
Hi,
I just found that from 4.3.x, `Zwsp` class was included in the code and the `trim` method removes them from the text. Currently in Khmer, we use zwsp as word boundaries due to the lack of word breaking support for Khmer on many OSs and softwares. I'm a WordPress user, and few years ago I opened a ticket [here](https://core.trac.wordpress.org/ticket/21025) discussing about this too.

I'm not sure if zwsp can make any problem?

Thanks 😃 

PS: I found that the zwsp trimming appears in code (`Serializer.serialize()`) again. It was removed once in 3.5.5. I'm not sure if zwsp is BOM, but I read in Wikipedia and some sources and they said that the BOM character is `\uFEFF`.

**Comment by sbbic** [comment] 2016-04-18 10:43
Yes, I confirm that this is broken from 4.3.x
When I try and publish something with zero-width spaces in Wordpress Tinymce strips the zero-width spaces from the post (which makes line breaks really bad).
It would be great to see a fix for this - especially since it is a regression. Thank you!

**Comment by spocke** [comment] 2016-04-29 04:35
Yes, we will look into this one.

**Comment by iseulde** [comment] 2016-08-24 08:01
Cross reported on WordPress Trac https://core.trac.wordpress.org/ticket/37808

**Comment by spocke** [comment] 2016-08-24 08:26
The issue with the BOM character is that it has a height that shows in Firefox when the font size is 11px or less. So the line jumps up and down if you navigate around contentEditable=false inline elements. But I guess fixing Kamer might be more important than that visual glitch and it isn't a problem for wordpress since the font size is higher there. We will probably bump the default text size in upcoming versions however that is kind of a braking change so I don't want to do that in a patch release.

**Comment by spocke** [comment] 2016-08-24 08:35
Fixed here: https://github.com/tinymce/tinymce/commit/1696e387e818d9c3f4e2e2d8871f0218208a0212

**Comment by iseulde** [comment] 2016-08-24 08:41
Thank you! That was fast. :)

**Comment by sbbic** [comment] 2016-08-24 09:17
Thanks so much!

**Comment by sovichet** [comment] 2016-08-24 12:06
Hello @spocke I built the js with your new commit and paste it into WordPress, and it is working fine. Thanks for your help. :)

**Comment by sbbic** [comment] 2016-08-25 07:09
I also want to confirm that the patch is working. Thank you @spocke @sovichet and @iseulde !

**Comment by S-mardii** [comment] 2016-09-15 10:00
@sovicet how do that work?

**Comment by sovichet** [comment] 2016-09-15 13:59
@S-mardii you meant how to get it work in WordPress or ...? Basically, I just pull source code and build it.

**Comment by S-mardii** [comment] 2016-09-16 02:26
@sovichet yeah on wordpress. Do you need to manually adjust the source code to make it work on wordpress?

**Comment by sbbic** [comment] 2016-09-16 02:30
@S-mardii Here's how to do it based on @sovichet http://www.sbbic.org/2016/08/24/fix-khmer-zero-width-space-issue-wordpress/

**Comment by S-mardii** [comment] 2016-09-16 02:41
@sbbic Thanks for the information. I will read that in details.

**Comment by spocke** [comment] 2016-09-20 07:44
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2016-09-20 07:44 UTC
Labels: component: input/output, status: verified, type: bug
