### ISSUE TITLE
Config max file size for image upload when 'automatic_uploads' is false

### ISSUE THREAD

**Issue by siyun7** [tinymce/tinymce#6157] opened 2020-10-30 15:48 UTC
This is a feature request.

Can we provide a option to set max upload image size when we set automatic_uploads false.

**Comment by lnewson** [comment] 2020-10-31 03:22
Hi @siyun7, I'm going to close this as a duplicate of https://github.com/tinymce/tinymce/issues/4897 which is the issue currently being used to track this feature request.

**Closed by lnewson** 2020-10-31 03:22 UTC
