### ISSUE TITLE
Image Plugin - Image Drag & Drop

### ISSUE THREAD

**Issue by punnguyen** [tinymce/tinymce#3055] opened 2016-07-11 11:49 UTC
Image CSS Styling is lost after image dragging in CHROME.
When I added a style for image (ex. border...) on the demo site https://www.tinymce.com/docs/demo/full-featured/ (used image plugin, advance tab) and I dragged this image somewhere in the editor, then the image css is missing.

**Comment by lnewson** [comment] 2020-04-26 11:29
Hi,

Thanks for the bug report! I've just tried reproducing this using TinyMCE 5.2.1 and I'm not able to reproduce the issue. The border was maintained when dragging the image within the editor.

As such it's likely this has been fixed since you logged this issue, so I'm going to go ahead and close it. If you're still able to reproduce the issue in the latest version however, then let us know and we'll reopen this issue.

Thanks Lee

**Closed by lnewson** 2020-04-26 11:29 UTC
Labels: type: bug
