### ISSUE TITLE
Clicking 'Cancel' on any popup and then inserting a new table triggers a full reload in Edge

### ISSUE THREAD

**Issue by rpg1503** [tinymce/tinymce#2660] opened 2016-01-27 20:06 UTC
Steps to reproduce:
1. Open Edge browser (latest version is 25.10586.0.0)
2. Go to https://www.tinymce.com/
3. Go to any window popup, ie: 'Insert/edit link'
4. Click 'Cancel'
5. Go to Table / Insert Table
6. Choose any dimension and click to confirm

TinyMCE is going to do a full reload/postback.

Note: It's reproducible in both tinymce website and in my own implementation. Also, I'm using Windows 10.

Did anybody run into this issue as well?

**Comment by rpg1503** [comment] 2016-02-01 16:42
Thanks a lot for looking into this issue. I know you guys are busy with all the current bugs, but do you have any time frame estimate for a fix? Perhaps Q1 or Q2?

**Comment by spocke** [comment] 2016-02-03 13:32
This is one of those really odd bugs it seems that is has to do with focus state in edge. I managed to work around it by waiting for a request animation frame when you select menu items not the nicest fix but hard to figure out externally what going on inside Edge.

**Comment by rpg1503** [comment] 2016-02-03 15:28
Thanks again for your quick response. It this a priority bug fix for the next release? If not, would you mind sending me a code snippet with your fix?

**Comment by lnewson** [comment] 2020-05-03 23:56
Hi,

I'm unable to reproduce either issue in TinyMCE 4.9.10 and 5.2.2, or even in a much older version such as 4.3.0 using the details provided on Microsoft Edge 44.17763.831.0 (Win 10). So it's likely this is something that was fixed within Microsoft Edge itself since this was originally reported. As such I'm going to close this, however if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-03 23:56 UTC
Labels: browser: edge, component: ui, status: verified, type: bug
