### ISSUE TITLE
TinyMCE 4.1.7 paste from word does not retain bullets and  line breaks.

### ISSUE THREAD

**Issue by TinyMCE-User** [tinymce/tinymce#2083] opened 2015-01-27 12:25 UTC
Description of problem:

I am using following initialization

tinyMCE.init(
    {   selector: "textarea",
        browser_spellcheck: "true",
        plugins: "paste",
        encoding: "xml",
        menubar: "false",
        extended_valid_elements: "ul,li,ol,strong,p,u,em,b,br,i,strike",
        paste_retain_style_properties: "color font-size",
        paste_word_valid_elements: "b,strong,i,em,h1,h2,table,tr,td",
        paste_use_dialog: false,
        cleanup_on_startup: true,
        paste_create_paragraphs: true,
        paste_create_linebreaks: true,
        paste_retain_style_properties: "all",
        paste_auto_cleanup_on_paste: true,
        init_instance_callback: function (editor) { CharacterCount(editor); },
        setup: function (ed) {
            ed.on('keyup', function (e) { CharacterCount(ed); });
            ed.on('SaveContent', function (ed) { ed.content = ed.content.replace(/&#39/g, "&apos"); });
            ed.on('undo', function (e) { CharacterCount(ed); });
            ed.on('redo', function (e) { CharacterCount(ed); });
            ed.on('change', function (e) { CharacterCount(ed); });
        },
        save_callback: "RemoveHTMLTagsBeforeRendering" 
    });

Steps to reproduce:
1. Used the above initialization of Tiny MCE 4.1.7
2. Copied text from word with bullets, numbering, font-style, bold, italics, underline , font-color using Ctrl+C
3. And pasted the copied text into TinyMCE editor using Ctrl+V
4. The pasted text lost the bullets, line-breaks, font-color,font-style,     underline but retained the numbering, bold, italics
5. Internet Explorer 10 browser was used.

Expected result: It should retain the word formatting

Actual result: It did not retain all the formatting

What initialization setting is missing ? Please help.

Thank you,

Rohit

> _**Legacy information imported from TinyMCE bug tracker:**_
> 
> _[#T7360](http://archive.tinymce.com/develop/bugtracker_view.php?id=7360) posted by [rohitiscancerian](http://archive.tinymce.com/profile.php?name=rohitiscancerian)_
> 
> _**Tags:** [msie msie9 msie10 tinymce 417]_
> _**Status:** Open_
> _**Resolution:** None_
> _**Attached URL:** none_

**Comment by toddmay1** [comment] 2015-12-10 19:01
I found success with pasting from MS Word for bullets and numbered lists.   Attempts to paste anything letter related fail (roman, abc lists).

The issue appears to be with the pasting from MS Word.   I am unable to find any special attributes from MS Word in the pasting process that is revealing the use of a lettered list.

To duplicate:
1) Open MS Word and type a sentence, press return.
2) Start a lettered list like a. This is my A line (return), b. This is by B line. (return) - Repeat x times.
3) Highlight MS Word text and paste into TinyMCE.
4) The list inside TinyMCE will not be letters, but will show as a numbered list.
5) Place cursor on any line item 1,2,3.
6) Note that TinyMCE bullet list in tool bar just became highlighted.
7) Select letter, roman, etc.  List will properly render.

**Comment by haseenaa** [comment] 2016-07-12 14:30
is the above issue resolved?

**Comment by fyrkant** [comment] 2017-05-24 14:45
Closing this due to old age, if anyone still has this issue in the latest version of TinyMCE please open up a new issue.

**Closed by fyrkant** 2017-05-24 14:45 UTC
Labels: browser: ie, browser: ie10, browser: ie9, origin: tinymce.com, plugin: paste, type: bug

**Comment by fvangrun** [comment] 2018-02-14 10:25
Hi, when pasting a line from Word with numbering, Tinymce is loosing the number.

**To reproduce**
Example of text in word:

1.	First line
2.	Second line
3.	Third line
-------------------------------------------
2 issues with numbering:

1/If you copy/paste all the text, tinymce with keep correctly the 1. & 2., but the last "numbering" will be lost.

2/ if you want to copy/paste only one line (for ex the second line) , tinymce will remove the numbering

Thanks in advance for your help

F.
