### ISSUE TITLE
search replace throws js error

### ISSUE THREAD

**Issue by manu37** [tinymce/tinymce#4769] opened 2019-01-19 14:27 UTC
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
http://fiddle.tinymce.com/M7gaab/4
click search icon

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
TinyMCE 5.0.0-rc-1-build.13

**Comment by lnewson** [comment] 2019-01-20 04:04
I can see the issue and it's caused by us switching checkboxes to use booleans, instead of strings, however it seems we missed the initial state in the Search & Replace plugin. Thanks for letting us know!

**Comment by lnewson** [comment] 2019-01-21 05:55
This should now be fixed as of TinyMCE 5.0.0-rc-2.

Note: There's still an error about being unable to read property 'Factory' of undefined, which isn't related to this and is a bundling issue we've fixed for the next release.

**Closed by lnewson** 2019-01-21 05:55 UTC
Labels: 5.x, plugin: searchreplace, status: escalated, status: verified, type: bug
