### ISSUE TITLE
Wrong selected "rel_list" item on Link editing when default target is enabled

### ISSUE THREAD

**Issue by valse** [tinymce/tinymce#3650] opened 2017-05-16 10:00 UTC
Hi,
If I enable a custom "rel_list" for the link plugin and set a default link target, when I try to edit the created link, the modal show the wrong Rel item selected.

I think that the modal must show the previously selected rel item and let me to change it with a new one.

[fiddle.tinymce.com/UPfaab](http://fiddle.tinymce.com/UPfaab)

Thanks
Marco

**Comment by lnewson** [comment] 2020-05-02 08:48
Hi,

I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely we've fixed the issue since this was originally reported, so I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-02 08:48 UTC
Labels: plugin: link, type: bug

**Comment by Maniraj-Vanna** [comment] 2020-06-23 11:46
> Hi,
> 
> I attempted to replicate this with TinyMCE 4.9.10 and 5.2.2, however it appeared to be working as expected. It's likely we've fixed the issue since this was originally reported, so I'll go ahead and close this. If you're still able to reproduce the issue in the latest version, then please let us know and we'll reopen this issue.
> 
> Thanks!

Is the issue fixed? @lnewson  .. I am getting the same issue here https://repl.it/@ManirajVanna/tinymcevanna#index.html where i am using tinymce version 5.. If I select No Follow from dropdown but then open again it selects the first dropdown Do Follow by default but selected value is No Follow.. You can reproduce the same in the provided link..
