### ISSUE TITLE
 Version 4.7.12 - Table plugin bug - Adding columns

### ISSUE THREAD

**Issue by lrusso** [tinymce/tinymce#4380] opened 2018-05-04 11:36 UTC
Tested in Firefox. The initial table width is 450px. Add two columns. Now check the table properties. The form dialog will say 560px and the style textbox in the advanced tab will say 450px.

In older versions of the table plugin, when the user adds a column, the table width remains the same, that would be the right thing.

http://fiddle.tinymce.com/Xogaab

**Comment by lnewson** [comment] 2020-05-08 08:01
Hi,

I'm unable to reproduce this issue in TinyMCE 4.9.10 using the details provided and the style field was removed in TinyMCE 5.x so can't be reproduced there. Looking back at the changelog however, it appears this issue was fixed in TinyMCE 4.7.13. As such I'm going to close this but if you're still experiencing issues then let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-08 08:01 UTC
Labels: plugin: table, status: escalated, status: verified, type: bug
