### ISSUE TITLE
Uncaught TypeError since 4.6.X

### ISSUE THREAD

**Issue by Andy-QT** [tinymce/tinymce#3670] opened 2017-05-20 13:29 UTC
**What is the current behavior?**
Javascript error when tinymce is too fast initialized, repeatedly.

**Console output in browser:**
- Firefox: TypeError: editor.getDoc(...) is null
- IE Edge: Unable to get property 'documentElement' of undefined or null reference
- Google Chrome: Uncaught TypeError: Cannot read property 'documentElement' of null

Chrom callstack:
Uncaught TypeError: Cannot read property 'documentElement' of null
    at getEventTarget (tinymce.js:37104)
    at bindEventDelegate (tinymce.js:37128)
    at Array.<anonymous> (tinymce.js:37202)
    at Object.each (tinymce.js:3625)
    at Editor.bindPendingEventDelegates (tinymce.js:37201)
    at initEditor (tinymce.js:43152)
    at tinymce.js:43301
    at tinymce.js:8556
    at tinymce.js:8025

**Minimal demo of the problem:**
[fiddle.tinymce.com](http://fiddle.tinymce.com/4Qfaab) 
In this test you have to click the Button multiple times and fast. Firefox shows the error quicker.

**Version:**
Error occurs since version 4.6.0

**Comment by jayarjo** [comment] 2017-05-20 18:23
Editor initialization is an async operation. So if you trying to remove the editor that didn't yet finished initialization that would be a potentially erroneous operation.

Consider a simple change like this: http://fiddle.tinymce.com/4Qfaab/2 (just an example).

Also can you describe scenario, where you need to init/remove the editor so many times and so fast?

**Comment by Andy-QT** [comment] 2017-05-21 09:51
Thank you for the example. 

Usage description: 
I have a list of entries in a table and by clicking on an entry a form appends to document.

Workflow:
1. click table entry
2. load data from server via ajax
3. create form instance
4. append form to DOM
5. initialize TinyMCE to textarea#editor

If you switch to fast between the table entries, the error occurs

**Comment by spocke** [comment] 2017-05-22 09:57
I guess we could add guards for the init so that if the editor is removed while it's being initialized we simply ignore the init call. But still the initialization of tinymce is async and has always been async it's just that this issue is probably easier to get to now when it takes slightly longer to initialize since it waits for the content css.

**Comment by spocke** [comment] 2017-05-23 13:12
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2017-05-23 13:12 UTC
Labels: resolution: fixed in coming release

**Comment by Andy-QT** [comment] 2017-05-24 13:00
This solved the issue! thanks!
