### ISSUE TITLE
Version 4.7.7 - Unable to select any entries in lists if page is scrolled down

### ISSUE THREAD

**Issue by rhansen-gs** [tinymce/tinymce#4237] opened 2018-02-20 21:09 UTC
Here is an example.  In the code below, if you scroll the page down and click "insert link" from the menu, clicking the "target" listbox shows no popup.  If you scroll the page to the top and click the target listbox again, the list works.   If you scroll down one only a little and click the listbox, the entries are shown in a disconnected box about halfway down the page.   it seems the positioning of the listbox is multiplied by the scroll position.

The bug does not occur on version 2.7.6
Bug exists in firefox, chrome, and ie

```
<html>
<head><script src='https://cdn.tinymce.com/4.7/tinymce.min.js'/></script></head>
<body style="padding-top: 800px;">
<script>tinymce.init({selector: '#fulltext', height: 500, plugins: 'link'});</script>
<textarea id="fulltext" name="fulltext">testing 123</textarea> 
</body>
</html>
```

**Comment by rustamwin** [comment] 2018-02-21 11:41
"target" listbox not working, because listbox container style "top" worked improperly

**Comment by rjpepmeyer** [comment] 2018-02-21 20:15
The dropdown menus in the table plugin are also affected. To reproduce, open [this fiddle](http://fiddle.tinymce.com/Lkgaab), scroll down to the table, open the table properties, and attempt to set an alignment.

**Comment by rhansen-gs** [comment] 2018-02-21 20:29
I noticed it originally in a local custom plugin, so I suspect it affects all plugins using a listbox.

**Comment by spocke** [comment] 2018-02-26 15:43
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by spocke** 2018-02-26 15:43 UTC
Labels: status: escalated, status: verified, type: bug
