### ISSUE TITLE
Links should trim whitespaces

### ISSUE THREAD

**Issue by javamo** [tinymce/tinymce#5305] opened 2019-12-04 22:38 UTC
**What is the current behavior? Describe the bug**
Using the link plugin. If the URL contains whitespaces at the beginning or end, the URL will be saved wrong.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Create a link and, in the modal, add a whitespace at the end of the link or the beginning.

**What is the expected behavior?**
Those spaces should be trimmed.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
All versions/browsers.

**Comment by HAFRMO** [comment] 2020-03-12 14:15
I was not able to replicate this issue. Since 5.1.0 there's a rather aggressive trimming on text you write into the url-input, and even prior to it it seems like the saved url was properly trimmed.

**Comment by lnewson** [comment] 2020-04-24 12:16
Closing as this issue appears to have been fixed in TinyMCE 5.1.0 as @HAFRMO mentioned above. If you're still having issues with this, can you please include more details about how to reproduce the issue and we can then reopen this and investigate further.

**Closed by lnewson** 2020-04-24 12:16 UTC
Labels: needs: more info
