### ISSUE TITLE
Editor without theme throws error

### ISSUE THREAD

**Issue by iseulde** [tinymce/tinymce#3947] opened 2017-09-25 13:43 UTC
Since 52e00b591bfc309a18b55f84c490368535be288a, editors without a theme (no theme object) throw the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined
    at getImplementation (tinymce.0421cdb5.js:25422)
    at reposition (tinymce.0421cdb5.js:25434)
    at <anonymous>
getImplementation @ tinymce.0421cdb5.js:25422
reposition @ tinymce.0421cdb5.js:25434
Promise rejected (async)
requestAnimationFrame @ tinymce.0421cdb5.js:479
(anonymous) @ tinymce.0421cdb5.js:25500
fire @ tinymce.0421cdb5.js:21534
fire @ tinymce.0421cdb5.js:21858
(anonymous) @ tinymce.0421cdb5.js:48492
each @ tinymce.0421cdb5.js:3495
globalEventDelegate @ tinymce.0421cdb5.js:48488
executeHandlers @ tinymce.0421cdb5.js:1055
defaultNativeHandler @ tinymce.0421cdb5.js:1082
```

It seems there needs to be an extra check for the theme object here: https://github.com/tinymce/tinymce/commit/52e00b591bfc309a18b55f84c490368535be288a#diff-2e5c98d81ce2481aa1042b2320728b65R37

**Comment by wuboy0307** [comment] 2017-10-02 10:42
Got this yesterday. It breaks my tinymce setup

**Comment by fyrkant** [comment] 2017-10-03 12:43
This bug/issue has been fixed in the latest version. If you can still reproduce this on the latest version please let us know and we re-open this ticket. Thanks.

**Closed by fyrkant** 2017-10-03 12:43 UTC
Labels: component: ui, status: escalated, status: regression, status: verified, type: bug

**Comment by LeonardChallis** [comment] 2017-10-13 07:16
Do we know when 4.7.1 will be in stable or at least accessible by specifying the version in the tinymce cloud link? We’ve been using `.../stable/...` but after introducing errors we’re thinking of switching to a specific version instead and manually updating periodically.

**Comment by PascalBoschma** [comment] 2017-10-24 12:35
Updating is not the fix. At least not when you use the TinyMCE Cloud. It's just there again.

**Comment by fyrkant** [comment] 2017-10-24 12:55
@LeonardChallis Can't say any specific date, but you can use the 4.7.1 on the dev cloud:
http://cloud.tinymce.com/dev/tinymce.min.js

@PascalBoschma Which version can you reproduce it on? 4.7.1?

**Comment by joelsamuelk** [comment] 2017-11-28 06:23
Still happens in 4.9 

tinymce.min.js?ver=4607-20171116:28 Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined

**Comment by abhi36** [comment] 2017-11-28 15:58
Yeah, still the issue is there saying `Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl'` while trying to scroll the page. Even its making unable to edit any posts in Wordpress. Freezing the browser.

**Comment by Tokkemon** [comment] 2017-11-28 19:08
Same here. Got a pile of these errors in the console. `Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined
    at h (wp-tinymce.php?c=1&ver=4607-20171116:29)
    at k (wp-tinymce.php?c=1&ver=4607-20171116:29)
    at <anonymous>`

**Comment by joelsamuelk** [comment] 2017-11-29 13:29
I have tried to reinstall WordPress and the theme but the error still occurs.

**Comment by vuhanguyen** [comment] 2017-11-30 05:05
I got pile of those errors with wordpress 4.9 too

**Comment by Bastlus** [comment] 2017-12-01 12:44
brocken for me too

**Comment by Afraithe** [comment] 2017-12-01 12:48
This is probably due to the tinymce core isn't in sync with the theme, either your cached, or your files didn't update correctly and you have a different version of the core and and theme for some reason.

Make sure you clear your browser cache, report back.

**Comment by PoeHaH** [comment] 2017-12-01 14:12
In WordPress 4.9, I get the same JS error in console - but it only appears when I scroll. Even more weird: when the page loads and I don't scroll until it's finished loading, the error will not show up. 

If however, I start scrolling back & forth before the page is fully loaded, it will spawn this error on every scroll movement.

I get this on a plugin settings page in WordPress.

**Comment by nofikoff** [comment] 2017-12-01 14:53
In my case. It was a conflict with the plugin wordpress Nivoslider

**Comment by chyvak1831** [comment] 2017-12-01 17:57
> but it only appears when I scroll. Even weirder: when the page loads and I don't scroll until it's finished loading, the error will not show up.
This issue appears on browser resize.

But it seems that problem in updating, because:
1) WordPress 4.9.1 running Twenty Seventeen theme. - if to resize while page load appears 'TypeError: Cannot read property 'getNotificationManagerImpl' of undefined' (WP&theme were updated, initially were installed older versions)

2) WordPress 4.9.1 running Twenty Seventeen theme. - if to resize while page load NO any issues (last version WP was downloaded and installed - i.e. not updated, directly downloaded).

**Comment by PoeHaH** [comment] 2017-12-02 04:16
@chyvak1831 
I just disabled & deleted ALL my plugins and I'm not using Twenty Seventeen theme. The issue is still there. Seems like a problem on tinyMCE's end?

**Comment by chyvak1831** [comment] 2017-12-02 04:26
@PoeHaH 
Sure, problem in editor.
I’ve just explained that on two blogs with the same configuration two different results, issue appears on blog which was updated throu WP admin; on other, which was downloaded and installed no any issues.
So, it seems that problem in WP updating...

**Comment by PoeHaH** [comment] 2017-12-02 04:28
@chyvak1831 aha, I see now - thanks for clarifying!

**Comment by kpettinga** [comment] 2017-12-05 15:45
Encountering this issue as well in a WordPress 4.9.1 install. Any solutions?

**Comment by yannbug** [comment] 2017-12-07 11:43
Same problem here on multisite WordPress 4.9.1 with all plugins up-to-date.

**Comment by laurentvd** [comment] 2017-12-08 15:23
Same here

**Comment by virtualscreenz** [comment] 2017-12-09 11:44
same error

**Comment by PoeHaH** [comment] 2017-12-09 11:49
@fyrkant Many people seem to have this issue on WordPress 4.9.1. Might be good to reopen the ticket?

**Comment by spocke** [comment] 2017-12-09 12:54
If it can be reproduced outside the wordpress integration then we can look into it. But I think this has to do with upgrading of tinymce done properly so the core and the theme is out of sync this is not something we can fix in tiny since we provide both parts as one package to wordpress and then it's up to them to bundle and release that part of wordpress. We haven't seen any other reports of this error from other integrations so it seems to be wordpress specific.

There is a wordpress specific ticket here it better that it's being tracked there:
https://core.trac.wordpress.org/ticket/42722

**Comment by PoeHaH** [comment] 2017-12-09 13:01
Fair enough @spocke! I understand this is a WP problem, rather than Tiny.

**Comment by tazmwebsolutions** [comment] 2017-12-13 01:14
Cleared cookie and cache seem to help for now.

**Comment by MollyWeb** [comment] 2017-12-13 15:17
Same issue for me on WP 4.9.1 on scroll.

**Comment by markorapaic** [comment] 2017-12-17 23:13
Same issue here on 4.9.1

**Comment by iam2611008** [comment] 2017-12-18 03:30
--- same as well here ---

**Comment by Maden-maxi** [comment] 2017-12-25 00:37
Same issue here on 4.9.1

**Comment by ipaulin** [comment] 2017-12-27 21:52
I've had this issue on the WordPress 4.9.1 only when the Advanced Custom Fields 4.4.12 plugin is activated.
Try to deactivate plugins one by one to see which one is responsible for this error.

**Comment by agrushcow** [comment] 2017-12-29 01:16
Same issue.

**Comment by NguyenHiep** [comment] 2017-12-29 18:20
Same issue.

**Comment by webkitvn** [comment] 2018-01-02 03:38
`Uncaught (in promise) TypeError: Cannot read property 'getNotificationManagerImpl' of undefined`

I can't update my post on 4.9.1

**Comment by sangar82** [comment] 2018-01-02 09:37
Fixed for me updating from  4.6.7 (CE) (2017-09-18)  to 4.7.4 (CE) (2017-12-05)

**Comment by connerbw** [comment] 2018-01-03 23:55
Issue happens for me when using `Select2` JS (budnled with a custom fields plugin)

Same behaviour described by @PoeHaH on Dec 1, 2017 (Only happens if TinyMCE is on screen, scrolling, ...)

**Comment by connerbw** [comment] 2018-01-04 02:11
Thanks for the [link to the WordPress issue](https://core.trac.wordpress.org/ticket/42722) @spocke 

That being said, there dozens and dozens of comments here since this issue's been closed? Is it because people don't like commenting on Trac?  It would be nice to see some collaboration between upstream/downstream...

**Comment by SergiOca87** [comment] 2018-01-10 11:09
Has anyone found a fix for this?

**Comment by duoeg** [comment] 2018-01-18 20:49
Confirmed, still an issue for 4.9.2 as on today. 

Getting this for every instance; on my current website, I'm getting this for every ACF repeater with a WYSIWYG field, and reproduced every time I add a new field.

**Comment by mnestorov** [comment] 2018-01-19 23:47
Confirmed, still an issue for 4.9.2.

**Comment by amiremami** [comment] 2018-01-21 15:20
Same issue here

**Comment by fyrkant** [comment] 2018-01-22 10:01
Hi everyone, there's no reason to keep commenting here, like spocke commented above this is wordpress specific problem so just keep an eye on their ticket instead: 🙇 

https://core.trac.wordpress.org/ticket/42722
