### ISSUE TITLE
IOS mobile terminal inserts pictures

### ISSUE THREAD

**Issue by WilliamAdolph** [tinymce/tinymce#7556] opened 2022-01-25 02:15 UTC
sorry, My English is not very good. This content is translated by my translation software：

At the IOS mobile terminal, click the finish button on the IOS keyboard, and then insert the picture. The picture runs to the front by default, rather than the expected cursor position last time

**Comment by hamza0867** [comment] 2022-04-27 09:38
Hello @WilliamAdolph 

Can you please provide a fiddle reproducing the issue ? Or a more detailed reproduction description ?
We tried but we could not reproduce the issue.

Thank you

**Comment by lnewson** [comment] 2022-06-05 23:24
As there's been no update on this for some time I'm going to close it. If the requested information above can be provided we'll be happy to reopen this issue.

**Closed by lnewson** 2022-06-05 23:24 UTC
Labels: needs: more info
