### ISSUE TITLE
Tinymce is not initializing on second time edit(reinitialize) in chrome 76.0.3809.100(current version) 

### ISSUE THREAD

**Issue by ganga-iaf** [tinymce/tinymce#5130] opened 2019-08-26 12:58 UTC
Hi 

We are facing an issue with tinymce (4.3.10) after last update to chrome (76.0.3809.100).In my app there are few text fileds with tinymce setup.When i click on edit button those text fields initialize with tinymce.

Issue: On first time clicking edit button everything is working fine (Tinymce initializing as expected).But when i click on cancel and again clicking on edit button text areas appearing without tinymce. Till last chrome update everything is working without issues.I tested in previous versions of chrome by downloading and installing them, everything is working fine.In firefox and IE working fine.

In console we got one error.we can see it on attached image.

![NotIntialisingTiny](https://user-images.githubusercontent.com/53358393/63692914-64677d00-c830-11e9-9255-22f33584f76e.PNG)
![ErrorInConsole](https://user-images.githubusercontent.com/53358393/63692926-6a5d5e00-c830-11e9-9471-47e47e9adc7f.PNG)

**Comment by wonderbugtiny** [comment] 2019-08-30 00:41
@ganga-iaf Please note that we only support TinyMCE version 5.x. Please verify if you can reproduce the issue in the latest version of TinyMCE by modifying this [fiddle](http://fiddle.tinymce.com/baaaab) with your basic configuration. Thank you.

**Comment by lnewson** [comment] 2019-10-15 21:32
Closing this due to lack of additional information. If you can provide the additional information mentioned above, then we're more than happy to reopen this issue.

**Closed by lnewson** 2019-10-15 21:32 UTC
Labels: needs: more info

**Comment by manoam** [comment] 2020-07-09 10:48
gjkkh
