### ISSUE TITLE
upload the  image  type  is  bmp

### ISSUE THREAD

**Issue by icezyp** [tinymce/tinymce#6211] opened 2020-11-12 06:51 UTC
can not upload bmp image ; in the source code, can not get the file obj when upload bmp, use api.getData()

**Comment by lincolndennis** [comment] 2020-11-12 23:54
Can you provide a reproduction example? For example, can you reproduce this issue in a Tiny Fiddle?

http://fiddle.tinymce.com/baaaab

Please also note the browsers and operating systems (name and versions) you are testing with.

**Comment by lnewson** [comment] 2020-12-20 22:47
TinyMCE didn't support uploading BMP images via the image dialog or dropzone component until TinyMCE 5.6.0, as it only supported JPEG, GIF and PNG image formats. Please try upgrading to TinyMCE 5.6.0 and see if that resolves your issue.

Since there's been no update in the last month however, I'm going to close this. If you're still experiencing issues, please provide the additional details requested above.

**Closed by lnewson** 2020-12-20 22:47 UTC
Labels: needs: more info, plugin: image
