### ISSUE TITLE
Mouse marking problems when selecting text and table

### ISSUE THREAD

**Issue by dknoblic** [tinymce/tinymce#4519] opened 2018-08-08 09:14 UTC
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
I have changed the example on https://www.tiny.cloud/docs/demo/full-featured/. After changing the content of the table "A simple table to play with" it isn't possible to mark specific content by selecting them by mouse (f.e. the headline "A simple table to play with" and the table.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**
Change the table of the example https://www.tiny.cloud/docs/demo/full-featured/ and try to mark selected content of text and table by using the mouse.

**What is the expected behavior?**
The user can mark specific content of text and table by selecting them by mouse.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**
- Windows 7 x64 / Windows 10 x64
- Firefox ESR 52.9.0 x32
- TinyMCE v 4.8.1-100 and 4.7.2

Thanks.

**Comment by fyrkant** [comment] 2018-08-08 10:01
Can you record a video of the problem? I'm not sure I understand the steps to reproduce.

**Comment by dknoblic** [comment] 2018-08-10 09:36
Hello fyrkant,

I have created this video https://youtu.be/9VdId_A4Gwc. First I have market text and table succesfully, the second try shows the unsuccesfully try to mark text and table after i have changed the table. thanks.

**Comment by dknoblic** [comment] 2018-09-26 13:01
Hello, is there a update available? thanks.

**Comment by fyrkant** [comment] 2018-09-26 13:06
So this only happens in the ESR version of Firefox?

**Comment by dknoblic** [comment] 2018-09-26 13:20
Yes. I can't reproduce this by using a non ESR version of Firefox.

**Comment by lnewson** [comment] 2020-05-09 10:08
The ESR version has been updated since this issue was reported and I'm no longer able to reproduce this using TinyMCE 4.9.10 or 5.2.2 with Firefox ESR 68.8.0. I'll go ahead and close this since I can't reproduce it, but if you're still able to reproduce the issue, then please let us know and we'll reopen this issue.

Thanks!

**Closed by lnewson** 2020-05-09 10:08 UTC
Labels: needs: more info
