### ISSUE TITLE
Windows 10 Anniversary MS Edge Update causes visual artifacts in TinyMCE Editor 

### ISSUE THREAD

**Issue by lafavemb** [tinymce/tinymce#3106] opened 2016-08-03 15:16 UTC
We are currently using TinyMCE and in preparation for the Windows 10 Anniversary Update noticed that the updates for MS Edge have caused UI issues in TinyMCE.  We noticed the issues in our own application, but also saw them when playing with the sample editor on the TinyMCE website.  The below screenshots are from using the latest MS Edge to view the sample TinyMCE editor.

![tinymce_4_3_12](https://cloud.githubusercontent.com/assets/20804711/17370696/3e03e02e-595a-11e6-98be-c55540267a00.jpg)
![tinymce_4_4_1](https://cloud.githubusercontent.com/assets/20804711/17370695/3dfcfb24-595a-11e6-8098-ca2643a2958f.jpg)

**Comment by tinydylan** [comment] 2020-04-26 11:55
Hi,

TinyMCE and the TinyMCE website have changed significantly since this issue was logged. 

For now, I'll close this issue, but if you can reproduce any other issues like this, can you please let us know? 

Thanks!

**Closed by tinydylan** 2020-04-26 11:55 UTC
Labels: browser: edge, component: ui, type: bug
