### ISSUE TITLE
TinyMCE 5 Preview: Save button is still active after save

### ISSUE THREAD

**Issue by doganmeh** [tinymce/tinymce#4679] opened 2018-11-23 17:51 UTC
Save button does not refresh after save; it is still enabled. 

Version 5.0.0-preview-5 (TBD)

**Comment by doganmeh** [comment] 2018-11-23 21:29
This happens only the first time 'save' button hit after the page load. 

Also isDirty() returns true when 'save' button erroneously active. Subsequent page reload shows save actually have worked.

**Comment by EkimChau** [comment] 2018-11-26 00:33
Hi doganmeh,

When save_onsavecallback is defined with a callbackFN(), the page should not refresh (the form is not submitted),  this is the expected behaviour.  

When the configuration save_enablewhendirty: true, is used, the button should respond to the isDirty() check.  setDirty(true) should enable the button and setDirty(false) should disable the button.

I noticed you're using Version 5.0.0-preview-5 (TBD) which is great!  Hopefully any weirdness you experienced was temporary.

Let us know if this is still an issue for you.

**Comment by doganmeh** [comment] 2018-11-26 15:48
@EkimChau thank you for the response, however, I am not sure I see what you are saying, and I don't think you see what I am saying either :)

What I am reporting here cannot be the default behavior as version 4 does not do it. With version 5, I am having to click "save" button twice to save. The first time I click, the button does not become disabled (although it saves). The second time I click it saves and the button becomes disabled as usual. And this issue occurs only for the 1st time saving after the page load. Subsequent savings are OK. 

I switched back to version 4. 

Regards,

**Comment by lnewson** [comment] 2019-03-01 04:10
@doganmeh I've tried to reproduce this using the latest version available atm (5.0.1), however I've been unable to. Is this still an issue and if so would you please be able to provide a way to reproduce the issue via a fiddle or something similar? If it helps, here's a fiddle I was using to test: http://fiddle.tinymce.com/cDgaab

I should also note that I did find one other issue in testing this, whereby clicking the "Cancel" button didn't reset the dirty state. However that's reproducible in 4.x as well as 5.x and as such I've added an issue to our backlog to get that fixed.

**Comment by wonderbugtiny** [comment] 2019-04-08 03:44
Closing due to lack of information. If you could include a way to reproduce the issue or provide additional details, then we would be happy to reopen this issue.

**Closed by wonderbugtiny** 2019-04-08 03:44 UTC
Labels: 5.x, needs: more info, plugin: save
