### ISSUE TITLE
Table error

### ISSUE THREAD

**Issue by pliasetski** [tinymce/tinymce#2803] opened 2016-03-23 16:10 UTC
Hello,
When I trying to delete table from context menu using "Delete table" button, I get console error.
Please see this video for more details: 
https://dl.dropboxusercontent.com/u/73896408/table%20console%20error.mp4

Could you help with this issue.

With best regards, Pavel

**Comment by tinydylan** [comment] 2020-04-26 11:13
Hi,

Unfortunately, that dropbox link is no longer available. I tested out deleting tables from the context menu using [this test page](https://www.tiny.cloud/docs/demo/full-featured/) on several browsers, but I was unable to reproduce the issue.

I'm closing this issue for now, however, if the issue persists, please let us know and we'll re-open this ticket to investigate.

Kind regards,

Dylan

**Closed by tinydylan** 2020-04-26 11:13 UTC
Labels: plugin: table, type: bug
