### ISSUE TITLE
Syntax Error when clicking "Insert/Edit Link" in TinyMCE 4 (stable).

### ISSUE THREAD

**Issue by toadicus** [tinymce/tinymce#3880] opened 2017-08-21 16:11 UTC
**Do you want to request a *feature* or report a *bug*?**
I am reporting an apparent bug.

**What is the current behavior?**
Current, clicking the "Insert/Edit Link" shortcut, or using the Menu item in "Insert", results in a SyntaxError, thus:

```
Uncaught SyntaxError: Unexpected token t in JSON at position 4
    at JSON.parse (<anonymous>)
    at Object.success (tinymce.min.js:23)
    at d (tinymce.min.js:20)
```

The link editor does not appear.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tinymce.com](http://fiddle.tinymce.com/) or similar.**

I have included the editor thus:

```
<script>
	tinymce.init(
			{
				selector: 'textarea',
				plugins: 'link autolink image',
				browser_spellcheck: true,
				image_list: '/image_list',
				link_list: '/link_list',
				width: 985,
				content_css: '/css/stylesheet.css',
				body_class: 'page',
			}
		);
</script>
```

**What is the expected behavior?**

The link editor should appear without an error.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

I have tested this in Google Chrome 60 in Windows and Linux.

**Comment by spocke** [comment] 2017-08-22 07:12
Make sure that your urls the "/image_list" and "/link_list" produce valid json,

**Comment by spocke** [comment] 2017-08-22 07:13
Closing this one since it seems like an implementation issue. If you feel it's not I can re-open the ticket but then I need a way to reproduce it.

**Closed by spocke** 2017-08-22 07:13 UTC

**Comment by toadicus** [comment] 2017-08-22 15:27
Turns out I wasn't double-quoting the keys in my json.  Thanks for pointing
me in the right direction!
