### ISSUE TITLE
Encoded characters in the string returned by getContent({format: text})

### ISSUE THREAD

**Issue by guangmiw8** [tinymce/tinymce#4220] opened 2018-02-13 00:43 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
tinymce.getContent({format: "text"}) returns string like this after applying style change without text selection: "ABCD!!%EF%BB%BF"

**What is the expected behavior?**
the returned string should not have the encoded characters

**Comment by spocke** [comment] 2018-02-13 15:18
Can you setup a test case at http://fiddle.tinymce.com that reproduces the issue so that we can look at it. Thanks

**Comment by guangmiw8** [comment] 2018-02-14 17:21
Here you go http://fiddle.tinymce.com/qkgaab

**Comment by spocke** [comment] 2018-02-22 14:06
I always get Hello in the alter in Chrome, FF, IE. Closing this one since it's can't be reproduced. Could be some odd browser extension.

**Comment by spocke** [comment] 2018-02-22 14:09
Right managed to reproduce it now. Yeah we need to trim nbzwsp characters when getting text out.

**Comment by lnewson** [comment] 2020-04-28 13:19
It appears that this issue was fixed in TinyMCE 4.7.10 based on the changelog and my testing, so I'm going to go ahead and close this. If you're still having issues, then please let us know and we'll reopen this issue.

**Closed by lnewson** 2020-04-28 13:19 UTC
Labels: component: input/output, status: escalated, status: verified, type: bug
